Add methodology sub-nav and empty page for vitals
Recidiviz/pulse-dashboard pull request #1002
Opened 2021-04-12 14:04 UTC by daschi

## Description of the change

This PR is part of adding the Vitals methodology, and adds the top right sub-nav on the methodology page and a path that can work for either vitals or projections. Since @jovergaag is working on the design polish for the projections methodology, I'm going to wait to fully implement the vitals methodology until that's ready so we can reuse some of the design components. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Part of #982 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-04-12 18:14 UTC, jovergaag requested changes
One small path bug.

2021-04-12 18:14 UTC, jovergaag commented on src/core/views.ts
> +  methodology: "/methodology/:dashboard",
This is not resolving correctly. When clicking on the Methodology link from the Vitals page, the path resolves to `http://localhost:3000/methodology/:dashboard/vitals` and I get a Not Found page.

2021-04-12 18:14 UTC, jovergaag commented on src/core/VitalsMethodology/index.tsx
> +// Copyright (C) 2020 Recidiviz, Inc.
2021

2021-04-13 03:32 UTC, Catacola commented on src/core/MethodologyLink.tsx
> +        height={12}
Can this be set in the scss file?

2021-04-13 15:20 UTC, Catacola commented
I'm still getting a 404 when I click on the methodology link in vitals:
<img width="1030" alt="Screen Shot 2021-04-13 at 10 16 53 AM" src="https://user-images.githubusercontent.com/5516210/114577288-7e421780-9c41-11eb-9983-c90c2caed194.png">

The path seems to be correct. Is this expected behavior for this in-between state?

2021-04-13 16:44 UTC, daschi commented
@Catacola Oh yeah, it only works if `showMethodologyDropdown` flag is true because that's what's adding the `methodology` navigation options.

2021-04-13 22:55 UTC, jovergaag approved these changes

2021-04-14 13:11 UTC, merged