Vitals Summary - Officer view
Recidiviz/pulse-dashboard pull request #1015
Opened 2021-04-15 23:34 UTC by jovergaag

## Description of the change

Enables the Officer View for the Vitals Page. For now, the table will not be shown in the Officer View.

Two important things to note
- Waiting on time series data for the officers, so this will need to be run in demo mode for testing
- We need to have `parent_entity_name` added to the `vitals_summaries` view to feed the breadcrumbs on the Officer View. Issue is [here](https://app.zenhub.com/workspaces/torch--5ec36552cdfe7bc58f04bdbe/issues/recidiviz/recidiviz-data/7002).

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #991

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-04-16 13:49 UTC, daschi commented on server/core/demo_data/vitals_summaries.json
> +{"entity_id": "OAKES", "entity_name": "Oakes",  "entity_type": "level_1_supervision_location", "parent_entity_id": "OAKES", "parent_entity_name": "STATE DOC", "overall": "65",  "timely_discharge": "-
I still don't quite understand why we need two summaries for the same data, where one has a `parent_entity_id` that matches its own `entity_id`?

2021-04-16 13:49 UTC, daschi commented on src/core/VitalsSummaryBreadcrumbs/VitalsSummaryBreadcrumbs.scss
> +    content: "/";
This gets underlined on hover, if we wanted to avoid that I think it might work better to add this as its own span element.

2021-04-19 18:24 UTC, jovergaag commented on server/core/demo_data/vitals_summaries.json
> +{"entity_id": "OAKES", "entity_name": "Oakes",  "entity_type": "level_1_supervision_location", "parent_entity_id": "OAKES", "parent_entity_name": "STATE DOC", "overall": "65",  "timely_discharge": "-
We had decided to do this originally - but that changed somewhere along the line and I wasn't aware. I'll update the fixtures to match the data here.

2021-04-21 18:47 UTC, daschi requested changes
Looks good! I just think we should add a safeguard for the missing data so that we can deploy staging without it crashing, or maybe wait to merge until that data is available if it's coming soon?

2021-04-21 18:47 UTC, daschi commented on src/core/models/types.ts
> +  parentEntityName: string;
I think this `parentEntityName` can be removed from the model now? same question for the metric model

2021-04-21 18:47 UTC, daschi commented on src/core/VitalsSummaryTable/VitalsSummaryTable.tsx
> +                to={`/community/vitals/${convertIdToSlug(value.entityId)}`}
This currently is causing an error because there aren't any time series for the POs in the data, do we expect that to be added soon? If not we may want to put a safeguard on line 111 in the `PageVitals/index.tsx` since that's causing the page to crash.

2021-04-21 18:47 UTC, daschi commented on src/core/VitalsSummaryBreadcrumbs/index.tsx
> +  return name ? `${toTitleCase(name)} Office` : name;
One of the entity names already has "Office" in it, maybe we could format it to remove any duplicates?

2021-04-21 22:47 UTC, jovergaag commented on src/core/VitalsSummaryTable/VitalsSummaryTable.tsx
> +                to={`/community/vitals/${convertIdToSlug(value.entityId)}`}
Yes, you should be able to view it in demo mode. I just confirmed with. @Catacola that the time series data for officer view is a bit down the road so I'll just add this whole officer view behind a flag for now.

2021-04-21 23:45 UTC, jovergaag commented on src/core/VitalsSummaryBreadcrumbs/index.tsx
> +  return name ? `${toTitleCase(name)} Office` : name;
I created a ticket to format the `entity_name` more consistently so that we don't have to account for these special cases. Formatting here for now.

2021-04-22 17:17 UTC, Catacola approved these changes
Looking good! I have a few minor comments but nothing blocking.

2021-04-22 19:42 UTC, jovergaag commented on src/core/PageVitals/helpers.ts
> +    )
It is because there is a single row for the "STATE_DOC" where both `entityId` and `parentEntityId` are STATE_DOC. If we do not include this then we get that row in the table for the top level view.

2021-04-22 19:44 UTC, jovergaag commented on src/core/PageVitals/helpers.ts
> +  return selectedTimeSeries.length > 0 ? selectedTimeSeries : undefined;
Thats how it was originally but it makes it much easier to guard for when there are no time series that match a given entity. The guards become more complicated and happen in a few places. I'm happy to revert this back to what it was and use those more complicated guards, this just seemed more clean to me.

2021-04-22 20:04 UTC, jovergaag commented on src/core/PageVitals/helpers.ts
> +  return selectedTimeSeries.length > 0 ? selectedTimeSeries : undefined;
That last commit reverts `getTimeseries` to return an empty array rather than `undefined` if not found. I kind of like it previously but am happy to go either way! Let me know what you think.

2021-04-26 16:43 UTC, Catacola commented on src/core/PageVitals/helpers.ts
> +  return selectedTimeSeries.length > 0 ? selectedTimeSeries : undefined;
That's a very good reason! I'm happy to leave it that way if it works better for you.

2021-04-26 18:10 UTC, daschi approved these changes

2021-04-26 18:29 UTC, merged