[WIP] Vitals download data
Recidiviz/pulse-dashboard pull request #1051
Opened 2021-04-26 18:57 UTC by jovergaag

## Description of the change

wIP

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1050

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-04-29 20:34 UTC, daschi requested changes
I think this makes sense, and I tested it on chrome & ie11 on both lantern & core. 

I did notice 1 issue, for the non-vitals Core downloads (i.e. Explore/community, etc.), the CSVs have lost the headers for the time period columns. They used to say `Month` and are not showing `Undefined`.

2021-04-29 20:34 UTC, daschi commented on src/flags.js
> +  enableVitalsDashboard: true,
do we want to merge this to main?

2021-04-29 21:01 UTC, jovergaag commented on src/flags.js
> +  enableVitalsDashboard: true,
oh crap.

2021-04-30 18:34 UTC, daschi approved these changes

2021-04-30 18:49 UTC, Catacola approved these changes
Probably outside the scope of this diff, but I think it would be a nice touch if we put some details in the name of the zip file like the data and the data downloaded. E.g. `ND_VITALS_2021_04_30.zip`.

2021-05-04 23:30 UTC, merged