Update loading state for population projection view
Recidiviz/pulse-dashboard pull request #1054
Opened 2021-04-27 20:49 UTC by Catacola

## Description of the change

Add a spinner for the chart and make sure there is empty space where the "last updated" message will appear.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-04-27 23:56 UTC, jovergaag requested changes

2021-04-27 23:56 UTC, jovergaag commented on src/core/PageProjections/index.tsx
> +        <PopulationSummaryMetrics isLoading isError={isError} />
The loading state of the `SummaryMetrics` doesn't seem to be working correctly. When I set isLoading to true for everything, the summary Metrics placeholders and titles don't seem to be correct.

2021-04-27 23:56 UTC, jovergaag commented on src/core/PopulationTimeSeriesChart/index.tsx
> +      <div className="PopulationTimeSeriesChart PopulationTimeSeriesChart--Loading">
The modifier in BEM is usually lowercase. `PopulationTimeSeriesChart--loading`

2021-04-28 00:14 UTC, jovergaag commented
Also - I was getting errors when trying to run this locally, due to the `simulationDate`. Both on staging data and in demo mode.

2021-04-28 21:46 UTC, Catacola commented
I see what happened. I updated the diff below this one which caused errors in this one. All should be fixed now.

2021-04-29 17:41 UTC, jovergaag approved these changes

2021-04-29 17:43 UTC, merged