Add e2e test for MO user restricted access flow using demo data
Recidiviz/pulse-dashboard pull request #1055
Opened 2021-04-27 21:00 UTC by daschi

## Description of the change

This PR is the first step towards adding e2e tests for different user levels. 

For now, these tests are running in DEMO mode and can be run by:

- Starting the demo server `REACT_APP_IS_DEMO=true yarn demo`
- Running the tests `yarn test-e2e-users`

The API request for the restricted supervision locations is being mocked for each user. When we move over to using auth0 access tokens and user attributes to get the restricted information, we'll want to change this so that it's actually going through the entire authentication flow. This will also be dependent on setting up a test user ([captured in zenhub-tasks/#225](https://github.com/Recidiviz/zenhub-tasks/issues/225)) and a GCS bucket with demo data. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1037

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-04-27 21:08 UTC, jessex reviewed
Just chiming in to say that I have no security concerns here!

2021-04-28 20:37 UTC, jovergaag requested changes
This is great, nice work. A couple of things:

- I'm not sure if we need the entire caseload json file...it will just bloat the repo unecessarily.
- Did you do that spike to investigate what actually logging in via Auth0 using a demo user would look like in the tests? That seems to be the next step, I just want to make sure we have at least a fuzzy path forward there.
- What was the reason you didn't add the lantern e2e tests to the github actions workflow? I remember that there was a reason, but can't remember what it was.

2021-04-28 20:37 UTC, jovergaag commented on .github/pull_request_template.md
> +- [ ] E2E have been run for Lantern changes
Can we add this to the github workflows?

2021-04-28 20:37 UTC, jovergaag commented on src/cucumber/features/lantern/userAccessLevels/loginAsUnrestrictedUser.feature
> +@skip-session-reload
We're missing copyright header here and on most of the other new files.

2021-04-28 20:37 UTC, jovergaag commented on src/cucumber/features/lantern/userAccessLevels/loginAsUnrestrictedUser.feature
> +        Then I should see "ALL" selected in the filter
It might be helpful to specify district filter here.

2021-04-28 20:37 UTC, jovergaag commented on src/cucumber/steps/userAccessSteps.js
> +    const restrictions = [null, "TCSTL", "13,TCSTL"][numRestrictedDistricts];
slick

2021-04-28 20:37 UTC, jovergaag commented on wdio.conf.js
> +    const { tags } = world.pickle;
Pickle world? :)

2021-04-28 20:54 UTC, daschi commented on .github/pull_request_template.md
> +- [ ] E2E have been run for Lantern changes
Do you mean run the tests as part of the CI? I think we should tackle that separately if so

2021-04-28 20:57 UTC, daschi commented on src/cucumber/features/lantern/userAccessLevels/loginAsUnrestrictedUser.feature
> +@skip-session-reload
Hmm looks like I can't add the copyright to the feature files, they don't get parsed correctly by cucumber-js.

2021-04-29 17:41 UTC, Catacola commented on .github/pull_request_template.md
> +- [ ] E2E have been run for Lantern changes
Might I suggest adding a go link to e2e testing documentation. Since developers need to spin up the dev server and invoke the tests while magic gremlins take over their browser, I think it would be useful to have quick access to a guide so that people new to the repo can get up to speed quickly.

2021-04-29 17:41 UTC, Catacola approved these changes
This diff really shows the power of cucumber. Those tests were extremely easy to read and comprehend.

2021-04-29 17:52 UTC, jovergaag commented on src/cucumber/features/lantern/userAccessLevels/loginAsUnrestrictedUser.feature
> +@skip-session-reload
kk.

2021-04-29 17:54 UTC, jovergaag approved these changes

2021-04-29 17:54 UTC, jovergaag commented on wdio.conf.js
> +    const { tags } = world.pickle;
My kind of world. You may already know this...but my apartment is named Pickle Palace 🥒

2021-04-29 20:54 UTC, merged