Update demo script and add to the readme
Recidiviz/pulse-dashboard pull request #1074
Opened 2021-05-05 16:18 UTC by daschi

## Description of the change

This updates the demo mode script so that it uses `yarn demo` instead of `yarn dev`. It also adds some additional setup instructions for running demo mode.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-05-05 16:35 UTC, Catacola commented on README.md
> +   - [ ] `.env-cmdrc` should exist and should have the correct values for the "development" environment. These variables can be found in the Recidiviz 1Password Vault.
I believe we still need the `.env` file since it's for the backend. I only covered the frontend env vars with `.env-cmdrc`.

2021-05-05 20:51 UTC, Catacola requested changes
Good news and bad news. Read below to learn more.

2021-05-05 20:51 UTC, Catacola commented on README.md
> +   - Long term solution would be to install [iTerm2](https://iterm2.com/), which will automatically shutdown processes after you close your terminal.
So I just did some testing with iTerm and it turns out this isn't true. It will leave them running as well. My guess as to why we've never seen it is that we keep our terminal windows open for, well, ever and just ctrl+c our way out as we should. I still think iTerm is worth using for many other reasons, but apparently this isn't one of them.

2021-05-05 20:51 UTC, Catacola commented on README.md
> +     ```
I found a much safer and easier way to do this: `redis-cli shutdown`. I just tested it on my machine by leaving a processing running by killing a tab. I used `pgrep` to find the running server, called `redis-cli shutdown`, and then used pgrep again and found nothing.

I was able to start my dev environment right back up without a lengthy cache rebuild.

2021-05-06 13:26 UTC, daschi commented on README.md
> +   - Long term solution would be to install [iTerm2](https://iterm2.com/), which will automatically shutdown processes after you close your terminal.
Ah okay! good to know - and thank you for testing that!

2021-05-06 13:29 UTC, daschi commented on README.md
> +     ```
ah okay that's much easier!!

2021-05-06 23:30 UTC, jovergaag approved these changes

2021-05-07 19:18 UTC, Catacola approved these changes

2021-05-07 19:18 UTC, Catacola commented on README.md
> +1. Make sure your `redis-server` is not still running from a previous session. To avoid this situation, always shutdown the demo server by using `CTRL + c`. If you need to shutdown the redis-server f
I think something is off with the numbering here.

2021-05-07 19:25 UTC, jovergaag commented on README.md
> +1. Make sure your `redis-server` is not still running from a previous session. To avoid this situation, always shutdown the demo server by using `CTRL + c`. If you need to shutdown the redis-server f
This 1. 1. 1. instead of 1. 2. 3 is an acceptable way to create an [ordered list](https://www.markdownguide.org/basic-syntax/#ordered-lists) in markdown.

2021-05-08 01:52 UTC, Catacola commented on README.md
> +1. Make sure your `redis-server` is not still running from a previous session. To avoid this situation, always shutdown the demo server by using `CTRL + c`. If you need to shutdown the redis-server f
Wow! Did not know that!

2021-05-10 14:50 UTC, merged