Update vitals page to reflect 30 day, 90 day, and  180 day time periods
Recidiviz/pulse-dashboard pull request #1078
Opened 2021-05-06 22:18 UTC by jovergaag

## Description of the change

Updates the vitals page to show the new 30 day and 90 day metrics, as well as adjusts the time series chart to look back 6 months, with a 30 day rolling average trend line.

The new data is currently in the staging bucket - I will try to remember to copy it back over after the calc run tomorrow morning also!

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes  #1026

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-05-07 19:21 UTC, Catacola reviewed
It's diffs like these that make me appreciate modern IDEs. The thought of doing this in notepad makes me cringe.

2021-05-10 15:34 UTC, Catacola approved these changes
And apparently I didn't approve. Whoops. I do this all the time with github

2021-05-10 15:42 UTC, daschi requested changes
I'm wondering if we want to decrease the `oPadding` on the `VitalsSummaryChart`, that'll make the bars a little bit thicker. I was testing it with using 2 instead of 8 and that seemed to work well. 

I also think we should change the `transformX` value for the `VitalsSummaryTooltip`, it's currently set to switch the direction of the tooltip when it reaches 4 bars away from the right edge, but now that we have more bars I think it would work better to change that number to 20 or more.

2021-05-10 15:42 UTC, daschi commented on src/core/PageVitals/index.tsx
> +                timeSeries={selectedTimeSeries.slice(-180)}
Are we expecting the timeseries data to continue to grow? Why do we need to slice it?

2021-05-10 15:42 UTC, daschi commented on src/core/models/VitalsMetrics.ts
> +      // TODO update when there is data
What needs to be updated? Is there an issue for this todo?

2021-05-10 15:42 UTC, daschi commented on src/core/models/types.ts
> +  parentmonthlyAvg?: number;
nit: `parentMonthlyAvg`

2021-05-10 18:20 UTC, jovergaag commented on src/core/PageVitals/index.tsx
> +                timeSeries={selectedTimeSeries.slice(-180)}
I don't believe that we are expecting it to change, I just thought that it was more safe to slice it to protect the scale of the chart in case something changed? I don't feel strongly either way.

2021-05-10 18:23 UTC, jovergaag commented on src/core/models/VitalsMetrics.ts
> +      // TODO update when there is data
I had removed this in a cleanup commit but forgot to push it up. Its removed now.

2021-05-12 20:18 UTC, merged