Restrict user access using auth0 access and id tokens
Recidiviz/pulse-dashboard pull request #1094
Opened 2021-05-13 21:40 UTC by daschi

## Description of the change

This PR got way bigger than I was expecting!! Let me know if it would be helpful for me to talk through the changes at a high level before a PR review. 

**Server Changes**
- Removes `restrictedAccess` endpoint 
- Updates the `newRevocationFile` endpoint to use the jwt `user` field that has the auth0 parsed access token data to create the cache key and filter the metric file
- Removes `restrictedDistrict` from subsetFilters flow and adds a helper `createUserRestrictionsFilters`
- Update `getFiltersByMetricName` to return no filters for files not listed (this is so we don't filter files like supervision_location_ids_to_names`)
- Adds some logic to allow Recidiviz users to toggle between state codes without restriction access on every state code (we may want to change this later to be more fine-grained so that a recidiviz user can have different access levels for different states, but for now we only have US_MO)
- Adds a `api/demoUser` endpoint that returns the properties for a demo user. I added this for the E2E test so we can mock the response and return different user attributes.

**React App Changes**
- Adds a `fetchDemoUser` client that can only be used in demo mode to fetch the user attributes
- Updates the auth0 hooks code to reflect what is currently in `recidiviz-dev`
- Updates the E2E test to mock the demo user endpoint instead of the restricted access endpoint
- Updates the stores to use the restrictions from the user and removes calls to the restricted access endpoint
- Adds a `enableUserRestrictions` property to the `src/tenants` file that helps recidiviz users toggle between tenants while having user restrictions in their user profile. 

**.env-cmdrc changes**
- Adds two new environments: "demo" and "server"
- Adds `METADATA_NAMESPACE` to an env var since it is used in the server, react app, and cucumber tests
- Adds the new environments to the package scripts for starting the app and running tests

TODO
- [ ] Do not merge/deploy until production is deployed next week and the users in auth0 are being updated correctly 
- [ ] Update the access token hook in the Auth0 `recidiviz` production tenant

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1034

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [x] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-05-13 21:49 UTC, daschi commented on server/core/fetchDemoUser.js
>  // Recidiviz - a data platform for criminal justice reform
The `isDemoMode.test.js` was renamed to `recidivizAccess.test.js`...not sure why git picked this up wrong

2021-05-14 16:49 UTC, Catacola reviewed
So far, so good!

2021-05-14 16:49 UTC, Catacola commented on server/utils/recidivizAccess.js
> +    userRestrictions.length > 0
Does this mean we only check for restricted access in MO? I thought it was PA that needed data to be restricted.

2021-05-14 16:49 UTC, Catacola commented on src/RootStore/TenantStore/lanternTenants.ts
> -
Given what I saw above, it looks like this is being moved from a constant here to a string defined within a helper function. This seems less maintainable than before.

2021-05-14 16:49 UTC, Catacola commented on src/api/fetchDemoUser.ts
> +  return process.env.REACT_APP_IS_DEMO === "true";
JSON makes me sad sometimes

2021-05-14 17:05 UTC, daschi commented on server/utils/recidivizAccess.js
> +    userRestrictions.length > 0
For now we only have restrictions for US_MO. I *think* US_PA decided they want to keep everything transparent, and the next restrictions we'll need to set up are for ID and ND.

2021-05-14 17:06 UTC, daschi commented on src/RootStore/TenantStore/lanternTenants.ts
> -
Hmm true, I'll revert this back to using the list!

2021-05-14 17:19 UTC, daschi commented on src/RootStore/TenantStore/lanternTenants.ts
> -
Actually might ask you about this later, I'm not sure what you mean about the string defined in a helper function

2021-05-14 19:45 UTC, Catacola approved these changes

2021-05-14 19:45 UTC, Catacola commented on src/auth0/rules/02-set-state-code-in-app-metadata.js
> +    "DC",
WHOOHOO

2021-05-14 19:45 UTC, Catacola commented on src/auth0/rules/02-set-state-code-in-app-metadata.js
> +    "WY",
I'm worried about the security implications of listing all 50 states + DC vs just the ones we're working in now.

2021-05-14 19:46 UTC, Catacola requested changes
Sorry. Clicked the wrong button.

2021-05-14 19:50 UTC, daschi commented on src/auth0/rules/02-set-state-code-in-app-metadata.js
> +    "WY",
oh yah good point...I'll remove the others

2021-05-17 21:12 UTC, jovergaag requested changes
Wow, good chunk of work. Let's do a round of revisions on this then maybe deploy it to staging for a very thorough QA round on it.

2021-05-18 14:08 UTC, daschi commented on server/core/__tests__/fetchAndFilterNewRevocationFile.test.js
> +      filters,
Oh yeah, good catch - the example filters here should have all of the values for violation_type, I'll update that.

2021-05-18 14:14 UTC, daschi commented on server/filters/filterHelpers.js
> +  subsetFilters,
Yeah it should be - I did find one other spot where it's still `subsetFilters` within `createSubsetManifest`, so I'll update that!

2021-05-18 14:16 UTC, daschi commented on server/routes/api.js
> +    const subsetFilters = createSubsetFilters({
It would be ignored here because `createSubsetFilters` only includes keys that are also in the subset manifest.

2021-05-18 14:17 UTC, daschi commented on server/utils/__tests__/cacheKeys.test.js
> +        "-level_1_supervision_location=04n,24"
Hmm...there will be more, but won't it be limited to the number of MO users at least? Each user should only have 1 set of locations.

2021-05-18 14:21 UTC, daschi commented on server/utils/__tests__/cacheKeys.test.js
> +                level_1_supervision_location: ["03"],
Yeah...that is kind of confusing. It's because the query param keys come thru camelcase, and the user restrictions keys from auth0 come through snake case. Eventually `createSubsetFilters` does snake case the query params, so maybe I should add a step before the filters are created to make all the keys snake case.

2021-05-18 14:50 UTC, daschi commented on src/RootStore/UserStore.ts
> +  get userRestrictions(): string[] {
Yeah I went back and forth on this about where would be the right place to keep it generic vs specific, in case we have other types of restrictions. I guess until that day comes we could be more specific here and just keep the naming of `allowedSupervisionLocationIds` starting from the UserStore. I'll update this all the way through.

2021-05-18 14:55 UTC, daschi commented on src/lantern/LanternStore/UserRestrictedAccessStore.ts
> -      this.isLoading = false;
These aren't needed anymore because they were setting the error & loading state of the `UserRestrictionsStore`, which was being used in the AuthWall before we removed this store from the higher RootStore. Now the AuthWall is only looking at the authError from the UserStore, and we are setting that auth error on line 154. We also don't need the `this.isLoading` state anymore because this store isn't fetching any data. 

I did test this by giving myself a fake supervision location ID in my user profile, but that was a while ago so after I make these updates I can test it again.

2021-05-20 20:26 UTC, jovergaag reviewed
After some thorough testing - I think this looks good! I'll hold off approving it until next week when we have the new schema in production.

2021-05-27 16:25 UTC, daschi commented
@jovergaag @Catacola I looked into the 1 user missing restrictions, I think I actually just needed to refresh the page, because I found the API Update Operation in the logs and it was updated at the same time as the others. I think once [this PR is in](https://github.com/Recidiviz/recidiviz-data/pull/7497), and I update the hooks PR to actually query the endpoint, we can merge this and deploy to production! Let me know if you think I'm missing anything...

2021-06-01 15:55 UTC, jovergaag commented
> @jovergaag @Catacola I looked into the 1 user missing restrictions, I think I actually just needed to refresh the page, because I found the API Update Operation in the logs and it was updated at the same time as the others. I think once [this PR is in](https://github.com/Recidiviz/recidiviz-data/pull/7497), and I update the hooks PR to actually query the endpoint, we can merge this and deploy to production! Let me know if you think I'm missing anything...

@daschi Are the hooks updated? LMK when you're ready for a final review/approval.

2021-06-11 20:54 UTC, jovergaag commented
@daschi Where are we with this? Is it time for another review?

2021-06-11 21:51 UTC, daschi commented
We're close! I've been monitoring the auth endpoints on recidiviz-data to make sure everything's been working as expected, and there was this issue https://github.com/Recidiviz/recidiviz-data/pull/7800 this week in production that was fixed, so would like to see after next week's production deploy if the auth0 updates all go well. I think we could plan to merge and deploy this next Tuesday or Wednesday after testing the endpoints again.

2021-06-16 19:37 UTC, jovergaag approved these changes
HUGE amount of work. Amazing job! 🥳

2021-06-16 20:41 UTC, Catacola approved these changes
I'm very excited for this!

2021-06-16 20:41 UTC, Catacola commented on server/routes/api.js
> +      (user && user[`${METADATA_NAMESPACE}app_metadata`]) || {};
You can use optional chaining (`?.`) for indices/keys as well:
```
const appMetadata = user?.[`${METADATA_NAMESPACE}app_metadata`] ?? {};
```

2021-06-16 22:08 UTC, merged