Vitals Caseload Button - linking to read only Case Triage page
Recidiviz/pulse-dashboard pull request #1173
Opened 2021-07-22 22:38 UTC by jovergaag

## Description of the change

Adds a button at the bottom of the Vitals Summary on the Officer View that links to a read only view of that Officer's Case Triage page.

Adds `entity_email_address` to the `vitals_summary` fixture.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1164

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-07-23 06:19 UTC, Catacola requested changes
Besides two minor nits, the current code looks good. However, I think we need a way to get this button to only appear for ID for now. ND won't have case triage for a bit, so this button won't work for them.

2021-07-23 06:19 UTC, Catacola commented on src/core/VitalsCaseloadButton/index.tsx
> +    currentEntitySummary.entityType !== ENTITY_TYPES.PO
```suggestion
    currentEntitySummary?.entityType !== ENTITY_TYPES.PO
```

2021-07-23 06:19 UTC, Catacola commented on src/core/VitalsCaseloadButton/VitalsCaseloadButton.scss
> +    margin-left: 6.5px;
Should these be in `(r)em` so the button scales?

2021-07-23 18:04 UTC, jovergaag commented on src/core/VitalsCaseloadButton/VitalsCaseloadButton.scss
> +    margin-left: 6.5px;
I don't think so. The button and button text stay sized the same as the page size decreases since there is so much space. It looks fine even on mobile so I don't see a reason to scale down the button or font. Making the size of the icon scale down while the button remained the same would be awkward.

2021-07-26 17:40 UTC, elchao96 requested changes

2021-07-26 17:40 UTC, elchao96 commented on src/core/VitalsCaseloadButton/index.tsx
> +              path: "impersonate_user",
Apologies for the misclarification earlier, but this path should actually only be to `/` to load the home page because on the Case Triage side, we'll build the impersonate_user API request manually since we need authorization headers. so `app.recidiviz.org/?impersonated_email=[officer_email]` would be the appropriate URL.

2021-07-26 18:08 UTC, Catacola approved these changes
I have a clarification on a previous comment I left, but it's not blocking.

2021-07-26 18:08 UTC, Catacola commented on src/core/VitalsCaseloadButton/index.tsx
> +    currentEntitySummary?.entityType !== ENTITY_TYPES.PO
You should be able to consolidate this entire clause into
```
currentEntitySummary?.entityType !== ENTITY_TYPES.PO
```
If `currentEntitySummary` is `null`, `currentEntitySummary?.entityType` will evaluate to `null`, and the entire statement will evaluate to `true`, removing the need for the initial `!currentEntitySummary` check.

2021-07-26 19:45 UTC, jovergaag commented on src/core/VitalsCaseloadButton/index.tsx
> +    currentEntitySummary?.entityType !== ENTITY_TYPES.PO
Doh. True that.

2021-07-26 19:45 UTC, jovergaag commented on src/core/VitalsCaseloadButton/index.tsx
> +              path: "impersonate_user",
fixed! Thanks for catching this!

2021-07-26 20:54 UTC, elchao96 approved these changes

2021-07-26 21:00 UTC, merged