send stateCode as query param when opening methodology page
Recidiviz/pulse-dashboard pull request #1212
Opened 2021-08-07 00:00 UTC by jovergaag

## Description of the change

When opening a methodology page in a new page, we were losing the current tenant state. This adds the logic to send the stateCode as a query param to the new page, check if the user has access, sets the `currentTenantId`, the pushes the path to the history again without the query param.

Also updates the US_ID methodology copy.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1205

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-08-09 18:39 UTC, daschi requested changes
There's a couple mobx warnings and a react warning that makes me think maybe there's another way to do this? I'm still thinking through it but happy to chat more on a call about it! Let me know what you think

2021-08-09 18:39 UTC, daschi commented on src/core/PageMethodology/index.tsx
> +    tenantStore.setCurrentTenantId(stateCode);
I'm also seeing a react error that we're setting state in a render, I wonder if setting the current tenant ID from a component like this is causing the issue? Maybe there's another place we should be setting it. I'm not exactly sure yet, still thinking through it and can look at the docs a bit more too...

<img width="1046" alt="Screen Shot 2021-08-09 at 10 29 56 AM" src="https://user-images.githubusercontent.com/5402804/128752175-67073d59-f3c9-4494-9f48-47abe11faff2.png">

2021-08-10 16:45 UTC, jovergaag commented on src/core/PageMethodology/index.tsx
> +export default observer(PageMethodology);
Removing `observer` removes the other MobX warning as well.

2021-08-10 16:46 UTC, jovergaag commented on src/core/PageMethodology/index.tsx
> +    tenantStore.setCurrentTenantId(stateCode);
I think its because I'm trying to push a new location before the page has finished rendering. Removing `push({ pathname: location.pathname });` on line 35 removes this warning, but then we still have the state code query param in the path. Maybe that's ok?

2021-08-10 16:51 UTC, jovergaag commented on src/core/PageMethodology/index.tsx
> +    tenantStore.setCurrentTenantId(stateCode);
I pushed up a commit with this change, LMK what you think. I think it's ok, we still have the check that `userHasAccess` on line 33 so if the user is messing with the state code in the URL they still can't see methodology from another state.

2021-08-10 19:15 UTC, daschi approved these changes
This seems to be working well, just wanted to point out one more console error I see when manually changing the stateCode. Though that prob won't happen that much outside of recidiviz users, just want to keep it in mind in case something strange happens with this routing:

<img width="1239" alt="Screen Shot 2021-08-10 at 12 11 44 PM" src="https://user-images.githubusercontent.com/5402804/128921135-ccae4378-e4f8-4f1e-847a-0db5ba41118f.png">

2021-08-10 19:15 UTC, daschi commented on src/core/PageMethodology/index.tsx
> +  const stateCode = new URLSearchParams(location.search).get("stateCode");
Now that we're keeping it in the params, can you access stateCode from the `useParams` hook?

2021-08-10 19:15 UTC, daschi commented on src/core/PageMethodology/index.tsx
> +  if (!Methodology || (stateCode && !userHasAccess(stateCode))) {
Looks like we're checking this boolean twice, maybe we can make a constant that's just `canAccessMethodology` ?

2021-08-10 23:11 UTC, jovergaag commented on src/core/PageMethodology/index.tsx
> +  const stateCode = new URLSearchParams(location.search).get("stateCode");
No, only `dashboard` is available. `location` is available in the props but since we're using `useHistory` might as well get it from there.

2021-08-10 23:27 UTC, merged