[Security] Gate API requests by state code
Recidiviz/pulse-dashboard pull request #1237
Opened 2021-08-19 06:30 UTC by Catacola

## Description of the change

This PR adds validation to all routes of the form `/api/:stateCode/*/` (state_code being of the form us_xx) to ensure that the requester has the same state_code in their `app_metadata` from Auth0 (or is a Recidiviz user).

There is now an explicit list of routes which don't get their jwt validated and processed. All other routes (even those not of the form above) will get checked for a valid jwt by default.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)

## Related issues

Closes #1227 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-08-19 06:32 UTC, Catacola commented on server/app.js
> +if (!isDemoMode) {
@jovergaag From your demo branch, I am under the impression that this is set for local demo mode but not deployed demo mode so these checks will be enabled for the pen testers when they retest. Please correct me if I'm wrong.

2021-08-19 16:27 UTC, jessex requested changes
Thank you for this, @Catacola ! Just a few questions from me.

2021-08-19 16:27 UTC, jessex commented on server/app.js
> +  "/api/:stateCode/:metricType/refreshCache",
Why is this one "unprotected?" Is there something else happening to ensure only admins can call it?

2021-08-19 16:27 UTC, jessex commented on server/utils/validateStateCode.js
> +      (route) => pathToRegexp(route).exec(req.originalUrl) !== null
This is case-insensitive, I presume?

2021-08-19 16:27 UTC, jessex commented on server/utils/validateStateCode.js
> +    if (/us_[a-z][a-z]/.exec(reqStateCode) === null) {
Why is it that there is separate treatment for "exempted routes" and routes without stateCode in the path? Why can't the latter be explicitly listed in the former? The upside to that is it should make it so that if someone in the future mistakenly adds a route without stateCode when they meant to include stateCode, it would mean that instead of just letting requests silently next their way through, it would fail at dev time, because presumably we'd have some sort of test that ensures all routes either have stateCode or are exempted.

2021-08-19 19:38 UTC, jovergaag requested changes
This looks awesome! Just a few comments.

2021-08-19 19:38 UTC, jovergaag commented on server/utils/validateStateCode.js
> +    if (userStateCode === "recidiviz" || userStateCode === reqStateCode) {
CSG users have a `lantern` state code, which should allow access to US_PA and US_MO.

2021-08-19 19:38 UTC, jovergaag commented on server/app.js
> +  "/file/:name",
I think we need to add `/api/generateFileLink` to this list.

2021-08-19 19:38 UTC, jovergaag commented on server/utils/validateStateCode.js
> +      next();
All of our routes that are protected are formatted as `/api/:stateCode/*`. Do we want to call next here if the state code is not formatted properly? I would think we would want to send a 400?

2021-08-19 19:38 UTC, jovergaag commented on server/utils/__tests__/validateStateCode.test.js
> +  it("should call next() if stateCode in request matches state code in app_metadata", () => {
We may want to add a test with an upper case state code just to be safe.

2021-08-19 19:40 UTC, jovergaag commented on server/app.js
> +  "/file/:name",
Or maybe not? We want it to be "protected" in the sense that we are using `checkJwt` but not validating the state code. Do we need to differentiate between the two?

2021-08-19 20:42 UTC, jovergaag commented on server/utils/validateStateCode.js
> +    if (/us_[a-z][a-z]/.exec(reqStateCode) === null) {
@jessex I agree. The only route as this is written that is not "unprotected" but does not include stateCode is `/api/generateFileLink`. I think it makes sense to add that to the exempted list and add the `checkJwt` back into it.

Maybe the exempted list can be renamed to `routesWithoutStateCode` and we add the `checkJwt` back into each route individually to be very explicit. 

Since @Catacola is OOO today, I'll push up a commit to see what you think.

2021-08-19 23:32 UTC, jovergaag commented on server/utils/validateStateCode.js
> +      (route) => pathToRegexp(route).exec(req.originalUrl) !== null
Yes. I added some tests to confirm that.

2021-08-19 23:33 UTC, jovergaag commented
@jessex @daschi This is ready for another look!

2021-08-20 01:22 UTC, daschi approved these changes
🔒

2021-08-20 02:30 UTC, jessex reviewed
One question!

2021-08-20 02:30 UTC, jessex commented on server/app.js
> +if (isDemoMode) {
Sorry if I missed this, but doesn't this mean that in both local mode and in demo mode there won't be any stateCode validation, so when we deploy this and ask the pin testers to retest they'll just find the same vulnerability has before?

2021-08-20 02:30 UTC, jessex commented on server/app.js
> +app.use(
Will this apply even in demo mode above?

2021-08-20 19:11 UTC, jovergaag commented on server/app.js
> +if (isDemoMode) {
In the deployed demo app, `isDemoMode` currently resolves to `false`. I know its confusing, I was in the middle of clearing up the terminology and ENV vars and in the code when the Vitals flurry started, so it's still in this in between state. I've got a commit with this DEMO -> OFFLINE name change that I can add here to make it more clear, but I lean towards keeping those two changes isolated since they are such big changes.

The new ENV vars are in `1Password` if you wanted to look at them. In the deployed demo app environment, `IS_DEMO = false`

I did realize yesterday evening that moving the state code validation middleware to the bottom of the file, means that it was never being hit, so the commit from today fixes that. I moved it back up and the `server.test.js` now reflects the new error message from the custom middleware state code validation.

2021-08-20 19:14 UTC, jessex commented on server/app.js
> +if (isDemoMode) {
Thanks for the explanation! Yes let's keep those changes isolated from one another. I see that this should work as expected now with the latest commit and test coverage.

2021-08-20 19:15 UTC, jessex approved these changes
I think we're good to go now! Thanks so much, @jovergaag and @Catacola!

2021-08-20 19:21 UTC, jovergaag commented on server/app.js
> +app.use(
Yes. That `isDemoMode` block only overrides the `checkJwt` middleware since in the tests and in local mode we are not authorizing users. The request will fall through to the rest of the middleware and routes in demo mode (which, until I can change the name, is actually local/test mode). In the deployed demo app, `isDemoMode = false` so the the user will be authorized on every route that specifies `checkJwt`

I really apologize for the confusion here. I was trying to do the demo mode transition in steps and got pulled away before having the chance to clean everything up.

2021-08-23 19:29 UTC, jovergaag approved these changes

2021-08-23 19:41 UTC, merged