Enable users to navigate between Pathways and Practices
Recidiviz/pulse-dashboard pull request #1295
Opened 2021-09-10 13:02 UTC by nasaownsky

## Description of the change

Added `ViewNavigation` component

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1259 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

2021-09-10 19:42 UTC, jovergaag requested changes
Hi @nasaownsky, great first PR! It looks amazing.

Just a couple of small comments for some finishing touches.

In addition to the comments below, can you please add ` background-color: $marble-3;` to the `.IE11Banner` high level block in `IE11Banner.scss`. The header in on the Pathways view is slightly different than on the Core view, so we're getting a small white strip. Instead of playing with the padding across both views, let's just change the background color so it is invisible.

```
.IE11Banner {
  background-color: $marble-3;
...
}

2021-09-10 19:42 UTC, jovergaag commented on src/core/ViewNavigation/ViewNavigation.tsx
> +            A birds-eye view of staff- and region-level resources and
I see that the "staff-" is in the designs, but I think that's a mistake. Checking with the designer...

2021-09-10 19:42 UTC, jovergaag commented on src/core/PathwaysLayout.scss
> +    margin-left: 5rem;
We need the `position: fixed;` declaration here to help position the `IE11Banner`

2021-09-10 19:42 UTC, jovergaag commented on src/assets/static/images/practices.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
There's something not exactly with this SVG. There is a small discoloration inside of the dot. Can you try to re-create the SVG to see if it looks any better?

<img width="136" alt="Screen Shot 2021-09-10 at 3 19 21 PM" src="https://user-images.githubusercontent.com/5872651/132908271-ae8cce9b-c63c-4f3e-89fa-ff5d266922fc.png">

2021-09-13 12:27 UTC, nasaownsky commented on src/assets/static/images/practices.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Fixed that.

2021-09-13 12:33 UTC, nasaownsky commented on src/core/PathwaysLayout.scss
> +    margin-left: 5rem;
The two adjacent fixed elements kinda breaks the header, so my suggestion is to modify `IE11Banner ` styles if its in the `PathwayLayout` component. Tested this in IE11 and its working as expected.

2021-09-13 17:54 UTC, jovergaag commented on src/assets/static/images/practices.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Looks great now, thank you!

2021-09-13 17:57 UTC, jovergaag commented on src/core/ViewNavigation/ViewNavigation.tsx
> +            A birds-eye view of staff- and region-level resources and
It sounds like this is intentional, so leave it as is! Thank you.

2021-09-13 17:58 UTC, jovergaag commented on src/core/PathwaysLayout.scss
> +    margin-left: 5rem;
Agreed, looks great!

2021-09-13 18:02 UTC, jovergaag requested changes
I found two other issues, apologies for not catching them during the first round.

1. When clicking on the Pathways icon, the tooltip stays open until the user clicks elsewhere on the page. We want the tooltip to display on hover only.
2. This new LH nav bar is visible on the Profile page. We want it to only be visible on the Pathways page, for now. Eventually it will be visible on the Profile page, but not until we are ready to launch the new view.

2021-09-13 18:31 UTC, nasaownsky commented
Yeah, forgot to push fix for the first issue. 

As for the second - seems like this happens due to routing\data structure in `App.js`. I see that `PathwaysLayout` and `CoreLayout` uses same `CORE_TENANTS` and it somehow leads to displaying two layouts at the same time. Could you take a look at this? I poorly understand data structure in pulse for now. Thanks!

2021-09-14 22:10 UTC, jovergaag approved these changes
Looks great! Thank you @nasaownsky

2021-09-14 22:11 UTC, merged