Enable users to navigate between compartments and transitions within Pathways
Recidiviz/pulse-dashboard pull request #1301
Opened 2021-09-13 15:52 UTC by nasaownsky

## Description of the change

Added styles for navigation within Pathways

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1262 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-09-13 18:29 UTC, jovergaag requested changes
This looks great! I have a few requests, mostly around naming conventions and practices that we try to use within this code base.

Thank you.

2021-09-13 18:29 UTC, jovergaag commented on src/core/CoreConstants.scss
> +$data-forest-light: rgba(37, 99, 111, 0.07);
The naming convention that we're trying to move to (but is not super apparent in this file) for our colors is `color-name-opacity-percentage`. So this name would be `$data-forest-07`

2021-09-13 18:29 UTC, jovergaag commented on src/core/PathwaysNavigation/PathwaysNavigation.scss
> +  .PageNavigation {
While this works and looks great, we're trying to keep styles for a given component entirely within that component's scss file. So, the preferred strategy would be to pass the view name in to `PageNavigation` and use that view name as a modifier to the `PageNavigation` classname. Then the `PageNavigation.scss` file would have view specific stiles in it, something like this:

```
.PageNavigation {
  view agnostic styles...

  &--Pathways {
     Pathways specific styles...
  }

  &--Core {
    Core specific styles...
  }
}
```

This is just an idea, if you find a better way to accomplish this please feel free to move forward. But we do want to keep all `.PageNavigation` styles inside of that scss file.

2021-09-13 18:29 UTC, jovergaag commented on src/core/PathwaysNavigation/PathwaysNavigation.scss
> +      .PageNavigation--Option {
Thank you for using BEM classnames! I know that you are working off of the classnames that already exist within the `PageNavigation` component. I think we should use this opportunity to clean them up a little bit! We should use lower case for the "element" and "modifier" names.  Also, in this component, `option` is the element and `selected` is the modifier, so I think these classnames should be `.PageNavigation__option--selected`, etc.

Thanks for doing this cleanup!

2021-09-13 18:29 UTC, jovergaag commented on src/core/PathwaysNavigation/PathwaysNavigation.scss
> +  .PageNavigation {
Within the next few months the Core views will be deprecated, so we can clean this component/styling up at that point.

2021-09-14 16:22 UTC, nasaownsky commented
Fixes arrived! 🚀

2021-09-15 14:29 UTC, jovergaag approved these changes

2021-09-15 14:29 UTC, jovergaag commented on src/core/PageNavigation.scss
> +  &--Pathways {
This is a little bit redundant and messy now...but it will be short lived and we can clean it up once Core is deprecated. Thanks for making this change!

2021-09-15 14:30 UTC, merged