Added user profile & methodology navigations to the sidebar
Recidiviz/pulse-dashboard pull request #1302
Opened 2021-09-15 09:28 UTC by nasaownsky

## Description of the change

1. Allow users to access the user profile from the new sidebar navigation 
2. Allow users to navigate to the Methodology from the sidebar navigation

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1260 , closes #1261 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-09-15 13:19 UTC, nasaownsky commented
Looking through the Issues I also thought that I could hook #1300 and reuse `TopBarUserMenuForAuthenticatedUser` in `ViewNavigation`. And it works as expected, but also needs some cleanup. I see that in `TopBarUserMenuForAuthenticatedUser` we using `slyled-components`, so should I leave it there or create separate .scss file for styles?

2021-09-15 19:21 UTC, jovergaag commented
> Looking through the Issues I also thought that I could hook #1300 and reuse `TopBarUserMenuForAuthenticatedUser` in `ViewNavigation`. And it works as expected, but also needs some cleanup. I see that in `TopBarUserMenuForAuthenticatedUser` we using `slyled-components`, so should I leave it there or create separate .scss file for styles?

That sounds like a good plan! As long as you're able to maintain the styling such that the tooltip is styled properly depending on which view the user is on. I think it makes sense to remove (or rename) the `TopBarUserMenuForAuthenticatedUser` component and just create a `UserAvatar` component that can be used in both places! And yes, please move it to .scss instead of a styled component.

Thank you!

2021-09-15 19:55 UTC, jovergaag requested changes

2021-09-15 19:55 UTC, jovergaag commented on src/core/ViewNavigation/ViewNavigation.tsx
> +              <ExternalLinkLogo />
This external link logo exists in our design-system. Can you please use the "Open" icon from the design system, similar to how it is done in `PracticesCaseloadButton`.

2021-09-15 19:55 UTC, jovergaag commented on src/core/PathwaysLayout.scss
> +    z-index: 2;
I think because of the `aside` the header is in a different z-index layer than these tooltips. I was able to make the header/tooltip/filter bar work for all views. If we ever need more breathing room in the z-index we will need to figure something else out, but this is working for now.

2021-09-16 10:40 UTC, nasaownsky commented
@jovergaag Share your thoughts about `UserAvatar`, and if it'll do I'll remove `TopBarUserMenuForAuthenticatedUser `.

2021-09-16 10:42 UTC, nasaownsky commented on src/core/PathwaysLayout.scss
>      position: fixed;
Also, do we need this change back? I remember we get rid of it in #1295

2021-09-16 15:41 UTC, jovergaag commented on src/core/PathwaysLayout.scss
>      position: fixed;
We did, but I ended up adding it back in because the position of the `IE11Banner`, and its scrolling behavior was wrong on the Pathways page without it.

2021-09-16 15:48 UTC, jovergaag commented
> @jovergaag Share your thoughts about `UserAvatar`, and if it'll do I'll remove `TopBarUserMenuForAuthenticatedUser `.

I like the `UserAvatar`. I think you should go for it and remove `TopBarUserMenuForAuthenticatedUser `. Thanks!

I'll approve once those tests are passing!

2021-09-16 16:04 UTC, nasaownsky commented on src/core/PathwaysLayout.scss
>      position: fixed;
Maybe this problem was without `padding-top: 0;`  in `.IE11Banner` of `PathwaysLayout`? It positions and scrolls fine with this property as I know .

2021-09-16 17:45 UTC, nasaownsky commented on src/core/PathwaysLayout.scss
>      position: fixed;
Nevermind, I found and fixed header issue. We can keep it.

2021-09-17 15:38 UTC, jovergaag approved these changes

2021-09-17 15:38 UTC, merged