Build "no data"/error states
Recidiviz/pulse-dashboard pull request #1337
Opened 2021-09-23 13:44 UTC by nasaownsky

## Description of the change

Adds `ChartErrorView` component and implements "No Data" & Error states for existing Pathways charts.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1314 
Closes #1315 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-09-23 13:48 UTC, nasaownsky commented on src/components/ChartErrorView/ChartErrorView.tsx
> +      logout({ returnTo: window.location.origin });
`logout` doesn't seem to be working. Is it intended?

2021-09-23 13:48 UTC, nasaownsky commented on src/core/PopulationTimeSeriesChart/index.tsx
> +          onResetFilters={() => null}
Here we need to clear all filters. Any ideas?

2021-09-23 21:59 UTC, jovergaag requested changes
Hi @nasaownsky, this is looking good! I made a few suggestions about how to organize it a little differently. Take a look and let me know what you think.

2021-09-23 21:59 UTC, jovergaag commented on src/core/PopulationTimeSeriesChart/index.tsx
> +        <ChartErrorView
I think what we want is to actually implement this inside of `ModelHydrator`. There is already a check there for `error`,  we would want to add the check for `noData` and just render this component from there!

If we implement this from the `ModelHydrator`, we don't have to worry about doing this loading/error/noData check inside of each visualization, and we can just wrap each viz with the `withMetricHydrator`.

2021-09-23 21:59 UTC, jovergaag commented on src/core/PopulationTimeSeriesChart/index.tsx
> +          onResetFilters={() => null}
You would want to import `defaultPopulationFilterValues` from `filterOptions.ts` and then 

`onResetFilters={() => filtersStore.setFilters(defaultPopulationFilterValues)}`

I think that will work, give it a try and let me know if it doesn't work as expected.

2021-09-23 21:59 UTC, jovergaag commented on src/components/ChartErrorView/ChartErrorView.tsx
> +      {isNoData ? <NoDataLogo /> : <ErrorLogo />}
This feels like a lot of logic inside of the component. Can you try making a `Error` component and a separate `NoData` component. They could inherit from the same parent component to avoid duplicate styling. I just think it would be nice to keep these a little more clean and easier to see immediately what is going to be rendered without having to think through the logic.

Another option is to pass the icon, button component, and subtitle component in to this `ChartErrorView` and this component just renders them directly. 

It could be something like this inside of `ModelHydrator`:
```
        <ChartErrorView
          title="Sorry, we're having trouble loading this chart"
          subTitle={
            <>
              Try reloading the page. If that doesn’t work, log out and log back
              in.
              <br />
              Contact us at{" "}
              <a href="mailto:feedback@recidiviz.org">
                feedback@recidiviz.org
              </a>{" "}
              if the issue continues.
            </>
          }
          image={<ErrorLogo />}
          callToAction={
            <>
              <button type="button" onClick={onReload}>
                Reload
              </button>
              <button type="button" onClick={onLogout}>
                Log out
              </button>
            </>
          }
        />
```

2021-09-23 21:59 UTC, jovergaag commented on src/components/ChartErrorView/ChartErrorView.tsx
> +      logout({ returnTo: window.location.origin });
I tested it and It is working exactly like this! You are running in offline without ever logging in to our auth server, so the logout is not applicable in your environment.

2021-09-24 13:53 UTC, nasaownsky commented
@jovergaag I made some improvements, check this out!

2021-09-24 21:07 UTC, jovergaag requested changes
Looks so much better, feels much more usable now! A few more suggestions about the chart container styles.

2021-09-24 21:07 UTC, jovergaag commented on src/core/PageProjections/index.tsx
> +      <PathwaysChartCard>
Is there any way we can render this from inside of the `ModelHydrator` instead so that we don't have to wrap every new chart with it? We could either wrap each of the status components with it, or add these styles to the `StatusWrapper` and wrap the `done` status branch with the same `StatusWrapper`. Play around with that and let me know what you think! It would just be nice to avoid needing to remember to wrap every chart with this card/container component.

2021-09-27 11:03 UTC, nasaownsky commented on src/core/PopulationTimeSeriesChart/index.tsx
> +    return <div className="PopulationTimeSeriesChart" />;
I don't know exactly why this was used in the first place, but without this lines app crashes. Seems like some problem with compartment usage.

2021-09-27 11:04 UTC, nasaownsky commented on src/core/ModelHydrator.tsx
> +    <PathwaysChartCard>
We can use `PathwaysChartCard ` like this.

2021-09-27 17:43 UTC, nasaownsky commented on src/core/PopulationSummaryMetrics/index.tsx
> +  if (isLoading || isError) {
Hooked up #1316, and seems like this component also not working without this statement.

2021-09-27 22:04 UTC, jovergaag approved these changes
When I sent the screenshots to the designer, @soniachokshi she said that she had a hard time figuring out if they were screenshots of the app or of the design. I can't think of a nicer compliment than that from a designer :)

WELL DONE @nasaownsky!

2021-09-27 22:04 UTC, merged