Build responsive navigation
Recidiviz/pulse-dashboard pull request #1354
Opened 2021-09-29 17:32 UTC by nasaownsky

## Description of the change

1. Improved Practices responsive layout
2. Added basic `MobileNavigation` component

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

Closes #1325 
Closes #1327 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-09-29 21:14 UTC, jovergaag commented on src/core/CoreConstants.scss
> +$font-ui-serif-24: 400 2.125rem/3rem $serif;
I don't see that this is being used anywhere.

2021-09-29 21:16 UTC, jovergaag commented
Looks like this is still a draft and you're still working, so far looks good!

2021-09-30 18:00 UTC, nasaownsky commented on src/core/CoreConstants.scss
> +$font-ui-serif-24: 400 2.125rem/3rem $serif;
Fixed! It is used in `title` of `MobileNavigation`

2021-09-30 19:52 UTC, jovergaag requested changes
This is looking better! I would love to see if we can find a way to style the `PathwaysLeftPanel` for mobile rather than add the separate component. Give that a try, if it is not working out then we can go back to this!

Another thing I found that is an existing bug but we should clean up here: these cards should fit onto a row and the filters should not wrap.
Design:
![Screen Shot 2021-09-30 at 12 51 01 PM](https://user-images.githubusercontent.com/5872651/135521197-ce8f0eeb-a119-4321-9bab-ddab008dced2.png)

implementation:
![Screen Shot 2021-09-30 at 12 51 45 PM](https://user-images.githubusercontent.com/5872651/135521259-2100b141-660a-4efb-abf8-c87768466191.png)


Another thing I just noticed, the 1024 width is a little funky, we seem to have lost the top nav..
![Screen Shot 2021-09-30 at 12 52 54 PM](https://user-images.githubusercontent.com/5872651/135521444-abda9628-f2f0-4fa4-b7ae-2b51263e2096.png)

2021-09-30 19:52 UTC, jovergaag commented on src/components/Drawer/index.ts
> -}
Was removing this unintentional?

2021-09-30 19:52 UTC, jovergaag commented on src/core/MobileNavigation/MobileNavigation.tsx
> +          kind={IconSVG.Hamburger}
@soniachokshi We are using the design-system hamburger icon here, but it looks slightly different than in the designs. Which do you prefer?

This is from the design-system
![Screen Shot 2021-09-30 at 12 36 15 PM](https://user-images.githubusercontent.com/5872651/135519448-e749a7fd-5769-4031-aceb-132acfbe4840.png)

2021-09-30 19:52 UTC, jovergaag commented on src/core/MobileNavigation/MobileNavigation.tsx
> +const MobileNavigation: React.FC<Props> = ({ title, children }) => {
Is there anyway to style the `PathwaysLeftPanel`  differently for mobile to accomplish this instead of creating this new component? Its all of the same components and put the `Drawer` directly in the `PathwaysLayout`?

2021-09-30 19:52 UTC, jovergaag commented on src/core/PagePractices/PagePractices.scss
> +    gap: 1.5rem;
Something is happening with the Practices page for me on mobile when accessed from the `ViewNavigation` inside of the drawer, it doesn't scroll. It also doesn't have the Mobile nav header/navigation

![Screen Shot 2021-09-30 at 12 44 29 PM](https://user-images.githubusercontent.com/5872651/135520342-16e82895-c587-4cb7-bff1-3a5b8742f36f.png)
.

2021-09-30 19:52 UTC, jovergaag commented on src/core/ViewNavigation/ViewNavigation.tsx
> +  if (mobile) {
On mobile, we need to have the page navigation embedded within the view navigation. 
![Screen Shot 2021-09-30 at 12 47 54 PM](https://user-images.githubusercontent.com/5872651/135520750-3cd7564b-2342-4582-8722-97662e125066.png)

2021-09-30 19:52 UTC, jovergaag commented on src/core/ViewNavigation/ViewNavigation.tsx
> +            <div className="ViewNavigation__navlink-heading">Profile</div>
We need to make Both the icon and the div clickable. Its a little confusing to click on "Profile" and it doesn't navigate anywhere!

2021-10-01 12:29 UTC, nasaownsky commented on src/core/MobileNavigation/MobileNavigation.tsx
> +const MobileNavigation: React.FC<Props> = ({ title, children }) => {
`PathwaysLeftPanel ` is component, that is only rendered inside `PagePathways`. And we need this nav block on other different pages like `PagePractices` and `PathwayProfile`, like you has mentioned above. So using it like this is more convenient, I think.

2021-10-01 12:29 UTC, nasaownsky commented on src/core/PagePractices/PagePractices.scss
> +    gap: 1.5rem;
Fixed

2021-10-01 12:29 UTC, nasaownsky commented on src/core/ViewNavigation/ViewNavigation.tsx
> +            <div className="ViewNavigation__navlink-heading">Profile</div>
Fixed

2021-10-01 13:24 UTC, nasaownsky commented on src/core/ViewNavigation/ViewNavigation.tsx
> +  if (mobile) {
Added

2021-10-01 13:28 UTC, nasaownsky commented
@jovergaag 

> Another thing I found that is an existing bug but we should clean up here: these cards should fit onto a row and the filters should not wrap.

On sizes between 1024px and 768px filters will not wrap, but on smaller sizes they should, otherwise they'll break layout.

2021-10-01 15:13 UTC, soniachokshi commented on src/core/MobileNavigation/MobileNavigation.tsx
> +          kind={IconSVG.Hamburger}
Can we use the icon in the designs? I'll work with Juan to consolidate them later, since I think the one that I used in the designs is more versatile. Thanks!

2021-10-04 17:55 UTC, jovergaag requested changes
WOW, this looks amazing. 

The designer said "what is this magic", which is a very good thing. Very well done @nasaownsky!

There are two remaining issues that I found that aren't commented below.
- This wasn't part of the ticket I don't think, but we might as well address it here. The chart axis labels get squished together on the narrower screen widths. Can you please check the screen width and render fewer ticks on the x axis in `PopulationTimeSeriesChart`
- Something in this new styling has removed the padding between the `PracticesSummaryCard`s. 
![Screen Shot 2021-10-04 at 10 54 36 AM](https://user-images.githubusercontent.com/5872651/135900288-6118ac17-7ae7-4a5b-8fcf-ac9b3778f7b1.png)
-

2021-10-04 17:55 UTC, jovergaag commented on src/components/Drawer/Drawer.tsx
> +  }
This whole effect is super smooth. Well done!

2021-10-04 17:55 UTC, jovergaag commented on src/core/PagePractices/index.tsx
> +    <PageTemplate mobileNavigation={<MobileNavigation title={stateName} />}>
The `PracticesSummaryBreadcrumbs` here need to be styled for responsive. They should be folded into the `ViewNavigation` I believe.
![Screen Shot 2021-10-04 at 10 14 29 AM](https://user-images.githubusercontent.com/5872651/135895121-1b6a9623-1a97-47c8-8b6b-6d2ef127d04c.png)

vs Design:
![Screen Shot 2021-10-04 at 10 16 28 AM](https://user-images.githubusercontent.com/5872651/135895201-428f84dc-677f-4420-9db1-6b7730d0116b.png)

2021-10-04 17:55 UTC, jovergaag commented on src/core/PathwaysProfile/PathwaysProfile.tsx
> +    <PageTemplate mobileNavigation={<MobileNavigation title="Profile" />}>
Amazing, thank you.

2021-10-04 17:55 UTC, jovergaag commented on src/core/PathwaysLayout.tsx
> -            <Footer />
I think we might want to leave this here. I know that it is not in the designs but I think that is an oversight. Checking with the designer...

2021-10-05 23:59 UTC, nasaownsky commented
Hey, @jovergaag! Thanks for great review, really appreciate it! I made several improvements and fixes, so check it out and leave your thoughts.

2021-10-06 01:11 UTC, jovergaag requested changes
Lots of progress! I like the `useIsMobile` hook.

There are still a couple more things to be cleaned up, but its getting very close!

2021-10-06 01:11 UTC, jovergaag commented on src/core/PathwaysLayout.scss
> +    @media screen and (max-width: $core-breakpoint-sm) {
I think this is what is causing the 1024 width resolution to be funky. I think?
![Screen Shot 2021-10-05 at 5 52 56 PM](https://user-images.githubusercontent.com/5872651/136124417-6e442a95-45f2-44a7-8b3d-09eda857492a.png)

2021-10-06 01:11 UTC, jovergaag commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        </NavLink>
I'm worried about the mobile getting out of sync with the desktop if we want to make a change to something like the `path` or the `onClick`, its possible that we would update one but not the other not realizing that they are nearly duplicate. Can you pull these `NavLink` components out and re-use them in the mobile/non-mobile renderings. I think your approach of the completely separate dom and classnames is a good one, we should just try to re-use the things that are the same.

2021-10-06 01:11 UTC, jovergaag commented on src/hooks/useIsMobile.ts
> +    const handleResize = () => setIsMobile(window.innerWidth < 1024);
Or maybe its this hook that is causing the 1024 width to be funky.

2021-10-06 01:11 UTC, jovergaag commented on src/hooks/useIsMobile.ts
> +    const handleResize = () => setIsMobile(window.innerWidth < 1024);
Oh, `<=`

2021-10-06 20:10 UTC, jovergaag requested changes
Just one more thing. Sorry to not catch it before!

2021-10-06 20:10 UTC, jovergaag commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        <ProfileNavLink />
Oh thats nice.

2021-10-07 22:28 UTC, merged