Create "Additional Filters" modal
Recidiviz/pulse-dashboard pull request #1408
Opened 2021-10-18 16:55 UTC by nasaownsky

## Description of the change

Howdy! I worked on this issue a few days and realized just today, that I need changes from #1393 firstly to make this working. But I already have done all UI, so I just spread existing filters on this new UI to make sure that all is working right. So check this out and leave your thoughts and I'll get back to them as soon as I finish with #1393. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1391 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-10-18 20:22 UTC, jovergaag commented on src/core/MoreFilters/MoreFilters.tsx
> +        {enabledFilters.map((filterType) => {
We will only want to show a subset of the filters in the modal. So some of the filters are available on the main page, and a subset are accessed via this modal. It is a different set of filters on the page/modal depending on tenant.

2021-10-18 20:26 UTC, jovergaag commented on src/components/Radio/Radio.tsx
> +const Radio: React.FC<Props> = ({
A few suggestions here. 

We will want these to be multi-select checkboxes instead of single-select radio inputs. Meaning, the user can select multiple of the filter options in the `AGE` section. This means, that by default 'All' is selected, but when the user selects another checkbox, 'All' automatically is de-selected and the other checkbox is active. The user can then select additional ages and they are active. If the user selects each of the age groups, 'All' will automatically become selected and the other checkboxes de-select.

There is logic for this in the `MultiSelect` component handleChange.

2021-10-18 20:29 UTC, jovergaag commented on src/components/Radio/Radio.tsx
> +const Radio: React.FC<Props> = ({
So you may need to create a component named something like `CheckboxGroup` or `MultiCheckboxGroup` or something along those lines to group all of those `input` fields.

2021-11-01 11:58 UTC, nasaownsky commented
@jovergaag So I succeeded in adding logic to this new `CheckboxGroup` component, but still need help in testing and  filters update handling.

2021-11-01 17:54 UTC, jovergaag commented on src/core/CoreStore/MetricsStore.ts
> +      enabledMoreFilters: [FILTER_TYPES.AGE, FILTER_TYPES.FACILITY],
Internally we have been calling these additional filters, so lets call this `enabledAdditionalFilters`.

2021-11-01 22:34 UTC, jovergaag commented
> @jovergaag So I succeeded in adding logic to this new `CheckboxGroup` component, but still need help in testing and filters update handling.

Hi @nasaownsky I worked on the filters today for a few hours and have made good progress but they're not done yet. Instead of pushing up a partially done commit I'll just pick it up again tomorrow.

In the mean time, you can start on the population by facility chart issue!

2021-11-02 18:19 UTC, jovergaag commented
@nasaownsky I updated the `MoreFilters` component to have working filtering functionality. It is quite quick and dirty and should definitely be cleaned up a little and tested. I'm happy to pick this up tomorrow again unless you want to look at it first.

There are a couple of other things that need to happen still:
- "Reset Filters" should use `setQuery` instead of resetting the filters store. That will update the query params which will automatically update the filters store. 
- The "More Filters" label should only show the number of filters that are set, instead of the number of filters available. So, if all of the filters in the modal are set to default, the label would be: <img width="141" alt="Screen Shot 2021-11-02 at 2 18 04 PM" src="https://user-images.githubusercontent.com/5872651/139922483-e3306b80-51d5-4ffd-865b-205f6aa154fc.png">. But if two of the filters in the modal are set it would be: <img width="151" alt="Screen Shot 2021-11-02 at 2 18 57 PM" src="https://user-images.githubusercontent.com/5872651/139922582-ce433a37-9af0-4383-919d-bf5802f233f0.png">
- We also need some tests for the new filtering logic. I'm happy to pick that up tomorrow if you are not able to get to it!

2021-11-04 00:59 UTC, jovergaag commented
@nasaownsky We decided to merge this as is to get the filter functionality in sooner than later, then I will create issues to  redesign the select/multi-select functionality now that we have more clarity from the PM on which filters are multi-select.  I'll do the code review tomorrow and we may be able to land it tomorrow!

2021-11-08 21:34 UTC, jovergaag requested changes
@nasaownsky I'm sorry for the delay reviewing this! I was out sick the last couple days last week.

Just a few small things here to address then we're all set!

2021-11-08 21:34 UTC, jovergaag commented on src/core/PathwaysFilterBar/PathwaysFilterBar.tsx
> +  });
Can we do this in `MoreFilters`? If not, lets call it `activeFiltersCount` instead of `filtersAmount`

2021-11-08 21:34 UTC, jovergaag commented on src/core/controls/CheckboxGroup.tsx
> +      }
This is all fairly complex. Can you please put a comment above each if statement explaining what that branch of logic is doing?

2021-11-08 21:37 UTC, jovergaag commented on src/core/MoreFilters/MoreFilters.scss
> +      flex: 0 32%;
During design review we decided to make this two columns instead of 3 for all filters.

2021-11-08 21:41 UTC, jovergaag commented on src/core/CoreStore/MetricsStore.ts
> +      enabledMoreFilters: [FILTER_TYPES.AGE, FILTER_TYPES.FACILITY],
During design review we decided to change which filters are `enabledFilters`. For this metric:
enabledFilters: time_period, gender, facility, 
enabledMoreFilters: age, legal_status

2021-11-08 21:50 UTC, jovergaag commented on src/core/controls/CheckboxGroup.tsx
> +      {enabledOptions.map((option) => {
In the design review we decided that it would be nice to alphabetize the `enabedOptions` - the same will be true when the facility filter moves into the Select dropdown on the page instead of in the modal, the options should be in alphabetical order. 

It have a task this week to create a multi-select dropdown so don't worry about making the facility filter multi-select when you move it out of the modal.

2021-11-08 22:52 UTC, jovergaag commented
@nasaownsky This PR should be your first priority as you work through all of these reviews. I would love to land it tomorrow (Tuesday). Thank you!

2021-11-09 12:35 UTC, nasaownsky commented
@jovergaag Welcome back, glad to see you in good health! PR now should be ready to land. 🚀

2021-11-10 01:50 UTC, jovergaag approved these changes

2021-11-10 01:51 UTC, merged