[Pathways][US_TN] Create facility population metric
Recidiviz/pulse-dashboard pull request #1427
Opened 2021-11-01 03:47 UTC by Catacola

## Description of the change

This PR creates a new metric `prisonFacilityPopulation` of type `PopulationSnapshotMetric` along with a skeleton viz which shows the current age, gender, and legal status of the selected data as a quick proof of having the data piped correctly.

The data for these population views are derived from the time series data. This could be changed lated for efficiency issues.

To repeat, `VizPopulationSnapshot` is a dummy class and it should be completely rewritten in the near future.

Create 
## Type of change

- [x] New feature (non-breaking change that adds functionality)

## Related issues

Beginning of #1417

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-11-01 16:11 UTC, jovergaag requested changes

2021-11-01 16:11 UTC, jovergaag commented on src/core/models/utils.ts
> +    )
I wonder if this filter should be in the `PopulationSnapshotMetric` since for all of these snapshots by dimension we will always want to most recent date?

2021-11-01 16:11 UTC, jovergaag commented on src/core/models/PopulationSnapshotMetric.ts
> +        record.facility !== "ALL"
Should this facility filter be in `createFacilityPopulationSnapshot` since it is only ever needed for the facility chart? Other population by dimension charts will want the "ALL" row.

2021-11-01 16:11 UTC, jovergaag commented on src/core/models/PopulationSnapshotMetric.ts
> +export default class PopulationSnapshotMetric extends PathwaysMetric<PopulationSnapshotRecord> {
I created an issue #1428 to write tests for this since we want to land it today without tests. Can you put a TODO in here please.

2021-11-01 16:53 UTC, Catacola commented on src/core/models/utils.ts
> +    )
You make a very good point. I'll make that change.

2021-11-01 16:53 UTC, Catacola commented on src/core/models/PopulationSnapshotMetric.ts
> +        record.facility !== "ALL"
100% true.

2021-11-01 16:53 UTC, Catacola commented on src/core/models/PopulationSnapshotMetric.ts
> +export default class PopulationSnapshotMetric extends PathwaysMetric<PopulationSnapshotRecord> {
Will do!

2021-11-01 17:37 UTC, jovergaag approved these changes

2021-11-01 22:36 UTC, jovergaag commented
@nasaownsky This PR is almost finished, you should base the facility population chart off of this branch. I will send you the updated fixture.

2021-11-02 18:39 UTC, jovergaag reviewed
@nasaownsky I am waiting for an answer to a question from the product manager and designer about filter behavior. In the other chart for US_TN, facility and age are multi-select, but in this chart, facility is single select which seems confusing and complex to me. I need to find out more detail about the intended behavior of these filters before moving forward here. I will let you know what I find out.

In the mean time, can you pull your commit into a separate branch please and we will merge this branch separately since it does not require the filters question to be cleared up.

2021-11-02 18:39 UTC, jovergaag commented on src/core/PathwaysTooltip/PathwaysTooltip.tsx
> +  average?: string;
Why is this optional?

2021-11-03 22:46 UTC, jovergaag approved these changes

2021-11-03 22:46 UTC, merged