Nasaownsky/1417 facility population chart
Recidiviz/pulse-dashboard pull request #1433
Opened 2021-11-03 13:43 UTC by nasaownsky

## Description of the change

Adds facility population chart.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1417 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-11-03 13:47 UTC, nasaownsky commented on src/core/PathwaysTooltip/PathwaysTooltip.tsx
> +  average?: string;
This is optional because in mocks we don't have average value or any 3rd entry in the tooltip of facility population chart. @jovergaag

2021-11-04 00:33 UTC, jovergaag requested changes
Just very small changes! Looks great thank you!

2021-11-04 00:33 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  if (!dataSeries) return <div className="ChartCountOverTimeWithAvg" />;
Shouldn't this be covered with the `HydrationStatus` wrapper component?

2021-11-04 00:33 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +        <div className="PopulationTimeSeriesChart__Header">
These BEM element names should be lower case `PopulationTimeSeriesChart__header`

2021-11-04 13:48 UTC, nasaownsky commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  if (!dataSeries) return <div className="ChartCountOverTimeWithAvg" />;
Good point.

2021-11-04 13:48 UTC, nasaownsky commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +        <div className="PopulationTimeSeriesChart__Header">
fixed

2021-11-08 21:55 UTC, jovergaag requested changes
This looks great! Love how easily it came together!!

There are a few comments that came out of design review on styling [here](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=3409%3A537).

2021-11-09 15:30 UTC, nasaownsky commented
@jovergaag In order to style and made work everything as desired, I created the `useIsDisplayPageNavigation` hook, which which returns true if there is more than one page Option. And it's working as expected, but also throws a bunch of test fails. So my question is: should I remove this hook (but then i can't make proper styling), or maybe there's solution that I can not find for now?

2021-11-10 03:33 UTC, jovergaag commented
> @jovergaag In order to style and made work everything as desired, I created the `useIsDisplayPageNavigation` hook, which which returns true if there is more than one page Option. And it's working as expected, but also throws a bunch of test fails. So my question is: should I remove this hook (but then i can't make proper styling), or maybe there's solution that I can not find for now?

I spent some time trying to figure out a better solution, but with the sticky `PathwaysLeftPanel` it is very challenging to move the whole PageTemplate up as one unit! I think your solution looks great.

I think there are 2 things that need to be done to get the tests to pass:
1. Add this to line 43 of `PathwaysFilterBar.test`
```
(useRootStore as jest.Mock).mockReturnValue({
    userStore: { userAllowedNavigation: {} },
  });
```
2. We also need to determine if the tenant is a PATHWAYS_TENANT or CORE_TENANT and only apply this new treatment to Pathways tenants in `FilterBar`. That should get `CoreFilterBar.test` to pass and also fix the Core layout page.

Let me know how that goes!

2021-11-10 03:36 UTC, jovergaag commented
Also, once you merge main, now that the facility filter is multi-select, there will need to be a little work done on `setPickedId` to choose from an array instead of a single value.

2021-11-10 18:54 UTC, jovergaag requested changes
Two small changes requested from design review

2021-11-10 18:54 UTC, jovergaag commented on src/core/SectionNavigation/SectionNavigation.tsx
> +      <div className="SectionNavigation__title" />
Eventually we will want to show/hide this depending on how many sections there are. But this is fine for now until we add more sections.

2021-11-10 18:54 UTC, jovergaag commented on src/core/SectionNavigation/SectionNavigation.scss
> +    color: $pine-1;
Feedback from design review: please change the bottom margin so that it is 32px

2021-11-10 18:54 UTC, jovergaag commented on src/core/PathwaysFilterBar/PathwaysFilterBar.tsx
> +                options={sortByLabel(filter.options, "label")}
Feedback from design review: let's sort all of the filters by their label except TIME_PERIOD. That one should have "6 months" at the top, and then "1 year", "2 years", and "5 years" at the bottom (increasing lengths of time)

2021-11-10 20:19 UTC, jovergaag approved these changes
It looks amazing. Well done and thank you!

2021-11-10 20:31 UTC, merged