Create "List of people in prison" table
Recidiviz/pulse-dashboard pull request #1435
Opened 2021-11-05 14:07 UTC by nasaownsky

## Description of the change

Added "List of people in prison" table

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1432 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-11-08 22:51 UTC, jovergaag requested changes
This looks amazing! So nice and clean, and we love the sorting of the columns, thank you!

I made a few suggestions and decided to change the name of the metric (sorry). I will send you the updated fixture with the new `age_group`/`age` column change.

2021-11-08 22:51 UTC, jovergaag commented on src/core/VizIncarcerationPopulation/VizIncarcerationPopulation.tsx
> +    ],
Eventually these will change depending on the state/tenant so we would want to put this in `tenants.ts`. I think its fine here for now unless you want to move it!

2021-11-08 22:51 UTC, jovergaag commented on src/core/VizIncarcerationPopulation/VizIncarcerationPopulation.tsx
> +        accessor: "age",
Even though it wasn't in the designs, we loved the sorts! Thank you! Can you add the sort for gender, facility, and legal_status as well? Alphabetical is fine.

2021-11-08 22:51 UTC, jovergaag commented on src/core/PopulationTimeSeriesChart/PopulationTimeSeriesChart.scss
> +    }
If we change the classname in the `VizIncarcerationPopulation` we probably don't need this.

2021-11-08 22:51 UTC, jovergaag commented on src/components/PathwaysTable/PathwaysTable.tsx
> +                return <td {...cell.getCellProps()}>{cell.render("Cell")}</td>;
We want to title case `gender` and `legalStatus` rows. Maybe that can be done in the metric's `createIncarcerationPopulationList` transformer?

2021-11-08 22:51 UTC, jovergaag commented on src/core/VizIncarcerationPopulation/VizIncarcerationPopulation.tsx
> +  const latestUpdate = max(dataSeries.map((d) => d.lastUpdated)) || new Date();
I think we want to put "Unknown" instead of the new date if `lastUpdated` is not defined.

2021-11-08 22:51 UTC, jovergaag commented on src/core/views.ts
> +  countByName: "countByName",
lets call this `personLevelDetail` instead of `countByName`

2021-11-08 22:51 UTC, jovergaag commented on src/core/models/utils.ts
> +      age: record.age as Age,
During design review we decided to add an additional column here. We will have `age_group` and `age`. `age_group` will replace the existing `age` and the new `age` will have the individual person's actual age. Filtering will happen on `age_group` and `age` will be displayed in the table.

I will send you the new fixture for this.

2021-11-08 22:51 UTC, jovergaag commented on src/core/models/IncarcerationPopulationMetric.ts
> +export default class IncarcerationPopulationMetric extends PathwaysMetric<IncarcerationPopulationRecord> {
I'm very sorry for this but I've decided to change the name of this metric. It was just too confusing when talking with people in the organization because we have another metric with similar name but very different meaning.

Let's call this `IncarcerationPopulationPersonLevel`. This name change should then ripple out to the types and record and viz. I will send you a new fixture with the updated file name.

2021-11-08 22:51 UTC, jovergaag commented on src/core/models/IncarcerationPopulationMetric.ts
> +      filter === "ALL" ? recordFilter !== "ALL" : recordFilter === filter;
Nice!

2021-11-08 22:51 UTC, jovergaag commented on src/core/VizIncarcerationPopulation/VizIncarcerationPopulation.tsx
> +    <div className="PopulationTimeSeriesChart">
With the metric name change, the classname will be updated to match!

2021-11-10 14:46 UTC, nasaownsky commented on src/core/VizIncarcerationPopulation/VizIncarcerationPopulation.tsx
> +  const latestUpdate = max(dataSeries.map((d) => d.lastUpdated)) || new Date();
we need this for `formatDate` when `noData` triggers. it accepts only date type

2021-11-10 18:49 UTC, jovergaag requested changes
This new naming convention makes so much more sense. Thank you for doing that!

Just two small changes requested. Design review is all good!

2021-11-10 18:49 UTC, jovergaag commented on src/core/VizIncarcerationPopulationPersonLevel/VizIncarcerationPopulationPersonLevel.tsx
> +      },
We do not need this Age Group column.

2021-11-10 18:49 UTC, jovergaag commented on src/core/models/IncarcerationPopulationPersonLevelMetric.ts
> +      this.compartment === "SUPERVISION" ? supervisionType : legalStatus;
This compartment will only ever be "INCARCERATION" so we will always use `legalStatus` here.

2021-11-10 20:16 UTC, jovergaag approved these changes
Woot! Thank you!

2021-11-10 20:35 UTC, merged