Add "As of [date]" to prison population by facility chart
Recidiviz/pulse-dashboard pull request #1454
Opened 2021-11-16 17:32 UTC by nasaownsky

## Description of the change

1. Added "As of [date]" to prison population by facility chart
2. Resolved Pathways TN no data error state crashing page

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1443 
Closes #1446 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-11-16 18:56 UTC, jovergaag requested changes

2021-11-16 18:56 UTC, jovergaag commented on src/core/PopulationTimeSeriesChart/PopulationTimeSeriesChart.tsx
> +      : new Date(),
I think we probably want to return undefined or an empty div on line 57 if `historicalPopulation.length < 1`. If there is no historical population data we will not want to render the chart

2021-11-16 18:56 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  const latestUpdate = max(dataSeries.map((d) => d.lastUpdated)) || new Date();
These snapshots will all have the same date, so you can just take the first item in `dataSeries` and use its `lastUpdated` to improve performance of this chart. We should also default to "Unknown" here if there is no `lastUpdated` date.

I'm realizing now that we should make this same adjustment in `VizPopulationPersonLevel.tsx` on line 37.

2021-11-16 19:13 UTC, nasaownsky commented on src/core/PopulationTimeSeriesChart/PopulationTimeSeriesChart.tsx
> +      : new Date(),
This task is performed by ModelHydrator. The error throws when interpreter tries to access historicalPopulation[0] element. The empty div or null doesn't work in that case.

2021-11-16 19:27 UTC, nasaownsky commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  const latestUpdate = max(dataSeries.map((d) => d.lastUpdated)) || new Date();
I don't quite understand what you mean by "Unknown". formatDate accepts only Date type, so if there's no data we need Date object. It will not be used anywhere, just prevents error throwing. Everything else handled by ModelHydrator.

2021-11-16 19:36 UTC, jovergaag commented on src/core/PopulationTimeSeriesChart/PopulationTimeSeriesChart.tsx
> +      : new Date(),
I agree, I think we need to return prior to ever accessing historicalPopulation[0]. 

I also agree that this task is supposed to be performed by the `ModelHydrator`, but we are seeing the error often enough that it seems there may be a timing issue where we try to access the non-existent element here before the `ModelHydrator` catches and renders the no data state. I'm not sure exactly what is going on but we are definitely seeing an error from trying `historicalPopulation[0].date`

2021-11-16 19:40 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  const latestUpdate = max(dataSeries.map((d) => d.lastUpdated)) || new Date();
I think we would need to do something like this on line 54:
`const latestUpdate =formatDate(dataSeries[0].lastUpdated, "MMMM dd, yyyy") || "Unknown";`

Then just add `latestUpdate` directly to the string in the chart title.

2021-11-17 13:13 UTC, nasaownsky commented
@jovergaag So I took the most optimal approach in my opinion, that could help to avoid those errors in the future. We just need to keep in mind that in cases where we trying to access elements in objects that could possibly be empty we should use the optional chaining operator `?.`

2021-11-17 18:15 UTC, jovergaag requested changes

2021-11-17 18:15 UTC, jovergaag commented on src/core/PopulationTimeSeriesChart/helpers.ts
> +      endDate: new Date(9999, 11, 31),
I don't really agree with the use of the arbitrary dates here. It feels a little like a hack. I would prefer to guard against the case that we don't have historical data in the chart component directly to make it easier to read and maintain for future developers.

2021-11-17 18:15 UTC, jovergaag commented on src/utils/formatStrings.ts
> +  if (!date) return "Unknown";
I like this solution!

2021-11-18 10:11 UTC, nasaownsky commented on src/core/PopulationTimeSeriesChart/helpers.ts
> +      endDate: new Date(9999, 11, 31),
That is the case, we already guard against the case that we don't have historical data in the chart component directly by using the optional chaining operator `?.`, but then `getDateRange` receives nothing and the App crashes agains, so we must guard against this either. And `getDateRange` must also necessarily return `Date` type, because otherwise other parts of the App start to crash.

2021-11-18 10:12 UTC, nasaownsky commented on src/core/PopulationTimeSeriesChart/helpers.ts
> +      endDate: new Date(9999, 11, 31),
This is the case, we already guard against the case that we don't have historical data in the chart component directly by using the optional chaining operator ?., but then getDateRange receives nothing and the App crashes agains, so we also must guard against this. And getDateRange must also necessarily return Date type, because otherwise other parts of the App start to crash.

2021-11-18 19:06 UTC, jovergaag approved these changes

2021-11-18 19:06 UTC, merged