Add Just In Time loading to the "List of people in prison" table
Recidiviz/pulse-dashboard pull request #1462
Opened 2021-11-17 17:53 UTC by nasaownsky

## Description of the change

Added Just In Time loading to the "List of people in prison" table 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1449 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-11-17 19:41 UTC, jovergaag requested changes
Beautiful implementation! The performance is so much better on the full dataset. It went from 10-15 seconds to 2-3 seconds which is mostly the network request. IE11 would previously crash on this table but is now loading fairly quickly and even sorting fairly quickly.

Well done! One styling fix is needed but the implementation is great. Thank you!

2021-11-17 19:41 UTC, jovergaag commented on src/core/VizPopulationPersonLevel/VizPopulationPersonLevel.tsx
> +        width: 250,
Are these statically assigned widths necessary? It would be really nice to allow them to size dynamically. On my laptop screen (1433px wide) the table now has a horizontal scroll which we definitely don't want.

2021-11-17 19:41 UTC, jovergaag commented on package.json
> +    "react-virtualized": "^9.22.3",
Why did you choose to use `react-virtualized` instead of `react-window`? It seems like `react-window` is much more lightweight and recommended for use unless it does not have a specific needed feature. Is there something that it didn't have that you needed here?

https://github.com/bvaughn/react-window#how-is-react-window-different-from-react-virtualized

2021-11-18 09:59 UTC, nasaownsky commented on src/core/VizPopulationPersonLevel/VizPopulationPersonLevel.tsx
> +        width: 250,
Yes. You see, virtualization works bad with table layouts, so we moved to flexbox layout. Its default width for columns is 150px and it's already used for dynamically sizing all columns. But if there's columns, that could be narrower or wider than default the width must be specified explicitly. You could read more here: https://react-table.tanstack.com/docs/api/useFlexLayout
or playing around with sizes, but firstly comment out lines 27-29 of `PathwaysTable.scss`.

2021-11-18 10:03 UTC, nasaownsky commented on package.json
> +    "react-virtualized": "^9.22.3",
At first I didn't succeed in using `react-window`, but with the `useFlexLayout` and `AutoSizer` everything works as expected and much more lighter at the same time.

2021-11-18 19:05 UTC, jovergaag commented on src/core/VizPopulationPersonLevel/VizPopulationPersonLevel.tsx
> +        width: 250,
I ended up making a few column width adjustments to match the real data showing up in the table, and made the rows a big taller to accommodate the admission reason wrapping.

This is such a huge improvement on this table, thank you!

2021-11-18 19:10 UTC, jovergaag approved these changes

2021-11-18 19:10 UTC, merged