Add "Admissions from supervision to prison over time" chart & new filters
Recidiviz/pulse-dashboard pull request #1489
Opened 2021-11-22 11:28 UTC by nasaownsky

## Description of the change

1. Added "Admissions from supervision to prison over time" chart 
2. Added DISTRICT filter to the `supervisionToPrisonOverTime` metric
3. Added MOST_SEVERE_VIOLATION and NUMBER_OF_VIOLATIONS filters to `supervisionToPrisonOverTime` metric

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1450 
Closes #1452 
Closes #1453 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-11-22 11:41 UTC, nasaownsky commented
Hey, @jovergaag! Looks like everything works fine, except new filters logic. Any ideas how to make filter separation by state? At first I was thinking about adding them to the `tenants.ts` file, but filters also can differ from metric to metric, and using them from `tenants.ts` file might be an inconvenient decision. Maybe use them from state copy files? But again this files is only for copy text. I would really appreciate any advices and implementation tips! Thanks.

2021-11-22 22:47 UTC, jovergaag commented
> 



> Hey, @jovergaag! Looks like everything works fine, except new filters logic. Any ideas how to make filter separation by state? At first I was thinking about adding them to the `tenants.ts` file, but filters also can differ from metric to metric, and using them from `tenants.ts` file might be an inconvenient decision. Maybe use them from state copy files? But again this files is only for copy text. I would really appreciate any advices and implementation tips! Thanks.

Good question. Maybe we can create a new object similar to `filterOption` that is called `enabledFilters`, probably also live in `src/core/utils`. It could be structured similarly to `filterOptions` with a key for each enabled state/tenant. Each state/tenant would have a key for each metric type. Similarly to `filterOptions` it would be accessible via the filters store. Does that seem like it will work?

2021-11-22 22:53 UTC, jovergaag reviewed
Let me know how the `enabledFilters` work goes. I think what I suggested will work out, but feel free to play around with it.

2021-11-22 22:53 UTC, jovergaag commented on src/core/models/SupervisionCountOverTimeMetric.ts
> +          numberOfViolations.includes(record.numberOfViolations) &&
This metric will need to have the results grouped and summed, similar to lines 81-91 of `PopulationOverTimeMetric`. Currently, when more than one option of any given filter are selected the chart is not making sense. That is because the results are not summed properly.

2021-11-24 13:41 UTC, nasaownsky commented
Check my implementation out! This is how I see it, let me know your thoughts. Also, could you please try to debug that test error, I honestly tried, but had no success. And one more thing: I noticed, that `Supervision to Liberty` chart is broken in `US_ID`, because we changed `SupervisionCountOverTimeMetric`. So, will the files for it also be updated, or should I split metric into two instances?

2021-11-24 22:42 UTC, jovergaag requested changes
This looks amazing! I pushed up a couple of commits with copy updates and fixes to those tests.

There are a few little things I commented on. The other remaining thing is the download is broken, something around creating the methodology file.

Don't worry about the US_ID Supervision to Liberty metric file - I have a task to update the metric file for US_ID before we land this.

2021-11-24 22:53 UTC, jovergaag commented on src/core/PageSystem/PageSystem.tsx
> +  const { filters, download, isLoading, note } = metric;
I'm getting an error on this line when I first open the page. After refreshing it goes away because the browser cache changes the timing. I think we have something going on with the `page` on line 61 of `MetricsStore`, it isn't properly updating to be "prison" before calculating the current metric based on the page/section. That might need a little work.

2021-11-24 23:16 UTC, jovergaag commented
One more small styling tweak, please decrease the margin here from 3.5rem to 2.5rem (for all section nav links including US_ID, not only this one):
![image (1)](https://user-images.githubusercontent.com/5872651/143324394-30fa9fbb-4bc7-4116-872f-50687c5fb3c3.png)

2021-11-25 14:28 UTC, nasaownsky commented on src/core/content/page/us_tn.ts
> +  },
The `download` wasn't work because you forgot to add methodology text for `supervisionToPrison` here

2021-11-25 14:29 UTC, nasaownsky commented on src/core/models/SupervisionCountOverTimeMetric.ts
> +        numberOfViolations: dataset[0].numberOfViolations,
Ok, I will think about how this can be made.

2021-11-25 14:31 UTC, nasaownsky commented on src/core/PathwaysFilterBar/PathwaysFilterBar.tsx
> +                      )[0]
Also `timePeriod` wasn't correctly displayed, so I fixed this little issue.

2021-11-25 14:35 UTC, nasaownsky commented on src/core/PageSystem/PageSystem.tsx
> +  const { filters, download, isLoading, note } = metric;
Could you try to do this please? I can't make it work for some reason

2021-11-29 23:36 UTC, jovergaag reviewed
This looks great! I'm going to hold off approving/merging this until we can get the schema change in the backend to make sure that `main` is always deployable. That should be done within the next couple of days.

2021-11-29 23:36 UTC, jovergaag commented on src/core/PathwaysFilterBar/PathwaysFilterBar.tsx
> +                      )[0]
i have just gone through and done a fairly significant overhaul on the filters in my multi-select PR. All of this should be a little more clean moving forward. Thanks for fixing this here!

2021-11-29 23:36 UTC, jovergaag commented on src/core/content/page/us_tn.ts
> +  },
Oops. We don't have the "default" methodology for this chart set in the copy doc. thank you!

2021-12-01 20:05 UTC, jovergaag approved these changes
A ton of great work here. Thank you @nasaownsky

2021-12-01 20:07 UTC, merged