Add admissions from supervision to prison by district chart
Recidiviz/pulse-dashboard pull request #1491
Opened 2021-11-29 16:23 UTC by nasaownsky

## Description of the change

Adds admissions from supervision to prison by district chart

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1451 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-11-29 16:39 UTC, nasaownsky commented
hey, @jovergaag! I've been struggling for a while now, and I'm asking for help or advice. I try to make `PopulationSnapshotMetric` metric more general and suitable for different accessors, and even had some progress with that, but had fall into problem where data from `supervision_to_prison_population_snapshot_by_dimension` does not fetch at all. So I've made separate `PopulationSnapshotSupervisionMetric` trying to debug this issue. And it seems to be completely legit implementation, but the data isn't displaying! Argh! Maybe I've missed something? Could you please look at with your fresh eyes?

2021-11-30 02:03 UTC, jovergaag requested changes
Sorry about that bad fixture file, I hope you didn't spend too much time on it! I sent a new file, give it a try.

I also pushed up a commit to get the chart populating and one for the synced content.

2021-11-30 02:03 UTC, jovergaag commented on src/core/models/utils.ts
> +export function createDistrictPopulationSnapshot(
Let's rename this to `createSupervisionPopulationSnapshot` and rename line 50 to `createPrisonPopulationSnapshot`

2021-11-30 02:03 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +            return <text textAnchor="middle">{accessorValue}</text>;
The district x-axis  labels are showing up as `DISTRICT_1` etc. Please format them such that they match the label in the filter options.

2021-11-30 13:27 UTC, nasaownsky commented on src/core/models/SupervisionPopulationSnapshotMetric.ts
> +export default class SupervisionPopulationSnapshotMetric extends PathwaysMetric<SupervisionPopulationSnapshotRecord> {
Yeah, I don't love neither. If I can come up with some elegant solution that could simplify things, I'll push it within next PR.

2021-11-30 18:53 UTC, jovergaag requested changes
One small change then we're all set! Once fixed I will merge this into the base branch and we will land it all together when the schema change is in.

2021-11-30 18:53 UTC, jovergaag commented on src/core/models/SupervisionPopulationSnapshotMetric.ts
> +      labels.push(d[this.accessor].toString());
We also need to convert this to the filter option label. 

![Screen Shot 2021-11-30 at 10 48 44 AM](https://user-images.githubusercontent.com/5872651/144109412-2c52e858-862c-4741-ab90-b8cb027e90b7.png)

2021-11-30 18:53 UTC, jovergaag commented on src/core/models/PrisonPopulationSnapshotMetric.ts
> +        count: sumBy("count", dataset),
Thank you for cleaning this up to be more consistent!

2021-12-01 18:11 UTC, jovergaag approved these changes

2021-12-01 18:11 UTC, merged