Add multi-select component and logic to Pathways filters
Recidiviz/pulse-dashboard pull request #1492
Opened 2021-11-29 22:49 UTC by jovergaag

## Description of the change

Adds multi-select component and logic to the Pathways filters.
-enables Multi-select dropdown in `PathwaysFilterBar`
-adds configuration to `filterOptions` to specify which filters are multi select on a per state level (some states will use multi-select for some filters while other states will remain single select for the same filter)
-adds the logic such that all filters live in the `filtersStore` as arrays, such that any filter can be converted from single select to multi-select with a one line change.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #1437 #940 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-12-01 20:49 UTC, Catacola requested changes
Everything works great, thanks! I have a few comments below. Feel free to push back on anything if you feel I'm offbase.

2021-12-01 20:49 UTC, Catacola commented on src/core/PathwaysFilterBar/PathwaysFilterBar.scss
> +// Copyright (C) 2020 Recidiviz, Inc.
```suggestion
// Copyright (C) 2021 Recidiviz, Inc.
```

2021-12-01 20:49 UTC, Catacola commented on src/core/PathwaysFilterBar/PathwaysFilterBar.scss
> +  }
Thankyouthankyouthankyouthankyouthankyouthankyou

2021-12-01 20:49 UTC, Catacola commented on src/core/controls/MultiSelect/CoreMultiSelect.js
> +  isChanged: PropTypes.bool,
I don't see this prop used anywhere in the component. The only thing I could see it doing is being passed to `ReactSelect` via `{...props}`, but I don't see an `isChanged` prop in the react select docs: https://react-select.com/props

2021-12-01 20:49 UTC, Catacola commented on src/core/models/PopulationOverTimeMetric.ts
> +    const monthRange: MonthOptions = parseInt(timePeriod[0]) as MonthOptions;
This is beginning to tickle my senses. If we need to put this comment everywhere, it feels like we're doing something wrong. However, I can't think of a good way to make the timePeriod filter just return one value without making the typing weird for all the filters. I can think of two options, but I'm unsure of their drawbacks:
1) Create a special filter class for things we know will always be single-select and use that for this filter.
2) Make a small helper function along the lines of `parseTimeFilter = (timePeriod: someType): MonthOptions => parseInt(timePeriod[0]) as MonthOptions`. This is a repeated enough pattern in this codebase and there are three things going on here (indexing, parsing, and casting), so it doesn't feel that frivolous.

2021-12-01 20:49 UTC, Catacola commented on src/core/models/__tests__/PopulationOverTimeMetric.test.ts
> +      enabledMoreFilters: [],
I know these are only in tests, but seeing as we need to specify `enabledMoreFilters: []` over and over, what do you think of making this an optional prop that defaults to `[]`?

2021-12-01 20:49 UTC, Catacola commented on src/core/withRouteSync.tsx
>      );
If you pass an empty array as the second argument to use effect (e.g. `useEffect(() => {some_code()}, [])`), it should only run on the initial render. I think you then   can drop the `initialLoad` state.

2021-12-01 20:49 UTC, Catacola commented on src/utils/formatStrings.ts
> +  return string && string.replace(/[-_]/g, " ");
I'm not sure what these `&&` checks are for. Typescript says these should always be strings, not nullable strings, so this check shouldn't be necessary. If the string is nullable, you should update the types and you can probably change them to `string?.replace()`.

2021-12-01 23:04 UTC, jovergaag commented on src/core/types/filters.ts
> +  isMultiSelect: boolean;
Great idea. I ended up switching it to `isSingleSelect` since there are far fewer single select filters and defaulting it to false.

2021-12-01 23:13 UTC, jovergaag commented on src/core/controls/MultiSelect/CoreMultiSelect.js
> +  isChanged: PropTypes.bool,
It is being used in `coreSelectCustomStyles` which lives in another component. I will move it out to avoid confusion.

2021-12-02 00:21 UTC, jovergaag commented on src/core/models/PopulationOverTimeMetric.ts
> +    const monthRange: MonthOptions = parseInt(timePeriod[0]) as MonthOptions;
I wrestled with this for a while as well (both before your review and after, to no avail). I agree that it is smelly. If we make the custom single-select class it generates a ton of additional code to handle both arrays and strings.

I ended up adding a getter to the FiltersStore which returns the `monthRange`. It is definitely better than it was. Let me know if you still think it could use some work.

2021-12-02 00:32 UTC, jovergaag commented on src/core/withRouteSync.tsx
>      );
whaat? I did not know this.

2021-12-02 00:57 UTC, jovergaag commented on src/utils/formatStrings.ts
> +  return string && string.replace(/[-_]/g, " ");
They were causing problems at some point, but seem to be working fine without the guard now that things are more clean.

2021-12-02 00:58 UTC, jovergaag commented
@Catacola Thank you for the amazing feedback! It is so much better now.

2021-12-07 07:53 UTC, Catacola commented on src/core/withRouteSync.tsx
>      );
Yup! This is because the second argument is the list of props that, when changed, trigger a rerun of the hook added in the first argument. If the argument is `undefined`, it will run whenever the component is rerendered. However, if it is supplied, it will only rerender if a supplied argument prop changed and since there are no props in `[]`, it will never rerun.

For a more official sounding explanation, see the note after https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects.

2021-12-07 08:02 UTC, Catacola approved these changes
Nice work

2021-12-07 08:02 UTC, Catacola commented on src/core/withRouteSync.tsx
>      // eslint-disable-next-line react-hooks/exhaustive-deps
You may not still need this line. I'm honestly not sure.

2021-12-07 17:58 UTC, merged