Add admissions from supervision to prison by violation charts
Recidiviz/pulse-dashboard pull request #1495
Opened 2021-12-02 14:15 UTC by nasaownsky

## Description of the change

1. Added the "Admissions from supervision by prison by most severe violation" chart
2. Added the "Admissions from supervision by prison by number of violations" chart
3. Fixed filters sorting bug to always put `All` option first

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1455 
Closes #1456 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-12-02 14:25 UTC, nasaownsky commented
@jovergaag Two things worth mentioning:
1. I haven't find in the designs light color for highlighting filtered bars in golden charts.
2. Also I don't know, how to separate golden charts from greenish. In the designs I noticed a trend where the charts turns gold if there are only few bars, so I've made it that way.

2021-12-02 19:10 UTC, jovergaag requested changes
Wow, I love how easily these two charts came together. Fantastic work! 

I know there has been a lot of churn the last few days as I have been renaming metrics and reorganizing things but I think its starting to pay off. Thank you for your patience :)

2021-12-02 19:10 UTC, jovergaag commented on src/core/models/PathwaysMetric.ts
> +  get legend(): string | undefined {
This isn't exactly a legend, and we may eventually have a legend on these charts so we should probably reserve that name. `chartXAxisTitle` is probably what we want here.

2021-12-02 19:10 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +              ticks: 4,
I just noticed that sometimes the bars extend above the highest tick which makes it hard to read sometimes. This exists for other charts as well in addition to these new charts. Can you please find a way to make sure that the highest tick is above the highest bar. 

![Screen Shot 2021-12-02 at 11 06 20 AM](https://user-images.githubusercontent.com/5872651/144486817-e2ebe8e6-7048-488c-9d8a-284770d2219c.png)

![Screen Shot 2021-12-02 at 11 08 10 AM](https://user-images.githubusercontent.com/5872651/144486931-676ef936-d8b0-446e-aae7-db1bd7bc2c12.png)

2021-12-02 19:13 UTC, jovergaag commented on src/core/CoreStore/MetricsStore.ts
> +        [PATHWAYS_SECTIONS.countByNumber]: this
Once you change the name of these I'll sync the content.

2021-12-03 14:13 UTC, nasaownsky commented
@jovergaag Most of the highest ticks now is above the highest bar, but not always as you can see on `Admissions from supervision by district` chart. This is Semiotic-spesific, and I have not found a better solution.

2021-12-07 01:30 UTC, jovergaag requested changes

2021-12-07 01:30 UTC, jovergaag commented on src/utils/formatStrings.ts
> +const roundToDecimals = (value: number): number => {
I think `getCeiling` is more accurate here. Great logic!

2021-12-07 16:56 UTC, nasaownsky commented on src/core/VizCountOverTimeWithAvg/VizCountOverTimeWithAvg.tsx
> +            ticks: 5,
Great! I made a couple of fixes with this in mind.

2021-12-07 18:44 UTC, jovergaag approved these changes

2021-12-07 18:44 UTC, jovergaag commented on src/utils/formatStrings.ts
> +const getTicks = (value: number) => {
YES, the ticks are so much better now! Thank you.

2021-12-07 18:45 UTC, merged