Add the "Admissions from supervision to prison by supervision level" chart
Recidiviz/pulse-dashboard pull request #1514
Opened 2021-12-10 11:11 UTC by nasaownsky

## Description of the change

Added the "Admissions from supervision to prison by supervision level" chart and filter.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1506 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-12-11 00:41 UTC, jovergaag commented
Hi @nasaownsky I don't have a fixture file with this dimension ready yet so I will hold off on review until that is set. With the new dimensions (filters) coming up in January the fixture files are getting to be too large for the FE to handle so I am working on a solution for that. Thank you for your patience while I get this sorted out!

You should already have the fixture files that you need to complete #1497 and #1500.

2021-12-17 21:22 UTC, jovergaag requested changes

2021-12-17 21:22 UTC, jovergaag commented on src/core/models/SupervisionPopulationSnapshotMetric.ts
> +            : !["ALL"].includes(record.supervisionLevel)) && // change to supervisionLevel.includes(record.supervisionLevel)) when the data is ready
The data in the `jovergaag/demo-filters` branch is ready for this now! If you base this off of that branch you should see a working chart.

2021-12-17 21:22 UTC, jovergaag commented on src/core/models/utils.ts
> +        supervisionLevel: record.supervision_level,
You will also need to add this to `createSupervisionPopulationTimeSeries`

2021-12-17 21:22 UTC, jovergaag commented on src/core/utils/filterOptions.ts
> +      { label: "All", value: "all" },
The value here should be all caps `ALL`

2021-12-20 16:40 UTC, nasaownsky commented
@jovergaag Do you plan to merge `jovergaag/demo-filters` into main? I have some issues with rebasing this branch, and my old files from `demo-data` is gone now.

2021-12-20 19:35 UTC, jovergaag commented
> @jovergaag Do you plan to merge `jovergaag/demo-filters` into main? I have some issues with rebasing this branch, and my old files from `demo-data` are gone now.

I will merge it Tuesday afternoon after the data platform production deploy. There is a schema change in that branch that relies on the deploy, so to keep `main` deployable I will wait for that data platform deploy.

I will do the rebase for you.

2021-12-21 23:33 UTC, jovergaag approved these changes

2021-12-22 18:46 UTC, merged