Add US_TN Prison to Supervision page
Recidiviz/pulse-dashboard pull request #1521
Opened 2021-12-16 09:31 UTC by nasaownsky

## Description of the change

Added US_TN Prison to Supervision page.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1497 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-12-16 09:38 UTC, nasaownsky commented
Hey @jovergaag! So the `prison_to_supervision_population_snapshot_by_dimension` file must be wrong or maybe I don't get it, because it has `"age_group":"55-59, 60+"` field, but we actually don't have this kind of filter, so the data display is incorrect. Is it new feature?

2021-12-17 04:28 UTC, jovergaag reviewed
I made quite a few changes to the fixtures, and they are now checked into the repo which should make your life a lot easier. Go ahead and base this off of the `jovergaag/demo-filters` branch and change the name of that metric file, and I think everything should work. The code all looks great!

Note: the new `supervision_to_prison_count_by_month` fixture is really big so it takes a long time for that over time chart to load. Give it time...it will load. First thing in January I will be working on moving the backend to fetch from a database instead of the metric files so as our metric data continues to grow the app will remain performant.

2021-12-17 04:28 UTC, jovergaag commented on src/core/CoreStore/MetricsStore.ts
> +      sourceFilename: "prison_to_supervision_population_time_series",
I made a mistake in the issue. This fixture is actually `prison_to_supervision_count_by_month`. This fixture is included in the PR that I just put up. I added the fixtures into the repo to make it easier to version control the fixtures. If you base this branch off of that branch you should have what you need here.

2021-12-17 04:28 UTC, jovergaag commented on src/core/models/SupervisionPopulationSnapshotMetric.ts
> +          (this.accessor === "district"
Nice change, love it.

2021-12-17 04:49 UTC, jovergaag commented on src/core/CoreStore/MetricsStore.ts
> +  get prisonToSupervisionPopulationOverTime(): PrisonPopulationOverTimeMetric {
We want this to be a `VizCountOverTimeWithAvg` so we will need to add a new conditional to `MetricVizMapper`

2021-12-17 04:49 UTC, jovergaag commented on src/core/models/PrisonPopulationSnapshotMetric.ts
> +            : facility.includes(record.facility)) &&
`facility` and `ageGroup` also need to be included to the map below when accumulating the `result`. That may have been your problem.

2021-12-17 04:49 UTC, jovergaag commented on src/core/CoreStore/MetricsStore.ts
> +  get prisonToSupervisionPopulationOverTime(): PrisonPopulationOverTimeMetric {
This also means that you will need to add `avg90day: parseInt(record.avg_90day),` into `createPrisonPopulationTimeSeries` so that you have the rolling average number for this chart.

2021-12-17 18:06 UTC, jovergaag requested changes
Couple small things but it looks great!

2021-12-17 18:06 UTC, jovergaag commented on src/core/models/PrisonPopulationOverTimeMetric.ts
> +        avg90day: sumBy("avg90day", dataset) || undefined,
You shouldn't need the `|| undefined` here.

2021-12-17 18:06 UTC, jovergaag commented on server/collections/resources/getCollections.js
> +    },
This should no longer be needed. The file for the time series chart on this page is `prison_to_supervision_count_by_month`. 

I'm really sorry for all of the file changes and schema changes, I know it has been confusing. We are starting to have a few states worth of data be ready in the data platform so there will be several engineers working to get the views thats support Pathways populated. I wanted to go through and make our naming as consistent as possible to make the data process as smooth as possible. I think we are there now and the fixtures in the repo will support Pathways for a few more states.

2021-12-17 18:26 UTC, nasaownsky commented
Here we go 🚀

2021-12-17 18:30 UTC, jovergaag approved these changes
Hi!

2021-12-22 19:19 UTC, merged