Change single-select filters in MoreFilters from check boxes to radio
Recidiviz/pulse-dashboard pull request #1537
Opened 2021-12-21 14:37 UTC by nasaownsky

## Description of the change

Changed single-select filters in `MoreFilters` from check boxes to radio

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1529 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-12-21 23:27 UTC, jovergaag requested changes

2021-12-21 23:27 UTC, jovergaag commented on src/components/Checkbox/Checkbox.tsx
> +        onChange={isSingleSelect ? onChange : handleChange}
I think we can use `handleChange` for both single and multi-select. Is that right?

2021-12-21 23:27 UTC, jovergaag commented on src/core/controls/CheckboxGroup.tsx
> +            <Checkbox
This functions perfectly! We will want the inputs to be round instead of squares though. Is it possible to use the existing `RadioGroup ` component here instead of these Checkboxes? I think it would be done on line 106 of `MoreFilters` instead of rendering `CheckboxGroup` if the filter is single select.

2021-12-22 12:17 UTC, nasaownsky commented on src/core/controls/CheckboxGroup.tsx
> +            <Checkbox
No, it's actually requires a lot of styling and logic rework to make `RadioGroup` functions properly in this component. As we already have all we needed, I think this work is unnecessary.

2021-12-22 12:33 UTC, nasaownsky commented on src/components/Checkbox/Checkbox.scss
> +    .Checkbox {
I also added new styling to radio inputs to separate more clearly single select from multi. What's your thoughts?

2021-12-22 20:18 UTC, jovergaag reviewed
I tried out using `RadioGroup` inside of `MoreFilters` and it didn't turn out to be too much logic work. I think that the function and concept of the two types of filters is different enough that it is important that we use and think of them separately. Take a look at that commit, it just needs some styling updates but I think it will be easier for us to maintain moving forward.

2022-01-05 19:21 UTC, jovergaag approved these changes
Looks great!

2022-01-05 19:21 UTC, merged