Fixes for ND launch
Recidiviz/pulse-dashboard pull request #1617
Opened 2022-01-28 15:27 UTC by nasaownsky

## Description of the change

Checked in the Issue what I've done so far. As for the person level tables and NULL values in the district and facility charts - I wasn't able to recreate these bugs and so not quite understand how it should be resolved.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1613 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-01-28 17:24 UTC, jovergaag commented
> As for the person level tables and NULL values in the district and facility charts - I wasn't able to recreate these bugs and so not quite understand how it should be resolved. 

No problem, I'll take a look. I know that some of these are really hard to re-create with fixture data. Thanks!

2022-01-28 19:01 UTC, jovergaag requested changes
The UI changes look great! 

I pushed up a commit to resolve the person level table bug, and left a comment clarifying the requirements for the filter behavior when switching pages. Let me know if you have questions.

2022-01-31 17:50 UTC, nasaownsky commented on src/core/PathwaysFilterBar/PathwaysFilterBar.tsx
> +  const [previousEnabledFilters, setPreviousEnabledFilters] = useState(
Hmm, this is really tricky. Spend all day trying to work something out, but none of my ideas could handle this. Is this a P1 feature, that we need to bring before launch, or we can move this to Issues and figure out something later?

2022-01-31 17:51 UTC, nasaownsky commented on src/core/PathwaysLeftPanel/PathwaysLeftPanel.scss
> +$pathways-left-panel-width: 24rem;
Could you show me some screenshots of that strange behavior?

2022-01-31 18:54 UTC, jovergaag commented on src/core/PathwaysFilterBar/PathwaysFilterBar.tsx
> +  const [previousEnabledFilters, setPreviousEnabledFilters] = useState(
It is really tricky. I spent some time this weekend thinking about how to do this (because my mind doesn't shut off sometimes :) ) and I came up with nothing. The only think I could think of is maintaining a previous filters state per page - but that will just become a mess. Let me talk to the product manager about other options here.

2022-02-01 01:34 UTC, jovergaag commented on src/core/PathwaysFilterBar/PathwaysFilterBar.tsx
> +  const [previousEnabledFilters, setPreviousEnabledFilters] = useState(
Update: the product manager said that the functionality to maintain the previously set filter state when navigating back to a previous page is not P0. So let's make sure that the filter is set to "ALL" when navigating to a page where that filter is not enabled, and remove this `previousEnabledFilters` logic.

2022-02-01 16:28 UTC, nasaownsky commented on src/core/PathwaysFilterBar/PathwaysFilterBar.tsx
> +  const [previousEnabledFilters, setPreviousEnabledFilters] = useState(
So this logic does exactly what we need, or did you find another elegant solution in existing PRs?

2022-02-01 20:43 UTC, jovergaag requested changes

2022-02-01 20:43 UTC, jovergaag commented on src/core/PathwaysFilterBar/PathwaysFilterBar.tsx
> +  const [previousEnabledFilters, setPreviousEnabledFilters] = useState(
Yes, the logic did what we wanted but there was quite a bit of extra code than was needed. Take a look at the commit I pushed up, I think it should also do what we want bit leverages the power of Mobx!

There is still a small bug in this, the `updatedFilters` in `MoreFilters` is not getting reset to an empty object when switching back and forth between pages, which means that filters are getting set incorrectly when navigating between pages and opening/closing/setting the modal. Once that is fixed this will be ready to go!

2022-02-02 18:41 UTC, jovergaag approved these changes
Well done, thank you!

2022-02-02 18:46 UTC, merged