Add "Liberty" metrics
Recidiviz/pulse-dashboard pull request #1629
Opened 2022-02-03 18:38 UTC by jovergaag

## Description of the change

We were trying to use our Supervision metrics to support the "Liberty to Prison" page, but with the change from `district` to `judicialDistrict` on that page it no longer made sense to share. So i created the over time metric and the snapshot metric here.

I also updated the ND district ids to match the new ids after we removed "OFFICE".

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-02-03 18:58 UTC, Catacola requested changes

2022-02-03 18:58 UTC, Catacola commented on src/core/utils/filterOptions.ts
> +      { label: "North Central", value: "NORTH CENTRAL" },
The values here should have underscores in place of spaces. e.g. `SOUTH_CENTRAL`

2022-02-07 21:27 UTC, jovergaag commented
@Catacola bump :)

2022-02-08 01:19 UTC, Catacola approved these changes

2022-02-08 01:19 UTC, Catacola commented on src/core/models/utils.ts
> +    });
Is this still needed after your other fixes for the metric files today?

2022-02-08 01:37 UTC, jovergaag commented on src/core/models/utils.ts
> +    });
GOOD CATCH! I'll remove it.

2022-02-08 01:41 UTC, merged