Refactor metrics to remove filtering by each dimension individually
Recidiviz/pulse-dashboard pull request #1638
Opened 2022-02-08 12:12 UTC by nasaownsky

## Description of the change

-Added tooling to group filtered records

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1596 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-02-08 12:16 UTC, nasaownsky commented
@jovergaag So I've added this tooling I've created in last PR, and it seems to work all right! 
Would you take a look at filtering? I tried some approaches, but none has worked.

2022-02-11 01:09 UTC, jovergaag reviewed
@nasaownsky Take a look at the commit that I pushed up. The `SupervisionPopulationSnapshotMetric` has the start of what I think will be a good implementation of the filters. I have not tested this much, and there are lots of typescript errors but it should hopefully get you headed in the right direction!

I ended up creating a new type called `Dimension` because we have some dimensions (charts: like Length of Stay) that will never be filters. This is causing some problems in the filtering logic because we're trying to use a `dimensionId` to index the filters...but see if you can make typescript happy. Note: Our filter types are not great, so feel free to overhaul them if needed.

2022-02-14 15:42 UTC, nasaownsky commented
I'm not exactly understand now how the `priorLengthOfIncarceration` and `lengthOfStay` charts should work. Earlier we had list with options in `filterOptions`, which were used to display specific values. For `priorLengthOfIncarceration` it was ALL, 0, 1 etc. They were not meant to be used as filters, instead they were used for highlighting chosen chart columns. And now that they're deleted, I'm not understand, where from to get them (not only to highlight, but and for simply displaying). @jovergaag

2022-02-15 02:47 UTC, jovergaag commented
> I'm not exactly understand now how the `priorLengthOfIncarceration` and `lengthOfStay` charts should work. Earlier we had list with options in `filterOptions`, which were used to display specific values. For `priorLengthOfIncarceration` it was ALL, 0, 1 etc. They were not meant to be used as filters, instead they were used for highlighting chosen chart columns. And now that they're deleted, I'm not understand, where from to get them (not only to highlight, but and for simply displaying).

`lengthOfStay` and `priorLengthOfIncarceration` will never be filters, they will only ever be charts. On those charts, since we don't have the corresponding filter, the "highlighting" functionality is not necessary, the bars will always be the default color. Does that make sense?

2022-02-17 02:35 UTC, jovergaag reviewed
Overall these metric filters are looking SO MUCH BETTER! Thank you! I pushed up a commit which has a solution for the time period filter.

I'm going to take another look at the dimension/filter type problem that I created first thing in the morning when I have a fresh brain.

2022-02-17 02:35 UTC, jovergaag commented on src/core/models/dimensions.ts
> +  prison_population_projection_time_series: [DIMENSION_TYPES.GENDER],
Why was LEGAL_STATUS removed here? And on line 78?

2022-02-17 02:35 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  );
I see what you mean about this dimension/filter change causing issues here (along with all of the typescript problems it has created). I need to spend some more time looking at this to see if that change is causing more problems than its solving. But it is late today and my brain is tired. I'll take a look at this first thing in the morning.

2022-02-17 02:35 UTC, jovergaag commented on src/core/utils/filterOptions.ts
> +        label: "JUDICIAL_DISTRICT_1",
Let's make these labels "District 1", "District 2" etc

2022-02-17 02:45 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  );
I'm sure that removing `lengthOfStay` as a filter is also why the Length Of Stay charts aren't working anymore. I think it is something in `filterRecords` but will have to take a closer look at it tomorrow. 

Thanks for your patience with PR reviews, things are moving quickly over here now trying to get ME and TN data loaded into the dashboard so I have not been diligent with reviews. Your PRs are my priority tomorrow!

2022-02-17 09:06 UTC, nasaownsky commented on src/core/models/PopulationProjectionOverTimeMetric.ts
> +          status.includes(record.legalStatus) &&
> Why was LEGAL_STATUS removed here? And on line 78?

Because in this metric the record name is the same, and filter name depends on compartment. If we use it like before from dimensions we would always get `legalStatus.includes(record.legalStatus)` which is not what we want.

2022-02-17 10:02 UTC, nasaownsky commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  );
Yeah, at first I was also thinking, that the problem is in `filterRecords`, but then I was checkout to `main`, and it turns out, that the `lengthOfStay` charts aren't also work. That was strange, especially with working `priorLengthOfIncarceration` chart, which is practically the same. So the problem appeared earlier. In short: the problem is in `utils.ts` on lines 147 and 177. If we remove all that logic and only keep `lengthOfStay: record.length_of_stay,`, the charts will work as usual. So the problem is in `lengthOfStayMap`, because only fixture file that comtains `length_of_stay` data is `supervision_to_prison_population_snapshot_by_dimension`, and it has another values for `length_of_stay`. Rather than `months_0_3, months_3_6, months_6_9...` and so on it has `[ "length_of_stay", [ "0", "12", "18", "24", "6", "all" ] ]`.

2022-02-17 23:13 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  );
Good find. I'll update the fixtures. We changed the schema a couple of weeks ago and I failed to update the fixtures to match!

2022-02-17 23:22 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  );
Fixed.

2022-02-18 00:41 UTC, jovergaag commented
> Because in this metric the record name is the same, and filter name depends on compartment. If we use it like before from dimensions we would always get legalStatus.includes(record.legalStatus) which is not what we want.

I see. Its not ideal but thats the way the data is laid out so we will work with it. I think its fine since the projections page is not using the new filtering function. Within the next few months US_ND will move to the "projections" charts on the prison and supervision pages, we can work on the projections metrics at that point.

2022-02-18 00:41 UTC, jovergaag requested changes
The only thing left is to copy that `datasetWithoutCount` logic to the rest of the metrics. Looking good!

2022-02-18 00:41 UTC, jovergaag commented on src/core/models/PrisonPopulationSnapshotMetric.ts
> +            // @ts-ignore
I played around a little bit with creating different dimension types `PrisonDimensions` and `SupervisionDimensions` and `LibertyDimensions`. It kind of worked and was helpful...but not really. I think that this `ts-ignore` is fine for now. I will create a ticket to work out our typing in a couple of weeks when things have stabilized a bit with all of our launches.

PS - we are launching US_ME next week and US_TN a couple of weeks after! Moving fast :)

2022-02-18 00:41 UTC, jovergaag commented on src/core/models/PrisonPopulationSnapshotMetric.ts
> +        };
The `avg90Day` should be pulled out of the object, similar to `count` for the metrics that have the that attribute.

2022-02-18 13:41 UTC, nasaownsky commented on src/utils/datasets.js
> +    return a[labelKey].localeCompare(b[labelKey], "en", { numeric: true });
It filters labels not only by alphabet, but in numeric-right way. So instead of `1, 12, 24, 6` we will get `1, 6, 12, 24`.

2022-02-18 14:03 UTC, nasaownsky commented
I've noticed, that we have problem with first render, when switching charts, and it came after merging later changes from main. If we change any filter in filter bar the render passes. Maybe it's `PageSystem` fix?

2022-02-22 22:06 UTC, jovergaag commented
> I've noticed, that we have problem with first render, when switching charts, and it came after merging later changes from main. If we change any filter in filter bar the render passes. Maybe it's PageSystem fix?

I don't see the problem. On first load, when switching charts, everything looks find to me. Can you give me more details about what you're seeing?

2022-02-23 00:34 UTC, nasaownsky commented
It's gone with revert. So I merged main again and now it should be good to go.

2022-02-24 02:39 UTC, jovergaag approved these changes
This is HUGE! Such a big improvement and less bug prone. Thank you!

2022-02-24 19:25 UTC, merged