Clean up console warnings and errors in tests from the FiltersStore
Recidiviz/pulse-dashboard pull request #1648
Opened 2022-02-10 12:49 UTC by nasaownsky

## Description of the change

Got rid of console errors caused by reaction in `FiltersStore`. Also got rid some more console errors, which I was able to catch.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1640 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-02-10 22:25 UTC, jovergaag requested changes
This is a great progress! I'm still seeing lots of warnings in the tests which would be nice to clean up:

`[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: CoreStore@12.metricsStore`
and
<img width="1146" alt="Screen Shot 2022-02-10 at 2 25 16 PM" src="https://user-images.githubusercontent.com/5872651/153507013-6a04ec37-02e7-4a96-96d0-624a441510f0.png">
and
<img width="1161" alt="Screen Shot 2022-02-10 at 2 25 22 PM" src="https://user-images.githubusercontent.com/5872651/153507025-e7cbccad-b1ec-4879-983c-f9173c664e1b.png">


I've also got several console warnings and errors: 
- In demo mode, I see an error for Intercom. We can just check `isDemoMode` and not `initIntercomSettings` if we are in demo mode.
- I also see these in my console which would be nice to clean up.

<img width="1775" alt="Screen Shot 2022-02-10 at 2 17 31 PM" src="https://user-images.githubusercontent.com/5872651/153506894-936beb4a-032f-420e-91f8-da0da59bfce1.png">

2022-02-10 22:25 UTC, jovergaag commented on src/core/CoreStore/FiltersStore.ts
> +      { delay: 300 }
I don't love this. Anytime we have to add a delay to something it sets off red flags in my head that its going to be buggy. Can we maybe put the `clearDisabledFilters` in a `useEffect` with a `filters` dependency in `PathwaysFilterBar`?

2022-02-11 12:25 UTC, nasaownsky commented on src/core/CoreStore/FiltersStore.ts
> +      { delay: 300 }
I tried many options, and they're all overwhelmed like my previous with useState, or aren't work. This is the compromise. Besides, this delay is official mobx `reaction` option, so I think there will no problems with it.

2022-02-11 13:45 UTC, nasaownsky commented
@jovergaag I've managed to clear majority of that errors/warnings except two: the `Cannot update a component ('PageSystem')` and the keys errors.

2022-02-15 02:43 UTC, jovergaag commented
> I've managed to clear majority of that errors/warnings except two: the `Cannot update a component ('PageSystem')` and the keys errors.

These look great! The keys error is because we're generating the methodology via markdown and its impossible to insert a key into the bulleted list in the markdown. So that one is fine!

I pushed up a commit that gets rid of the `PageSystem` error. Basically, that component didn't need to be an observer, all of its children could be observers and get observables directly from the stores. There is still a test failing and it creates an infinite loop somewhere in the `PathwaysFilterBar` when changing charts or changing pages but I think that's just a matter of putting a different guard on line 49. Maybe also check for `isLoading`?

Let me know your thoughts on this!

2022-02-15 02:45 UTC, jovergaag commented on src/App.js
> +}
YAY thank you.

2022-02-15 02:45 UTC, jovergaag commented on src/core/CoreStore/index.ts
> +  metricsStore: MetricsStore = new MetricsStore({ rootStore: this });
That's nice! Can you please also do that for the filtersStore and pagePracticesStore for consistency.

2022-02-15 17:55 UTC, jovergaag commented
> I pushed up a commit that gets rid of the `PageSystem` error.

Oops, I failed to enter my ssh password to push the commit so it never pushed. Should be here now :)

2022-02-15 19:53 UTC, nasaownsky commented on src/core/CoreStore/index.ts
> +  metricsStore: MetricsStore = new MetricsStore({ rootStore: this });
Seems like we need determine `PagePracticesStore` in the old way, because it's throws an error if not. Also, new logic of `PathwaysFilterBar` looks great, but could you please fix its testing? I can't get why they aren't work.

2022-02-18 01:34 UTC, jovergaag approved these changes
So much nicer!! THANK YOU

2022-02-18 01:35 UTC, merged