[US_ND] Admissions from Supervision to Prison by officer chart
Recidiviz/pulse-dashboard pull request #1672
Opened 2022-02-23 14:36 UTC by nasaownsky

## Description of the change

Added Admissions from Supervision to Prison by officer chart

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1612 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-02-23 14:42 UTC, nasaownsky commented
The chart isn't display. May it be problem with the data? I checked metadata and `time_period` manifest is different in `supervision_to_prison_population_snapshot_by_officer` than in `supervision_to_prison_population_snapshot_by_dimension`, but replacing it doesn't change anything.

2022-02-24 02:52 UTC, jovergaag reviewed
I started to debug it but ran out of time. I'll take a look again in the mormning.

2022-02-24 02:52 UTC, jovergaag commented on src/tenants.ts
> +        PATHWAYS_SECTIONS.countByOfficer,
Please move this up to be just below `countByLocation`

2022-02-24 02:54 UTC, jovergaag commented
It might be best to create a new metric for this since there are so many differences in dimensions between it and `SupervisionPopulationSnapshotMetric`

2022-02-25 11:35 UTC, nasaownsky commented
Yeah I tried, but no data appeared. In #1674 snapshot charts also wasn't work, but changed `time_period` in fixture made it work there. Here it isn't affect chart. Maybe another problem in fixtures?

2022-02-28 22:40 UTC, jovergaag commented
@nasaownsky You were right, the fixtures were missing an important value. It is fixed now and I'm seeing data in the chart. There is still some formatting to do to make it look pretty. I'll review it once that formatting is all finished!

2022-02-28 23:29 UTC, jovergaag commented
Also, please sort them from the highest count to the lowest, with the highest on the left of the X-axis, and only show the 20 officers with the highest counts.

2022-03-01 19:24 UTC, jovergaag requested changes
Looks good other than those quick changes based on requirements change.

2022-03-01 19:24 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +  if (isOfficer) sortByValues(data, "value").splice(20);
I've shown this to the design team, and they have decided to change the requirement. We will not show the officer name on the x-axis, and only show the name in the tooltip. Do not splice it to the highest 20 officers.

This allows us to show all officers - specifically the highest revocation count officers, AND the lowest revocation count officers which is also important. Sorry for the changes.

2022-03-02 22:38 UTC, jovergaag reviewed
This looks great now! As with the other ND chart, I'm waiting for sign-off from data quality and product. Once that is in I will approve and merge!

2022-03-03 17:53 UTC, jovergaag requested changes
Design review uncovered a couple of things. The download data is broken because of a missing filter option, and we need to change the formatting of the name to be title case.

2022-03-03 17:53 UTC, jovergaag commented on src/core/models/utils.ts
> +        officerName: record.officer_name,
Please format this name so that it is title case - feedback from design review.

2022-03-14 22:38 UTC, jovergaag approved these changes
Done, finally :)

2022-03-14 22:40 UTC, merged