Pathways design polish
Recidiviz/pulse-dashboard pull request #1723
Opened 2022-03-24 11:49 UTC by nasaownsky

## Description of the change

- [x] Download data icon is incorrect size. Try to make the existing icon 16x16px. If that doesn't work with the icon imported from web-libraries use the icon below.
- [x] Change the color of the highlighted bar(s) on the gold charts to #25B894
- [x] Decrease the width of the LH Nav (previous design update)
- [x] Make LH Nav icons smaller (previous design update)
- [x] Change line and dot style in line graphs

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1697 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-03-24 18:12 UTC, jovergaag requested changes
Looking pretty good!

2022-03-24 18:12 UTC, jovergaag commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +                return { fill: styles.signalHighlight };
After working with the designer on this for a bit, we have decided to change the highlight/hover color interaction. Instead of giving the highlighted/hovered bars a new color, let's keep them the SAME color, and just fade the other (NOT highlighted or hovered) bars by adjusting the opacity by 0.45.

Does that make sense? That way the gold chart and the green chart have the same interaction. Let me know if you have questions on this.

2022-03-28 14:34 UTC, nasaownsky commented on src/core/VizPopulationSnapshot/VizPopulationSnapshot.tsx
> +                return { fill: styles.signalHighlight };
I don't know how to manage the opacity the way you specified, `fill-opacity` will make columns semi-transparent, which we don't want, I suppose. So we'll need specified colors anyway.

2022-04-12 22:24 UTC, jovergaag approved these changes

2022-04-13 18:16 UTC, merged