[Workflows] move new search UI to homepage
Recidiviz/pulse-dashboard pull request #1938
Opened 2022-06-03 20:16 UTC by macfarlandian

## Description of the change

This moves the new caseload search page into position as the Workflows home, shifting the previous homepage (searching CR-eligible clients only) to `/workflows/compliantReporting`.

This change is live in the [preview channel](https://recidiviz-dashboard-stag-e1108--client-profile-dbjoepju.web.app/workflows) ... we may want to hold this out of `main` until release time though as it will ungate the entire new UI flow for all users once it's released to prod.

## Type of change

- [x] New feature (non-breaking change that adds functionality)

## Related issues

> Closes #1933 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- ~E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))~

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-06-03 21:29 UTC, Catacola requested changes
Works fine for me! I have a few small change requests.

2022-06-03 21:29 UTC, Catacola commented on src/core/PagePracticesV2/PagePracticesV2.tsx
> +  });
To ensure this only runs once, can you wrap this in a `useEffect()` hook?
```suggestion
  useEffect(() => {
    window.scrollTo({
      top: 0,
    })
  }, []);
```

2022-06-03 21:29 UTC, Catacola commented on src/core/views.ts
>  // `[...OPPORTUNITY_TYPES, "profile"]` caused a TypeError in Jest,
Update comment please

2022-06-03 21:32 UTC, macfarlandian commented on src/core/PagePracticesV2/PagePracticesV2.tsx
> +  });
I'm not so sure that is actually the behavior we want ... I don't think this component will actually unmount/remount on navigation since it's above the router

2022-06-03 21:37 UTC, macfarlandian commented on src/core/PagePracticesV2/PagePracticesV2.tsx
> +  });
no I was wrong, it does actually work. i don't understand why but what else is new

2022-06-03 21:44 UTC, Catacola approved these changes
Thanks!

2022-06-13 16:37 UTC, macfarlandian commented
closing this as we now intend to defer the homepage swap to a later release with more features. the incidental improvements here will be incorporated elsewhere

2022-06-13 16:37 UTC, closed without merging