[Workflows] Enable Workflows for ND and add basic support for multiple opportunities
Recidiviz/pulse-dashboard pull request #2093
Opened 2022-07-26 19:19 UTC by jovergaag

## Description of the change

- Enables workflows for ND
- Updates the workflows opportunity route and redirects `/workflows` to `/workflows/compliantReporting` to ensure a smooth transition for existing TN users
- Adds `workflowsOpportunities` to the tenant config to configure opportunities per tenant
- Routes to appropriate opportunity page per tenant

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #2092

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-07-26 21:47 UTC, macfarlandian requested changes

2022-07-26 21:47 UTC, macfarlandian commented on src/PracticesStore/PracticesStore.ts
> +  opportunities: OpportunityType[] = [];
might rename this to `opportunityTypes` or something so it doesn't get confused with actual Opportunity objects

2022-07-26 21:47 UTC, macfarlandian commented on src/PracticesStore/PracticesStore.ts
> +    );
seems like this could be a computed get method instead of a manual reaction

2022-07-26 21:47 UTC, macfarlandian commented on src/PracticesStore/PracticesStore.ts
> +      earlyTermination: undefined,
maybe we update the type to be a `Partial<Record<whatever>>` so that we don't have to do this? (I'm not sure we even need this member anymore honestly, we barely use it and it could just be replace by an `<array>.length` ... it has been on my list to get rid of this but haven't gotten around to it

2022-07-26 21:47 UTC, macfarlandian commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        to={`/${PATHWAYS_VIEWS.workflows}/${opportunities[0]}`}
I know the routing is a little convoluted but this one was actually intended to go directly to the workflows root url (regardless of whatever happens to be there, allegedly it will be the full caseload search eventually)

2022-07-26 21:47 UTC, macfarlandian commented on src/core/WorkflowsLayouts/WorkflowsNavLayout.tsx
> +  const { opportunities } = practicesStore;
could be `{practicesStore: { opportunities } } = useRootStore()`

2022-07-26 21:47 UTC, macfarlandian commented on src/core/WorkflowsLayouts/WorkflowsNavLayout.tsx
> +              })}
love this. elegant solution

2022-07-26 21:47 UTC, macfarlandian commented on src/core/views.ts
> +  practices: `/${PATHWAYS_VIEWS.workflows}/:opportunityId`,
I think we still need a root page, even if we are redirecting everyone in TN away from it at the moment? I doubt we are going to want to replicate that experience in ND because it was basically just a corner we cut to accelerate the first TN release

2022-07-26 22:40 UTC, daschi commented on src/App.js
> +                    <Redirect from="/workflows" to="/workflows/compliantReporting" />
The Recidiviz logo in the `WorkflowsFormLayout` is linking to `/workflows`, which on the ND page is redirecting to here. Wondering if we want to make this state-specific at this point, or will it be something that'll be figured out once we have a landing page?

2022-07-26 22:42 UTC, jovergaag commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        to={`/${PATHWAYS_VIEWS.workflows}/${opportunities[0]}`}
I had played around with leaving it as the root url, but in this in between state until the root url points to the full caseload search, we are redirecting `/workflows` to `/workflows/compliantReporting` to ensure consistency for TN users. However, that redirect is not valid for ND.

I figured that we have two options
1. Point this global nav link at the first opportunity for now - which works as expected for both TN and ND - then change it to be the full caseload search when we are ready for that to be the homepage at which point we remove the TN redirect
2. Leave this global nav pointing at `/workflows` but use a hook to navigate to the correct opportunity page based on the tenant, and remove the redirect.

The first seemed more straightforward for now and is a temporary solution but I am open to it if you think we should implement #2.

2022-07-26 22:47 UTC, daschi commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        to={`/${PATHWAYS_VIEWS.workflows}/${opportunities[0]}`}
I like option 1 for now...it seems like option 2 would be useful if we decide not to show the caseload search as the landing page for certain states, and if the opportunities will be prioritized, but that doesn't seem difficult to implement later when it's needed.

2022-07-26 22:59 UTC, jovergaag commented on src/App.js
> +                    <Redirect from="/workflows" to="/workflows/compliantReporting" />
Hm, I think you have an old version of the branch. If you pull down the latest version you should see ND navigating to the correct opportunity type.

2022-07-26 23:03 UTC, daschi commented on src/App.js
> +                    <Redirect from="/workflows" to="/workflows/compliantReporting" />
Strange I am still seeing it route to `/workflows/compliantReporting` after pulling

2022-07-26 23:10 UTC, jovergaag commented on src/App.js
> +                    <Redirect from="/workflows" to="/workflows/compliantReporting" />
After you go to the Profile and select "North Dakota", then clicking on the workflows icon? If I navigate to ND from the profile page it defaults to Early Termination.

2022-07-26 23:11 UTC, jovergaag commented on src/App.js
> +                    <Redirect from="/workflows" to="/workflows/compliantReporting" />
Oh I see what you mean, you're manually navigating to `/workflows` while on ND. I see. I'll think about that.

2022-07-26 23:14 UTC, macfarlandian commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        to={`/${PATHWAYS_VIEWS.workflows}/${opportunities[0]}`}
I guess maybe it depends on the timing of the ND launch versus the TN homepage changeover (a question for @sychang maybe, which one she thinks will happen first?) If we are OK launching in ND without a proper homepage, or if we think TN will be ready to switch over pretty soon, then I think option 1 does work (but there may be more change-management later if we have two or more groups of users whose homepage is going to change). 

Otherwise I think option 2 is better  ... once there are three states then TN will be the exception from the default, and once they switch over we can remove the special-case redirect feature entirely without affecting anything in any other states

2022-07-26 23:17 UTC, daschi commented on src/App.js
> +                    <Redirect from="/workflows" to="/workflows/compliantReporting" />
Not just manually - it's by clicking on the Recidiviz logo in the side nav

2022-07-27 00:13 UTC, jovergaag commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        to={`/${PATHWAYS_VIEWS.workflows}/${opportunities[0]}`}
[This commit](fada03170b27f5702ab8593ce4428365a6ddac77) is a rough attempt at option 2. It allows us to redirect the root url to whatever we want it to be based on the tenant. I think I like it better than option 1 now that it is written out. LMK what you think. If we like it I will write some tests.

2022-07-27 00:23 UTC, macfarlandian commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        to={`/${PATHWAYS_VIEWS.workflows}/${opportunities[0]}`}
yeah that is pretty good actually ... I thought you were going to have to do something way grosser than that!

2022-07-27 07:16 UTC, sychang commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        to={`/${PATHWAYS_VIEWS.workflows}/${opportunities[0]}`}
Maybe not relevant anymore, but ND launch will definitely happen before TN changeover.

2022-07-27 16:40 UTC, macfarlandian commented on src/core/ViewNavigation/ViewNavigation.tsx
> +        to={`/${PATHWAYS_VIEWS.workflows}/${opportunities[0]}`}
no that's good to know! I suspected that would be the case. all the more reason to go with jen's new solution

2022-07-27 19:25 UTC, Catacola commented on src/core/views.ts
> +  practices404: `/${PATHWAYS_VIEWS.workflows}/not-found`,
While we're here, can you update theses to `workflows`?

2022-07-27 19:48 UTC, jovergaag commented on src/core/views.ts
> +  practices404: `/${PATHWAYS_VIEWS.workflows}/not-found`,
they will be changed in Daniela's PR I think - I will rebase once that is merged and see where we're at!

2022-07-27 21:23 UTC, jovergaag commented on src/PracticesStore/PracticesStore.ts
> +      earlyTermination: undefined,
It wasn't being used anywhere so I removed it!

2022-07-27 21:29 UTC, macfarlandian commented on src/PracticesStore/PracticesStore.ts
> +      earlyTermination: undefined,
amazing

2022-07-27 22:06 UTC, jovergaag commented on src/tenants/US_TN.ts
> +  workflowsOpportunities: ["compliantReporting"],
@Catacola I tried adding this directly to the navigation `workflows` key - but that navigation object is set up to control access to specific pages based on permissions, not necessarily to load specific content when on a specific page.

Do we think that we will ever want to show certain opportunities to specific users and not to others? @sychang

2022-07-27 22:14 UTC, jovergaag commented on src/tenants/US_TN.ts
> +  workflowsOpportunities: ["compliantReporting"],
Actually - workflows uses the feature variants and not the Pathways permissions framework - so even if we do want to gate access to specific opportunities by users we can do that easily using feature variants.

I think this structure with `workflowsOpportunities` is the cleanest way to implement this rather than trying to embed it within the navigation `workflows` array.

2022-07-28 16:55 UTC, Catacola approved these changes

2022-07-28 16:55 UTC, Catacola commented on src/tenants/US_ND.ts
> +    workflows: ["earlyTermination"],
😁

2022-07-28 17:17 UTC, macfarlandian commented on src/WorkflowsStore/__tests__/WorkflowsStore.test.ts
> -});
this test unfortunately was just watching the deleted method to know when the async subscriptions were finished running; I think we do still want to maintain a test of this behavior so we should restore it and sub in a different computed value to watch (e.g. the clients returned by `mockSubscribeToCaseload`)

2022-07-28 17:17 UTC, macfarlandian commented on src/core/views.ts
> +export const WORKFLOWS_PATHS: Record<string, string> = {
I think it's actually better ergonomics if you don't declare the type here ... that way Typescript will enforce the specific keys in this object instead of allowing arbitrary ones to be read and written

2022-07-28 21:24 UTC, jovergaag commented on src/WorkflowsStore/__tests__/WorkflowsStore.test.ts
> -});
Good catch. Thank you!

2022-07-28 21:31 UTC, macfarlandian commented on src/WorkflowsStore/__tests__/WorkflowsStore.test.ts
>    workflowsStore.hydrate();
you can remove this line since `waitForHydration` calls this method

2022-07-28 21:31 UTC, macfarlandian commented on src/WorkflowsStore/__tests__/WorkflowsStore.test.ts
> +  expect(mockSubscribeToOfficers).not.toHaveBeenCalled();
so this is not quite right, what we actually want to verify in this test is that it disposes of its old subscriptions when replacing them with new ones (they don't get garbage-collected automatically and will leak memory otherwise). 

I think you can still just use `mockUnsub` here because there is a default mock implementation of `subscribeToCaseloads` that returns it?

2022-07-28 21:59 UTC, jovergaag commented on src/WorkflowsStore/__tests__/WorkflowsStore.test.ts
> +  expect(mockSubscribeToOfficers).not.toHaveBeenCalled();
Ok. I clearly don't understand all of this very clearly...but I think it is right now?

2022-07-28 22:26 UTC, macfarlandian commented on src/WorkflowsStore/__tests__/WorkflowsStore.test.ts
> +  expect(mockSubscribeToOfficers).not.toHaveBeenCalled();
yeah don't feel too bad, i wrote these tests and I barely understand what is happening in them

2022-07-28 22:26 UTC, macfarlandian approved these changes
🙌🏻

2022-07-29 17:04 UTC, merged