[Workflows] Use firestore rules to prevent cross-state data access
Recidiviz/pulse-dashboard pull request #2101
Opened 2022-07-27 04:03 UTC by Catacola

## Description of the change

Update the firestore rules to prevent cross state read or write access. This is done by ensuring that the state code in the user request matches either the state code of the modified documents or the retrieved documents (or is a recidiviz user).

Tests have been written to cover the changes. Additionally, I tested this in staging against real data. All flows are working without modification.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #2055

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-07-27 16:15 UTC, daschi requested changes

2022-07-27 16:15 UTC, daschi commented on firestore-config/firestore.rules
> +        || request.auth.token.stateCode == resource.data.stateCode
Trying to learn about the firestore rules, but what is the difference between `resource.data.stateCode` here and `request.resource.data.stateCode` on the write? Is `resource` available at the top level for reads?

2022-07-27 16:15 UTC, daschi commented on firestore-config/reads.test.js
> +  async (userState, getUserContext) => {
Might be overkill but wanted to ask if we should add a test for "user cannot read other state data"

2022-07-27 16:15 UTC, daschi commented on firestore-config/writes.test.js
> +  "%s user can write cross-state data",
nit: user can not write cross-state data
```suggestion
  "%s user can not write cross-state data",
```

2022-07-27 16:45 UTC, macfarlandian commented on firestore-config/firestore.rules
> +        || request.auth.token.stateCode == resource.data.stateCode
IIRC `resource` is the existing document (for both reads and writes) and `request.resource` is the incoming write

2022-07-27 16:45 UTC, macfarlandian commented on firestore-config/reads.test.js
> +  async (userState, getUserContext) => {
+1

2022-07-27 17:38 UTC, Catacola commented on firestore-config/firestore.rules
> +        || request.auth.token.stateCode == resource.data.stateCode
^ Bingo

2022-07-27 17:41 UTC, Catacola commented on firestore-config/reads.test.js
> +  async (userState, getUserContext) => {
Not overkill. Totally meant to write this, but guess I only did it for the writes.

2022-07-27 17:43 UTC, macfarlandian requested changes

2022-07-27 17:44 UTC, Catacola commented on firestore-config/firestore.rules
> +        || request.auth.token.stateCode == resource.data.stateCode
Ohhhhhh, that just made me realize that we are open to a vulnerability where a TN user can overwrite a ND doc and vice versa as long as they set the new state code to their state code.

2022-07-27 17:45 UTC, macfarlandian commented on firestore-config/writes.test.js
> +);
sorry I think i got sidetracked by something in the middle of this review and forgot to add this, but maybe we need to migrate the user-generated documents to include a state code field before making these security changes? I suspect that something is going to break (possibly with reads as well as writes)

2022-07-27 18:42 UTC, Catacola commented on firestore-config/firestore.rules
> +  }
I've been debating that same thing. The only thing it may open us up to is someone in a state accessing data while we're still developing for that state. E.g. any authorized user can create a firebase token, even if workflows isn't enabled in their state. Say we're developing a new tool for ID. An ID user could, in theory, generate a valid firestore token and read ID data from firestore. I'm not sure this is a big issue, but it could happen with this change.

2022-07-27 18:42 UTC, Catacola commented on firestore-config/writes.test.js
> +);
fine by me

2022-07-27 18:46 UTC, macfarlandian commented on firestore-config/firestore.rules
> +  }
ah I thought they would be prevented from generating a token by the permissions check in auth0 but I see that is not the case. I do agree this concern is valid if not hugely likely, but maybe we should solve for it in the token exchange endpoint instead? (e.g. by inspecting the user permissions or something)

2022-07-27 20:35 UTC, Catacola commented on firestore-config/firestore.rules
> +  }
Agreed! Created a task to do so here: https://github.com/Recidiviz/pulse-dashboard/issues/2104

2022-07-27 22:16 UTC, Catacola commented on firestore-config/writes.test.js
> +);
Sorry, missed your second message. That migration should be extremely easy. We can just slap `stateCode: "US_TN"` on everything.

2022-07-27 22:31 UTC, daschi commented on firestore-config/writes.test.js
> +      getOtherUserContext(testEnv).firestore(),
I think I'm confusing myself on how this should work - I expected that this would be `getUserContext` and the state code would be `otherUserState` and that would fail, and then below `getUserContext` with `userState` would pass?

2022-07-27 23:41 UTC, Catacola commented on firestore-config/writes.test.js
> +      getOtherUserContext(testEnv).firestore(),
With the first command, I'm building a bunch a document with the name "foo" in each of the collections with the state_code of the second state. I then make sure that the first state cannot override the other state's date, even if they try to set the state code to match theirs. This was a vulnerability in my original implementation of these rules.

2022-07-28 15:50 UTC, daschi approved these changes

2022-07-28 18:29 UTC, macfarlandian reviewed
this is looking great but a couple of small comments. also this is definitely going to break all writes now so we need to block it on both a data migration and a FE change to update the write methods

2022-07-28 18:29 UTC, macfarlandian commented on firestore-config/firestore.rules
> +      allow write: if allowWrite();
maybe these `write` rules should all be `update` instead now that there is a separate `create` rule? probably makes no practical difference in its current state but if something changes this would clobber a more restrictive `create` rule

2022-07-28 18:29 UTC, macfarlandian commented on firestore-config/writes.test.js
> +);
i'm not so sure we should allow this actually ... I can't think of a use case for it, seems like something we would only do by mistake and bring ruin upon ourselves

2022-07-28 19:01 UTC, macfarlandian commented on firestore-config/firestore.rules
> +      allow create: if allowCreate();
noticed something else here actually ... for this collection (as well as for `featureVariants`) I think we should instead check that the document ID matches the email address in the auth token, for both reads and writes. There is no real use case for letting a user access someone else's preferences (including Recidiviz users since we don't actually administer anything via the frontend)

2022-07-29 21:52 UTC, Catacola commented on firestore-config/writes.test.js
> +);
I was thinking it would be for us to fix a mistake, but I guess we could always do that in the actual firestore UI

2022-07-29 22:04 UTC, macfarlandian commented on firestore-config/writes.test.js
> +);
yeah i think that would be the preferred method. i am not sure by what mechanism we would do it within the workflows app anyway? (if there is one it's probably not there on purpose)

2022-08-15 21:38 UTC, macfarlandian commented on firestore-config/firestore.rules
> +      allow write: if false;
you can just drop this line, I believe nothing is allowed by default

2022-08-15 21:41 UTC, macfarlandian commented on firestore-config/firestore.rules
> +      allow write: if hasProperStateCodePrefix(clientId) && (isRecidiviz() || stateCodeMatchesClientId(clientId));
I did not actually believe it was possible to do this without a migration until I reached this line. incredible

2022-08-15 21:48 UTC, macfarlandian commented on firestore-config/testUtils.js
> + * Update collections are readable and writeable only by TN or Redidiviz
reviditiz

2022-08-15 21:51 UTC, macfarlandian commented on server/workflows/firebaseToken.js
> +    uid = req.user[`${METADATA_NAMESPACE}email_address`];
is this ... broken in the wild? or do these values just happen to be the same but this is the more reliable source?

2022-08-15 22:01 UTC, Catacola commented on firestore-config/firestore.rules
> +    return clientId.size() > 7 && clientId.lower()[0:3] == "us_" && clientId[5] == "_";
It could totally be done in regex. I even use a regex like 4 lines below.

2022-08-15 22:09 UTC, Catacola commented on server/workflows/firebaseToken.js
> +    uid = req.user[`${METADATA_NAMESPACE}email_address`];
Auth0 supplies a string that may or may not include your email address. I changed it to be the user's email address assuming we got to specify the uid to be whatever we wanted as long as it was unique. It worked against the staging firestore for me. I can revert this and add a new field with the user's email if that would be better.

2022-08-15 22:10 UTC, Catacola commented on src/WorkflowsStore/__tests__/WorkflowsStore.test.ts
> +  await workflowsStore.hydrate();
I think it happened because pycharm yelled at me so it did it to make it happy, but it looks like `waitFoyHydration()` might do the trick as well.

2022-08-15 22:11 UTC, Catacola commented on firestore-config/firestore.rules
> +      allow write: if false;
I'm pretty sure that's true. I was being pedantic, but I guess that's overkill.

2022-08-17 17:23 UTC, merged