[Workflows] Support reading/writing to clientUpdatesV2 with globally unique id
Recidiviz/pulse-dashboard pull request #2115
Opened 2022-07-29 00:17 UTC by daschi

## Description of the change

This updates the subscription to `clientUpdates` to first subscribe to `clientUpdatesV2`, and to then subscribe to `clientUpdates` collection if the document does not exist. 

It also updates the write functions so that we are merging the old document and the new changes and saving it to the new `clientUpdatesV2` collection.

This adds a new rule for the new collection, which I can update once the other firestore rules PR is merged.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #2090 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-07-29 00:33 UTC, daschi commented
I’ll look into the failing test on Monday! I think I am checking for an object as falsy and that’s failing, but was having by TS issues with using ‘Object.keys’

2022-08-04 17:27 UTC, macfarlandian requested changes

2022-08-04 17:27 UTC, macfarlandian commented on src/WorkflowsStore/Client.ts
> +      !this.fetchedUpdatesV2.current() ||
I think you don't want this test here because it will only be falsy (i.e. `undefined`) while the initial fetch is pending. So it would result in always using the value from the old collection

2022-08-04 19:49 UTC, daschi commented on src/WorkflowsStore/Client.ts
> +      !this.fetchedUpdatesV2.current() ||
Once the initial fetch completes though, would this not get re-computed?

2022-08-04 19:55 UTC, daschi commented on src/WorkflowsStore/Client.ts
> +      !this.fetchedUpdatesV2.current() ||
I am seeing v2 update on the frontend, but when I refresh I see it flash from v1 to v2 which is not great....I'll think about this a bit to see if we can wait until both are loaded before returning something

2022-08-04 21:37 UTC, daschi commented on src/WorkflowsStore/Client.ts
> +      !this.fetchedUpdatesV2.current() ||
Okay I switched this around to return v2 from the `if` statement...let me know if that works better! I tested this with the staging firestore and it seemed to be doing all the right things 🤞

2022-08-04 21:38 UTC, daschi commented on src/WorkflowsStore/Client.ts
> +      !this.fetchedUpdatesV2.current() ||
also happy to switch this to use `compliantReportingUpdates` as the collection name instead

2022-08-05 21:51 UTC, macfarlandian approved these changes
I realized that if we are going to move to subcollections as discussed in https://github.com/Recidiviz/pulse-dashboard/pull/2149#discussion_r938333947 then there isn't really any benefit to doing it as part of this PR, as we still have to do this migration to implement the new ID scheme. I'm going to go ahead and get this merged to unblock further development

2022-08-05 22:01 UTC, merged