[Workflows] make OpportunityDenial and OpportunityPreview opportunity type agnostic
Recidiviz/pulse-dashboard pull request #2156
Opened 2022-08-08 22:40 UTC by jovergaag

## Description of the change

Changes `CompliantReportingDenial` to `OpportunityDenial` and `CompliantReportingPreview` to `OpportunityPreview` to make them opportunity type agnostic. Also updates the updates the client update functions to include the opportunity type to handle multiple opportunity types.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #2099

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2022-08-09 19:18 UTC, jovergaag commented on src/core/WorkflowsClientProfile/EarlyTerminationModule/EarlyTerminationModule.tsx
> +const OPPORTUNITY_TYPE = "earlyTermination";
Note: this component is nearly identical to `CompliantReportingModule`. I considered making a generic component to be used for both, but somehow if felt right to keep them separate for now until we know what the form is going to look like. If anyone thinks otherwise lmk and I can make the generic component.

2022-08-09 19:20 UTC, jovergaag commented on src/core/WorkflowsClientProfile/EarlyTerminationModule/EarlyTerminationModule.tsx
> +              {getPrintText(client, OPPORTUNITY_TYPE)}
There is still an issue when printing the form - the print button gets stuck on "Printing...". The 
'COMPLETED' update is registered in firestore but I'm not sure whats going on in `WorkflowsStore` such that it is reflected here in the component. There is a [ticket](https://app.zenhub.com/workspaces/polaris-614c9f27fa19b10015ddd495/issues/recidiviz/pulse-dashboard/2158) to sort this out.

2022-08-09 20:32 UTC, macfarlandian requested changes

2022-08-09 20:32 UTC, macfarlandian commented on src/WorkflowsStore/__tests__/Client.test.ts
> +  OPPORTUNITY_TYPES.forEach(async (opportunityType) => {
could make for easier debugging if you moved this into a `test.each` instead

2022-08-09 20:32 UTC, macfarlandian commented on src/core/WorkflowsClientProfile/Details.tsx
> +        `None according to judgment orders in ${contentManagementSystem}`}
i found this naming a little confusing ... should maybe be "caseManagementSystem" instead? 

Also I think "judgment orders" and "Board Actions" in these bits of copy are probably state-specific language for TN also ... something to flag for @sychang maybe to extend the copy template

2022-08-09 20:32 UTC, macfarlandian commented on src/core/WorkflowsClientProfile/EarlyTerminationModule/EarlyTerminationModule.tsx
> +const OPPORTUNITY_TYPE = "earlyTermination";
yeah I think this makes sense for now ...can revisit when we implement the next opportunity

2022-08-09 20:32 UTC, macfarlandian commented on src/firestore/firestore.ts
> +  opportunityType: OpportunityType,
love it ... I was implementing something similar as part of #2152 that will dovetail nicely with this

2022-08-09 21:01 UTC, jovergaag commented on src/core/WorkflowsClientProfile/Details.tsx
> +        `None according to judgment orders in ${contentManagementSystem}`}
Oh yep, it is totally a case management system not content :) 

I have asked Serena and Lily for clarification on these strings in the copy doc. I'll update them when I hear back.

2022-08-09 21:10 UTC, daschi commented on src/firestore/firestore.ts
> +      ...(oldDocument?.[opportunityType] ?? {}),
I don't think we need this - this was just to be able to migrate the old compliantReporting updates.

2022-08-09 21:26 UTC, jovergaag commented on src/firestore/firestore.ts
> +      ...(oldDocument?.[opportunityType] ?? {}),
When you say we don't need this, do you mean spreading the `oldDocument`? Is that migration already over and done with? I will delete line 436 if so.

2022-08-09 21:34 UTC, daschi commented on src/firestore/firestore.ts
> +      ...(oldDocument?.[opportunityType] ?? {}),
No not yet, I think we will need to write a separate migration script to make sure we've copied over all the old documents and then delete them. We just don't need to replace `compliantReporting` with `opportunityType`, because we only need to migrate compliant reporting. Does that make sense?

2022-08-09 21:49 UTC, jovergaag commented on src/firestore/firestore.ts
> +      ...(oldDocument?.[opportunityType] ?? {}),
I think there are some `earlyTermination` documents in the old client updates collection. I don't think its doing any harm to keep it referencing the correct opportunity type here, but let me know if I'm missing something.

2022-08-10 05:37 UTC, sychang commented on src/core/WorkflowsClientProfile/Details.tsx
> +        `None according to judgment orders in ${contentManagementSystem}`}
Just responded to the comment saying we can use "None according the DOCSTARS" for this case. 

I think we can reduce configuration complexity in generalizing this by just saying "None according to ${contentManagementSystem}" so it's one less thing that needs to be configured. We lose out on a tiny bit of information, but not a huge amount and it can be explained in the methodology.

2022-08-10 17:30 UTC, Catacola requested changes

2022-08-10 17:30 UTC, Catacola commented on src/core/WorkflowsClientProfile/OpportunityDenial.tsx
> +};
It feels to me like the `Opportunity` classes should define a method that returns these. Since the below component already gets the opportunity class, it can just call this method directly to get the allowed reasons. This will prevent us from needing to remember to update this component every time we add a new opportunity.

2022-08-10 17:30 UTC, Catacola commented on src/core/WorkflowsClientProfile/OpportunityPreview.tsx
> +  )[0];
If you just want the first match, you can user `arr.find()` instead of `arr.filter()[0]`. This has the advantage of both being more terse and faster (on average).

```suggestion
  const opportunity = values(client.opportunities).find(
    (opp) => opp !== undefined
  );
```

2022-08-10 17:32 UTC, jovergaag commented on src/core/WorkflowsClientProfile/Details.tsx
> +        `None according to judgment orders in ${contentManagementSystem}`}
@sychang I just added a state specific copy object that allows us to use the state specific language, and it is structured in a way that it will be easy to pull from the copy doc whenever we get around to that. I think its fine to keep the extra detail in there!

2022-08-10 17:37 UTC, jovergaag commented on src/core/WorkflowsClientProfile/OpportunityDenial.tsx
> +};
I was imagining that this copy would live in the copy doc at some point, and this component would just load the copy from the content system whenever we get around to that. But I suppose the opportunity could also load the copy. I'll update it to see what that looks like.

2022-08-10 17:38 UTC, Catacola commented on src/core/WorkflowsClientProfile/OpportunityDenial.tsx
> +};
Actually, I see that the `Opportunity` below is a record and not the opportunity class, but it has the `opportunityType`, so we should be able to fetch the class somehow.

2022-08-10 18:42 UTC, jovergaag commented on src/WorkflowsStore/__tests__/Client.test.ts
> +  OPPORTUNITY_TYPES.forEach(async (opportunityType) => {
Much nicer! Thank you.

2022-08-10 19:37 UTC, macfarlandian commented on src/core/WorkflowsClientProfile/Details.tsx
> +};
i like the pattern here but i think the names are maybe too generic ... something should indicate that these strings are specifically for special conditions empty states

2022-08-10 19:37 UTC, macfarlandian commented on src/core/WorkflowsClientProfile/OpportunityPreview.tsx
> +  if (!opportunity) return null;
looking at this again I feel like this logic should move up to the client profile and this component should just take an `Opportunity` as a prop? That way at least we have one generic component and the temporary logic is not spread across two different locations

2022-08-11 18:32 UTC, jovergaag commented
@daschi @Catacola This is ready for another look!

2022-08-11 23:29 UTC, daschi approved these changes
looks good to me ⭐

2022-08-11 23:29 UTC, daschi commented on src/WorkflowsStore/Opportunity/EarlyTerminationOpportunity.ts
> +  INCOMPLETE_CASE_PLAN_GOALS: "Has not completed case plan goals",
Is this how it should appear in the side bar, or is this just a placeholder till we have the copy?

2022-08-12 00:00 UTC, jovergaag commented on src/WorkflowsStore/Opportunity/EarlyTerminationOpportunity.ts
> +  INCOMPLETE_CASE_PLAN_GOALS: "Has not completed case plan goals",
The copy itself is final - but the codes are just made up. What do you mean by side bar?

2022-08-12 00:20 UTC, daschi commented on src/WorkflowsStore/Opportunity/EarlyTerminationOpportunity.ts
> +  INCOMPLETE_CASE_PLAN_GOALS: "Has not completed case plan goals",
Oh because it looks like the keys in this map are what we're displaying on the frontend in the denial reasons drop down when you select one, just wondering if there is a different format it should be?

2022-08-12 17:11 UTC, jovergaag commented on src/WorkflowsStore/Opportunity/EarlyTerminationOpportunity.ts
> +  INCOMPLETE_CASE_PLAN_GOALS: "Has not completed case plan goals",
Oh yes, I had seen that a while ago and forgotten about it. I'm not sure what to do about that. 

@sychang Thoughts on what code we should display in the drop down when a client is marked as ineligible for ND? The codes currently being displayed are ones that I just made up and are the following:

<img width="724" alt="Screen Shot 2022-08-12 at 10 10 32 AM" src="https://user-images.githubusercontent.com/5872651/184409263-a08981cb-9e6d-43c8-a92c-20e9032497f6.png">

Which show up like

<img width="678" alt="Screen Shot 2022-08-12 at 10 08 55 AM" src="https://user-images.githubusercontent.com/5872651/184409079-117ab918-056f-4eec-8931-b1f440771ff6.png">

2022-08-12 18:58 UTC, jovergaag commented
@Catacola Would love a re-review from you on this today, I would like to get it merged and deployed so we can start getting some `earlyTermination` events flowing into prod views to develop the impact metrics against.

I think I would like to merge this as is without updating the codes (discussion above), and wait until next week when Serena is back to update the codes in the dropdown.

2022-08-15 17:33 UTC, Catacola approved these changes

2022-08-15 23:02 UTC, macfarlandian approved these changes
🙌🏻

2022-08-15 23:03 UTC, merged