Feature lantern specific district or region
Recidiviz/pulse-dashboard pull request #461
Opened 2020-08-31 18:55 UTC by DmitryJakubovsky

## Description of the change

* Added ability for district and region administrators to filter by their jurisdiction.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#437]
> Closes [#438]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-09-01 00:09 UTC, jessex commented on src/utils/authentication/viewAuthentication.js
> +    // 'https://dashboard.recidiviz.org/user_metadata': {
What's the status of this PR? I see this commented out bit and I see some merge conflicts. Is this ready for review?

2020-09-01 18:03 UTC, DmitryJakubovsky commented on src/utils/authentication/viewAuthentication.js
> +    // 'https://dashboard.recidiviz.org/user_metadata': {
Yes, this PR is ready now. You can uncomment this metadata info for testing functionality as a district or region administrator.

2020-09-02 19:33 UTC, jessex requested changes
Thanks, @DmitryJakubovsky! Some code comments and also some issues noted in my testing.

2020-09-02 19:33 UTC, jessex commented on src/utils/authentication/user.js
> + * Returns Auth0 user districts or null if it missed
Let's reword this docstring. "Returns the district or districts that a user should be limited to viewing data for, if there is user metadata in Auth0 specifying a district or region (group of districts) for the user."

2020-09-02 19:33 UTC, jessex commented on src/views/tenants/us_mo/community/Revocations.js
> +  const userDistricts = getUserDistricts(user);
It doesn't appear this filtering is working quite in the way you expect it, particularly when there is a `region` but not a `district`. Although the district dropdown filter does only include the districts for that region and although the Revocation Matrix chart does appear to be filtered to only include data points for that region's set of districts, it does _not_ appear that all of the other charts are being filtered to only that set of districts. For example, comment your testing block in `viewAuthentication` so that the `region` is set but not the district, and you'll see that the charts for Admissions by Month and the Admitted Individuals list (and potentially other charts, as well) are showing the same data, and that it appears to be the same data as when there is no specified `region`. Furthermore, for the Admissions by District chart, it does not appear to be highlighting the bars for the specified `district` or `region`, as called for in the PRD.

So I think that the district filtering is not being applied everywhere as expected.

2020-09-02 19:33 UTC, jessex commented on src/utils/authentication/user.js
> +export function getUserMetadata(user) {
I think I misled you by mistake with my comments in the two issues. We don't want to use `user_metadata` for this feature, but rather the existing `app_metadata` that we already use for `state_code`. Sorry about that!

We should be able to get rid of this function and retrieve the district and region from the response to `getUserAppMetadata`.

2020-09-02 19:33 UTC, jessex commented on src/components/charts/new_revocations/ToggleBar/DistrictFilter.js
> +        <Select
I noticed that two errors are printed to the console when we specify a particular district, pointing to this line:

<img width="1792" alt="Screen Shot 2020-09-02 at 13 11 15" src="https://user-images.githubusercontent.com/431895/92027488-dc0f9800-ed1f-11ea-8533-d4eebac099a9.png">

2020-09-02 19:33 UTC, jessex commented on src/views/tenants/us_pa/community/Revocations.js
> +  const { user } = useAuth0();
I suspect that this pattern of invoking Auth0 and then immediately trying to get data off of the user may not work how you expect. That `useAuth0` hook executes asynchronously, right? The `user` that gets passed immediately into the next two calls may not be resolved yet, right?

2020-09-03 10:04 UTC, DmitryJakubovsky commented on src/components/charts/new_revocations/helpers.js
> +export const transformFilters = (filters, userDistricts) => {
Yes, you are right, renamed this function name

2020-09-03 10:04 UTC, DmitryJakubovsky commented on src/utils/authentication/user.js
> + * Returns Auth0 user districts or null if it missed
Renamed. Sorry for the meager description.

2020-09-03 10:04 UTC, DmitryJakubovsky commented on src/views/tenants/us_mo/community/Revocations.js
> +  const userDistricts = getUserDistricts(user);
Fixed all defects.

2020-09-03 20:20 UTC, jessex commented on src/views/tenants/us_pa/community/Revocations.js
> +  const { user } = useAuth0();
You are right, and I was mistaken. I tested with a test user with live authentication and this worked as expected. Thanks!

2020-09-03 20:20 UTC, jessex commented on src/views/tenants/us_mo/community/Revocations.js
> +  const userDistricts = getUserDistricts(user);
All appears to be working as expected. Thanks!

2020-09-03 20:23 UTC, merged