refactored js backend and added tests
Recidiviz/pulse-dashboard pull request #465
Opened 2020-09-03 16:08 UTC by Wmaileq

## Description of the change

- generalized api routes
- moved functions to separate files
- some functions refactored
- unit tests for server/core
- unit tests for server/utils
- added babel preset and plugin without which tests for server did not work

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Partially closes  #25 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-09-03 16:10 UTC, Wmaileq commented on server.js
> +  api.metrics
There is no metricType and file params here.

2020-09-04 00:01 UTC, jessex requested changes
Thanks for the great test coverage boost and the refactor on the backend. Big fan of the decomposition going on here. I have a handful of comments but did not test locally or do a full review yet, because after some PRs I merged today you now have some merge conflicts, including some updated logic in the backend that needs to be accounted for. This will probably require changes to most of your new files.

2020-09-04 00:01 UTC, jessex commented on server.js
> +app.get("/api/:stateCode/:metricType/:file", checkJwt, api.metrics);
I'm not sure I understand this in full. This is a sample of API calls that the frontend makes today:
- `/api/us_nd/community/goals`
- `/api/us_mo/newRevocations/revocations_matrix_cells`

The latter makes sense in your update here, as there is a state code (us_mo), a metric type (newRevocations), and a file (revocations_matrix_cells). However, the former does not. It has a state code (us_nd), a metric type (community/goals), and that's it. `goals` is not a single file as you can see in the files by metric type mapping. It is a collection of files. community/goals and community/explore are hierarchically similar, but they have different overlapping sets of files.

How does this new API structure support all of the calls we currently make?

2020-09-04 08:24 UTC, Wmaileq commented on server/core/__tests__/fetchMatrics.js
> +// Recidiviz - a data platform for criminal justice reform
Yes, this is my fault

2020-09-04 08:29 UTC, Wmaileq commented on server.js
> +app.get("/api/:stateCode/:metricType/:file", checkJwt, api.metrics);
You are right, i thought that we can to generalize this routes into one because they had similar structure. I was mistaken and i will revert and think what can we do with this.

2020-09-04 11:03 UTC, Wmaileq commented on .babelrc
> +    [
In general: changes were made because jest did not run for me with this .babelrc. 
I made investigations and found that this config file was written according to already deprecated repo ([old repo](https://www.npmjs.com/package/babel-preset-env)) but actual guide is here [new repo](https://babeljs.io/docs/en/next/babel-preset-env.html) .

2020-09-04 11:05 UTC, Wmaileq commented on yarn.lock
> +"@babel/code-frame@^7.10.4":
this dependencies came with "@babel/plugin-transform-runtime": "^7.11.5", that required for running jest.

2020-09-07 10:37 UTC, Wmaileq commented
Merged changes and added full coverage to server folder.

2020-09-09 01:00 UTC, jessex requested changes
Looking good so far, @Wmaileq. One notes from local testing: I don't know what the command is to run the tests under `/server`. Running `yarn test` appears, at least in my environment, only to run the tests under `/src`. If a separate command is required to run server tests then, we should add a new command under `packages.json` that runs the server tests, like `yarn server-test` and we should rename `yarn test` to `yarn client-test` and then we should make it so that `yarn test` runs both of those commands. We should also update the README to includes notes on how to run all tests, server and client.

2020-09-09 08:59 UTC, Wmaileq commented on server/core/fetchMetrics.js
> +const memoryCache = cacheManager.caching({
Updated and added tests

2020-09-09 18:03 UTC, jessex requested changes
One more nit, and also I note that the build is failing: https://travis-ci.org/github/Recidiviz/pulse-dashboard/builds/725517712

I have the same exact set of errors when I try to run `yarn test` locally (the errors are all in `yarn test-client`) so it's not an environmental issue.

2020-09-10 10:18 UTC, Wmaileq commented
Fixed jest config.
Build success: https://travis-ci.org/github/Recidiviz/pulse-dashboard/builds/725874306

2020-09-10 19:57 UTC, jessex approved these changes
Great work, @Wmaileq!

2020-09-10 20:06 UTC, merged