Completely removed jquery
Recidiviz/pulse-dashboard pull request #470
Opened 2020-09-07 14:49 UTC by Wmaileq

## Description of the change

- removed unused deps that use jquery as dep
- replaced bootstrap-jquery functions in favor of react-bootstrap components
- replaced perfect-scrollbar by react-perfect-scrollbar

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #24 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-09-08 21:31 UTC, jessex requested changes
This is looking good, @Wmaileq! No functional regression that I've seen in local testing, but I did notice two stylistic changes that we don't want:


The export menus for the Lantern view have changed from the regular ellipsis (that you can see on master) to these blue button dropdown menus:
<img width="1093" alt="Screen Shot 2020-09-08 at 15 20 15" src="https://user-images.githubusercontent.com/431895/92529560-f4802680-f1e7-11ea-9a2a-f40728cbd809.png">


The user menu in the top right has similarly changed. Now it has an arrow indicating it's a dropdown, the subtitle under the user's name is now apparently centered instead of left-justified, and the dropdown menu has been changed so that the logout item is too thick:
<img width="202" alt="Screen Shot 2020-09-08 at 15 21 47" src="https://user-images.githubusercontent.com/431895/92529728-44f78400-f1e8-11ea-83c2-743dc5d8712c.png">

2020-09-08 21:31 UTC, jessex commented on src/components/charts/new_revocations/RevocationsByDistrict/ModeSwitcher.js
> +// TODO: delete jquery if component is being used
Is this TODO still relevant?

2020-09-08 21:31 UTC, jessex commented on src/components/topbar/TopBarUserMenuForGuest.js
> +// TODO: rewrite jquery to react-bootstrap if will be used
Same here: is this TODO still relevant?

2020-09-09 09:09 UTC, Wmaileq commented on src/components/charts/new_revocations/RevocationsByDistrict/ModeSwitcher.js
> +// TODO: delete jquery if component is being used
Yes, in this component `data-toggle="buttons"` is used - it is jquery functionality.
As this component is not used i didn't spent time rewriting this component to react-boostrap.

2020-09-09 09:13 UTC, Wmaileq commented on src/components/charts/new_revocations/RevocationsByDistrict/ModeSwitcher.js
> +// TODO: delete jquery if component is being used
Actually, i think this is duplicated component, so i think we can remove it.

2020-09-09 09:16 UTC, Wmaileq commented on src/components/topbar/TopBarUserMenuForGuest.js
> +// TODO: rewrite jquery to react-bootstrap if will be used
This component is not used anywhere.
But now i think it will be used in future, so despite it is not being used now i will refactor it.

2020-09-09 17:50 UTC, jessex reviewed
This looks great, @Wmaileq! Thanks a lot for the cleanup. See my comment below about order of merges between this and your prop types PR.

2020-09-09 17:50 UTC, jessex commented on src/components/charts/ExportMenu.js
> +  // Shape should be taken from ./propTypes.js (now not merged)
For this reason, we'll hold off on merging this until #472 has been merged

2020-09-11 16:46 UTC, jessex commented on src/components/charts/ExportMenu.js
> +  // Shape should be taken from ./propTypes.js (now not merged)
@Wmaileq now that #472 is merged, you should be able to resolve this. Looking at `propTypes.js` myself, I don't see what you're referring to, or else I'd make the change myself.

2020-09-14 21:45 UTC, jessex approved these changes
Thanks, @Wmaileq!

2020-09-14 21:49 UTC, merged