Fixes bubble chart formatting bug on smaller screen sizes
Recidiviz/pulse-dashboard pull request #487
Opened 2020-09-24 00:53 UTC by jovergaag

## Description of the change

On smaller screen sizes, the violation sum row formatting breaks. This work fixes that bug, as well as cleans up a few lint/console warnings, and updates the README to include a new process for downloading `.env` files.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #485 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-09-24 04:46 UTC, jessex requested changes
Thanks for all of the cleanup, and of course for the fix, which appears to be working from my local testing. And congrats on getting started with this repo, @jovergaag!

Just one doc nit and one question for you.

2020-09-24 04:46 UTC, jessex commented on README.md
> +From the 1Password shared vault, download and unzip the `pulse_dashboard_env_vars.zip` and copy the files into the project directory.
Since this is an open source project that is theoretically buildable by someone outside of Recidiviz, let's tweak the beginning of this sentence a bit. Something like, "For Recidiviz staff, from the shared vault, ..." And then maybe at the end of this we'd say something like, "For anyone trying to set this up independently, construct environment variables by hand based on the explanation in this readme."

Something like that maybe?

2020-09-24 04:46 UTC, jessex commented on server/core/fetchMetrics.js
> +/* eslint-disable no-console */
Ahhhh thank you 🙌

2020-09-24 04:46 UTC, jessex commented on src/assets/styles/spec/components/dashboard.scss
> -@media screen and (max-width: 1350px) {
For those of us less adept with CSS, can you explain what the actual change here was?

2020-09-24 23:15 UTC, jovergaag commented on src/assets/styles/spec/components/dashboard.scss
> -@media screen and (max-width: 1350px) {
Most of the changes in this file are some just moving things around and adding new lines before class declarations to conform to css style guidelines.

One of the important changes here was the re-ordering of the `@media screen and (max-width <>)` statements. This bug only appeared on screen widths between 1350 and 1420px, so the `@media screen and (max-width 1420px)` styles should have been applied to the violation row, instead the 1868px styles were applied as you can see in the screenshot. css files are read top to bottom, so the least restrictive screen width filters should be placed higher in the file down to more restrictive. 

The other important change that ultimately was what fixed the issue was changing the width of the cell and column to `width: 8%` for max-width 1420px on line 359 to prevent the cells from wrapping.

2020-09-25 04:32 UTC, jessex commented on src/assets/styles/spec/components/dashboard.scss
> -@media screen and (max-width: 1350px) {
Thanks for taking me to CSS School, @jovergaag!

2020-09-25 04:32 UTC, jessex approved these changes
Thanks, @jovergaag!

2020-09-25 17:26 UTC, jovergaag commented on src/assets/styles/spec/components/dashboard.scss
> -@media screen and (max-width: 1350px) {
I'm also now realizing that this screenshot should not have been posted. I'll remove it now and be sure to use demo data from now on.

2020-09-25 18:38 UTC, merged