Add Intercom support for Lantern dashboard (MO and PA only)
Recidiviz/pulse-dashboard pull request #492
Opened 2020-09-28 21:56 UTC by jovergaag

## Description of the change

Adds Intercom support for the MO and PA dashboards. The Intercom widget is present on the bottom right corner of the app for authenticated users on those dashboards. 

Functionality has been tested and the Intercom users config has been modified to include the custom attribute `state_code`.

Note: I will work with @chrispmlee on local testing to get QA/sign off from requester. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #452 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-09-28 22:47 UTC, jessex requested changes
Looks good, @jovergaag! In local testing, though, I notice that the Intercom widget is still enabled even when I switch over to a non-Lantern state like ND. I think we will want to make sure that's _not_ the case.

2020-09-28 22:47 UTC, jessex commented on src/utils/initIntercomSettings.js
> +const APP_ID = "pqcz3ikn";
Is this sensitive / should it be in an environment variable / should we rotate it now that it has been checked in?

2020-09-29 00:42 UTC, jovergaag commented on src/utils/initIntercomSettings.js
> +const APP_ID = "pqcz3ikn";
Oh yes, I meant to add the environment variable that but in all the excitement forgot to. I'll do that now.

@chrispmlee and I had discussed that if a user logs in with a Lantern state email, they would have the widget available to them as they navigate between state dashboards (not sure if that is possible or not, maybe a CSG user?) If we want to be very specific about not having the widget available on ND despite the user's state code, then I can disable Intercom specifically on that page. Thoughts?

2020-09-29 00:46 UTC, jessex commented on src/utils/initIntercomSettings.js
> +const APP_ID = "pqcz3ikn";
I think that makes sense for sure, but there are currently three groups of users to be aware of:
- Actual end-users who always have access to one state, e.g. internal users in MO or ND, and should be irrelevant to this discussion since they cannot switch states
- CSG users who have access to all of the _Lantern_ states, and because they can only switch states among Lantern states, they should always see the Intercom widget (and we'd want to be sure that the state code passed to Intercom was accurate both in their initial state they load into and the state that they switch to)
- Recidiviz users who have access to all states, and because they can switch between Lantern and non-Lantern states, if we wanted to be perfect, we would make sure that the widget only showed up for the Lantern states and went away when switching to non-Lantern states

So I would suggest doing the specific thing and not showing the widget on non-Lantern states. I believe Vlad had done this successfully, if I recall, on his Help Scout branch/PR.

2020-09-29 18:55 UTC, jovergaag commented on src/utils/initIntercomSettings.js
> +const APP_ID = "pqcz3ikn";
That makes sense. I had thought CSG had access to the ND dashboard but it makes sense that they would not.

I've updated it so that the widget only appears on MO and PA, not on ND no matter which user is logged in. For Recidiviz users, the widget is disabled when the user selects ND on their profile page and is re-enabled when they select PA or MO. That should satisfy the use cases you outlined above.

I'm still waiting on support from Intercom to change the APP_ID. Once that is finished I'll put this up for re-review.

2020-09-30 19:13 UTC, jovergaag commented
Update on this. The Intercom has been incredibly slow responding to support by both @chrispmlee  and I. Changing the app id is not something we can do without support. @sychang confirms that this is not necessary for PA launch since there are only 10 DOC leadership and they all have direct email access to us. 

I will continue to keep on top of Intercom to help us change out app id.

2020-09-30 19:45 UTC, jessex commented
Yes their support team in general has been quite slow, disappointingly. But thanks for staying on top of this!

2020-10-02 22:07 UTC, chrispmlee commented
Yes still no response from Intercom, we have pinged them every day. I did local testing on my side, and it looks good to me (aside from APP_ID stuff) Will need to work with product a little bit more to figure out how we will use intercom's Help Center. Also submitted a ticket for design to help revamp and make it look ~sparkly~ for when we do have documents up on Help Center.

2020-10-14 21:26 UTC, jovergaag commented
@jessex I think we're finally ready! Moved the new app id to env files. The styling of the chat drawer has also been updated.

FYI - the app id in the .env.development.local and .env.development are for the test workspace, so messages generated from non production apps do not end up on the main workspace. Only .env.production has the production workspace id. 

Important note about the test workspace: the launcher icon at the bottom RH corner of the APP is an on-brand green. For the test workspace it is black. So if you see a jarring black icon, just know that in production it will nicer. Or you can try it with the production id locally and see the colors for yourself.

2020-10-14 21:53 UTC, jessex approved these changes
Beautiful. Thanks so much for driving this to ground, @jovergaag!

2020-10-14 21:53 UTC, jessex commented on README.md
> +For Recidiviz staff, download and unzip the `pulse_dashboard_env_vars.zip` from the shared 1Password vault and copy the files into the project directory.
Just want to make sure you've updated this in 1Password, @jovergaag!

2020-10-14 22:02 UTC, jovergaag commented on README.md
> +For Recidiviz staff, download and unzip the `pulse_dashboard_env_vars.zip` from the shared 1Password vault and copy the files into the project directory.
I did indeed.

2020-10-14 22:07 UTC, merged