Update PA risk charts with PA specific risk categories
Recidiviz/pulse-dashboard pull request #493
Opened 2020-09-29 23:14 UTC by jovergaag

## Description of the change

PA and MO have different risk categories. This changes the risk categories for PA to apply the correct risk categories in the Risk Level, Gender, and Race charts, as well as in the Case Table.

I also added some constant files to use constants instead of string state codes and Core/Lantern state arrays.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #491

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-09-29 23:31 UTC, jessex requested changes
Thanks, @jovergaag! I dig the cleanup/rationalization here. Just a nit and an idle thought from me.

2020-09-29 23:31 UTC, jessex commented on src/tenants.js
> +    "avaiableStateCodes": [lantern.MO],
Whoooooops, typo: should be `availableStateCodes`

2020-09-29 23:31 UTC, jessex commented on src/utils/transforms/labels.js
> +const riskLevelValueToLabelByStateCode = {
I think in the long-run we will want to declare state-specific manifests for these sorts of things, maybe even as an expansion of `tenants.js` or something like it, but I don't think it's a requirement just yet.

2020-09-29 23:42 UTC, jovergaag commented on src/utils/transforms/labels.js
> +const riskLevelValueToLabelByStateCode = {
I totally agree. I was thinking of heading down that route in this PR but given the time pressure just wanted to make sure we can get this in before PA launch which *might?* be Thursday.

2020-09-29 23:42 UTC, jovergaag commented on src/tenants.js
> +    "avaiableStateCodes": [lantern.MO],
great catch.

2020-09-30 02:01 UTC, jessex approved these changes
🙌

2020-09-30 18:04 UTC, merged