error boundaries added
Recidiviz/pulse-dashboard pull request #500
Opened 2020-10-01 12:30 UTC by Wmaileq

## Description of the change

- Added fetching error catching
- Charts wrapped with ErrorBoundaries

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #285 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-01 22:03 UTC, jessex requested changes
Well done, @Wmaileq! Code looks solid to me. I don't think the error boundary is working exactly as prescribed, though, at least not in my testing. 

To test this, I updated the name of the file being requested in the API call from a given chart component, e.g. changing L68 of `RevocationMatrix.js` from `revocations_matrix_cells` to `bogusbogus`. You see that the error successfully renders in place of the chart, but then a few seconds later the page crashes anyway:

<img width="1772" alt="Screen Shot 2020-10-01 at 15 55 51" src="https://user-images.githubusercontent.com/431895/94867750-0cba1e80-03ff-11eb-8862-a5a01e40e907.png">

2020-10-02 03:11 UTC, sychang commented on src/components/Error.js
> +  text: "Oops... Something went wrong. Check console for detailed info.",
Copy suggestion: "Something went wrong while loading this chart. Check back later or contact feedback@recidiviz.org for more information."

2020-10-02 04:56 UTC, Wmaileq commented
> Well done, @Wmaileq! Code looks solid to me. I don't think the error boundary is working exactly as prescribed, though, at least not in my testing. 
> 
> 
> 
> To test this, I updated the name of the file being requested in the API call from a given chart component, e.g. changing L68 of `RevocationMatrix.js` from `revocations_matrix_cells` to `bogusbogus`. You see that the error successfully renders in place of the chart, but then a few seconds later the page crashes anyway:
> 
> 
> 
> <img width="1772" alt="Screen Shot 2020-10-01 at 15 55 51" src="https://user-images.githubusercontent.com/431895/94867750-0cba1e80-03ff-11eb-8862-a5a01e40e907.png">
> 
> 

Yes, it is the dev environment issue, you can close error overlay by pressing 'esc' or cross at the right top of the screen or by disabling error overlays globally in dev. mode
In production it should work as expected.

2020-10-02 19:40 UTC, jessex approved these changes
We're good to go here! Was able to properly test by producing a build and running that locally against the dev database, changing one of the Lantern charts to use a bogus API path which doesn't exist in staging. Pushed up another commit which fixed some whitespace issues with the error message. Ready to merge! Thanks, @Wmaileq.

2020-10-02 19:51 UTC, merged