separated getFilters and getViolation and added tests.
Recidiviz/pulse-dashboard pull request #502
Opened 2020-10-01 16:35 UTC by Wmaileq

## Description of the change

- downloads prettified
- getFilters and getViolation separated

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Part of #25 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-01 19:17 UTC, jessex commented
Hey, @jovergaag: would you mind taking a pass through this code review when you get a chance? It's another boost in test coverage for the app.

2020-10-06 02:44 UTC, jovergaag requested changes
Just one small copy change but this looks great! Thanks!

2020-10-06 02:44 UTC, jovergaag commented on src/assets/scripts/utils/getViolation.js
> +  console.log(reportedViolations, violationType);
oops!

2020-10-06 02:44 UTC, jovergaag commented on src/assets/scripts/utils/getFilters.js
> +    : `Supervision type: ${pipe(
Should this be "Supervision level: "?

2020-10-06 02:44 UTC, jovergaag commented on src/assets/scripts/utils/downloads.js
> +import downloadjs from "downloadjs";
Thanks for cleaning this up!

2020-10-06 02:44 UTC, jovergaag commented on src/assets/scripts/utils/__tests__/getFilters.js
> +      "3 years, District: SLCRC, Case type: Sex Offence, Supervision type: Probation, Supervision type: Enhanced Supervision";
I believe this addition should be "Supervision level"

2020-10-06 02:45 UTC, jovergaag commented on .eslintignore
> +!src/assets/scripts/utils/getViolation.js
Should we whitelist `downloads` now that it is prettified?

2020-10-06 18:40 UTC, Wmaileq commented on .eslintignore
> +!src/assets/scripts/utils/getViolation.js
Not yet, there are a lot of eslint errors here that should be fixed while separating\writing tests on downloads functions.

2020-10-06 18:41 UTC, Wmaileq commented on src/assets/scripts/utils/downloads.js
> +import downloadjs from "downloadjs";
It was just prettified, the next step should be fixing all eslint errors (15 problems)

2020-10-06 21:07 UTC, jovergaag approved these changes
💯

2020-10-08 15:52 UTC, Wmaileq commented
@jovergaag, @jessex Please merge this one, as i have no rights.

2020-10-13 18:53 UTC, merged