Tech debt: Top level classnames and BEM refactor
Recidiviz/pulse-dashboard pull request #512
Opened 2020-10-05 10:46 UTC by Wmaileq

## Description of the change

- Added classnames to top level containers
- Some (Chip, Error) components styles refactored to BEM (__ - element), (_ - modificator)
- Fixed some eslint\prettier confilcts

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-06 02:18 UTC, jovergaag requested changes
This looks great! THANK YOU for taking on this monotonous but useful task. 

I made a few comments about naming conventions, and a few things to add.

One other request. In each of the tenants `Revocations`, can you add/modify container classes for the high level components, for consistency in navigating the DOM. For example, add `AllChartsContainer`, and `MatrixContainer`.

2020-10-06 02:18 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationMatrix/RevocationMatrixCell.js
> +    <div className="RevocationMatrixCell cell">
Here is where we could either go as you did with `RevocationMatrixCell` or use `RevocationMatrix__cell` since the cell will always be a child element of the matrix. That might make nesting styles a bit easier. This one is a judgment call, it's up to you. But wanted to let you know know in case the styling of the matrix was difficult without the nesting.

2020-10-06 02:18 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationMatrix/RevocationMatrixRow.js
> +      className={cx("RevocationMatrixRow", "violation-row", {
Same naming here as with the cell, it's really just a judgment call based on how the styles are laid out.

2020-10-06 02:18 UTC, jovergaag commented on src/components/topbar/TopBarLayout.js
> +  <div
It would make sense to me to name this `TopBar`, then the child elements would be `.TopBar__title`, `.TopBar__logo` etc.

2020-10-06 02:18 UTC, jovergaag commented on .eslintignore
> +!src/components/charts/ExportMenu.js
Good catches!

2020-10-06 02:18 UTC, jovergaag commented on src/components/charts/new_revocations/ToggleBar/FilterField.js
> +    <div className={cn("FilterField", topLevelFilterClassName)}>
It would be really nice to add a modifier here based on the label. So we could easily find the `.FilterField--admission-type` (for example) when searching the DOM.

2020-10-06 18:46 UTC, Wmaileq commented on src/components/charts/new_revocations/Chip.scss
> +    .Chip_selected & {
I used __ as an element separator and _ as modifier separator
If -- for modifier is more familiar then i will change it :)

2020-10-06 18:51 UTC, Wmaileq commented on src/components/charts/new_revocations/RevocationMatrix/RevocationMatrixCell.js
> +    <div className="RevocationMatrixCell cell">
I think it should be RevocationMatrixCell as independent block with all internal styles and in the same time RevocationMatrix__cell as an element of RevocationMatrix. 
But... if this element should be used only inside of RevocationMatrix component, maybe there is no sense to create RevocationMatrixCell block and it should be just element of RevocationMatrix.

2020-10-06 21:08 UTC, jovergaag commented on src/components/charts/new_revocations/ToggleBar/FilterField.js
> +        `FilterField--${toHtmlFriendly(label).toLowerCase()}`,
👍

2020-10-06 21:14 UTC, jovergaag commented on src/utils/transforms/labels.js
> +  return string.replace(/\W+/g, '-');
👍

2020-10-06 21:16 UTC, jovergaag approved these changes
👍

2020-10-08 15:54 UTC, Wmaileq commented
@jovergaag @jessex Please merge this one if it looks good.

2020-10-13 19:14 UTC, jovergaag requested changes
One small update that I missed in my first review.

2020-10-13 19:14 UTC, jovergaag commented on src/components/charts/new_revocations/Chip.js
> +    className={cx("Chip", {
I just noticed this last remaining issue. This should be `Chip--selected` and `Chip--shrinking`. Also, there is a border/outline that is appearing on the click mouse down that should not be there..

2020-10-14 13:34 UTC, Wmaileq commented on src/components/charts/new_revocations/Chip.js
> +    className={cx("Chip", {
Thanks for point it out, missed it.
Focus outline deleted

2020-10-14 21:48 UTC, jovergaag approved these changes
🎉

2020-10-14 21:48 UTC, merged