WIP: Select\Multiselect\Filter fields refactor
Recidiviz/pulse-dashboard pull request #518
Opened 2020-10-06 18:36 UTC by Wmaileq

## Description of the change

- Select separated into MultiSelect and Select
- Filters that use Select refactored and generalized
- Filter types (reportedViolations, violationType, etc.) picked out into constants. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #503 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-07 23:56 UTC, jovergaag commented
@Wmaileq I am partially through reviewing this, I'll pick it up in the morning when I have a fresh brain.

2020-10-08 23:57 UTC, jovergaag requested changes
Great work @Wmaileq! Overall I think it looks great. It feels much more clean to me broken out into multiple components. I also really like the move toward constants and React hooks for optimization.

Just a few things in there to look at. 

Another thing that I noticed. The `MultiSelect` functionality seems to have regressed in IE11. It now no longer has the multi select function, and closes the drop down after a single select. 

Thanks!

2020-10-08 23:57 UTC, jovergaag commented on src/components/charts/new_revocations/ToggleBar/AdmissionTypeFilter.js
> +  const onValueChange = useCallback(
Great idea moving toward optimizing! I only looked into this briefly but it looks like the memoization of the child is still being broken. You may need to use React.memo on those children if we really want to take advantage of these memo hooks.

2020-10-08 23:57 UTC, jovergaag commented on src/components/charts/new_revocations/ToggleBar/AdmissionTypeFilter.js
> +  const onValueChange = useCallback(
Actually maybe removing `onChange` from the deps would fix it? Not sure, something to look into.

2020-10-08 23:57 UTC, jovergaag commented on src/components/toggles/ToggleBar.js
> +import React, { useCallback, useMemo } from "react";
It doesn't need to happen in this PR but let's make a mental note to somehow get rid of this component and merge it with the other `ToggleBar`. It's super confusing to have both of these, especially for someone new to the repo!

2020-10-08 23:57 UTC, jovergaag commented on src/components/controls/utils.js
> +export const flatOptions = (options) =>
Beautiful

2020-10-08 23:57 UTC, jovergaag commented on src/components/charts/new_revocations/ToggleBar/DistrictFilter.js
> +    if (district) {
Have you tested this user context branch to verify it is working as expected? We removed the region condition below so just want to make sure you checked that.

2020-10-09 12:21 UTC, Wmaileq commented on src/components/charts/new_revocations/ToggleBar/DistrictFilter.js
> +    if (district) {
Just checked it, all works as expected.

2020-10-09 12:49 UTC, Wmaileq commented on src/components/charts/new_revocations/ToggleBar/AdmissionTypeFilter.js
> +  const onValueChange = useCallback(
As perfomance optimizations is not target of this PR i've reverted it and, maybe, will come back later.

2020-10-09 12:54 UTC, Wmaileq commented on src/components/charts/new_revocations/ToggleBar/ToggleBarFilter.js
> +const ToggleBarFilter = ({
As long as i remember this was done in another PR: https://github.com/Recidiviz/pulse-dashboard/pull/512/files#diff-4246339bd834789c3b3212cee11462ceL33

2020-10-09 20:00 UTC, jovergaag requested changes
Couple more little styling fixes.

2020-10-12 15:38 UTC, Wmaileq commented on src/components/charts/new_revocations/ToggleBar/AdmissionTypeFilter.js
> +  const onValueChange = (selected) => onChange(map("value", selected));
No issues, this hooks work as expected but do bring a little benefit while corresponding components and linked vars and callbacks are not wrapped with memo's, useCallback's and useMemo's
I think we can do this optimization in another PR and test if perfomance becomes faster or not.

2020-10-12 15:39 UTC, Wmaileq commented on src/components/controls/MultiSelect/MultiSelect.scss
> +  &__value-container {
> IE11 still seems to be broken for the Lantern dashboards. ND looks ok.

Yes, did not have windows PC at hand, testing IE11 right now :)

2020-10-12 16:05 UTC, Wmaileq commented on src/components/controls/MultiSelect/MultiSelect.scss
> +  &__value-container {
Fixed IE11 bug(option selecting does not close select) and fixed width of all filter fields (now distributing evenly)

2020-10-13 20:09 UTC, jovergaag requested changes

2020-10-13 20:09 UTC, jovergaag commented on src/components/charts/new_revocations/ToggleBar/FilterField.scss
> +  flex-basis: 100%;
The product team has been through a round of QA and has a suggestion on how to make the district filter look nice on tablet. I will put this in another issue so we can get this PR merged, just letting you know that it is coming.

2020-10-13 20:09 UTC, jovergaag commented on src/components/controls/MultiSelect/MultiSelect.js
> -      setTimeout(() => {
Regardless of whether the above helps or not (I did not try it on your branch), we need to make sure the input gets focused after each selection, and that the dropdown does not close after each selection until the user closes it.

2020-10-16 14:45 UTC, Wmaileq commented on src/components/controls/MultiSelect/MultiSelect.js
> -      setTimeout(() => {
I've reverted this and tested in IE11 emulator, safari and chrome and multiselect works as expected.

2020-10-16 14:46 UTC, Wmaileq commented
As #541 and this intersect each other, we should wait till #541 would be merged, then merge master here and then we can close PR

2020-10-16 22:37 UTC, jovergaag approved these changes
Looks great! Thank you.

2020-10-16 22:38 UTC, merged