WIP: filter types separated from containers
Recidiviz/pulse-dashboard pull request #529
Opened 2020-10-08 12:20 UTC by Wmaileq

## Description of the change
**PR conflicts with #518 , so should be reviewed\merged after this one**
 
- Filter options constants moved from Revocations containers to view/tenants/constants
It looks like Revocations container in us_mo and us_pa are almost identical, so they should be generalized.
view/tenants/constants _maybe_ should be moved just to src/constants

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #505 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-08 15:39 UTC, Wmaileq commented
I believe this should be enough for single PR, will continue working with src/components in another branch.

2020-10-13 20:48 UTC, jovergaag requested changes
This is great. The tenant Revocation pages are so much nicer now, thank you!

One small regression on the ND page that I could see.

Does this close the issue or was there more that you wanted to do? You had commented that this is enough in this PR, did you want to open another PR or close the issue and open another issue for individual organizational things we find?

2020-10-13 20:48 UTC, jovergaag commented on src/utils/charts/axis.js
> -function axisCallbackForMetricType(isRateMode) {
🎉

2020-10-13 20:48 UTC, jovergaag commented on src/utils/charts/choropleth.js
> -function countyNameFromCode(stateCode, countyCode) {
🎉

2020-10-13 20:48 UTC, jovergaag commented on src/utils/charts/toggles.js
> +  return {
Nice.

2020-10-13 20:48 UTC, jovergaag commented on src/utils/charts/toggles.js
> +  if (metricType === "rates") {
There seems to be a regression on the ND page, under Facilities > Explore if you click on the "Rates" filter. The first chart gets cut off at the top. Is it because of removing this `stepSize`?

2020-10-13 20:48 UTC, jovergaag commented on src/utils/transforms/__tests__/datasets.test.js
> -  it('filter facilities', () => {
I don't know the repo well enough (especially the ND page) to know this filter...is this filter no longer available?

2020-10-13 20:48 UTC, jovergaag commented on src/utils/transforms/__tests__/months.test.js
> +    "4",
Is this because of a new eslint config? This is taking up a ton of vertical space in this file and others. I would prefer we leave it on one line if possible.

2020-10-13 20:48 UTC, jovergaag commented on src/utils/transforms/datasets.js
> -function filterFacilities(dataPoints, facilityType, stateCode) {
Oh I see, `filterFacilities` is no longer used. Great!

2020-10-13 20:48 UTC, jovergaag commented on src/views/tenants/us_mo/community/Revocations.js
> +  console.log(filters);
stray console log here.

2020-10-13 20:48 UTC, jovergaag commented on src/views/tenants/us_mo/community/Revocations.js
> -const admissionTypeOptions = [
Wow, this whole file is so much more clean. Great work.

2020-10-13 20:48 UTC, jovergaag commented on src/views/tenants/us_mo/community/Revocations.js
> +      ? { admissionType: filterOptions.admissionType.defaultValue }
YAY. Those array indexes as defaults have been bugging me.

2020-10-13 20:49 UTC, jovergaag commented on src/utils/transforms/__tests__/months.test.js
> +    "4",
Now that I've been through all the files, I think we should definitely consider leaving this type of array on one line. Its a lot of new vertical space that was added which I find more difficult to read.

2020-10-14 13:51 UTC, Wmaileq commented on src/utils/transforms/__tests__/datasets.test.js
> -  it('filter facilities', () => {
Yes, all unused functions were deleted

2020-10-14 14:17 UTC, Wmaileq commented on src/utils/transforms/__tests__/months.test.js
> +    "4",
Now it works like this because of printWidth set to 80 in .prettierrc.json
Related issue: https://github.com/prettier/prettier/issues/4210
So the only thing we can do now is to place prettier-ignore for every case.

2020-10-14 14:26 UTC, Wmaileq commented on src/utils/transforms/__tests__/months.test.js
> +    "4",
I placed prettier-ignores into `months.test.js`
If the format is ok i will look through other files and format in such way.

2020-10-14 15:07 UTC, Wmaileq commented on src/utils/charts/toggles.js
> +  if (metricType === "rates") {
Fixed by reverting `toggleYAxisTicksFor`, but its strange

2020-10-14 15:07 UTC, Wmaileq commented on src/utils/charts/toggles.js
> +  if (metricType === "rates") {
Need to look deeper and figure it out

2020-10-14 16:50 UTC, Wmaileq commented
> Does this close the issue or was there more that you wanted to do? You had commented that this is enough in this PR, did you want to open another PR or close the issue and open another issue for individual organizational things we find?

I think we can open 2 issues: 
1. Generalize `Revocations.js` MO and PA component
2. Organize `utils`\`constants` in `components` folder

2020-10-14 22:38 UTC, jovergaag requested changes
One small change then you're good to go.

2020-10-14 22:38 UTC, jovergaag commented on src/utils/charts/toggles.js
> +  return {
Looks better now, thanks

2020-10-14 22:38 UTC, jovergaag commented on src/utils/transforms/__tests__/months.test.js
> +    "4", "5", "6", "7", "8", "9", "10", "11", "12", "1", "2", "3"
This looks much nicer and will be much easier to scroll through the files. But I'm just thinking about how difficult it will be to maintain this. Adding the ignore statement then formatting the array manually any time we need to change it will become burdensome. I think we better stick with the standard prettier formatting.

Sorry to ask you to do this but lets revert back to your original array one item per line format.

2020-10-19 21:58 UTC, jovergaag approved these changes
Well done. Things are starting to feel a bit more organized! Thank you.

2020-10-19 21:58 UTC, merged