added pre commit testing
Recidiviz/pulse-dashboard pull request #530
Opened 2020-10-08 12:23 UTC by Wmaileq

## Description of the change

- Added pre commit testing

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

No related issues

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-09 20:40 UTC, jovergaag requested changes
Comments in line.

2020-10-09 20:40 UTC, jovergaag commented on package.json
> +      "pre-commit": "lint-staged && yarn test"
I'm a little hesitant to add this hook. For two reasons:

1. As our test coverage continues to grow for the repo the test suite will take longer to run which means longer to commit.
2. I often will break a large task up into smaller chunks and commit throughout, even if the tests aren't passing yet. This wouldn't allow me to do this.

I would love to hear your thoughts on this and why you want to add it. Maybe I can be convinced!

2020-10-10 00:30 UTC, Wmaileq commented on package.json
> +      "pre-commit": "lint-staged && yarn test"
For the first case I see the solution in running tests only for changed files, is this reasonable?

For the second case: I think any committed code should never fail tests
Actually is this the case?
When you add new code it could be not covered with tests but in this case pre-commit hook will not fail and you can add tests in next commit.
But I can't imagine situation when you need to commit code that FAILS tests, I think test fixes should be included.

2020-10-13 19:21 UTC, jovergaag commented on package.json
> +      "pre-commit": "lint-staged && yarn test"
What if you changed this to a pre-push hook instead of pre-commit?

If I'm working on a larger chunk of work, I will often make many smaller commits so that I can revert that chunk if it ends up not being applicable. Often times the commits will not be passing tests, or, if doing TDD and I have written one or more tests for a feature that is not finished yet the test(s) will not be passing until the end.

I think a pre-commit hook isn't flexible to support different people's personal workflow styles.

But I would be open to the pre-push test hook!

2020-10-14 21:50 UTC, jovergaag requested changes
See my note on previous comments.

2020-10-15 09:29 UTC, Wmaileq commented on package.json
> +      "pre-commit": "lint-staged && yarn test"
@jovergaag This sounds logical! I think we have come to a common opinion.

2020-10-15 23:26 UTC, jovergaag requested changes

2020-10-15 23:26 UTC, jovergaag commented on package.json
> +      "pre-push": "yarn test --only-changed"
I changed a test to ensure that it failed, committed it, then pushed it up to this branch. The push was successful. I removed the `--only-changed` flag and did the same thing and it triggered the tests, which failed, and push failed. I think we should remove the `-only-changed` flag here. 

I think the 'changed' files are ones which are staged, so after a commit there is no longer anything staged.

2020-10-16 10:29 UTC, Wmaileq commented on package.json
> +      "pre-push": "yarn test --only-changed"
My fault, fixed

2020-10-16 17:19 UTC, jovergaag approved these changes
👍

2020-10-16 18:04 UTC, merged