Tech debt/gender race charts
Recidiviz/pulse-dashboard pull request #538
Opened 2020-10-14 13:26 UTC by Wmaileq

## Description of the change

- Common parts picked out of RevocationsByGender, RevocationsByRace, RevocationsByRiskLevel, RevocationsByViolation components.

While refactoring this code noticed:
1. RevocationsByDistrict/PercentRevokedByExits.js and RevocationsByDistrict/PercentRevokedByPopulation.js are almost identical and could be generalized.
1. New RevocationsByFeature component could be used at RevocationsOverTime and all RevocationsByDistrict charts.
1. ExportMenu component should not accept chart node, it should accept only datasets and labels fields.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #506 

New issues need to be opened if we want to continue refactor.

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-14 23:09 UTC, jovergaag requested changes
This looks great! I think we can go even a step further...

There is still lots of nearly identical code in` RevocationsByRace` and `RevocationsByGender` and their associated helpers. Can we just render `RevocationByDimension` directly in the tenant `Revocations` top level page component and pass in the appropriate title/filter/api bucket name etc?

Eventually, we should be moving the architecture of this repo to a place where data is fetched and manipulated somewhere that is NOT the component, and the components are super simple. Simply displaying the props that they are passed. So by pulling a lot of this label manipulation out of the component we are slowly headed in that direction.

Does that make sense? Let me know if you have questions. Give that a shot and let me know if it turns out to be really ugly and we can figure out a different way forward.

2020-10-14 23:11 UTC, jovergaag commented
@Wmaileq Go ahead and do the work for your great idea #2 above in this PR. I think it makes sense to move all the dimension charts to use this new `RevosationsByDimension` component as long as it makes sense!

2020-10-16 10:46 UTC, Wmaileq commented
> This looks great! I think we can go even a step further...
> 
> There is still lots of nearly identical code in` RevocationsByRace` and `RevocationsByGender` and their associated helpers. Can we just render `RevocationByDimension` directly in the tenant `Revocations` top level page component and pass in the appropriate title/filter/api bucket name etc?
> 
> Eventually, we should be moving the architecture of this repo to a place where data is fetched and manipulated somewhere that is NOT the component, and the components are super simple. Simply displaying the props that they are passed. So by pulling a lot of this label manipulation out of the component we are slowly headed in that direction.
> 
> Does that make sense? Let me know if you have questions. Give that a shot and let me know if it turns out to be really ugly and we can figure out a different way forward.

I think that we should divide components on dumb components that are just render UI and container components that do all the business logic.
For example: `RevocationByDimension` is the dumb component but `RevocationsByRace` and `RevocationsByGender` are smart components.
In my opinion we can create `RevocationByDimensionContainer` smart component and render it straight to Revocations page.
That RevocationByDimensionContainer should receive url and all the utils needed to transform data to target format and return RevocationByDimension dumb component that will render UI.

I will give it a try and will reply here.

2020-10-16 10:49 UTC, Wmaileq commented on src/components/charts/new_revocations/RevocationsByFeature.js
> +import React from "react";
@jovergaag Thank you!

2020-10-20 13:35 UTC, Wmaileq commented
I will end with RevocationsByDistrict refactor tomorrow and right after that we can review and merge this!

2020-10-21 23:34 UTC, jovergaag commented
@Wmaileq I'm still making my way through this review. Theres a ton of good work in here! Lots of changes so it's taking a while to review. I'll continue tomorrow.

2020-10-27 01:24 UTC, jovergaag commented
@Wmaileq I apologize for taking so long to review this. It's a big PR and merging in master is not going to be fun after the other big PRs that are going to land, sorry.

I am going to try to merge two PRs this evening ( #562 and #579) that will make it into the production deploy tomorrow. Then I will merge #558. At that point, I'll ask you to merge master into this branch and do a round of QA yourself before I restart my review. Does that sound fair?

We just have so much code churning right now, it makes me really nervous before our PA launch so I'm tapping the brakes on this and #558 for now.

2020-10-27 12:28 UTC, Wmaileq commented
@jovergaag no worries, I understand that a lot of changes here.
So, I think, we wait until #558 merged and then proceed.

2020-10-28 09:02 UTC, Wmaileq commented on src/components/charts/new_revocations/RevocationsByGender/createGenerateChartData.js
> +const GENDER_LABELS_MAP = { FEMALE: "Women", MALE: "Men" };
It looks like it could be moved to translations, just because it is very similar to raceLabelMap and riskLevelsMap.
@jovergaag Do you agree?

2020-10-28 23:34 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsByGender/createGenerateChartData.js
> +const GENDER_LABELS_MAP = { FEMALE: "Women", MALE: "Men" };
Well these labels are the same no matter which tenant is active. The translations are meant to translate between terminology used by different tenants. So MO uses 'Gender' and PA uses 'Sex' but both use the terms 'Female' and 'Male'.

2020-10-29 00:44 UTC, jovergaag reviewed
@Wmaileq  I am half way through this review, it looks so good. I think this is much cleaner and easier to work with than the previous components. Great job. 

I'll continue reviewing tomorrow. In the meantime just wanted to give you these two comments.

2020-10-29 00:44 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsByDimension/RevocationsByDimensionComponent.js
> +        [`RevocationsByDimension__chart-wrapper--${classModifier}`]: classModifier,
I don't see this classModifier being passed in from any of the charts. It would be nice to add it.

2020-10-29 09:29 UTC, Wmaileq commented on src/components/Revocations.js
> +            dataFilter={applyAllFilters(transformedFilters, undefined, true)}
Yes, I agree with you. Also `undefined` looks annoying here.

2020-10-29 09:55 UTC, Wmaileq commented on src/components/charts/new_revocations/RevocationsByDimension/RevocationsByDimensionComponent.js
> +        [`RevocationsByDimension__chart-wrapper--${classModifier}`]: classModifier,
@jovergaag started to use `chartId` as modifier

2020-10-30 18:16 UTC, jovergaag approved these changes
@Wmaileq This is awesome. So much cleaner and less duplicate code to maintain. Well done!

Thanks for your patience while it took me so long to get this reviews during our PA launch this week!

2020-10-30 19:18 UTC, merged