Fix/ file linting
Recidiviz/pulse-dashboard pull request #558
Opened 2020-10-21 15:46 UTC by Wmaileq

## Description of the change

- eslint whitelist replaced with the blacklist where remaining not linted files are kept.
- unused src/assets/scripts/metrics folder deleted.
- unused src/assets/scripts/metrics/programReportCards.js deleted

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Part of #505 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-22 20:13 UTC, jovergaag requested changes
Just a couple of comments. Only remaining thing is possibly removing the rest of the ignored files in `.eslingignore`.

2020-10-23 11:36 UTC, Wmaileq commented on server/core/demo_data/expand_optimized_fixture.js
> +  const totalDataPoints = parseInt(metadata.total_data_points, 10);
Eslint threw error here. I think it is better to just off the eslints "radix" rule.

2020-10-23 14:06 UTC, Wmaileq commented on .eslintignore
> +src/serviceWorker.js
Fixed this, only 2 lines left:
`src/auth0/**/*.js` - because this files are not used in project.
`src/components/charts/GeoViewTimeChart.js` - because of #544

2020-10-23 14:07 UTC, Wmaileq commented on src/App.test.js
>  // TODO: Currently fails because it's not picking up all dependencies,
Ok, i will do it in a separate PR

2020-10-27 00:17 UTC, jovergaag commented on src/components/charts/community/test_utils/snapshotTesting.js
> -// Recidiviz - a data platform for criminal justice reform
I see that this test isn't being run currently. Is there a reason for it not running or is it just an oversight and we need to refactor it so that it will run? I don't know the ND dashboard very well so its unclear to me if this stuff is still relevant or not. There so much good work here (and in all the associated `test_data`), I would hate to remove it unless it really is no longer used.

@jessex

2020-10-27 00:20 UTC, jovergaag reviewed
@Wmaileq Apologies for not getting to this review sooner. We had some high priority things come up at the end of last week and I didn't have enough time/energy to get to reviewing the open PRs. I want to get Joshua's opinion about removing the snapshot testing. @jessex

2020-10-27 00:58 UTC, jessex commented
When we first started working with Inobright, one of their earlier contractors had suggested we try snapshot testing early on so that we could, for example, check that a page looked as expected in all filter states (so, create snapshots for all possible filter states, render in each state, then compare against the snapshot in each state). I don't have a strong opinion as to whether that's _necessary_ or _overkill_ but I do know that that testing has lapsed and I don't think it's actually being run as part of the build at this moment. Given that, I would think that if we wanted to bring it back we should file a ticket and make a concerted effort to explore snapshot testing as a first class part of the build, and I would not be opposed to removing it in the interim.

2020-10-27 01:14 UTC, jovergaag commented
@jessex Thanks for the context. I agree to go ahead and remove it. 

I'm going to wait to approve this until after #579 and #562 are merged, then do another round of QA. There is a ton of code changed here so I just want to make sure we don't lose anything during the merge and create some bugs right before our launch tomorrow.

2020-10-27 12:19 UTC, Wmaileq commented
@jovergaag Merged and looked through all the files.
Since most changes are just stylistic changes this should not have any regressions.

2020-10-28 03:32 UTC, jovergaag approved these changes
NICE.

It always feels good to clean house. 🎉 
![Screen Shot 2020-10-27 at 8 31 34 PM](https://user-images.githubusercontent.com/5872651/97387557-7826cd00-1893-11eb-9a3e-425b31ade315.png)


Thank you @Wmaileq 

I'll merge this when the build finishes.

2020-10-28 05:29 UTC, merged