lantern revocations page generalized
Recidiviz/pulse-dashboard pull request #562
Opened 2020-10-22 14:07 UTC by Wmaileq

## Description of the change

- Generalized MO and PA Revocations pages because they were almost identical.
- Generalized MO and PA Layout pages because they were identical.
- Moved components from view folder to components folder.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Part of #505 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-22 22:04 UTC, jovergaag requested changes
This is awesome. Great refactor.

Just a couple comments on how we can go one step further.

2020-10-22 22:04 UTC, jovergaag commented on src/views/tenants/us_mo/community/Revocations.js
> +    violationTypes={[
Actually, if you do that, there is no need for this `UsMoCommunityRevocations` at all. We can just render the `Revocations` component directly from `App.js`. That leaves only tenant copy/constants inside the tenants directory which is super clean. Ultimately what I think we should do is create a context to load all of these tenant specific constants into so they can be accessed directly from the component that needs them. This is setting us up so that the tenant directory is all related to the context.

At least that is the case for lantern tenants, we can move core in that direction eventually. Thoughts?

2020-10-22 22:04 UTC, jovergaag commented on src/views/tenants/us_mo/community/Revocations.js
> +    violationTypes={[
Same for PA obviously.

2020-10-22 22:04 UTC, jovergaag commented on src/views/tenants/us_mo/community/Revocations.js
> +    violationTypes={[
If this is the case, we can just set the i18n locale in the layout where it is now.

2020-10-23 14:22 UTC, Wmaileq commented on src/components/layouts/LanternLayout.js
> +  setTranslateLocale(stateCode);
Yeah, i thought of it too, maybe it is better to place it to the `StateCodeProvider`?

2020-10-23 15:32 UTC, Wmaileq commented on src/views/tenants/constants/filterOptions.js
> +  [SUPERVISION_TYPE]: { enabled: false, defaultValue: "All" },
Removed `skippedFilters` condition from Revocations page, but this flag not for filter but for component -  there is no `Supervision level filter` component on `MO` page, and no `Supervision Type filter` component on `PA` page. Renamed flag to be more descriptive.

2020-10-23 15:33 UTC, Wmaileq commented on src/views/tenants/us_mo/community/Revocations.js
> +    violationTypes={[
Moved and deleted!
Now there is the only one difference between MO and PA code on this line: https://github.com/Recidiviz/pulse-dashboard/pull/562/files#diff-eeeb2e0f3ad07c19e4bbf8bf7fb7c811c15a12198ec041c896d0647fcc9f0cd1R226

2020-10-23 15:43 UTC, Wmaileq commented on src/views/tenants/us_mo/community/Revocations.js
> +    violationTypes={[
About core layout: I quickly compared code on the Explore and Goals pages and it looks like they are almost completely different.

2020-10-27 00:50 UTC, jovergaag requested changes
I have noticed an error `Unable to set property 'locale' of undefined or null reference` when I am at the login page. Other than that everything looks good.

2020-10-27 00:50 UTC, jovergaag commented on src/contexts/StateCodeContext.js
> +    setTranslateLocale(currentStateCode);
Great idea.

2020-10-27 00:55 UTC, jessex commented
@jovergaag if that error only shows up when you're on the login page, then I don't think @Wmaileq will be able to super effectively debug it since he doesn't have access to that page. Might be possible, though!

2020-10-27 00:57 UTC, jovergaag commented
@jessex I realized that right after I commented. Just pushed up a fix.

2020-10-27 01:07 UTC, jovergaag approved these changes
Awesome, this looks great!

2020-10-27 04:11 UTC, merged