App tests
Recidiviz/pulse-dashboard pull request #575
Opened 2020-10-26 12:58 UTC by Wmaileq

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Part of #25 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-27 01:54 UTC, jovergaag requested changes
Just a couple of non-happy-path tests that we should look into.

Thanks!

2020-10-27 01:54 UTC, jovergaag commented on src/App.test.js
> +      isAuthenticated: true,
Can you add a test case for when `isAuthenticated` is false and when `loading` is true. We just want to be sure that nothing is rendered before the user is authenticated. We could also probably want a test to ensure that the user is redirected to the login page.

If this is too difficult to write tests for in demo mode, let me know and I can take over those last couple.

2020-10-27 11:31 UTC, Wmaileq commented on src/App.test.js
> +      isAuthenticated: true,
Tests added!
Thinking about what we need here (integrational or unit tests) came to the idea that unit tests here would just cover internal react-router logic, what we don't really need.
So I've covered `App` in a bundle with the `TenantRoutes` and the `StateCodeProvider` components that resulted in having almost 100% coverage on the `TenantRoutes`.
Despite this, I think we need to do unit tests for `TenantRoutes` and `StateCodeProvider` anyways.

2020-10-28 16:20 UTC, jovergaag requested changes
Just getting clarification on `TenantRoutes` test.

2020-10-28 16:26 UTC, Wmaileq commented on src/components/TenantRoutes.js
> +  return Children.toArray(children).reduce((node, child) => {
@jovergaag 
![image](https://user-images.githubusercontent.com/26236198/97465706-60168280-1953-11eb-9727-8a1ed720ed0c.png)
TenantRoutes completely covered by this PR :)

2020-10-28 22:45 UTC, jovergaag approved these changes
Thank you!!

2020-10-28 22:45 UTC, jovergaag commented on src/components/TenantRoutes.js
> +  return Children.toArray(children).reduce((node, child) => {
Oh! I haven't actually logged into Coveralls, or worked with it before. I'm a little surprised that `TenantRoutes` is considered covered. 

Let's go ahead and merge this and you can continue adding tests for the uncovered files, then we can go back and add unit tests for `TenantRoutes` later. We will be continuing to refactor some of the other components so it feels more important to have them covered as we refactor. 

Eventually I would like to change the routes to add `:state_code` to the route and maybe even the filter state - at that point the `TenantRoute` tests will be more important but that is much further down the road. I actually don't think `TenantRoutes` is a great implementation and would like to find a different solution overall...

2020-10-28 22:45 UTC, jovergaag commented on __helpers__/mockWithTestId.js
> +import React from "react";
Great idea.

2020-10-28 22:55 UTC, merged