UI Fixes from final QA round
Recidiviz/pulse-dashboard pull request #579
Opened 2020-10-26 23:31 UTC by jovergaag

## Description of the change
Serena found a few remaining issues during her final (maybe?) round, along with additional methodology updates from CSG. 
1. Methodology updates
2. Update Race labels for PA: "African American" -> "Black", "Caucasian" -> "White"
3. Remove "Pacific Islander" from the Race charts for both MO and PA since that data is not being collected
4. Pluralize the "Violation Filter" bubble labels.
5. Fix styling on violation filter bubbles when scrolled all the way to the top - bubble should not be full width
6. Fix animation on scroll when filter bars change to `topBarIsShrinking` mode
7. Fix typo in verify page

Details can be found in the issue #574

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #574

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-26 23:37 UTC, jovergaag commented on src/hooks/usePageLayout.js
> +const usePageLayout = () => {
We were previously keeping a boolean here, `isTopBarShrinking`, but the animation when scrolling down the page when the `ViolationFilter` bar was active was funky because the timing of the different filter renders and updates to this boolean sourced from many different components. So I moved this to a context such that there is one event that changes the boolean and all components can then access that single value.

2020-10-27 01:16 UTC, jessex requested changes
Great work, @jovergaag! Just some potential copy issues in the PA methodology text from the first commit. Also, in local testing, it _looks to me_ like we no longer have a smooth transition from wide to thin on the scroll down the page. _Last I checked_, that thinning was a gradual animation, but now it just instantly clicks back and forth. However, I just checked production and it looks like that's how it's currently behaving in prod, too, so I don't know when that functionality regressed, or if it was removed intentionally. Do you have any insight into that? If not, we should probably file a ticket for it.

2020-10-27 01:16 UTC, jessex commented on src/views/tenants/utils/us_pa_methodology.js
> +      body: `Counts include all people who were admitted to SCIs from parole. This includes people on parole who were admitted for non-revocation sanctions and those who were admitted for revocation.
I think this is a mistake? Looking at the methodology doc listed in #574, it doesn't include this "Counts include all..." line for the "Filtering by violation history" section. It only exists under the "Who is included" section.

2020-10-27 01:16 UTC, jessex commented on src/views/tenants/utils/us_pa_methodology.js
> +Filtering by violation history: If the user has filtered the page by clicking on a specific violation type (i.e., low technical) or bubble (i.e., low technical and three violation reports) within the
Similarly, this addition of the "Filtering by violation history" prefix shouldn't be here. That's just the header, which is already up on L99.

2020-10-27 01:25 UTC, jovergaag commented on src/views/tenants/utils/us_pa_methodology.js
> +      body: `Counts include all people who were admitted to SCIs from parole. This includes people on parole who were admitted for non-revocation sanctions and those who were admitted for revocation.
Thanks. I've done these copy updates too many times, starting to move too quickly, le sigh.

2020-10-27 01:38 UTC, jovergaag commented
@jessex I don't remember the smooth transition, if there was a regression I am not quite sure when it would have happened. I'll make an issue to add it back in and ask @sychang for input on requirements.

2020-10-27 01:44 UTC, jessex approved these changes
Thanks, @jovergaag! 👏

2020-10-27 02:21 UTC, sychang commented
Thank you for all of this! +10000 on so many rounds methodology changes and major shoutout for helping iterate on it so quickly.

Not super helpful but I also noticed the transition / thinning on the additional filters bar looked a bit different than I remember it but I also couldn't pin exactly how and when it changed. Happy to discuss later, definitely not launch-blocking or high-pri here.

2020-10-27 02:57 UTC, merged

2020-10-27 02:57 UTC, jovergaag commented
@sychang It's all part of the process!

Lets sync up tomorrow on the additional filters transition.

2020-10-27 13:38 UTC, sychang commented
Chatting offline with Jen, but for posterity, here's a screencapture of the filter bar transition in demo mode, which is indeed a bit different for both the top filter bar and the additional filters: https://drive.google.com/file/d/1REE81PaTOE7Ecn9cFtYI7E32A_x_gZzi/view?usp=sharing