Tests/ Layouts and Intercom
Recidiviz/pulse-dashboard pull request #583
Opened 2020-10-28 10:54 UTC by Wmaileq

## Description of the change
**Should be rebased to master's head after #575 merge**

- Intercom slightly refactored from common function to hook and now should be used only on pages where it should be visible, instead of toggling on every page.
- Layout tests added
- Intercom utils\hook tests added

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-10-28 11:01 UTC, Wmaileq commented on src/utils/initIntercomSettings.js
> -  window.Intercom("boot", window.IntercomSettings);
@jovergaag Was it working? 
As I have no access I can't check, but here we set settings to `window.intercomSettings` and then boot Intercom with `window.IntercomSettings` which should be `undefined`.
Is it an error or have I missed something?

2020-10-28 23:00 UTC, jovergaag commented on src/utils/initIntercomSettings.js
> -  window.Intercom("boot", window.IntercomSettings);
When I add `  console.log(window.intercomSettings)` to line 26 I see an object with an app_id. This seems to be working as expected.

2020-10-28 23:32 UTC, jovergaag requested changes
One small change to disable Intercom on ND

2020-10-28 23:32 UTC, jovergaag commented on package.json
> +      "@testing-library/react-hooks/dont-cleanup-after-each.js"
I'm curious why you added this. Did you have tests failing? Or just for performance?

2020-10-28 23:32 UTC, jovergaag commented on src/components/layouts/__tests__/CoreLayout.test.js
> +    expect(getByText("Some > Nested > Pathname")).toBeInTheDocument();
👍

2020-10-28 23:32 UTC, jovergaag commented on src/utils/initIntercomSettings.js
> -  window.Intercom("boot", window.IntercomSettings);
I realized I didn't answer your question - yes it is working.

2020-10-28 23:32 UTC, jovergaag commented on src/utils/initIntercomSettings.js
> -export function disableIntercomLauncher() {
We need to be able to disable the Intercom launcher for the ND page. Intercom should only be available on the LanternLayout, not on the CoreLayout. Since it is initialized in `App.js`, the launcher is enabled but it just hasn't been updated with the user settings in `useIntercom` when on the ND page. I think the best thing to do is set `hide_default_launcher: true` on line 22.5 here to disable it by default. I tested that locally and it worked when switching back and forth between tenants.

The Intercom launcher is an `<iframe>` so it is going to be hard to write a test for it not having it in your browser DOM for reference.  I will in the meantime figure out if we can send you the app_id for Intercom so you can see what is happening.

2020-10-29 08:33 UTC, Wmaileq commented on src/utils/initIntercomSettings.js
> -  window.Intercom("boot", window.IntercomSettings);
@jovergaag yeah, `console.log(window.intercomSettings)` working now :) 
But I am curious about `master`, is intercom working on master now? It seems to be an error here, which I was trying to point out. 

In master we assign `appId` to `window.intercomSettings`, and then read them with `window.Intercom("boot", window.IntercomSettings`). (Upper and lower cased **I**)

2020-10-29 08:52 UTC, Wmaileq commented on package.json
> +      "@testing-library/react-hooks/dont-cleanup-after-each.js"
https://github.com/Recidiviz/pulse-dashboard/pull/583/files#diff-b31924d36fcfd13a11cf4636cec0a249ff3f5fa63221a1ebef9be6dfa3acca76R29

Hooks are unmounting every test (after every `it`), without this setup, what is not what we expect, in my opinion. 
In tests I want to take control of mounting, rerender, and unmounting of hooks to get conditions closer to the real.

2020-10-29 09:25 UTC, Wmaileq commented on src/utils/initIntercomSettings.js
> -export function disableIntercomLauncher() {
>  I think the best thing to do is set hide_default_launcher: true on line 22.5 here to disable it by default.

Yes! I think this is the best solution. Now it should work as expected, thanks for the hint!

2020-10-29 09:26 UTC, Wmaileq commented
Fixed the issue and rebased to the masters current head.

2020-10-30 19:29 UTC, jovergaag approved these changes
Awesome. Thank you!

2020-10-30 19:36 UTC, merged