Fix vertical alignment of filter chip - label and delete button
Recidiviz/pulse-dashboard pull request #601
Opened 2020-11-03 21:42 UTC by jovergaag

## Description of the change

The filter chips were vertically misaligned. This was the case in the 'Additional Filters' filter bar as well as the filter buttons in the revocations by district chart.

The chips after the fix:
![Screen Shot 2020-11-03 at 1 16 40 PM](https://user-images.githubusercontent.com/5872651/98042071-c548f880-1dd7-11eb-91be-507cb68711db.png)
![Screen Shot 2020-11-03 at 1 41 31 PM](https://user-images.githubusercontent.com/5872651/98043588-515c1f80-1dda-11eb-925f-8d5aef34c8e9.png)
![Screen Shot 2020-11-03 at 1 41 36 PM](https://user-images.githubusercontent.com/5872651/98043593-5325e300-1dda-11eb-860c-061f258714df.png)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #595

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-11-03 21:53 UTC, jovergaag commented
@sychang "am i ok"? :)

2020-11-03 22:49 UTC, sychang commented
You are so ok!

2020-11-03 23:28 UTC, macfarlandian requested changes

2020-11-03 23:28 UTC, macfarlandian commented on src/components/charts/new_revocations/ToggleBar/ViolationFilter.js
> +          className={cn({ "Chip--shrinking": isTopBarShrinking })}
what's the reasoning behind moving this logic out here? it kind of seems to me that it was better off encapsulated within the `Chip` component rather than the parent having to know it needs to apply this classname. Especially since `Chip` is still conditionally applying other classnames to itself based on props

2020-11-04 17:02 UTC, jovergaag commented on src/components/charts/new_revocations/ToggleBar/ViolationFilter.js
> +          className={cn({ "Chip--shrinking": isTopBarShrinking })}
There is only one Chip on the page (out of 15ish) that shrinks based on the scroll of the page. Prior to this PR the other chips were shrinking but that was a bug. 

Other options are to pass a boolean into Chip that specifies whether a particular instance is shrinkable. Or shrink the Chip when it is nested under `.FilterField--shrink`. I'm not a fan of the second option. I'll push up a commit to see what the first option looks like.

2020-11-04 17:14 UTC, jovergaag commented on src/components/charts/new_revocations/ToggleBar/ViolationFilter.js
> +          className={cn({ "Chip--shrinking": isTopBarShrinking })}
@macfarlandian That is much better, good suggestion. Ready for another look.

2020-11-04 17:30 UTC, macfarlandian approved these changes
🎸 🎶

2020-11-04 18:01 UTC, merged