Agent chart added #490
Recidiviz/pulse-dashboard pull request #603
Opened 2020-11-04 14:27 UTC by Wmaileq

## Description of the change
**Should be rebased after #602 will be merged**

- RevocationCharts BEM implemented
- Added some translations "revoked", "admissions"
- Added Agent Chart

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #490 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-11-04 21:16 UTC, jovergaag requested changes
This is looking great! When we were looking through this we were able to flesh out a few more requirements. I made comments below.

2020-11-04 21:16 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsByDistrict/RevocationsByDistrict.js
> +  const chartTitle = `${translate("Revocations")} by district`;
Can you do the same for the Gender, Race, and Risk Level charts please. Somehow we missed this translation in the refactor.

2020-11-04 21:16 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationCharts/RevocationCharts.js
> +      case "Agent":
The button for this chart in the labels menu should translate for the different tenants - Officer (MO)/Agent (PA)

2020-11-05 14:44 UTC, Wmaileq commented
@jovergaag fixed issues.
Also toggled treatCategoryAllAsAbsent to true.
Curious whether all other charts should be toggled in the same way or am I missing something?

2020-11-06 22:21 UTC, jovergaag requested changes
There are a few things to continue to look into.
* PA chart
* translations
* I'm going to look into the percent data to figure out why we're seeing strange results on the percent chart
* Export - this is something I didn't comment on below. We will want to export ALL of the data that matches the filter instead of truncating it to 50. Also, can you please make the data in the export rows instead of columns for officer names? That will make it much easier to read.

Re: `treatCategoryAllAsAbsent` - no we should not set that to true for this chart (yet). That means that there are no 'ALL' rows in the data coming from the API and so the data passes through the filters differently. For this view we do have the 'ALL' rows right now. However, this metric file is over 4 times larger than any of the other files and running this locally the performance impact is significant. I think we will have to trim down the metric file, and that might mean removing the ALL rows. But for now, do not include that boolean.

2020-11-06 22:21 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationCharts/RevocationCharts.js
> +                "RevocationCharts__button--selected": selectedChart === chart,
We are not seeing the chart in PA - in either live data or demo mode.

2020-11-06 22:21 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationCharts/RevocationCharts.js
> +    conditionallyHide(selectedChart, translate("Officer"), officerChart),
I don't think we need to translate this here - the copy translation is done on line 106. Maybe this is why the agent chart isn't rendering? Same goes for line 64. Sorry - I may have led you astray on this in my original review.

2020-11-06 22:21 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsByOfficer/RevocationsByOfficer.js
> +      chartId="revocationsByAgent"
This should be `revocationsByOfficer`

2020-11-06 22:21 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsByOfficer/createGenerateChartData.js
> +  const denominators = map("supervision_count", filteredData);
We are having a bug in the counts such that most of the officers are showing 100% - with a multiple of 8 in the denominator. The chart with demo data looks fine so this is almost certainly a backend bug. I'm going to look into the metric views and see if I can figure out what is going on, unfortunately that is lower priority than the IE11 performance issue so it might be a few days.

2020-11-11 16:02 UTC, Wmaileq commented
@jovergaag All done except 

> Also, can you please make the data in the export rows instead of columns for officer names? That will make it much easier to read.

I think maybe it is not the last chart where we should rotate, and the solution is the `ExportMenu` prop. It is not 5 minutes task so it would be easier to make an extra issue for this.

2020-11-12 22:50 UTC, jovergaag commented
@Wmaileq This is no longer rendering any data in the chart - even in demo mode. Maybe due to the merge master?

The data won't be ready to support this for another, so there is no rush to get this in. Considering that, I think it is worth adding the ability to `rotateData` within the `ExportMenu` component. If you want to do that in a separate PR to avoid this PR getting too big that is fine.

2020-11-13 15:28 UTC, Wmaileq commented
@jovergaag for me it is working, but you need to specify District. Because flag `treatCategoryAllAsAbsent` is disabled.

2020-11-16 23:02 UTC, jovergaag reviewed
This looks great for now. Let's put it on hold while we sort out the backend.

I chatted with the product manager and she agrees that it is best to pivot the axis of the data export for most of the charts. I'll create a new issue for this so we can get it merge and ready for when this is ready to go.

2020-11-16 23:02 UTC, jovergaag commented
@Wmaileq Sorry for taking so long to get back to you on this. I was on vacation on Friday.

I just pushed up a commit that lets us see data in the officer chart. We were filtering for `district != 'ALL'` in `createGenerateChartData`. Removing that fixed the issue on live data immediately, and I just updated the fixture file so you can see a better set of data on the default filters.

2020-12-03 22:16 UTC, jovergaag approved these changes
Great! This will be followed up by a few other tasks to address remaining issues.

2020-12-03 22:17 UTC, merged