Perfomance revocation matrix cells (#564)
Recidiviz/pulse-dashboard pull request #607
Opened 2020-11-06 12:03 UTC by Wmaileq

## Description of the change

- Added frontend caching

Caching of data added.
Cache lifetime set to 5 minutes. Could be changed. (We have 10 minutes cache on the backend)
Possible pitfalls: If user changes state twice charts could be not fresh because of cache, but, in my opinion, it is okay.
Refresing of the page resets cache.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #564 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-11-06 15:54 UTC, Wmaileq commented
Memory leak removed in this PR too. (useEffect cleanup )

2020-11-06 20:20 UTC, jovergaag requested changes
This is awesome, great implementation.

I like the idea of the cache to avoid redundant fetches, but I'm thinking we may want to store the data somewhere else and not in the `useChartData` hook.

I've been thinking a lot about how to improve performance of the filters - and also possibly reducing page load time. One thing I've considered is breaking the data up into 3 year data and 1 year or less data. The 3 year data is roughly 40% of the overall data we receive from the API. The 3 year filter view of the data is not used very often by our users - so it is wasteful to be running the 3 year data through the filters every time. I've been thinking about sectioning off the 3 year data and storing both the 3 year and 1 year or less data in a context and only adding it to the full dataset that is run through the filters when that specific filter is selected. 

Considering this, keeping the data in a central store will be useful and necessary - so I'm wondering if we want to write data to the store instead of caching it here - and simply caching the names of the files that exist in the store and return the data from the store to avoid the redundant fetch.

I would appreciate your input and thoughts here. I love this implementation for the short term, but in the long term I think we would end up doing this cache differently. Maybe we do this in two steps? This implementation then move the data to a context in the second step? Or shall we tackle it here? Let me know what you think.

2020-11-06 20:20 UTC, jovergaag commented on src/hooks/useChartData.js
> +    const cacheKey = `${url}-${file}`;
I ran some performance analysis on this. The loading time and memory usage on this branch of the initial load of the MO page on staging data are 50% and 20% better respectively which is I'm assuming due to the cached matrix data, which is great. The scripting and blocking time are significantly worse - I assume it is because of waiting for the additional promises to resolve. I don't think this additional blocking time is awful, especially considering our big problem right now is memory.

The issue I see with this cache solution, is switching back and forth between tenants. Switching from PA -> MO is averaging 1.5GB memory usage on Chrome. I'm assuming this is because the cache is holding onto data for both tenants. I think this is worth looking into - and clearing this cache when switching tenants. Most of our users do not have the ability to switch tenants - but a good chunk of them do so we need to plan for this.

2020-11-06 20:20 UTC, jovergaag commented on src/hooks/useChartData.js
> +    const cacheKey = `${url}-${file}`;
I added you to the performance analysis google doc so you can see some of the numbers I'm seeing on staging data. Let me know if you did not receive the email or have trouble viewing the doc.

2020-11-09 16:48 UTC, Wmaileq commented
Still in progress

2020-11-09 18:54 UTC, Wmaileq commented
> This is awesome, great implementation.
> 
> 
> 
> I like the idea of the cache to avoid redundant fetches, but I'm thinking we may want to store the data somewhere else and not in the `useChartData` hook.
> 
> 
> 
> I've been thinking a lot about how to improve performance of the filters - and also possibly reducing page load time. One thing I've considered is breaking the data up into 3 year data and 1 year or less data. The 3 year data is roughly 40% of the overall data we receive from the API. The 3 year filter view of the data is not used very often by our users - so it is wasteful to be running the 3 year data through the filters every time. I've been thinking about sectioning off the 3 year data and storing both the 3 year and 1 year or less data in a context and only adding it to the full dataset that is run through the filters when that specific filter is selected. 
> 
> 
> 
> Considering this, keeping the data in a central store will be useful and necessary - so I'm wondering if we want to write data to the store instead of caching it here - and simply caching the names of the files that exist in the store and return the data from the store to avoid the redundant fetch.
> 
> 
> 
> I would appreciate your input and thoughts here. I love this implementation for the short term, but in the long term I think we would end up doing this cache differently. Maybe we do this in two steps? This implementation then move the data to a context in the second step? Or shall we tackle it here? Let me know what you think. 

Thinking about 3 and 1 year separating, if we want not to store 3 year data while 3 year filter is not chosen, does it make sense to filter this on backend side?
Or, if I understand correctly, if we do this on front end side, we receive all the data, but 40% of it should be moved to trash immediately?

2020-11-10 01:38 UTC, jovergaag commented
> Thinking about 3 and 1 year separating, if we want not to store 3 year data while 3 year filter is not chosen, does it make sense to filter this on backend side?
> Or, if I understand correctly, if we do this on front end side, we receive all the data, but 40% of it should be moved to trash immediately?

No, I was thinking to fetch all of the data, then break it into 3 year and 1 year or less. Store the 3 year, and only run the 1 year or less through the filters until the 3 year filter is selected. at that point, add the 3 year data onto the data running through the filters. We will be iterating through 30% less data each time the filters are run, until 3 year filter is selected, then we filter all data without having to fetch again.

2020-11-10 08:26 UTC, Wmaileq commented
> > Thinking about 3 and 1 year separating, if we want not to store 3 year data while 3 year filter is not chosen, does it make sense to filter this on backend side?
> > Or, if I understand correctly, if we do this on front end side, we receive all the data, but 40% of it should be moved to trash immediately?
> 
> No, I was thinking to fetch all of the data, then break it into 3 year and 1 year or less. Store the 3 year, and only run the 1 year or less through the filters until the 3 year filter is selected. at that point, add the 3 year data onto the data running through the filters. We will be iterating through 30% less data each time the filters are run, until 3 year filter is selected, then we filter all data without having to fetch again.

I got it!

2020-11-10 16:34 UTC, Wmaileq commented
https://github.com/Recidiviz/pulse-dashboard/pull/608 here started work on separating "3 year" and "less" data.

2020-11-10 21:56 UTC, jovergaag requested changes
Overall this looks good. There was a big change merged today that changes the way we work with files, optimized vs non-optimized. I think there will be a good deal of work to merge in those changes.

Unfortunately, I've been looking at the performance of this branch and it has gotten significantly worse. The commits that you pushed up today increased the memory usage by 2x and the blocking time by 2.5x. The memory use is probably because the data is being cached in the optimized format but then it is parsed and also being held in the non-optimized format. The PR that was just merged should resolve this.

I'm not sure where the additional blocking time is coming from. It is very noticeable on the page. The initial load is very slow to respond, even in Chrome. I don't have any initial ideas of how to resolve this, my first sense is to merge master in with the other optimization improvements and see where we land.

2020-11-10 21:56 UTC, jovergaag commented on src/contexts/ChartDataContext.js
> +const apiCache = new Map();
I like the use of `Map` here instead of an object. Smart.

2020-11-10 21:56 UTC, jovergaag commented on src/hooks/useChartData.js
> +    const cacheKey = `${tenant}-${file}`;
I'm sorry if I wasn't clear. The tenant is 'us_mo', and the url is 'us_mo/newRevocations`. I think we want to keep the store pretty clean and only include the precise tenant string. Then use the full url below in `callMetricsApi`

2020-11-11 14:06 UTC, Wmaileq commented
The critical part divided into new PR that closes 2 issues #612.
Maybe cache is not a good decision :(
Lets close this 2 issues and then proceed.

2020-11-17 01:03 UTC, jovergaag commented
@Wmaileq Do you want to close this PR or take another approach?

2020-11-17 09:52 UTC, Wmaileq commented
> @Wmaileq Do you want to close this PR or take another approach?

Actually, as caching data frontside slows down the application(uses more memory) we can close this PR.
Also now I realized that caching is not very useful, because cases, when user needs to load already loaded data, are rare.

2020-11-17 09:53 UTC, closed without merging