downloads refactor
Recidiviz/pulse-dashboard pull request #619
Opened 2020-11-18 15:42 UTC by Wmaileq

## Description of the change

- Refactored `downloads` functions
- Added export csv rotate if columns count more than rows count. 

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #616 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-11-18 15:45 UTC, Wmaileq commented
@jovergaag 
Almost finished here.

Need to test all the exports and then it will be ready for review. Also tests needed here.

Also, tomorrow I will investigate if we can replace this `document.getElementById`s with react approach.

2020-11-20 03:37 UTC, jovergaag requested changes
These exports are so much easier to read now! A few requested changes:

- For the district names, please convert them to strings so they will all be left justified. Most programs opening a csv will left justify strings and right justify numbers so for district names they are all over the place.
- Please add the name of the dimension as the column header for the first column.

A few other comments in line. 

Great work!

2020-11-20 03:37 UTC, jovergaag commented on src/components/charts/common/bars/utils.js
> +  configureDownloadButtons({
This is so much nicer with the props object, thank you.

2020-11-20 03:37 UTC, jovergaag commented on src/utils/downloads/configureFileName.js
> +function configureFilename(chartId, filters, withoutFilters) {
It looks like the third param is `shouldZipDownload` when this is being used in downloads, lines 44, 117, etc. Mismatch withoutFilters/shouldZipDownload

2020-11-20 03:37 UTC, jovergaag commented on src/utils/downloads/configureFileName.js
> +function configureFilename(chartId, filters, withoutFilters) {
Might want to update it here or there to make it less confusing.

2020-11-20 03:37 UTC, jovergaag commented on src/utils/downloads/createMethodologyFile.js
> +import moment from "moment";
Can you add a test for this, just to ensure the major sections are there.

It would also be nice to include a test on the chartTitle per locale to ensure our translations stay intact.

2020-11-20 03:37 UTC, jovergaag commented on src/utils/downloads/downloadCanvasAsImage.js
> +  destinationCtx.fillStyle = "#FFFFFF";
There's a lot of static styling in here. Are any of these styles shared with the charts themselves? Can we point both of them at a single stylesheet to ensure the download/chart stay in sync, and make it easier to update in the future.

2020-11-20 03:37 UTC, jovergaag commented on src/utils/downloads/downloads.js
> +  const downloadChartAsImageButton = document.getElementById(
Were you not able to find another way to do this?

2020-11-20 03:37 UTC, jovergaag commented on src/utils/downloads/transformChartDataToCsv.js
> +    console.log(e);
Should we `console.error` here instead?

2020-11-20 03:37 UTC, jovergaag commented on src/utils/downloads/transformChartDataToCsv.js
> +  if (!isTable && labels.length > datasetsWithoutTrendLine.length) {
This approach is working great other than for the matrix. The matrix axis got flipped which is confusing. I think that one should never be flipped no matter how many labels there are.

2020-11-20 03:47 UTC, jovergaag commented
One more thing, the `TenantExportMenu` and `ExportMenu` continue to make me think whenever I need to remember which is which. Can you rename `TenantExportMenu` -> `ChartCartExportMenu` please.

2020-11-20 08:28 UTC, Wmaileq commented on src/utils/downloads/configureFileName.js
> +function configureFilename(chartId, filters, withoutFilters) {
Yes, I've done it on purpose, because, in my opinion, function `configureFilename` does not need to know about `shouldZipDownload` I thought this parameter name would be more descriptive.
When you read `withoutFilters` you know that this parameter disables filters, but when you see `shouldZipDownload` I think it is a bit confusing, and you need to go through func body to realize what this parameter do.

2020-11-20 08:31 UTC, Wmaileq commented on src/utils/downloads/downloads.js
> +  const downloadChartAsImageButton = document.getElementById(
Yes, I think this should be done in new PR, because this refactor will result in a lot of changes, but PR is big already.

2020-11-20 14:29 UTC, Wmaileq commented on src/utils/downloads/createMethodologyFile.js
> +import moment from "moment";
I am not sure that I got it, looks like chartTitle goes from props, not from translations...
Added unit tests, so all the external functions mocked.

2020-11-20 20:42 UTC, jovergaag commented on src/utils/downloads/createMethodologyFile.js
> +import moment from "moment";
Oh you are right. Nevermind :)

2020-11-23 15:05 UTC, Wmaileq commented on src/utils/downloads/downloadCanvasAsImage.js
> +  destinationCtx.fillStyle = "#FFFFFF";
All exported charts consist of: heading, filters applied, and the whole copied chart canvas.
1. We have no filters on the website charts
2. I am not sure that the heading should inherit from the website, but if this is the case I can do it.
3. the whole chart canvas is just copied to export canvas, so no differences here.

Maybe it is a good idea to inherit background from the source.

2020-11-23 15:06 UTC, Wmaileq commented
Added dimensions to all the export data, tested all the charts, all should work as expected!

2020-11-24 01:45 UTC, jovergaag requested changes
I have just a few small nit picks on the labels. We also still need to convert all the row labels to strings to ensure they are left justified.

Thanks!

2020-11-24 01:45 UTC, jovergaag commented on src/components/charts/GeoViewTimeChart.js
> +      dimension: "Region",
Let's call this 'County'

2020-11-24 08:00 UTC, Wmaileq commented on src/components/charts/common/bars/utils.js
> +export function configureDownloads({
Yeah, forgot to comment but I investigated here, looks like CSV doesn't support types, so we cannot set the type of cell to string implicitly, different CSV readers have different technics.
We can add `'` to the start of the cell, this converts cell to string in Excel, but in `Mac's Numbers app` it will look like this:
![image](https://user-images.githubusercontent.com/26236198/100064984-44b07180-2e44-11eb-8b4e-29fc289396ae.png)

2020-12-01 17:53 UTC, jovergaag commented on src/components/charts/common/bars/utils.js
> +export function configureDownloads({
Oh. Right that makes sense. Let's not add the `'` and just leave it the way it is. Thanks for looking into it!

2020-12-01 18:48 UTC, jovergaag approved these changes
Wonderful, thank you! 🎉

2020-12-01 18:48 UTC, merged