[API] Add path and query param validations for new revocations endpoint
Recidiviz/pulse-dashboard pull request #679
Opened 2020-12-22 22:14 UTC by daschi

## Description of the change

This PR adds path and query param validations for the `/api/:stateCode/newRevocations/:filename` endpoint. This is the first step towards requesting files by filter params from the frontend, and the param validations are set to optional here until we add the query params to the frontend as part of #657. 

I chose to use the package `express-validator` because I thought the documentation was pretty good and it's straightforward, but let me know if there is a different validation package you prefer!

## Type of change
- [x] New feature (non-breaking change that adds functionality)

## Related issues

> Closes #653 

Relates to #657 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-12-23 21:57 UTC, jovergaag requested changes
The param validation all looks good. Since you started digging into it...a couple of small requests on the error statuses :)

2020-12-23 21:57 UTC, jovergaag commented on server/routes/api.js
> +      const status = err.status || 500;
hooray. Thank you.

public-dashboard is doing this: `res.status(500).json({ error: err.message });` which i think does a nice job of tidying up the message. Currently the body of the response is pretty hard to read so I think we should adopt this.

So, when I renamed a file in the bucket, the error comes through here with `{ code: 404 }`, so the status here is set to 500 to send to the FE. That's a huge improvement from the status 200 we were receiving :). I wonder if we should also check for that `code: 404` here and set the status to 404 as well?

2020-12-23 21:57 UTC, jovergaag commented on server/routes/api.js
> +const BAD_REQUEST = 400;
Should we add a 500 here as well, then include it on line 32?

2020-12-23 21:57 UTC, jovergaag commented on server/routes/api.js
> +      const status = err.status || 500;
Or just check the `code` in general and set the status accordingly. Why is it coming through as `code`? 🤔

2020-12-28 21:19 UTC, daschi commented on server/routes/api.js
> +      const status = err.status || 500;
Yeah that's a good idea, I'll add the check for `code`.[ Here's the documentation for the json API responses for google cloud storage.](https://cloud.google.com/storage/docs/json_api/v1/status-codes#401-unauthorized)

2020-12-29 01:14 UTC, jovergaag approved these changes
Supa! 🚀

2020-12-30 17:52 UTC, merged