Move filters to FiltersStore
Recidiviz/pulse-dashboard pull request #680
Opened 2020-12-24 00:40 UTC by jovergaag

## Description of the change

Moves the filters and filterOptions to a central Store. This will make it easier to trigger a fetch if the currently cached dimension values for any given file do not fulfill the new filter state.

Eventually, there will be a `DataStore` action which will be called from FiltersStore.setFilters() to evaluate the local data/trigger the fetch. We could have put that logic directly in the Revocations component where the filters currently live, but this seems much more clean.

This is very much a WIP - I just wanted to get some feedback on it before going too much further. Next steps are to access the filters directly in the chart components and filter components rather than passing them down from `Revocations`. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #644

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2020-12-24 00:56 UTC, jovergaag commented on src/App.js
> +            <StoreProvider stateCode={lanternTenant.MO}>
I don't love wrapping both of these `LanternLayouts` individually but we need the stateCode. Until we get around to adding a `UserStore` where we can pull the stateCode from, this seemed like the best approach.

2020-12-24 00:56 UTC, jovergaag commented on src/App.test.js
> +  Revocations.type.mockReturnValue(mockWithTestId(mockRevocationsId));
This was necessary because Revocations is now a wrapped function (observer)

2020-12-24 01:52 UTC, macfarlandian reviewed
I ... think I follow? I can already see how much of an improvement this will be. Overall I think it makes sense beyond any specific comments below. 

One additional thing I would strongly recommend is that you enable the MobX runtime linting in both your test and application environments and see what warnings it throws. They are kind of annoying (in large part because they don't have stack traces, which drove me nuts) but I found they helped me understand the flow of data better.

2020-12-24 01:52 UTC, macfarlandian commented on src/App.js
> +            <StoreProvider stateCode={lanternTenant.MO}>
a few thoughts; not sure if any of them will prove helpful: 

- if `stateCode` was an observable property rather than a constructor argument, would that help? (i.e. do you ever really need to render both of these layouts at the same time? I don't really know how this part of the app works so sorry if that's a useless question)
- alternatively, what if you had a single root store (and thus a single context/provider) that had multiple "tenant stores" or whatever it would make sense to call them? within each one you could use the state code to look up the matching tenant. I think in general it will probably make our lives easier to just have a single root store with everything in it, so it might be worth it to figure out how to have that now even if it's a little weird with pieces missing

2020-12-24 02:13 UTC, jovergaag commented
@macfarlandian Thank you!

> One additional thing I would strongly recommend is that you enable the MobX runtime linting in both your test and application environments and see what warnings it throws. They are kind of annoying (in large part because they don't have stack traces, which drove me nuts) but I found they helped me understand the flow of data better.

I have them in my index locally but there are SO MANY ERRORS right now that it crashes the browser, so I have them commented out for the moment. Once I can access the filters in the charts and filter components directly, and add an `observer` then it should quiet down and I will enable the linters.

> I think in general it will probably make our lives easier to just have a single root store with everything in it, so it might be worth it to figure out how to have that now even if it's a little weird with pieces missing

Good point. I'll spend some more time on that before going any further.

2021-01-12 01:33 UTC, jovergaag commented on src/tenants.js
> -    regions: {
This was added for the district restricted access feature that was prematurely coded quite a while ago - that feature is coming up this week but we have decided on a different approach than these regions.

2021-01-12 01:33 UTC, jovergaag commented on src/utils/authentication/user.js
> -export function getUserDistricts(user) {
Same here - the implementation of the district restricted access has changed.

2021-01-12 01:33 UTC, jovergaag commented on src/components/Revocations.js
> -              onChange={createOnFilterChange(METRIC_PERIOD_MONTHS)}
I would love feedback on this approach of accessing the values and options directly in the component via the store vs via the props. It definitely has changed how the filters are tested. Is this a step backward composition wise?

2021-01-12 01:33 UTC, jovergaag commented on src/components/Revocations.js
> -  const transformedFilters = limitFiltersToUserDistricts(
This is removed because the implementation of the District Restricted Access feature will be different than what was initially planned months ago when it was originally written (but not yet ready).

2021-01-12 01:37 UTC, jovergaag commented
@macfarlandian This is nearly ready for a final review. I am working on a few more tests and finding a better way to wrap components in a `StoreProvider` in the tests that is not so cumbersome, as well as a better way to set the default Tenant in the `TenantStore`.

I wanted to get some feedback while I'm finishing up these remaining items. Thoughts on the overall implementation?

2021-01-12 15:58 UTC, daschi commented on src/RootStore/FiltersStore.js
> +    this.restrictedDistrict = restrictedDistrict;
For the `restrictedDistrict` feature -- does this mean that there are some users that can only see data for 1 district?

2021-01-12 15:58 UTC, daschi commented on src/RootStore/TenantStore.js
> +    // default currentTenantId on line 49
Could this similarly also apply to setting the `restrictedDistrict` from the user in the `FiltersStore`?

2021-01-12 15:58 UTC, daschi commented on src/components/charts/new_revocations/RevocationsOverTime.js
> +      filterStates={filters}
I think `filterStates` was removed as a prop for this component?

2021-01-12 16:06 UTC, daschi commented on src/components/Revocations.js
> -              onChange={createOnFilterChange(METRIC_PERIOD_MONTHS)}
I think I like this change for the filter components. `ToggleBarFilter` now has a very clear/consistent onChange, and the other filters contain the code specific to their use cases. This pattern would differ from how we talked about passing in the `apiData` from the upcoming `DataStore`, but I think we have a good reason to pass in the data as a prop, and I'm not sure I know the drawbacks yet of accessing the filters from the store per component. Happy to keep chatting about it if you want to think through the idea more too..

2021-01-12 17:49 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +    this.restrictedDistrict = restrictedDistrict;
Yes exactly. There will be a file mapping email addresses to district number, and the district filter will be locked to that district.

2021-01-12 17:49 UTC, jovergaag commented on src/RootStore/TenantStore.js
> +    // default currentTenantId on line 49
Yes!

2021-01-12 19:30 UTC, macfarlandian requested changes
looking really good overall! love how much prop drilling you've been able to eliminate from these components.

2021-01-12 19:30 UTC, macfarlandian commented on src/components/charts/community/RevocationCountOverTime.js
> +export default observer(RevocationCountOverTime);
what observable data is being used here?

2021-01-12 19:30 UTC, macfarlandian commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +      filters={filters}
`filters` is an observable data structure, so `CaseTableComponent` needs to be an `observer` as well, right? I would even go further and say it ought to just consume the filters directly from the context rather than having it passed down like this. I think this pattern can cause unnecessary re-renders of this parent component when all it's doing is passing new data to its children

2021-01-12 19:30 UTC, macfarlandian commented on src/components/charts/new_revocations/Matrix/Matrix.js
> +          filters={filters}
I don't think you need to pass this anymore? isn't `ExportMenu` getting this from context now?

2021-01-12 19:30 UTC, macfarlandian commented on src/components/charts/new_revocations/ToggleBar/__tests__/ToggleBarFilter.test.js
> +      reaction(
similar to the other tests I think maybe `when` would be a better option here?

2021-01-12 19:34 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +      this.setFilters(this.defaultFilters);
Yes exactly.

2021-01-12 19:35 UTC, jovergaag commented on src/RootStore/TenantStore.js
> +      setCurrentTenantId: action,
Yep! Good catch.

2021-01-12 19:36 UTC, jovergaag commented on src/components/__tests__/Revocations.test.js
> +// Copyright (C) 2020 Recidiviz, Inc.
uff. Indeed it is.

2021-01-12 19:42 UTC, jovergaag commented on src/components/charts/community/RevocationCountOverTime.js
> +export default observer(RevocationCountOverTime);
Good catch. We have lots of components that are named nearly identically unfortunately. I must have added this thinking it was `RevocationsOverTime` by mistake.

2021-01-12 19:47 UTC, jovergaag commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +      filters={filters}
This is a mistake. CaseTableComponent does not even need filters!

2021-01-12 20:04 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +  filters = observable.map();
I struggled with this a lot. I started with it initialized as an object but get this linting warning: `[mobx] Observable FiltersStore@5.filters.isMobXObservableMap? being read outside a reactive context`. It seems like Mobx sees it as an observable.map. 

<img width="1750" alt="Screen Shot 2021-01-12 at 12 03 41 PM" src="https://user-images.githubusercontent.com/5872651/104366459-44406880-54ce-11eb-8b74-0e7d0f523e70.png">

2021-01-12 20:06 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +  filters = observable.map();
I think because different components are observing specific attributes of the filters object, it has to be an observable.map?

2021-01-12 20:18 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +  filters = observable.map();
I will play around with making filters a Map rather than an object.

2021-01-12 20:19 UTC, jovergaag commented on src/components/__tests__/Revocations.test.js
> +// Copyright (C) 2020 Recidiviz, Inc.
I'm going to change these in another PR so that it doesn't clutter this PR.

2021-01-12 20:21 UTC, daschi commented on src/RootStore/FiltersStore.js
> +  filters = observable.map();
I was wondering this too and I read this in the [API docs](https://mobx.js.org/api.html#observablemap):

`Creating observable Maps is the recommended approach for creating dynamically keyed collections if you don't have enabled Proxies.`

So I thought we were using it because IE11 doesn't support enabled proxies.

2021-01-12 21:02 UTC, macfarlandian commented on src/RootStore/FiltersStore.js
> +  filters = observable.map();
weird ... I think there's probably a way to leave it as an object if that makes things easier? maybe it could at least be an `observable.object` to make it less confusing? I am still a bit fuzzy about all of this honestly so if it works and is reasonably readable then I don't think we need to be too precious about it

2021-01-12 22:27 UTC, jovergaag commented on src/components/__tests__/Revocations.test.js
> +    reaction(
Not overkill! In fact it turns out that the expect in this test as well as the other test with this pattern were never running at all. I ended up approaching these tests completely differently. I still don't love them but its at least now doing what i think its doing :)

2021-01-12 22:34 UTC, jovergaag commented
@macfarlandian and @daschi  This is ready for another look

> If you are concerned about the tight coupling between UI and data source, maybe you could preserve the original filter components but wrap each one in a container component that interacts with the data store and passes it as props? I don't think this is all that critical, considering that all they're doing is reading the data rather than applying any logic to it, but if portability is a big concern then maybe that would help?

@daschi and I have been talking about the container concept over the last few days. It would remove our callback scope issue  which is causing charts to hold on to memory after being unmounted. Ultimately we decided to move ahead with a DataStore performing the fetch instead of the chart which also solves the scope problem. We decided that the container is just going to be a lot of extra code but provides no benefit over what the DataStore provides. I'm inclined to go this route and see how it feels after the DataStore is in and we can make adjustments after that if it still seems too tightly coupled.


I think I'm going to leave the StoreProviderWrapper for the tests for another day. There is a lot of work blocked behind this so the sooner we can get it in the better. It will also allow us more experience working with the observer components in the tests to get a feel for how best to implement the wrapper.

2021-01-12 22:48 UTC, macfarlandian commented on src/components/__tests__/Revocations.test.js
> +    FiltersStore.prototype.setRestrictedDistrict = setRestrictedDistrictSpy;
would it be better to mock FiltersStore here instead? I am worried this will pollute other test suites. 

(same applies to the other test where a similar pattern was implemented)

2021-01-13 01:04 UTC, jovergaag commented on src/components/__tests__/Revocations.test.js
> +    FiltersStore.prototype.setRestrictedDistrict = setRestrictedDistrictSpy;
I had originally tried to set up a `__mocks__/FiltersStore` but no matter how I set that up I wasn't able to make it work for both test files. This updated mock feels a little clunky but I agree that its safer - in fact I think that spy was picking up another call in the ToggleBarFilter test.

2021-01-13 01:43 UTC, macfarlandian approved these changes
🥇

2021-01-14 00:43 UTC, jovergaag commented
@macfarlandian @daschi Based on your comments above about the `observable.map` - I dug into this a little more. As it turns out, the filters was an observable map, but the filter values that were being set weren't individually observable.

Here is the `filters` object before my last two commits - note that the filter keys are at the top level of the object (not inside `data`, and are not observable:
<img width="1756" alt="Screen Shot 2021-01-13 at 1 12 35 PM" src="https://user-images.githubusercontent.com/5872651/104529326-500b5800-55be-11eb-9f29-a3c8664a6ec4.png">

Here is the `filters` object after the most recent commits - note that the filter keys are inside of `data` and are each observable
<img width="1766" alt="Screen Shot 2021-01-13 at 1 11 53 PM" src="https://user-images.githubusercontent.com/5872651/104529306-471a8680-55be-11eb-8a60-50b24b3e98f9.png">


Notice that the values in the filters object are now each observable - which I think is what we want. What we were doing before was working because the filters would run when the `filters` object would change, but now each of the filter values themselves is observable - useful for things like the `timeDescription` in each chart.

I also found that the `ExportMenu` exports were broken so I fixed that in the final commit.

A final review of those last two commits is appreciated!

2021-01-14 00:45 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsOverTime.js
> +  const chartId = `${translate("revocations")}OverTime`;
While working on this I found a bug - so I fixed it here. Meant to put it in its own commit but...such is life. Issue #689

2021-01-14 00:49 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +  filters = observable.map();
I tried to make this an `observable.object` but nothing I did made Mobx happy. I'm ok with it being an `observable.map` if you all are... at least until we better understand the nuances of these different observables.

2021-01-14 02:03 UTC, macfarlandian approved these changes
I think the nuance of this approach may have gone slightly over my head, but the changes seem reasonable to me. I say let's give it a shot!

2021-01-14 19:10 UTC, merged