Add DataStore for new revocation charts
Recidiviz/pulse-dashboard pull request #694
Opened 2021-01-15 00:59 UTC by daschi

## Description of the change

WIP - Will update this description tomorrow!

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-01-15 19:00 UTC, macfarlandian commented on src/RootStore/DataStore/RevocationsOverTime.js
> +  }
why doesn't this just call `getQueryStringFromFilters`?

2021-01-15 19:00 UTC, macfarlandian commented on src/RootStore/RootStore.js
> +    });
i think you should include `getTokenSilently` here too as a `computed`?

2021-01-15 19:00 UTC, macfarlandian commented on src/api/metrics/urlHelpers.js
> + * @param {string} filters.supervisionType - Supervision Type of "All"
*or

2021-01-15 19:00 UTC, macfarlandian commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  const { filtersStore } = useRootStore();
I don't quite understand why one store comes in as a prop while the other is read from the context? (same question applies to all of the other components that do this)

if nothing else it is making this code hard to follow because it is not obvious which store is being used where

2021-01-15 19:00 UTC, macfarlandian commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  }, [dataStore.filteredData, comparator]);
I wonder whether it would be cleaner for sorting to be done on the datastore instead of here? mutating the `computed` array in this component feels like it could be bug-prone or at the very least somewhat obscure

2021-01-15 21:18 UTC, daschi commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  const { filtersStore } = useRootStore();
@jovergaag After chatting on slack, we decided to move these into the components.

2021-01-15 21:52 UTC, daschi commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  }, [dataStore.filteredData, comparator]);
For now I updated this to copy the data before calling sort on it. I think this PR is already pretty big so would like to separate out thinking through moving this to the datastore in a different branch.

2021-01-19 17:33 UTC, macfarlandian commented
@daschi are the TODOs in the description things you are planning to add to this PR? just wondering whether I should wait for more changes before reviewing again

2021-01-19 21:54 UTC, jovergaag requested changes
Holy cow this is so nice! Those components are looking so fresh and clean!

I found a few little issues and have a few questions. But this is getting really close I think!

2021-01-19 21:54 UTC, jovergaag commented on src/RootStore/DataStore/CaseTable.js
> +  auth0Context = observable.map({ loading: true });
This is coming from the `rootStore` so I don't think we need it as a a class attribute anymore.

2021-01-19 21:54 UTC, jovergaag commented on src/RootStore/DataStore/Matrix.js
> +  get queryFilters() {
This is never different per data store right? Should we put this on the parent `DataStore` class?

2021-01-19 21:54 UTC, jovergaag commented on src/RootStore/DataStore/RevocationsCharts.js
> +      (queryString) => this.fetchData(queryString, false)
I think we should set `isLoading` to true here. When I was playing around with this, I changed a filter, and during the time that the fetch was happening in the background the chart didn't change - then all of a sudden it changed. This might be confusing to a user because they may not understand that the chart changed in response to the filter change. I think it would be more clear (on all charts) to set `isLoading` to true when the fetch is initiated.

@sychang Thoughts on this? Should we show the loading indicator in the chart if a filter is changed such that it is requesting new data?

2021-01-19 21:54 UTC, jovergaag commented on src/RootStore/DataStore/CaseTable.js
> +    reaction(
I think this can be an `autorun` instead of `reaction`, for all data stores.

2021-01-19 21:54 UTC, jovergaag commented on src/RootStore/DataStore/RevocationsOverTime.js
> +  get districts() {
I find this a little confusing to keep this in this store. Ultimately it doesn't matter which metric file we're pulling the list of districts from, but I think it would make more sense to store this list elsewhere.  

We have a feature coming down the pipe where we will receive a file ` supervision_location_ids_to_names.json` which will list all the district numbers and map them to their name to be displayed in the filter. When we implement that we will use that as the list of districts for the filter. Until then, parsing them from this metric file is fine, lets just let it live elsewhere.

What about in the `FiltersStore`?

2021-01-19 21:54 UTC, jovergaag commented on src/RootStore/RootStore.js
> +  get getTokenSilently() {
Why can't we just access this directly from `rootStore.auth0Context`?

2021-01-19 21:54 UTC, jovergaag commented on src/api/metrics/urlHelpers.js
> + * @param {string} filters.supervisionType - Supervision Type or "All"
We're missing `supervisionLevel` in this list. MO and PA have different filters enabled 🎊 .

2021-01-19 21:54 UTC, jovergaag commented on src/components/Revocations.js
> +      <RevocationCharts timeDescription={timeDescription} />
😍

2021-01-19 21:54 UTC, jovergaag commented on src/components/Revocations.js
> +      <RevocationCharts timeDescription={timeDescription} />
I think we lost our `ErrorBoundary` around these charts.

2021-01-19 21:54 UTC, jovergaag commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  const filteredData = store.filteredData.slice();
Why is this necessary?

2021-01-19 21:54 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationCharts/RevocationCharts.js
> +        <ErrorBoundary>{renderSelectedChartSingularLoad()}</ErrorBoundary>
Oh there it is. Nevermind!! :)

2021-01-19 21:54 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationCharts/RevocationCharts.js
> +  const store = dataStore.revocationsChartsStore;
Is there a benefit to accessing the store in this parent and passing it down to the chart rather than accessing it directly in the chart?

2021-01-19 21:54 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsByOfficer/RevocationsByOfficer.js
> +      generateChartData={createGenerateChartData(dataStore)}
Eventually we should generate this chart data in the data store and pass the transformed data to the chart. For another day...

2021-01-19 21:55 UTC, jovergaag commented on src/RootStore/DataStore/DataStore.js
> +  revocationsCharts;
I find the plural `revocationsCharts` to be a little misleading, thinking that it would have the data for all the charts. Maybe just `revocationsChart`?

2021-01-19 22:31 UTC, sychang commented on src/RootStore/DataStore/RevocationsCharts.js
> +      (queryString) => this.fetchData(queryString, false)
Yes, let's add the loading indicator!

2021-01-20 15:16 UTC, daschi commented
@macfarlandian I did the IE11 performance testing last Friday, and I'll spend this morning adding the tests for the new data stores and responding to Jen's comments. I'll re-request a review when that's ready! Thanks for checking

2021-01-20 15:25 UTC, daschi commented on src/RootStore/DataStore/Matrix.js
> +  get queryFilters() {
Yeah I would like to DRY up the stores, but right now the `DataStore` is not a parent class, it's acting as a "root store" for all of the data stores. I think I could create another store as an abstract class like `BaseDataStore` that will be the parent to the other stores and have all of the shared attributes.

2021-01-20 15:33 UTC, daschi commented on src/RootStore/DataStore/CaseTable.js
> +    reaction(
Ah okay, that makes sense. I would remove the `when` and the `reaction` and replace it with `autorun` that checks the auth0Context condition.

2021-01-20 15:37 UTC, daschi commented on src/RootStore/RootStore.js
> +  get getTokenSilently() {
I think we can, I was probably overthinking it :)

2021-01-20 15:42 UTC, daschi commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  const filteredData = store.filteredData.slice();
I added this to avoid directly mutating the observable data on line 46 with the sort. @macfarlandian mentioned we should move the sorting to the data store. I started going down that path but it seemed a little more complicated and figured this PR was already getting pretty big that we could tackle that in a separate issue.

2021-01-20 15:43 UTC, daschi commented on src/components/charts/new_revocations/RevocationCharts/RevocationCharts.js
> +        <ErrorBoundary>{renderSelectedChartSingularLoad()}</ErrorBoundary>
Yeah, but you make a good point that it's a little hidden. I'm going to move this back into the `Revocations` component so it matches all the other components' pattern.

2021-01-20 15:46 UTC, daschi commented on src/components/charts/new_revocations/RevocationCharts/RevocationCharts.js
> +  const store = dataStore.revocationsChartsStore;
I kept it here since we need the `setSelectedChart` and `selectedChart` states in this parent component, but I'm open to also connecting each of the child component charts directly to the store too since mobx says it's better to access the data closer to the rendering component.

2021-01-20 17:59 UTC, daschi commented on src/RootStore/DataStore/RevocationsOverTime.js
> +  get districts() {
Oh okay, in that case what do you think about creating a `DistrictsStore`, that will eventually fetch the new json file?

2021-01-20 22:07 UTC, jovergaag commented on src/RootStore/RootStore.js
> +  get getTokenSilently() {
Oh I see, ok. The `UserStore` removes the useAuth0 context so we will prob have to make adjustments depending on who merges first!

2021-01-20 23:04 UTC, daschi commented
This is ready for another review. I pulled out the shared properties and methods into a `BaseDataStore` superclass and added a test for that class. I think there's still some more tests that could be added for each DataStore's `filterData` function, which I could look into tomorrow (or move onto a new issue?). Let me know what you think..

2021-01-21 01:01 UTC, jovergaag commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  const filteredData = store.filteredData.slice();
As we've discussed before, I think we should do all the data prep in the store and only send formatted/sorted/filtered data to the components. One day we will be there :)

2021-01-21 02:44 UTC, jovergaag requested changes
THIS IS USEABLE IN IE11!!! I actually used the dashboard in IE11- filtered and switched charts for at least 10 mins and it never crashed. Well done!!!

Just one issue with `eagerExpand`, but its oh so close!

2021-01-21 02:44 UTC, jovergaag commented on src/components/charts/new_revocations/ToggleBar/DistrictFilter.js
> +  return <FilterField label="District">{getSelectElement()}</FilterField>;
Oh nice. I was wondering what was wrong with the district filter. Thanks for fixing it!!

2021-01-21 02:44 UTC, jovergaag commented on src/RootStore/DataStore/BaseDataStore.js
> +        this.fetchData(this.queryFilters);
One thing that is a little wonky with this (only in IE11 - Chrome is fine) - when I'm on the profile page and switch from one Lantern tenant to the other...the page becomes unresponsive for 20 seconds or so (depending on if switching to PA or MO) while the data is fetched and loaded. This means the user can't navigate back to the dashboard because the "Lantern" button is disabled for a while.

However, only Recidiviz and CSG users are the ones who are able to switch tenants...so maybe this isn't a big deal? I'm inclined to say not a big deal for now...CSG users are not on IE11 (at least to my knowledge). @sychang Does this seem like something we need to resolve? 

We can kick off the fetch when the user navigates back to the dashboard page to make IE11 happy...but it is kind of nice to have that fetching happening in the background for non-IE11 browsers so that when the user gets to the dashboard the data/charts are ready to go.

2021-01-21 04:10 UTC, sychang commented on src/RootStore/DataStore/BaseDataStore.js
> +        this.fetchData(this.queryFilters);
This is absolutely not a big deal, since no one on Recidiviz nor CSG are using IE11

2021-01-21 04:19 UTC, jessex commented on src/RootStore/DataStore/BaseDataStore.js
> +        this.fetchData(this.queryFilters);
Just flying by with a quick comment: sounds like something to defer to some later point, so let's just make sure we file a task so we don't forget!

2021-01-21 14:46 UTC, daschi commented on src/RootStore/DataStore/RevocationsOverTimeStore.js
> +  *fetchData(queryString = "") {
This needs to also store the expanded data to create the `districts` data. I'm going to open a separate issue to create a `DistrictsStore` as a fast follow to this.

2021-01-21 14:49 UTC, daschi commented on src/RootStore/__tests__/BaseDataStore.test.js
> +  describe("when API responds with an error", () => {
I added a note to that issue that data fetching is coming from the data stores now for new revocations charts.

2021-01-21 14:50 UTC, daschi commented on src/api/metrics/__tests__/urlHelpers.test.js
> +// Recidiviz - a data platform for criminal justice reform
Do you mean `getQueryStringFromFilters`? Yeah I can move it into the DataStore helpers.

2021-01-21 14:50 UTC, daschi commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  const filteredData = store.filteredData.slice();
I can open a issue for this

2021-01-21 14:51 UTC, daschi commented on src/RootStore/DataStore/BaseDataStore.js
> +        this.fetchData(this.queryFilters);
I can open an issue for this

2021-01-21 17:38 UTC, jovergaag commented on src/api/metrics/__tests__/urlHelpers.test.js
> +// Recidiviz - a data platform for criminal justice reform
Yes thats what I meant. Thanks for being psychic :)

2021-01-21 17:55 UTC, jovergaag approved these changes
You're a hero 🌈

2021-01-21 18:16 UTC, macfarlandian approved these changes
🎉

2021-01-21 18:24 UTC, merged