Add the subset_manifest for violationType and generate cache keys based on filter params
Recidiviz/pulse-dashboard pull request #705
Opened 2021-01-21 23:18 UTC by daschi

## Description of the change

This is the first step towards implementing the subsets of revocations files for the frontend. This PR includes changes for both the FE and BE because I needed to pass the value "All" as a default value for `violationType`. 

I'm still thinking through how we want the `refreshCache` endpoint to work. I'm thinking right now that we would want to loop through all the possible subsets and create a cache key for each one. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #654 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-01-25 22:31 UTC, jovergaag requested changes
Cool! It is a little confusing since we're handling both the subset keys and the original keys, but I think you did a good job of documenting those, and they won't last long before we swap over to the subset keys entirely so i say its ok!

Few comments...

2021-01-25 22:31 UTC, jovergaag commented on server/core/cacheManager.js
> +  const cache = Array.isArray(cacheKey)
It might be nice to put a comment here explaining when it will be an array and when it won't. Or tests. It will help when we switch away from `cacheKeyOriginal`

2021-01-25 22:31 UTC, jovergaag commented on server/core/cacheManager.js
> +    [cacheKeyOriginal] = cacheKey;
I'm not understanding this line - why do we want to set the `cacheKeyOriginal` to the array cacheKey?

2021-01-25 22:31 UTC, jovergaag commented on server/core/refreshRedisCache.js
> +      // TODO: Remove line 57 once the front end is ready to receive the subset files.
This should be line 59

2021-01-25 22:31 UTC, jovergaag commented on server/constants/subsetManifest.js
> +const SUBSET_MANIFEST = [
As I'm looking at this and thinking through edge cases, I think we need to guard against dimensions being added to the subset manifest that are multi-select filters. The only dimension right now that is multi-select is the district filter. We can't allow that to be subsetted because a user can easily select districts that are in more than one subset.

Can you add a guard and comment here to that effect pretty pls.

2021-01-25 22:31 UTC, jovergaag commented on server/utils/cacheKeys.js
> +const {
We're missing the copyright comment here.

2021-01-25 22:31 UTC, jovergaag commented on server/utils/__tests__/cacheKeys.test.js
> +import { getCacheKey, getSubsetCacheKeyCombinations } from "../cacheKeys";
Also missing copyright comment here :)

2021-01-25 22:31 UTC, jovergaag commented on server/utils/cacheKeys.js
> + * @returns {string[][]} - A nested array of all the combinations. [["dimensionKeyA=0", "dimensionKeyB=0"]]
Can you show the [1] index of this return value in the comment. I think it would be helpful to see that it is `["dimensionKeyA=0", "dimensionKeyB=1"]`

2021-01-25 22:55 UTC, daschi commented on server/core/cacheManager.js
> +    [cacheKeyOriginal] = cacheKey;
This is actually de-structuring the array to get the value for `cacheKeyOriginal`. When `cacheKey` is an array it'll look like: `[cacheKeyOriginal, cacheKey]`. The de-structuring here is taking the first element and assigning it to the `cacheKeyOriginal` variable defined on line 95. I didn't originally write it as a de-structuring assignment, I blame eslint for that :P

2021-01-25 23:07 UTC, daschi commented on server/constants/subsetManifest.js
> +const SUBSET_MANIFEST = [
Sure, I added a function to get the subset manifest that will validate the values, but for now it's all defined in the same place. Let me know what you think and if it's overkill?

2021-01-25 23:57 UTC, jovergaag commented on server/core/cacheManager.js
> +    [cacheKeyOriginal] = cacheKey;
OH. Of course it is :)

2021-01-26 00:09 UTC, jovergaag approved these changes
🌮

2021-01-26 14:57 UTC, merged