Restricted district access
Recidiviz/pulse-dashboard pull request #707
Opened 2021-01-23 00:21 UTC by jovergaag

## Description of the change

We want to set the dashboard view to a specific district for certain users. This is not for all users of any given state, only for a subset of users. If a user's district is restricted, it should lock the district filter to that district, and filter all data such that the charts show only data for that district. The exception to that is for the district chart, we want to show all districts in the district chart, but highlight the restricted district.

If there is an error with the fetch when fetching the list of restricted users, or if the district ID for that particular user is invalid, display an error and do not show any data to that user. That error message looks like this:
![Screen Shot 2021-01-22 at 3 58 55 PM](https://user-images.githubusercontent.com/5872651/105562038-8e46fc80-5ccd-11eb-9ad2-1766e494ecc9.png)

This PR:
- adds the restricted access email file to the API
- fetches the restricted access email file from the UserStore
- if the current user's email address is in the list of restricted access emails, set the restrictedDistrict after verifying that the restrictedDistrict is valid
- moves the list of districts for the district filter into the TenantStore since that list is dependent on the Tenant
- makes a few changes to the eslintconfig. I'm really struggling getting linting and prettier working for both .js and .ts files simultaneously. I think we will just need to duplicate rules in both the JS and TS "overrides" section. I'm definitely open to other suggestions here...
- Adds the new error message format

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #670 and #632

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-01-25 19:38 UTC, daschi requested changes
This is exciting!! I have a some comments/questions for now, mostly about the mobx setup.

2021-01-25 19:38 UTC, daschi commented on src/RootStore/DataStore/BaseDataStore.js
> +      if (userStore && !userStore.userIsLoading) {
I think we may need another condition here to wait on the `restrictedDistrictIsLoading`, this looks like it is currently fetching data when the user loads for all districts, and then after `restrictedDistrictIsLoading` is updated it loads the restricted district data.

2021-01-25 19:52 UTC, jovergaag commented on src/RootStore/DataStore/BaseDataStore.js
> +          tenantId: this.rootStore.currentTenantId,
We need tenantId to be in the reaction so that the fetch will be triggered when the tenant changes. Without this, switching between MO and PA didn't fetch the new data.

2021-01-25 19:53 UTC, jovergaag commented on src/RootStore/UserStore.ts
> +        this.fetchRestrictedDistrictData(this.rootStore?.currentTenantId);
Same reason as previous comment, so that we fetch new data when the tenant changes.

2021-01-25 20:22 UTC, jovergaag commented on src/RootStore/UserStore.ts
> +  async fetchRestrictedDistrictData(
I was struggling to get the flow generator to work with TypeScript, but I just got it to work so pushing that up!

2021-01-25 23:28 UTC, jovergaag commented on src/utils/authentication/viewAuthentication.js
> +    // email: "notarealemail@recidiviz.org",
No I left those in there so that it is easy to switch demo mode to restricted access.

2021-01-25 23:29 UTC, jovergaag commented on src/RootStore/__tests__/UserStore.test.ts
> +        expect.any(Function)
I tried for a long time but couldn't get that to work. The expectation was expecting a function typed: `mockConstructor` but it was receiving a function typed `anonymous`.  I couldn't figure out how to type case the mockConstructor. Any ideas @macfarlandian?

2021-01-25 23:30 UTC, jovergaag commented on src/RootStore/__tests__/UserStore.test.ts
> +        new Error(ERROR_MESSAGES.unauthorized)
If there is an API error - we want to fail closed - meaning not show the dashboard at all and tell the user that they're not authorized to see the page. Serena wanted to show the same message as when there is an authorization error in this case.

2021-01-25 23:33 UTC, jovergaag commented on src/RootStore/DataStore/BaseDataStore.js
> +      if (userStore && !userStore.userIsLoading) {
Hmm, I don't think that it relies on `restrictedDistrictIsLoading`. We only need the user (specifically `getTokenSilently` to initiate this fetch. The restricted district fetch can happen simultaneously.

The only thing that relies on the `restrictedDistrictIsLoading` is the AuthWall, which gates whether or not the dashboard can be displayed.

2021-01-25 23:46 UTC, jovergaag commented on src/RootStore/UserStore.ts
> +      restrictedEmails &&
Hmm, good point. We are encrypting the response but once it lands those addresses are exposed locally. @macfarlandian Thoughts on whether this is a security concern to send several email addresses in the network response?

2021-01-26 00:03 UTC, jovergaag commented on src/RootStore/UserStore.ts
> +      restrictedEmails &&
I guess, it this does seem problematic, the solution is to add a queryString to the URI which has the email address, or make it a POST request and add the email address to the body and add the filtering to the BE such that the API responds with the restricted district ID string.

2021-01-26 00:38 UTC, macfarlandian commented on src/RootStore/DataStore/BaseDataStore.js
> +          tenantId: this.rootStore.currentTenantId,
FWIW, if this is only about making sure this reacts to changes in `currentTenantId`, it might be better to [use `reaction`](https://mobx.js.org/reactions.html#reaction) instead of `autorun` and reference `currentTenantId` in the data function. You could achieve the same result with less indirection

2021-01-26 00:38 UTC, macfarlandian commented on src/RootStore/TenantStore.js
> +      setCurrentTenantId: action,
this shouldn't be necessary with `makeAutoObservable`?

2021-01-26 00:38 UTC, macfarlandian commented on src/RootStore/UserStore.ts
> +      restrictedEmails &&
it does seem ... questionable? In practical terms I am not sure if it's exposing information to anyone who doesn't already have it (i.e. because it's their colleague's email address) but I think if we can avoid it we probably should. This may just be a hard compliance issue also but that is a question for @jessex

2021-01-26 00:38 UTC, macfarlandian commented on src/RootStore/__tests__/UserStore.test.ts
> +        expect.any(Function)
I think you can do something like `jest.Mock<RootStore>` when you typecast the mock object and it will pick up the type definition of the thing it's mocking?

2021-01-26 15:04 UTC, daschi commented on src/RootStore/DataStore/BaseDataStore.js
> +      if (userStore && !userStore.userIsLoading) {
Yeah, but if the restricted district is not loaded yet by the time the DataStore fetches data, then the first fetch on page load will use the default filters which includes all districts. That'll fetch all of the districts on page load, and then when the filter is updated with the restricted district, it will do a 2nd fetch for just the restricted data. I think we would only want the client to fetch the data with the restricted district filter on.

2021-01-26 17:38 UTC, jovergaag commented on src/RootStore/DataStore/BaseDataStore.js
> +      if (userStore && !userStore.userIsLoading) {
Weird. In demo mode it does fetch twice, but in dev mode it only fetches once. Investigating...

2021-01-26 19:57 UTC, jovergaag commented on src/RootStore/DataStore/BaseDataStore.js
> +      if (userStore && !userStore.userIsLoading) {
Fixed.

2021-01-26 20:29 UTC, jessex commented on src/RootStore/UserStore.ts
> +      restrictedEmails &&
Thanks for looping me in here, everyone.

After giving this some thought, I think this is close enough to the borderline that we should go with one of Jen's suggested alternatives instead of the current approach. It's not just that you could be seeing your colleagues' email addresses and that in certain hard-to-enumerate scenarios that might be problematic, it's also that if someone were able to somehow get access to this view when they shouldn't have it, this would further escalate their level of access by handing them a set of email addresses for other users. We should avoid building paths of rapid escalation like this, so let's take a different approach.

2021-01-27 00:25 UTC, jovergaag commented on .travis.yml
> +  - yarn test-server
I realized that Travis was only running our client tests, so I added this to run the server tests separately. Since we are running with `--coverage` on the client tests, I did not include it here.

2021-01-27 00:27 UTC, jovergaag commented on src/RootStore/UserStore.ts
> +      restrictedEmails &&
I created a new endpoint called `restrictedAccess`. The `UserStore` makes a POST request and includes the user's email in the body. The response only includes the restricted access object that matches the user's email address, if any.

2021-01-27 19:33 UTC, macfarlandian commented on src/RootStore/UserStore.ts
> +    const endpoint = `${tenantId}/restrictedAccess`;
if `tenantId` can be undefined here, won't this path be invalid?

2021-01-27 19:33 UTC, macfarlandian commented on src/RootStore/__tests__/UserStore.test.ts
> +    });
no error here?

2021-01-27 19:33 UTC, macfarlandian commented on src/RootStore/__tests__/UserStore.test.ts
> +      endpoint = `${tenantId}/restrictedAccess`;
this describe block and the one  below it do not seem to actually be using this endpoint for anything. should we be verifying that it is not called, or something like that?

2021-01-27 21:43 UTC, jovergaag commented on src/RootStore/UserStore.ts
> +    const endpoint = `${tenantId}/restrictedAccess`;
Yes you're right, it should not be undefined. I wrote this before adding the `this.rootStore?.currentTenantId` check in the autorun. Good catch, thank you!

2021-01-27 22:17 UTC, macfarlandian approved these changes

2021-01-28 16:48 UTC, daschi reviewed
I wouldn't want to hold this up much longer, but had a couple other comments that I'll leave up to you to decide! Happy to go with this as it is too.

2021-01-28 16:48 UTC, daschi commented on server/routes/api.js
> +    res.status(400).json({ error: "request is missing userEmail parameter" });
NBD for now, b this could also be defined in the `app.js` endpoint as a validation (similar to how we're doing the param validations). Also `400` is  defined in this file as a constant `BAD_REQUEST`.

2021-01-28 16:48 UTC, daschi commented on server/routes/api.js
> +      (result) => {
I wonder if instead of making the `cacheResponse` more complicated, whether it would be better to define another fetch function that wraps `fetchMetrics` for this particular case. Something like `fetchRestrictedDistricts` that would call `fetchMetrics` and then modify the results before passing it to the cache.

2021-01-28 19:42 UTC, jovergaag commented on server/routes/api.js
> +      (result) => {
Great suggestion. I like it much better this new way!

2021-01-28 19:58 UTC, daschi approved these changes
⭐ ⭐ ⭐

2021-01-28 21:41 UTC, merged