[API] Move filters to a shared directory and create filtered subset files & metadata dimensions
Recidiviz/pulse-dashboard pull request #728
Opened 2021-01-28 23:28 UTC by daschi

## Description of the change

This adds a shared directory `shared-filters` (name TBD -- I think we should probably name this something else, but wanted to get something up for review!) which is added via npm as a local path dependency. This is so the frontend can require this shared code since CRA does not allow imports from outside the `src/` directory. 

The shared functionality that's been moved out of the frontend includes:

- `filterOptimizedDataFormat` - Takes an unflattened matrix (2d array) and returns an array of filtered objects
- `dataFilters` - The boolean checks for filters, exports `matchesAllFilters` and `matchesTopLevelFilters`
- `optimizedFormatHelpers` - Exports the helpers for working with the unflattened and flattened matrix

There's still a lot of TODOs I would like to get to:

- [ ] Add JSDOCs for all the shared functions and the new server helpers
- [ ] Add tests for the shared-filters functions
- [ ] Add tests for the server side filtering helpers (`transformFilters`, `applyFilters`)
- [ ] Add the same functionality to the `refreshCache` endpoint. This PR only adds applying the filters for the `newRevocationFile` endpoint. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #655 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-01-29 17:30 UTC, macfarlandian reviewed
1. what does the development workflow look like with this setup? will changes in the filters package get picked up by either of the dev servers? I know @ohaibbq has been grappling with a similar issue in `case-triage`, maybe there is some convergence between the two solutions that should be considered here
2. that aside, with this one as it is i feel like the `shared filters` directory needs, like, a README or something to explain what is going on here? the folder structure and import strategy are very unintuitive. I am not dead set against it if it works well but ... it makes my brain itch a little

2021-01-29 20:34 UTC, daschi commented
@macfarlandian 

> what does the development workflow look like with this setup? will changes in the filters package get picked up by either of the dev servers? I know @ohaibbq has been grappling with a similar issue in case-triage, maybe there is some convergence between the two solutions that should be considered here

You can run `yarn link` to have the dev server pick up the changes in the filters package, I noticed @ohaibbq added those notes to a ReadMe, which I'll also add here!

> that aside, with this one as it is i feel like the shared filters directory needs, like, a README or something to explain what is going on here? the folder structure and import strategy are very unintuitive. I am not dead set against it if it works well but ... it makes my brain itch a little

Yes that makes sense! I'll add a readme to the filters package. Is there a different folder structure that would be better? I saw some examples where they put each package within a `packages/` directory, but I think that might make it seem like we're using `yarn workspaces` or something similar. I thought this would be an easy way to get it up and running, but let me know if it'd be better to implement the workspaces instead.

2021-01-29 21:32 UTC, macfarlandian commented
no it's fine ... not having a normal root package opens up a whole new can of worms that you probably need to get into. it's just like ... _weird_ to me that a package is inside another package but I don't think it's necessarily _bad_

2021-01-29 23:34 UTC, daschi commented on server/routes/__tests__/api.test.js
>        [newRevocations],
This test is failing and I've spent a lot of time trying to figure out why the `fetchMetrics` shows it's being called again after the file is cached. I don't see this happening locally, but wanted to get this ready for review in the meantime as I work out how to test this better.

2021-02-01 18:29 UTC, macfarlandian commented on server/filters/subsetFileHelpers.js
> +  if (useIndexValue) return subsets[value];
couldn't you just check if `value` is a number instead of using the additional flag? it looks like you are assuming it is a string otherwise

2021-02-01 19:08 UTC, daschi commented on server/core/__tests__/fetchAndFilterNewRevocationFile.test.js
> +    transformFilters.mockImplementationOnce(() => mockTransformedFilters);
Oops, this was leftover and should've been deleted, good catch!

2021-02-01 21:49 UTC, jovergaag requested changes
Cool! I'm glad it worked out to share this code.

I'm very interested to see how this behaves on the API server performance wise. Since we're already seeing memory issues when refreshing the cache, what does this do to the refresh job now that we're adding all of this additional filtering. Also, would be very interested to do some QA on real data once this is in staging!!

2021-02-01 21:49 UTC, jovergaag commented on server/filters/filterHelpers.js
> +          file === "revocations_matrix_distribution_by_district" && DISTRICT,
What would it look like to skip any filter that is in the `INVALID_SUBSET_DIMENSIONS`? That would maybe shave off some time performance wise.

2021-02-01 21:49 UTC, jovergaag commented on server/filters/subsetFileHelpers.js
> +function createFlattenedValueMatrix(filteredDataPoints, subsetMetadata) {
Where did you pull this logic from? Did it also come from /src? Is this also something that could be shared?

2021-02-01 21:49 UTC, jovergaag commented on server/utils/cacheKeys.js
> + * @param {Array[][]} subsetManifest
We lost the @return comment here.

2021-02-01 21:49 UTC, jovergaag commented on shared-filters/README.md
> +Shared filtering functionality for filtering the optimized data formats on the [frontend](https://github.com/Recidiviz/pulse-dashboard/tree/master/src) and the [backend-server](https://github.com/Rec
Thanks for the great documentation!

2021-02-01 21:49 UTC, jovergaag commented on shared-filters/README.md
> +You must first run `yarn link` within the `shared-filters` directory, and then run `yarn link shared-filters` in each of the dependent directories to use the linked package.
What about the build process? If they are linked locally, does that translate into the build?

2021-02-01 21:49 UTC, jovergaag commented on server/filters/applyFilters.js
> +  const { flattenedValueMatrix, metadata } = metricFile[fileKey];
What about the case where the metricFile is not the optimized format, but is .json. As it is written we are never allowing for that possibility. For prod builds we always use the optimized format, but for QA of data runs I often just dump the data into a json and point the API at it for testing. Can we account for that here?

2021-02-01 21:49 UTC, jovergaag commented on src/RootStore/DataStore/BaseDataStore.js
> +  get filters() {
This doesn't seem quite right to me. If this lives in the FiltersStore, why not just access it from there rather than adding the getter here?

2021-02-01 23:25 UTC, daschi commented on server/filters/subsetFileHelpers.js
> +  if (useIndexValue) return subsets[value];
Yes, I think that should work fine!

2021-02-01 23:34 UTC, daschi commented on package.json
> +    "test-filters": "TZ=UTC jest ./shared-filters",
Yeah -- I'll make a new `test` script that runs all three?

2021-02-01 23:36 UTC, daschi commented on server/filters/__tests__/filtersHelpers.test.js
> +        supervision_type: "DUAL",
Yes...I think the FE is passing the values in all caps. We could change that so that everything is lowercase.

2021-02-01 23:36 UTC, daschi commented on server/filters/__tests__/filtersHelpers.test.js
> +        supervision_type: "DUAL",
Oooh I see, supervision_type is not lowercase in the test..will update that!

2021-02-01 23:39 UTC, daschi commented on server/filters/applyFilters.js
> +function applyFilters(fileKey, subsetFilters, metricFile) {
Yeah I like that, makes sense!!

2021-02-01 23:45 UTC, daschi commented on server/filters/subsetFileHelpers.js
> +function createFlattenedValueMatrix(filteredDataPoints, subsetMetadata) {
I wrote this logic (heavily influenced by the filterOptimizedDataFormat function)...do we need it to be shared? I didn't place it in the filters package because I didn't see any place we needed to convert an array of data points to a flattened matrix on the frontend.

2021-02-01 23:50 UTC, daschi commented on shared-filters/README.md
> +You must first run `yarn link` within the `shared-filters` directory, and then run `yarn link shared-filters` in each of the dependent directories to use the linked package.
Yes since it's part of the package.json it should get included in the build

2021-02-01 23:52 UTC, daschi commented on server/filters/applyFilters.js
> +  const { flattenedValueMatrix, metadata } = metricFile[fileKey];
Hmm yes, I didn't realize that dev need. I can add a filtering option for json

2021-02-01 23:55 UTC, daschi commented on src/RootStore/DataStore/BaseDataStore.js
> +  get filters() {
Hmm..I put this here because I wanted to have an easier access to the plain JS filters object for the query string function, whereas in the filters store it's expecting it to be an observable map.

2021-02-02 16:49 UTC, daschi commented on server/filters/applyFilters.js
> +  const { flattenedValueMatrix, metadata } = metricFile[fileKey];
@jovergaag I think this will be a big change, I'm wondering how you would feel about moving this out into a fast follow? I have a WIP branch that I could open as a separate PR.

2021-02-02 16:53 UTC, daschi commented on server/filters/filterHelpers.js
> +          file === "revocations_matrix_distribution_by_district" && DISTRICT,
I'm not sure I understand the question, maybe we can chat more about it on a call?

2021-02-02 16:54 UTC, daschi commented on server/core/__tests__/refreshRedisCache.test.js
> +            expect(applyFilters).toHaveBeenNthCalledWith(
Do you mean because we are filtering it for each possible subset combination?

2021-02-03 21:06 UTC, jovergaag commented
Note: blocked by #641

2021-02-04 22:56 UTC, macfarlandian approved these changes
all good for my silly little issues

2021-02-05 00:26 UTC, jovergaag requested changes
WOW. So much great work in here! Great documentation and tests throughout!

I made a few comments, nothing huge. We need to get that un-nesting PR merged so we can do a good thorough round of QA on this. But all the non-data related QA is looking good!

2021-02-05 00:26 UTC, jovergaag commented on server/filters/createSubset.js
> + * Apply the subset filters to the data in the metric file and return and object keyed by the metric name that includes the
return 'an' object

2021-02-05 00:26 UTC, jovergaag commented on server/core/fetchAndFilterNewRevocationFile.js
> +    (metricFiles) => {
This should only ever be returning a single file right? `metricFiles` might be misleading here.

2021-02-05 00:26 UTC, jovergaag commented on server/filters/subsetFileHelpers.js
> +function createFlattenedValueMatrix(filteredDataPoints, subsetMetadata) {
No this is great, if it didn't come from /src the it doesn't need to be shared! I guess the other place where similar logic likely this lives is in recidiviz-data.

2021-02-05 00:26 UTC, jovergaag commented on src/RootStore/DataStore/CaseTableStore.js
> +      filters: this.filters,
I still don't think I understand why we need to have `filters` on the data stores?

2021-02-05 00:26 UTC, jovergaag commented on src/RootStore/DataStore/CaseTableStore.js
> +    }
It might be nice to pull this out into a function to make it easier to understand why we are doing it. `filterExpandedDataFormat`. Or better yet, maybe just `filterData` and that function can check and call the appropriate filter function?

2021-02-05 00:26 UTC, jovergaag commented on src/RootStore/DataStore/MatrixStore.js
> +    return filterOptimizedDataFormat(data, metadata, dataFilter);
This is in all the stores, maybe we can pull it out somewhere!

2021-02-05 00:26 UTC, jovergaag commented on src/api/metrics/__tests__/fileParser.test.js
> +const VERBOSE_FORMAT = [
This is the first time we're referring to this format as 'VERBOSE'. Maybe 'EXPANDED' for consistency?

2021-02-05 00:26 UTC, jovergaag commented on src/api/metrics/fileParser.js
> +  // If it's verbose json data format that is ready to go, return that.
Oh, I see that you're using verbose here. I think either way is fine, as long as we use consistent naming!

2021-02-05 00:26 UTC, jovergaag commented on src/hooks/__tests__/useChartData.test.js
> +const mockUrl = "us_mo/newRevocations";
We're never hitting this endpoint from `useChartData` now. Should we change this to a ND endpoint?

2021-02-05 00:59 UTC, jovergaag commented on shared-filters/__tests__/dataFilters.test.js
> +const { matchesTopLevelFilters, matchesAllFilters } = require("../dataFilters");
Reminder to add the violationType=ALL and reportedViolations=All filter tests here - they may not make the merge.

2021-02-05 14:52 UTC, daschi commented on server/core/__tests__/refreshRedisCache.test.js
> +            "-charge_category=0-violation_type=0",
Sort of, but not really intentionally, it's because of the ordering in the subset manifest and then these lines in `getAllSubsetCombinations`:

```
        const currentResults = {
          ...item,
          ...previousResults,
        };
```

Since I'm spreading the "previousResults" after the incoming "item", the order ends up being opposite of how it's listed in the subset manifest.

2021-02-05 14:59 UTC, daschi commented on server/filters/__tests__/createSubset.test.js
> +    it("returns a filtered dataset as a flattenedValueMatrix", () => {
Ah yes, this is a typo in the test description, it should say that it returns a filtered dataset in the expanded format. I assumed that was the behavior we wanted with JSON, as the frontend is also set up to work with JSON responses? Let me know if I misunderstood that and whether we should always be caching & sending the flattened value matrix..

2021-02-05 15:10 UTC, daschi commented on src/RootStore/DataStore/CaseTableStore.js
> +      filters: this.filters,
I added it as a convenience method, so that I didn't need to parse the filters like this in every subclass datastore:

`Object.fromEntries(toJS(this.rootStore.filters));`

2021-02-05 15:11 UTC, daschi commented on src/RootStore/DataStore/CaseTableStore.js
> +    }
Yeah, now that this is basically the same across all of the stores I think I could pull it into `BaseDataStore`..

2021-02-05 15:12 UTC, daschi commented on src/RootStore/DataStore/MatrixStore.js
> +    return filterOptimizedDataFormat(data, metadata, dataFilter);
haha great minds -- ignore my previous comment, I see you that the same thing :)

2021-02-05 15:13 UTC, daschi commented on src/api/metrics/__tests__/fileParser.test.js
> +const VERBOSE_FORMAT = [
Yeah I think EXPANDED works better, I'll change all the references to that!

2021-02-08 23:47 UTC, jovergaag approved these changes
Its a beautiful thing.

IE11 is smokin fast! 🔥 🔥 🔥 

You're my hero.

2021-02-08 23:47 UTC, jovergaag commented on server/filters/__tests__/createSubset.test.js
> +    it("returns a filtered dataset as a flattenedValueMatrix", () => {
I think we should always be caching and sending the data in the format that is specified in `FILES_BY_METRIC_TYPE`. So if it listed as .json, it is stored and sent as JSON, if it is .txt it is cached and sent in the optimized format.

2021-02-08 23:47 UTC, jovergaag commented on server/filters/createSubset.js
> + * the `data` key.
Great documentation, thank you!

2021-02-08 23:47 UTC, jovergaag commented on src/RootStore/__tests__/BaseDataStore.test.js
> +      it("sets ignoredSubsetDimensions to the default values", () => {
Thanks :)

2021-02-09 18:44 UTC, merged