Support for violation_type=ALL and reported_violations=ALL values
Recidiviz/pulse-dashboard pull request #743
Opened 2021-02-04 00:10 UTC by jovergaag

## Description of the change

This is in support of a breaking change in the views, and on its own is a breaking change. Must be deployed in production on Tuesday once [#5529](https://github.com/Recidiviz/recidiviz-data/pull/5529), which is the first production deploy since that PR has been merged.

In support or reducing the size of the lantern views, we needed to unnest the `violation_type` and `reported_violations` dimensions, which means adding the 'ALL' values. This changes how the filters are run in the FE, as well as how the Matrix displays active cells. Updates fixtures to reflect this change.

#5529 (mentioned above) also removes all `charge_category` values except for 'ALL' for US_PA, so I disabled the corresponding filter, Case Type, in this PR as well. Issue #711 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #641 and #711

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-04 16:29 UTC, daschi requested changes
I have a couple suggestions/questions! I tested this using the demo_data fixtures and I noticed that the matrix is entering a `loading` state when you de-select one of the reported_violations filters, I think this is because we're missing the `all` values in the matrix cells metadata. Also, wanted to confirm that the fixture data is only a subset of the actual data exported from the query, as it seems the matrix chart is missing a lot of data.

2021-02-04 16:29 UTC, daschi commented on server/core/demo_data/revocations_matrix_cells.metadata.json
> +{"total_data_points": 40000, "value_keys": ["total_revocations"], "dimension_manifest": [["admission_type", ["all", "boards_return", "mental_health", "revocation"]], ["charge_category", ["all", "dome
Should this have the `all` values for reported_violations and violation_type?

2021-02-04 16:29 UTC, daschi commented on src/components/charts/new_revocations/__tests__/helpers.test.js
> +    describe("with violationType = 'ALL' filter applied", () => {
NOTE: we need to add the filtering logic and these tests in #728 as part of the `shared-filters` package after this merges

2021-02-05 01:03 UTC, jovergaag reviewed
I don't know why i always put comments in a review...

2021-02-05 01:03 UTC, jovergaag commented on src/RootStore/__tests__/BaseDataStore.test.js
> +      rootStore.filtersStore.setFilters({
You're right. it looks better now.

2021-02-05 14:37 UTC, daschi commented on server/core/demo_data/revocations_matrix_cells.metadata.json
> +{"total_data_points": 40000, "value_keys": ["total_revocations"], "dimension_manifest": [["admission_type", ["all", "boards_return", "mental_health", "revocation"]], ["charge_category", ["all", "dome
Oooh okay, in that case I think we need to add `violation_type` and `reported_violations` to the `MatrixStore`'s list of `ignoredSubsetDimensions` (though maybe this should be renamed to just `ignoredDimensions` since this file will never have a subset)? That way we don't get a true value for `shouldFetchNewSubsetFile` because the "all" filter value won't be in the matrix store's dimension manifest.

2021-02-05 17:37 UTC, daschi commented on server/core/demo_data/revocations_matrix_cells.metadata.json
> +{"total_data_points": 40000, "value_keys": ["total_revocations"], "dimension_manifest": [["admission_type", ["all", "boards_return", "mental_health", "revocation"]], ["charge_category", ["all", "dome
Another thought I just had -- maybe we should add to the file's metadata whether or not it's a file that has subsets. That way in the frontend & backend we don't need to keep two lists of metrics that expect to have subsets...

2021-02-05 20:24 UTC, jovergaag commented on server/core/demo_data/revocations_matrix_cells.metadata.json
> +{"total_data_points": 40000, "value_keys": ["total_revocations"], "dimension_manifest": [["admission_type", ["all", "boards_return", "mental_health", "revocation"]], ["charge_category", ["all", "dome
Actually - I don't think that what I wrote earlier about the matrix never being able to subset due to the missing ALL values. I think weactually still could subset it - it would just never any all values that end up in that particular subset. Serena and I had decided when designing the new behavior that we never want the Matrix to reload because it would lead to a jarring user experience. I guess I will change the note to reflect that.

The caseload file also doesn't have ALL values - for any dimension. And we may want to subset it at some point.

> Another thought I just had -- maybe we should add to the file's metadata whether or not it's a file that has subsets. That way in the frontend & backend we don't need to keep two lists of metrics that expect to have subsets...
We don't keep that list on the FE do we? I only see it in `subsetManifest`. The FE only cares if the new filter value is in the current dimension manifest - it doesn't know which files are being subsetted and which aren't.

2021-02-05 21:17 UTC, daschi commented on server/core/demo_data/revocations_matrix_cells.metadata.json
> +{"total_data_points": 40000, "value_keys": ["total_revocations"], "dimension_manifest": [["admission_type", ["all", "boards_return", "mental_health", "revocation"]], ["charge_category", ["all", "dome
> We don't keep that list on the FE do we? I only see it in subsetManifest. The FE only cares if the new filter value is in the current dimension manifest - it doesn't know which files are being subsetted and which aren't.


No we don't need that list in the FE I guess...

 I still think we need to add `violation_type` and `reported_violations` as `ignoredSubsetDimensions` for the `MatrixStore` though, otherwise the `shouldFetchNewSubsetFile` will return true for the matrix whenever those values are "all".

2021-02-05 21:18 UTC, jovergaag commented on server/core/demo_data/revocations_matrix_cells.metadata.json
> +{"total_data_points": 40000, "value_keys": ["total_revocations"], "dimension_manifest": [["admission_type", ["all", "boards_return", "mental_health", "revocation"]], ["charge_category", ["all", "dome
Good point about adding to the `ignoredSubsetDimensions` for `MatrixStore`. Done

2021-02-05 21:37 UTC, daschi approved these changes
🍦  looks great! I think I would've passed in the `ignoredSubsetDimensions` as a constructor parameter in the MatrixStore and then assigned it in the BaseDataStore constructor since `ignoredSubsetDimensions` isn't an observable value, but this works too!

2021-02-05 22:22 UTC, jovergaag commented
> 🍦 looks great! I think I would've passed in the ignoredSubsetDimensions as a constructor parameter in the MatrixStore and then assigned it in the BaseDataStore constructor since ignoredSubsetDimensions isn't an observable value, but this works too!

That is what I had done initially, but didn't like it so I changed it to be the action, but I ended up adding it back in based on your comment!

2021-02-05 22:25 UTC, daschi commented on src/RootStore/DataStore/MatrixStore.js
> +      additionalIgnoredSubsetDimensions: [
I think this should be updated to `ignoredSubsetDimensions`

2021-02-05 22:28 UTC, merged