Add button to Profile page to navigate to the dashboard
Recidiviz/pulse-dashboard pull request #753
Opened 2021-02-08 16:56 UTC by daschi

## Description of the change

This PR adds a "Navigate" button below the StateSelector on the Profile page to fix a few issues:

- Users on IE11 were experiencing a delay when trying to navigate after switching tenants because the data loaded on state selection
- Users selecting US_ND were seeing the sidebar before navigating to the dashboard, which may be confusing for new users.
- It was not immediately clear how to navigate to the dashboard after selecting a new tenant from the dropdown

The tenant is not set in the store until the user clicks on the "Navigate" button, which will also navigate the user to the dashboard page. This PR also hides the US_ND sidebar on the profile page.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #703 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-08 23:07 UTC, macfarlandian requested changes

2021-02-08 23:07 UTC, macfarlandian commented on src/components/layouts/__tests__/CoreLayout.test.js
> +    expect(container.firstChild.className).toContain("is-hidden");
could this expect the element `not.toBeVisible()` instead of inspecting the class names?

2021-02-09 00:06 UTC, jovergaag approved these changes

2021-02-09 16:18 UTC, daschi commented on src/components/layouts/__tests__/CoreLayout.test.js
> +    expect(container.firstChild.className).toContain("is-hidden");
@macfarlandian I tried to set this up, but since I added the styles to `pageContainer.scss`, the styles aren't being loaded by the `render` function. I could update this to pass the styles in directly, but not sure I want to make that change for a test. I was curious if you've found a good way to transform & load scss files in the test dom? Maybe this is reason for us to move away from scss and start adding in `styled-components`?

2021-02-09 17:32 UTC, macfarlandian commented on src/components/layouts/__tests__/CoreLayout.test.js
> +    expect(container.firstChild.className).toContain("is-hidden");
oh interesting. yeah I wouldn't worry about it for now then, never mind! (I don't really know of a good solution off teh top of my head, considering you would also have to transpile the SCSS, probably not worth it)

2021-02-09 17:33 UTC, macfarlandian approved these changes

2021-02-09 19:04 UTC, merged