Add Sentry.ErrorBoundary to App and set some context / tags
Recidiviz/pulse-dashboard pull request #755
Opened 2021-02-08 23:41 UTC by daschi

## Description of the change

This PR adds the `@sentry/react` client package and configures a `Sentry.ErrorBoundary` that wraps everything at the `App.js` level and adds some additional context if available:

- currentTenantId
- filters
- user (currently sending entire user object, let me know if we should limit this information)

I want to make note of the types of errors that `ErrorBoundary` does not catch, and we may want to add some more error reporting context in other places (i.e. async requests, etc). 

**Error boundaries do not catch errors for:**
- Event handlers
- Asynchronous code (e.g. setTimeout or requestAnimationFrame callbacks)
- Errors thrown in the error boundary itself (rather than its children)

@jessex Just wanted to ask you security-wise, has Sentry been approved as a vendor and can we send user details in error reports?

This PR also comments out the Segment script for now while we test this PR, but for merging it we will follow this plan so we don't error out on the Segment/Sentry integration:

1. Deploy to staging for testing / QA
2. Uncomment out the Segment script
3. Merge PR
4. Remove the Sentry integration on Segment
5. Deploy to production

Steps 3-5 should happen the same day!

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #589

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-09 00:47 UTC, jovergaag reviewed
I'll have to get the env var from you and do more testing on this tomorrow.

One comment is that I forced a fetch error, and the error that was thrown was a `TypeError` instead of a 404 error. I had meant for this issue to have two requirements 1. Make sure that Sentry is notified in the ErrorBoundary (which this PR is fulfilling) and 2. check the response code after a fetch and throw an error if it is not 200. I'm sorry for not being more clear on that, I had written the issue thinking I would for sure be the one working on it and didn't include enough detail. Do you want to tackle that here or should we create another issue?

2021-02-09 00:47 UTC, jovergaag commented on src/components/Revocations.js
> +            <DistrictFilter />
😍

2021-02-09 00:47 UTC, jovergaag commented on src/components/ErrorBoundary.js
> +  };
YAY DETAILS!

2021-02-09 00:47 UTC, jovergaag commented on src/components/ErrorBoundary.js
> +  };
I don't actually see this coming through in the Sentry Error yet though...

2021-02-09 00:47 UTC, jovergaag commented on src/index.js
> +
Can this be done in `App.js`? We're initializing a bunch of other services there so it might make more sense to keep it in the same place.

2021-02-09 00:47 UTC, jovergaag commented on .env.frontend.example
> +REACT_APP_SENTRY_ENV={SENTRY_ENVIRONMENT}
So we will have a `staging` and a `production` environment such that we can keep track of errors separately. And just ignore errors that are neither of those two environments (like development) so we do away with the inbound/localhost filters. Is that what you had in mind?

Let's deploy this to staging tomorrow and set up the staging environment in Sentry to test out that env setup.

2021-02-09 01:44 UTC, jessex commented
Thanks for checking in, @daschi! In summary, Sentry received an assigned risk level of MEDIUM and was cleared to handle only anonymized user data -- nothing directly identifiable -- because Sentry is explicit that any customer data they receive _may_ be stored or processed outside of the United States. So we should not send any non-anonymized PII to Sentry.

What are you planning to send to Sentry with this PR? Let me know if you'd like to discuss this offline!

2021-02-09 14:39 UTC, daschi commented
@jovergaag Oooh, my mistake! I think the card is pretty clear actually, I just didn't read it closely enough yesterday. I can update this PR with the additional error reporting! I think I was getting that workflow mixed up with this issue https://github.com/Recidiviz/pulse-dashboard/issues/590 -- Is 590 supposed to be for the BE?

@jessex Okay good to know! I was thinking about whether it might be useful to send the user's email address to Sentry in case it can help debug issues, but maybe just sending the state code and filters state is enough. @jovergaag Do you have any thoughts about what additional context we might want to send to sentry for errors that I may have missed?

2021-02-09 14:41 UTC, daschi commented on src/components/ErrorBoundary.js
> +  };
I was testing this out a few different ways yesterday, but you can see the context & tags on this issue that came through:
https://sentry.io/share/issue/cad7ae0c7131417f897116a422002846/

The filters is getting set as context so that will show up under the `Details` tab, and the `currentTenantId` under the `Tags` tab.

2021-02-09 20:51 UTC, jovergaag commented on src/components/ErrorBoundary.js
> +  };
Oh ok now I see them for that issue. Cool 😎

2021-02-09 20:59 UTC, jovergaag commented
> Do you have any thoughts about what additional context we might want to send to sentry for errors that I may have missed?

@daschi We will definitely want to be notified if there is an error fetching the restricted district or if `verifyRestrictedDistrict` fails because that results in the full page being blocked. So maybe send the restricted district if it exists - or in the case of verification not passing - send the malformed district id.

Other than that, the user information would be nice but not necessary given the security concerns.

2021-02-09 23:36 UTC, jovergaag commented
>  Is 590 supposed to be for the BE?

No you're right, I had meant #590 to be for the FE, so that we check `response.ok` in the metrics client. I think what you've done here is great, notifying Sentry in the catch blocks of the data stores. Then we can use #590 to check the response status and send sentry the response code.

2021-02-10 00:18 UTC, jovergaag requested changes
Looking good! I'm so excited about the environments. 

I think there are two things remaining, remove the user information from the scope, and add back the ErrorBoundary around the chart components so that we only lose one chart if there is an error in that specific component.

2021-02-10 00:18 UTC, jovergaag commented on src/components/Revocations.js
> +            <DistrictFilter />
I got all excited about removing these `ErrorBoundary`s But I think we actually want to keep them. When I throw an Error in the Matrix component, we used to see the whole page load correctly except for the Matrix, which would show an error in place of the Matrix saying this chart can't load. Now, I get a full page error.

![Screen Shot 2021-02-09 at 4 10 41 PM](https://user-images.githubusercontent.com/5872651/107445484-60e1b780-6af1-11eb-88ee-ea77dddfd8f3.png)

2021-02-10 00:51 UTC, jovergaag commented
> Error boundaries do not catch errors for:
> Event handlers
> Asynchronous code (e.g. setTimeout or requestAnimationFrame callbacks)
> Errors thrown in the error boundary itself (rather than its children)

I think the last two are probably ok for now. The event handlers is one I've had on my mind for a while. All of our `RevocationsByDimension` chart data is being transformed in a `createGenerateChartData` callback. I just threw an error in the district `createGenerateChartData` and it was never caught - page rendered fine. All the more reason to move that logic into the data stores.

I think those are the only callbacks that look troublesome, at least on the Lantern side of things.

I think we should prioritize issue #702 to move all of the chart logic out of the components into the stores instead of writing code to handle errors specifically in the callbacks. I'll mark #702 for next sprint.

2021-02-10 15:26 UTC, daschi commented on src/components/Revocations.js
> +            <DistrictFilter />
ah yeah that makes sense, okay will add those back!

2021-02-10 16:38 UTC, daschi commented
> No you're right, I had meant #590 to be for the FE, so that we check response.ok in the metrics client. I think what you've done here is great, notifying Sentry in the catch blocks of the data stores. Then we can use #590 to check the response status and send sentry the response code.

@jovergaag Hmm, maybe we can chat about this more today, I didn't add the Sentry.captureException to `callMetricsApi` because I wasn't sure if we needed to capture it both at the fetch level and where we're actually calling it in the DataStore/useChartData try/catch blocks. I assumed it would report two sentry errors for the same exception. Maybe we could just set the tags in the scope at that level? I think we can see the API status code in the issue breadcrumbs already too.

2021-02-11 19:54 UTC, jovergaag approved these changes
👷‍♀️ 🚧

2021-02-11 19:58 UTC, jovergaag commented
When should we do the merge/deploys? I think it would make sense to do it sooner than later so that the remainder of the error reporting issues can leverage the new tooling. Thoughts?

2021-02-11 22:58 UTC, daschi commented
@jovergaag I could do it either right now or early tomorrow morning?

2021-02-11 23:14 UTC, merged