Alexk new chart design for race charts
Recidiviz/pulse-dashboard pull request #761
Opened 2021-02-10 14:59 UTC by AlexK-ino

## Description of the change

- Changed translation files for adding new graphs to the chart
- Changed the appearance of the revocation by race
- Added data from state_race_ethnicity_population.json

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #712 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-10 17:35 UTC, AlexK-ino commented
hi @jovergaag!

I see such a problem that when the master branch is pulled, changed data matrices for charts are picked up?
Is there any other background information I should consider? (Or maybe I just misunderstood)
If there is one, I would be happy to take it into account in solving problems after the pull. 
Thank's

2021-02-11 08:34 UTC, AlexK-ino commented
I noticed that filteredData does not have the specified denominators (revocation_count_all, supervision_count_all) 

Is it necessary for all bars to specify one denominator total_state_population_count?

2021-02-12 01:26 UTC, jovergaag requested changes
Great progress! I'm sorry about the fixtures, two of the columns that you needed were overwritten in a recent change so I pushed up a commit to this branch that should make your life easier!

I put a few comments in there. Another thing that I noticed that I did not comment below is that the "%" is getting cut off from the label on the RH side of the chart if the bar is too long.

![Screen Shot 2021-02-11 at 5 23 53 PM](https://user-images.githubusercontent.com/5872651/107719842-fb76fd80-6c8d-11eb-95da-bc4c6b00f879.png)

Also, the tooltips are always showing the counts from `race=WHITE`. 

Other than that things are looking pretty good! Take a look at those things and I'll do another round of QA.

Thank you!

2021-02-12 01:26 UTC, jovergaag commented on src/RootStore/DataStore/BaseDataStore.js
> +      const { data } = processResponseData(
This can now be `parseResponseByFileFormat`, which removes the need for the `processResponseData` function to be added to the helpers file.

2021-02-12 01:26 UTC, jovergaag commented on src/components/charts/new_revocations/ModeSwitcher.js
> +  mode: PropTypes.string.isRequired,
I think that was an important Prop requirement. Maybe you can add the race values and create a custom prop type in `src/components/charts/propTypes.js`?

2021-02-12 01:26 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsByRace/RevocationsByRace.js
> +        generateChartData={newCreateGenerateChartData(revocationsChartStore)}
We have standardized on this being called `createGenerateChartData`. I think its fine to leave it with that name even though it accepts the additional `statePopulationData` prop!

2021-02-12 01:26 UTC, jovergaag commented on src/components/charts/new_revocations/utils/getCounts.js
> +      if (riskLevel === "STATE_POPULATION") {
We may need to temporarily have a separate `getCounts` function for the gender chart and for the race chart. Eventually they will be able to share this, but until the gender chart is changed to the new design it will need to keep this old version of `getCounts`.

In the new version (so for this new Race chart)` the concept of `riskLevel` no longer exists. The labels are each population count, so instead of `riskLevel` here, maybe `if(population === "STATE_POPULATION")`

2021-02-12 01:26 UTC, jovergaag commented on src/components/charts/new_revocations/utils/getCounts.js
> +      if (riskLevel === "STATE_POPULATION") {
I did notice that the gender chart is broken now...I bet it is because of the changes here!

![Screen Shot 2021-02-11 at 5 20 40 PM](https://user-images.githubusercontent.com/5872651/107719622-84da0000-6c8d-11eb-97fa-d54236323db9.png)

2021-02-12 07:30 UTC, AlexK-ino commented on src/components/charts/new_revocations/BarChartWithLabels/BarChartWithLabels.js
> +import "chartjs-plugin-datalabels";
Yes, Prettier is installed and in use, but for some reason it ignored this import. And unfortunately, I didn't pay attention to it

2021-02-13 00:31 UTC, jovergaag commented
@AlexK-ino We are hoping to get this merged and deployed by Tuesday so I went ahead and pushed up a few commits. This should be good to go now and is ready for review by @daschi.

Also - I am also going to get started on the Gender chart this afternoon so I have assigned it to myself and removed it from the 'High Priority Requests' queue. I think the next issue for you to get started on is #622

Thanks for all of your great work on this! It was a solid foundation that I just put a few finishing touches on!

2021-02-16 16:33 UTC, daschi reviewed
It's looking pretty good! Just had a few comments/questions ⭐

2021-02-16 16:33 UTC, daschi commented on src/components/charts/new_revocations/RevocationsByRace/RevocationsByRace.js
> +        defaultMode="WHITE"
nbd, we might want to save these modes as constants at some point

2021-02-16 16:33 UTC, daschi commented on src/components/charts/new_revocations/BarChartWithLabels/HorizontalBarChartWithLabels.js
> +          datalabels: {
It looks like any percentage 95+ gets cut off from the chart area and we lose the label...I wonder if there's an option to keep that visible, or maybe we need to adjust the chart container size? 

![Screen Shot 2021-02-16 at 11 12 38 AM](https://user-images.githubusercontent.com/5402804/108089721-e9a7a880-7047-11eb-828c-d1bbd7b3ce39.png)

2021-02-16 16:33 UTC, daschi commented on src/components/charts/new_revocations/utils/__tests__/getCounts.test.js
> +    PURPLE: {
🐞 🙏 💜 

also yay tests!

2021-02-16 16:33 UTC, daschi commented on src/components/charts/new_revocations/RevocationsByRace/RevocationsByRace.js
> -        metricTitle={(mode) =>
This is printing console warnings for the expected `metricTitle` in the the `RevocationsByDimensionComponent` and `ExportMenu` components, was intentionally removed?

2021-02-16 16:33 UTC, daschi commented on src/utils/charts/toggles.js
> +  id,
nbd for this PR - I was just curious if these `tooltip` related helpers should be in the `tooltips.js`? What is the difference between `toggles` and `tooltips`?

2021-02-16 17:50 UTC, daschi commented
@jovergaag It looks like @MeloncholyShiro incorporated some of the feedback I had in their branch #768. Would it make sense to update that branch and merge it into this one?

2021-02-16 17:55 UTC, sychang commented on src/components/charts/new_revocations/BarChartWithLabels/HorizontalBarChartWithLabels.js
> +                ? `${parseFloat(value).toFixed(1)}%`
I think showing a percentage is fine since they'll see 8 / 19,460 upon hover. Perhaps what we could do is change this to "<0.1%" (or "<0.05%" if we are rounding) to show things that are very small but non-zero?

2021-02-17 00:57 UTC, jovergaag commented on src/components/charts/new_revocations/utils/__tests__/getCounts.test.js
> +    PURPLE: {
💜

2021-02-17 00:58 UTC, jovergaag commented
@daschi 

> @jovergaag It looks like @MeloncholyShiro incorporated some of the feedback I had in their branch #768. Would it make sense to update that branch and merge it into this one?

I don't think so. This is fairly close to being merged and we have some time pressure to get it deployed so I would rather not have the gender chart PR hold this up.

2021-02-17 01:49 UTC, jovergaag commented on src/components/charts/new_revocations/BarChartWithLabels/HorizontalBarChartWithLabels.js
> +  const translateRaceLabels = translate("raceLabelMap");
Great suggestion. I ended up just changing the data, numerators, and denominators are passed in so that it only has data for the currently active tab to make the chart more generic.

2021-02-17 04:26 UTC, jovergaag commented on src/utils/charts/toggles.js
> +  id,
I had started on this last week but it turned into a pretty big piece of work. I vote that we do this in a separate PR.

2021-02-17 04:27 UTC, jovergaag commented on src/components/charts/new_revocations/BarChartWithLabels/BarChartWithLabels.js
> +      },
Good catch. I pushed up a change for this but then started down a different path that removes `chartjs-plugin-datalabels` since it has become a little unruly in the other charts. I'll continue on that path first thing in the morning to see if it will work out.

2021-02-17 19:30 UTC, jovergaag commented on src/components/charts/new_revocations/BarChartWithLabels/BarChartWithLabels.js
> +      },
I was able to get the data label displaying nicely without the plugin - but then decided to revert it due to [this issue](https://github.com/chartjs/Chart.js/issues/6946) in Chart.js and the suggestion to use plugins rather than the animation solution which I had implemented.

2021-02-17 19:56 UTC, daschi approved these changes
Looks great!! just a small copy note 👍

2021-02-17 19:56 UTC, daschi commented on src/views/tenants/utils/us_mo_translations.js
> +  },
just a small nitpick - wondering if we want to keep "Population" capitalized in all three

2021-02-17 22:11 UTC, jovergaag approved these changes

2021-02-17 22:23 UTC, merged