Kesich/shrink header
Recidiviz/pulse-dashboard pull request #765
Opened 2021-02-12 06:14 UTC by Catacola

## Description of the change

- Collapses the Lantern header bar when scrolling down. 
- Returns the bar when scrolling back up.
- Slims down the filter bar.
- Fixes a bug where the filter chip would slightly change size while scrolling.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #628

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-12 20:22 UTC, jovergaag requested changes
Welcome to Lantern! 🏮  

This looks great, thank you! Just a couple of comments for some small changes.

Also, the shrinking Chip was by design (although admittedly a bit jarring). I showed the new TopBar and shrinking animation to Sonia and she loved it and said to leave the Chip as small rather than shrink it so we're good to go there!

2021-02-12 20:22 UTC, jovergaag commented on src/hooks/usePageLayout.js
> +        if (window.pageYOffset < lastOffset) {
So smooth! 😻

2021-02-12 20:22 UTC, jovergaag commented on yarn.lock
> +"@babel/code-frame@^7.12.13":
What version of node are you on? I'm just curious where all these updates came from. The `.nvmrc` is on 14.15.1 - is that what you were using?

2021-02-12 20:22 UTC, jovergaag commented on src/components/topbar/TopBar.js
> +        "wide-navbar": isWide,
We are slowly trying move all of our classnames to BEM. This might be a great time to refactor these since you're in here! `Topbar--wide` and `Topbar--hidden`

2021-02-18 04:07 UTC, Catacola commented on yarn.lock
> +"@babel/code-frame@^7.12.13":
These changes all no longer registered once I rebased today, so maybe I was riding an update that someone else later entered? Whatever happened, it looks to no longer be an issue.

2021-02-18 14:50 UTC, daschi approved these changes

2021-02-18 17:58 UTC, jovergaag approved these changes
🔹

2021-02-18 18:14 UTC, merged