Add dimension validations on the backend for new revocation files
Recidiviz/pulse-dashboard pull request #766
Opened 2021-02-12 22:26 UTC by daschi

## Description of the change

This PR adds a validation step when fetching files from GCS that will check whether the incoming new revocations files have any invalid or unexpected dimension values. This may happen if there was an issue with generating the data, and could point to having too many data points. The validation does not throw an error if there are values in the expected set that are not in the incoming source files. 

These validations will likely fail first in the `refreshCache` endpoint with the daily cron jobs. @jovergaag is planning to add the Sentry client to the backend to report these failures. 

Before deploying this branch, we will need to upgrade the node version in the gae-staging.yaml to the latest stable version for GAE which is 12. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #663

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-17 17:03 UTC, daschi commented on server/models/metrics/US_MO.js
> +        supervision_type: DEFAULT_SUPERVISION_TYPES.concat(["all"]),
@jovergaag I think we shouldn't have "all" values in the case table, should I open an issue for this?

2021-02-17 17:12 UTC, jovergaag commented on server/models/metrics/US_MO.js
> +        supervision_type: DEFAULT_SUPERVISION_TYPES.concat(["all"]),
@daschi Oh yes, that is a bug. @jjdressel11 had noticed another bug that was causing duplicate rows in the caseload view yesterday afternoon. Maybe she can tackle the two of these together - or maybe they are even related.

2021-02-18 00:00 UTC, jovergaag requested changes
YAY validations. We are close to being able to breathe easier!

Few comments, biggest one is around naming. Definitely open to chatting about it!

2021-02-18 15:00 UTC, daschi commented on server/models/metrics/US_MO.js
> +        supervision_type: DEFAULT_SUPERVISION_TYPES.concat(["all"]),
This will be fixed by adding "EXTERNAL_UNKNOWN" instead of "ALL" for missing values with https://github.com/Recidiviz/recidiviz-data/pull/5887

2021-02-18 15:39 UTC, daschi commented on server/models/BaseMetrics.js
> +// Recidiviz - a data platform for criminal justice reform
I agree models is kind of a stretch here...we could try the collections/resources and see how that reads. The collections would then refer to `BaseMetrics` and `NewRevocationsMetrics`, where `BaseMetrics` is used for several of the collections. The "resources" are then descriptions of the data in the collections.

2021-02-18 16:03 UTC, jjdressel11 requested changes
Very excited about this!

2021-02-18 16:03 UTC, jjdressel11 commented on server/models/metrics/US_PA.js
> +module.exports = {
I tried to poke around your branch locally to understand how this is working, but I very much do not know javascript! However, I think there is too much duplication between these `.../metrics/US_PA.js` and `.../metrics/US_MO.js` files, and it will be unnecessarily tedious to maintain as we add new states and new dimensions. For each filename, the dimension _keys_ are the same between the two states. The only thing that changes between the states are the valid dimension _values_. Can you define all of these file -> dimensions mappings in `server/models/metrics/shared.js`, but have the instantiation of this object require a `state_code` to fetch the valid dimension values for the given state? (So then the only thing in the US_MO and US_PA files would be the definitions of each `DEFAULT_` list.)

2021-02-18 17:17 UTC, daschi commented on src/components/Revocations.js
> +          <>
It removes a console warning that `ErrorBoundary` is expecting 1 child element instead of an array, so this wraps the elements in a fragment.

2021-02-18 17:21 UTC, daschi commented on server/models/metrics/US_PA.js
> +module.exports = {
Yeah that's a good point, I'll try to reduce the duplication here!

2021-02-18 19:35 UTC, jovergaag commented on src/components/Revocations.js
> +          <>
Oh bless you.

2021-02-22 22:11 UTC, jovergaag reviewed
Just two suggestions. I don't feel strongly about either of them so lmk if you like it the way that it is.

2021-02-22 22:11 UTC, jovergaag commented on server/collections/resources/dimensions/index.js
> +const { US_MO_DIMENSIONS } = require("./us_mo");
We are validating the dimension values, not the dimensions. Should this be called `US_MO_DIMENSION_VALUES`?

2021-02-22 22:25 UTC, jovergaag commented on server/collections/resources/getCollections.js
> +          risk_level: dimensions.risk_level,
I missed this the previous review...risk_level doesn't exist on officer view.

2021-02-22 23:09 UTC, jjdressel11 approved these changes
GREAT work on this. Such an exciting step forward.

2021-02-22 23:09 UTC, jjdressel11 commented on server/collections/resources/dimensionValues/us_pa.js
> +const {
So much cleaner !!

2021-02-22 23:09 UTC, jjdressel11 commented on server/collections/resources/index.js
> +  US_DEMO: getCollections(US_MO),
confirming that demo should be `US_MO`?

2021-02-22 23:33 UTC, daschi commented on server/collections/resources/index.js
> +  US_DEMO: getCollections(US_MO),
I chose it arbitrarily instead of creating a default metadata set for US_DEMO. It works with US_MO's values and if we ever need to change the metadata in the demo files to something different, then we could always create a default set for that.

2021-02-22 23:34 UTC, jovergaag approved these changes
✅ 🏁

2021-02-22 23:36 UTC, merged