Fixed arrow display when sorting
Recidiviz/pulse-dashboard pull request #769
Opened 2021-02-15 15:56 UTC by MeloncholyShiro

## Description of the change

Fixed the arrow display when sorting, hopefully picked up the right solution. And you don't have multiple sorting choices

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #727 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-15 16:11 UTC, Wmaileq requested changes

2021-02-15 16:11 UTC, Wmaileq commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  const [toggledField, setToggledField] = useState();
We have this field already defined in `useSort` hook. Don't duplicate the logic.

2021-02-15 16:24 UTC, MeloncholyShiro commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +  const [toggledField, setToggledField] = useState();
Fixed

2021-02-15 16:49 UTC, Wmaileq commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +    field,
Do not need to add extra dependencies. Your `Sortable` button should not know anything about other fields. (right now ALL the buttons will rerender on every `sort.field` change)
You can just move logic from line 51 of `src/components/charts/new_revocations/CaseTable/Sortable.js`
to the line below.

2021-02-15 16:50 UTC, Wmaileq commented on src/components/charts/new_revocations/CaseTable/Sortable.js
> +const Sortable = ({ children, order = null, field, sortField, onClick }) => (
If you are working here, please take care of these inline styles on line 46 and move them to `.Sortable`.

2021-02-15 17:00 UTC, MeloncholyShiro commented on src/components/charts/new_revocations/CaseTable/Sortable.js
> +const Sortable = ({ children, order = null, field, sortField, onClick }) => (
Done

2021-02-15 17:00 UTC, MeloncholyShiro commented on src/components/charts/new_revocations/CaseTable/CaseTable.js
> +    field,
Done

2021-02-16 12:56 UTC, Wmaileq approved these changes

2021-02-16 21:37 UTC, jovergaag approved these changes
I pushed up a commit renaming the Sortable.scss.

This looks great! Thank you @MeloncholyShiro

2021-02-16 21:37 UTC, jovergaag commented on src/components/charts/new_revocations/CaseTable/Sortable.css
> +.Sortable {
In this repo we use `.scss` instead of `.css`.

2021-02-16 22:37 UTC, merged