Load supervision locations into store for the SupervisionLocationFilter
Recidiviz/pulse-dashboard pull request #785
Opened 2021-02-17 23:31 UTC by daschi

## Description of the change

This PR adds the `SupervisionLocationsStore` that will fetch supervision locations from the `supervision_location_ids_to_names` file in the buckets. It transforms the data into filter options for the SupervisionLocationFilter dropdown. 

I've also added these keys to the `*_translations` files which will make it easy for us to specify which values to use for filtering vs display:

`supervisionLocationValueKey` - the key that has the value to use for the filters
`supervisionLocationLabelKey` - the key that has the label for displaying in the filters
`supervisionLocationFilterKey` - the key we want to store the filter value as in the filters object (i.e. `levelOneSupervisionLocation`)

This also fixes a bug in the restricted access where malformed supervision location IDs were not throwing an auth error. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #704 
> Closes #759 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-18 17:57 UTC, jovergaag approved these changes
🔹

2021-02-18 19:05 UTC, jovergaag requested changes
Its working pretty good! Its the basis of a pretty big change so I think we should try to get the naming and organization to a place where we're really comfortable before merging. Let me know if you want to chat about it.

2021-02-18 19:05 UTC, jovergaag commented on src/RootStore/SupervisionLocationsStore.js
> +    const endpoint = `${tenantId}/newRevocations/${this.file}`;
Just doing some QA and it looks like US_PA looks great but US_MO has a bunch of extra IDs that do not exist in any of the metrics rows. I'm checking with Anna about where these IDs came from and if we can get them filtered out in  the pipeline

2021-02-18 19:51 UTC, daschi commented on src/components/charts/new_revocations/ToggleBar/SelectDropdown.js
> +const SelectDropdown = ({
Hmm yeah I wasn't sure if we really needed to, it helped me read the `SupervisionLocationFilter` and understand it more easily. I think it would make sense to move it to `src/controls` if you're okay with keeping it its own component. It could just become a generic component then for dropdowns that can have a (potentially optionally) disabled single value

2021-02-18 19:54 UTC, daschi commented on src/components/__tests__/Revocations.test.js
> +  const SupervisionLocationFilterId = "district-filter";
I think I like number 2 as well as long as the UI label refers to it as `District`. If we end up changing the language on the UI to match Supervision Location, I could see us wanting to change back, but for now `District` is easier to parse and matches the UI so I think that makes sense!

2021-02-19 23:58 UTC, jovergaag approved these changes

2021-02-19 23:58 UTC, jovergaag commented on src/RootStore/DistrictsStore.js
> +  *fetchDistricts({ tenantId }) {
This makes so much more sense to me as `districts` instead of `supervisionLocations`. I think this was the right choice.

2021-02-19 23:58 UTC, jovergaag commented on src/RootStore/TenantStore/tenants.js
> +    [US_PA]: "level_2_supervision_location_external_id",
It will not be too far in the future that we will want to filter on both level_1 and level_2. Will this structure allow us that flexibility?

2021-02-19 23:58 UTC, jovergaag commented on src/components/__tests__/Revocations.test.js
> +  const DistrictFilterId = "district-filter";
nit: I don't think this needed the capital D.

2021-02-19 23:58 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +      .sort(compareStrings("value"));
I think that in order to get this out the door to unblock the data PR - if the state_code is US_MO filter it against the known set of districts that exist in prod right now. Then once we get that location ids file cleaned up we can remove it. Thoughts on that?

2021-02-19 23:58 UTC, jovergaag commented on src/RootStore/__tests__/FiltersStore.test.js
> +    it("clears the filters when switching tenants", () => {
Nice.

2021-02-20 00:19 UTC, merged