Alexk export data on ipad
Recidiviz/pulse-dashboard pull request #795
Opened 2021-02-19 15:18 UTC by AlexK-ino

## Description of the change

Fixed a bug in exporting data from the iPad.

The server/tmp directory is used for temporary files, which are deleted after downloading.

Previously tested possibility to do this without server, but all tried libraries and methods manually led to the same errors (WebKitBlobResource error 1 or Unknown file without extension)

That's why it was decided to use download in this way.

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #622 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-20 01:36 UTC, jovergaag requested changes
Hi @AlexK-ino - the code looks pretty good - but I'm seeing bugs downloading files in Chrome. When trying to download the image file from the Matrix, I get an error. When downloading any other files, the .zip downloads successfully but OS X is not able to open the .zip.

![Screen Shot 2021-02-19 at 5 35 15 PM](https://user-images.githubusercontent.com/5872651/108578818-e119d100-72d8-11eb-8b19-f5ed4372d021.png)

I have not yet tried this on iOS, let's get the traditional browsers working then i'll test on iOS!

Thank you,
Jen

2021-02-20 15:01 UTC, AlexK-ino commented
Hi Jen!
Corrected a bug in Matrix graphics 

On the broken zip files:
I am using OS X. I had this problem once before I created the PR. 
I have not been able to reproduce this problem at this time. If you get it, please send us the file, we will take a look at it. I, unfortunately, don't have it left.
![Снимок экрана 2021-02-20 в 18 00 32](https://user-images.githubusercontent.com/75606430/108600018-88fcd080-73a5-11eb-8f1e-e85299113464.png)

2021-02-23 00:44 UTC, jovergaag commented
@jessex I want to check in with you about the potential security concerns with this implementation. There is a [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=167341) that [downloading files from the client in iOS](https://github.com/eligrey/FileSaver.js/#ios) is not possible until recent versions of iOS. Vlad, Alex, and I all did research into different packages and we came to the same conclusion, the only solution is to upload the file to the server in a tmp file and then download to the client.

This seems like a potential security risk, about the potential for malware to be injected into the payload before being uploaded to the server. Before we continue to work on the kinks in this PR, thoughts on whether it is a non-starter security wise?

2021-02-23 02:04 UTC, jessex commented
@jovergaag can you tell me more about that concern? Where does the data come _from_ before it goes to _our server_? Is it that the user presses the button on their client and then the data goes from their client, up to the server, and then back down to their client? If so, uploads-and-back-downloads for different users are not shared, right? So the concern would be limited to if someone hacked their client to upload malware targeting _our server_, as opposed to targeting a separate user of the app? Want to make sure I understand this clearly before proceeding.

2021-02-24 19:15 UTC, jovergaag commented
> @jovergaag can you tell me more about that concern? Where does the data come _from_ before it goes to _our server_? Is it that the user presses the button on their client and then the data goes from their client, up to the server, and then back down to their client? If so, uploads-and-back-downloads for different users are not shared, right? So the concern would be limited to if someone hacked their client to upload malware targeting _our server_, as opposed to targeting a separate user of the app? Want to make sure I understand this clearly before proceeding.

@jessex The data is coming from the javascript client. When the user presses the 'Export Data' button, the javascript bundles up the blob, then sends it to the server which then responds to the browser with a downloader url for the client to download from directly. iOS seems to not have a mechanism to download a file directly from a browser without trying to open it in a new tab. It can download it from a server via the url, but not from the web app. 

My concern is that the bundle that is created by the javascript could possibly be intercepted and injected with malware before landing on the server. Maybe? It is all handled within the Javascript and encrypted in transit so I believe it will be OK but am not positive.

There are not any [security advisories](https://github.com/expressjs/multer/security/advisories) for Multer which is the package we are using handle the file downloader POST request and responding with the downloader URL. 

This process is only used for iOS, other browsers will download directly from the javascript client.

2021-02-24 19:18 UTC, jessex commented
I think we're okay here, @jovergaag, because the client side code that gets triggered when you click the download button grabs data that had previously been downloaded into _memory_, so to corrupt the blob that's going to be sent back up to the server they would need to somehow corrupt memory/cache in the browser itself. As long as the actual upload back to the server is encrypted via TLS, then I think you can proceed here!

2021-02-25 19:13 UTC, jovergaag commented
@jessex Thank you!

@AlexK-ino I have done some more testing on this branch and the download is working as expected in demo mode, but the unsupported format error is only popping up in dev mode and when deployed to staging. I will do some investigation and push up a commit once I get that working. I'll circle around for your input when I'm finished with that. THANK YOU!

2021-03-02 19:40 UTC, macfarlandian commented on src/api/exportData/exportDataClient.js
> +export default async function exportDataClient(
given its brittleness I kind of wish this function were ... not public, or named differently, or that it would actually throw an error or something for the browsers it is known not to support instead of just failing silently if it were actually to be used incorrectly? i am not totally sure though which, if any, of those options is best here

2021-03-02 19:40 UTC, macfarlandian commented on src/api/exportData/downloadData.js
> +async function downloadZipFile({ files, filename, getTokenSilently }) {
there is a truly miserable amount of prop drilling in this PR in service of this `getTokenSilently` function ... why can't this function retrieve it from the datastore directly?

2021-03-03 00:45 UTC, jovergaag requested changes

2021-03-03 00:45 UTC, jovergaag commented on src/api/exportData/transformCanvasToBase64.js
> +export default transformCanvasToBase64;
I find it a little confusing how files are now split up between exportData and utils/downloads. The only thing actually using an API is exportDataClient. Should we leave that inside of api and move everything else back to downloads? Or is there another reason all of the other formatting/downloading is in api?

2021-03-03 00:45 UTC, jovergaag commented on src/api/exportData/downloadData.js
> +      downloadjs(content, filename);
This is funny...IE11 requires the old download package? Wow what a run around.

2021-03-03 00:45 UTC, jovergaag commented on src/api/exportData/downloadData.js
> +    await exportDataClient(formData, filename, getTokenSilently);
What about desktop Chrome and Firefox and Safari? Do they need to hit the download api? I thought that we could get away with just downloading them directly and only hit the api for mobile?

2021-03-03 14:55 UTC, daschi commented on server/routes/api.js
> +  const protocol = process.env.AUTH_ENV === "development" ? `http` : `https`;
Yeah it was part of it, this was causing the secure origin error, and then there was also the issue of trying to create a new `tmp/` folder on the GAE environment. You can't create a new directory but you can use the existing `/tmp` directory on the server.

2021-03-03 15:07 UTC, daschi commented on server/routes/api.js
> +    /* Checking on Chrome iOS */
No it's only not deleted if the header `upgrade-insecure-requests` is not in the request. I'm not sure why this was added here, so I wasn't sure if I should delete it. I **think** [maybe Chrome sometimes sends an additional request](https://web.dev/fixing-mixed-content/#upgrading-insecure-requests) when downloaded content to ensure security and maybe this is trying to ignore that extra request, but I couldn't reproduce that locally at all. I could remove it and re-deploy and see if there are any issues..

2021-03-03 15:15 UTC, daschi commented on src/api/exportData/downloadData.js
> +async function downloadZipFile({ files, filename, getTokenSilently }) {
Yes that's true...the datastores are only accessible in a react component because of how they're initialized in the `StoreProvider`....is there another way you found to share datastores ? It would be nice if this was just a download data component that we could render wherever we need it, but that felt like a big change to the US_ND dashboard, which I thought we wanted to just leave as is.

2021-03-03 15:16 UTC, daschi commented on src/api/exportData/downloadData.js
> +      downloadjs(content, filename);
I think so? I'll try one more time to make sure I didn't miss something when testing this with the other package..

2021-03-03 15:17 UTC, daschi commented on src/api/exportData/downloadData.js
> +    await exportDataClient(formData, filename, getTokenSilently);
I didn't realize we only wanted to hit the API for mobile...I could try to rearrange this so that's how it's working

2021-03-03 15:19 UTC, daschi commented on src/api/exportData/transformCanvasToBase64.js
> +export default transformCanvasToBase64;
I was trying to pull stuff out of `utils/downloads` because it was confusing me where the actual download was coming from. I really just wanted to try to put it all in one place, so I could put it back into utils/downloads..I guess it isn't really doing anything with an API so it doesn't make sense here.

2021-03-03 15:49 UTC, daschi commented on src/api/exportData/downloadData.js
> +      downloadjs(content, filename);
Ok confirmed that `JsFileDownloader` is not the right tool for downloading zip files on IE11.

2021-03-03 16:03 UTC, daschi commented on server/routes/api.js
> +    /* Checking on Chrome iOS */
Hm okay I was able to recreate this - chrome sends this header on iOS when the user clicks on the download dialog, and if this check isn't here then the server will delete the file before the user has a chance to download it. I'm trying to think of how we can then delete this file after the user has downloaded it...

2021-03-03 16:43 UTC, daschi commented on src/api/exportData/exportDataClient.js
> +export default async function exportDataClient(
I updated this to `exportZipDataOnMobileDevices` and added an error if it's not used for a mobile user - let me know what you think and if that helps.

2021-03-03 17:56 UTC, macfarlandian commented on src/api/exportData/downloadData.js
> +async function downloadZipFile({ files, filename, getTokenSilently }) {
oh yeah I see ... what I have been doing in Spotlight is just initializing the application's root store outside of the Provider and exporting it so I can access it outside of React. Then you'd have to make sure you were always calling these download functions from a reactive context. I don't know whether making that change as part of this would really be worth it?

2021-03-03 19:25 UTC, jovergaag commented on src/api/exportData/downloadData.js
> +    await exportDataClient(formData, filename, getTokenSilently);
We could hit the API for desktop, but it seems to me that if the local download is working on desktop then we should avoid the additional RTT unless absolutely necessary.

2021-03-03 19:27 UTC, jovergaag reviewed
This all looks great! I agree that the downloads directory is a big ball or yarn. Once we get into torch we can work on cleaning it up.

Code looks good, I'm going to hold off on approving until we can get this deployed to staging and tested on all the devices (hopefully this evening).

2021-03-05 15:46 UTC, daschi commented
@sychang and @jovergaag - The path of least resistance that I could find to make the chrome iOS download work for the US_ND dashboard was to also upload it as a zip file. Is that flow okay for mobile devices on the ND dashboard?

2021-03-05 15:54 UTC, sychang commented
Yes!

2021-03-05 18:10 UTC, jovergaag approved these changes
⬇️

2021-03-05 18:13 UTC, merged