mvp-styles
Recidiviz/pulse-dashboard pull request #813
Opened 2021-02-24 08:50 UTC by MeloncholyShiro

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-25 04:06 UTC, Catacola reviewed
Thanks for getting a start on this work. Which issue is this PR for?

2021-02-26 04:38 UTC, Catacola requested changes
Looking good so far. I noticed a small issue with the top corners of the dropdown. I think there's still a border-radius applied to the top corners.

<img width="381" alt="Screen Shot 2021-02-25 at 10 29 42 PM" src="https://user-images.githubusercontent.com/5516210/109255677-1b441080-77ba-11eb-8394-444f430c2d95.png">
<img width="897" alt="Screen Shot 2021-02-25 at 10 38 28 PM" src="https://user-images.githubusercontent.com/5516210/109255719-31ea6780-77ba-11eb-965d-69243a9587b7.png">

2021-02-26 04:38 UTC, Catacola commented on src/components/controls/Select.scss
> +    border-radius: 15px !important;
Are all of the `!important` labels necessary? If they are, that's no problem, but I like to only use this when necessary because it makes debugging future layouts harder.

2021-02-26 17:48 UTC, MeloncholyShiro commented on src/components/controls/Select.scss
> +    border-radius: 15px !important;
> 
> 
> Are all of the `!important` labels necessary? If they are, that's no problem, but I like to only use this when necessary because it makes debugging future layouts harder.

Above in the description of the task, I wrote that react-select is not really friendly with .css / .scss files, and in any case applies its own styles, which can override either more specific (Will look strange), or !important, it is more friendly with css-in-js

2021-03-03 05:51 UTC, Catacola commented on src/components/controls/Select.scss
> +    border-radius: 15px !important;
Got it! That makes much more sense. Thanks!

2021-03-03 07:00 UTC, Catacola requested changes
From a design standpoint, this looks good. However, this change shouldn't clobber the existing dropdowns used in the Lantern views.
<img width="872" alt="Screen Shot 2021-03-03 at 12 01 11 AM" src="https://user-images.githubusercontent.com/5516210/109766352-aad33000-7bbb-11eb-9172-d889b21919da.png">

I believe the best approach is to break this out into its own component instead of setting style flags. We can call it CoreSelect.js

2021-03-03 22:50 UTC, jovergaag commented
> I believe the best approach is to break this out into its own component instead of setting style flags. We can call it CoreSelect.js

I agree that this should become its own component. Maybe we need to start moving the repo to a top level "Core" and "Lantern" directory to house components under. We had tried to implement code splitting to reduce the bundle size (to keep IE happy) but there were so many shared components it didn't help much. If we do end up sharing fewer components, code splitting might end up making sense! We may want to wait for @daschi reorganization PR to decide what to do here.

2021-03-03 22:54 UTC, daschi commented
I agree we should create a separate select component for the core layout. The reorganization PR is up and ready for a review (https://github.com/Recidiviz/pulse-dashboard/pull/855), if we want to continue on this PR to add a new component, we should just make sure it is easy to move to the core/ directory when we need to resolve conflicts.

2021-03-05 07:17 UTC, Catacola commented
Looks good! I'll manage the merges tomorrow when I have time to deal with any conflicts that come up.

2021-03-05 18:18 UTC, Catacola reviewed
This looks good to go. I'll start merging now. Thank you!

2021-03-05 18:18 UTC, Catacola approved these changes

2021-03-05 18:19 UTC, merged