togglebar redesign for further changes
Recidiviz/pulse-dashboard pull request #815
Opened 2021-02-24 15:05 UTC by AlexK-ino

## Description of the change

changed tooglebar.js styles for the new design

## Type of change

- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #792 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-25 03:20 UTC, Catacola requested changes
Hi Alex! Thanks for getting started on this.

There was a mistake on my end. The task linked to this was supposed to be a master task for 3 smaller tasks describing the individual changes needed: 
- #794
- #796
- #797

These should give a much better description of the changes required.

2021-02-25 03:20 UTC, Catacola commented on shared-filters/yarn.lock
> +
It's not clear where these additional packages came from.

2021-02-25 03:20 UTC, Catacola commented on src/components/toggles/ToggleBar.js
> +  backgroundColor: "#F4F5F5",
You can use `$core-background` in `src/assets/styles/spec/settings/baseColors.scss` for this value.

2021-02-25 15:05 UTC, AlexK-ino commented on src/components/toggles/ToggleBar.js
> +  backgroundColor: "#F4F5F5",
Thank you!
I didn't pay attention to the variables

2021-02-25 15:07 UTC, AlexK-ino commented on shared-filters/yarn.lock
> +
Oops, sorry - those are redundant modules, I got rid of them

2021-02-25 15:08 UTC, AlexK-ino commented
@Catacola Yes, I get it now. That's what @MeloncholyShiro  is doing now, and when he's done, we'll merge it.

2021-03-11 06:45 UTC, Catacola commented
@AlexK-ino Thanks for your additional work on this. I pulled much of this together in some separate work and I'll merge yours in there. I'll take the rest of this issue from here. Thanks for bringing it to this point.

2021-03-18 05:42 UTC, closed without merging