Meloncholyshiro move selector
Recidiviz/pulse-dashboard pull request #817
Opened 2021-02-24 17:24 UTC by MeloncholyShiro

## Description of the change

All that you asked in the task I have implemented, but tell me, was it worth it to remove already get? unnecessary components, or leave them? And what to do with the logo, is it worth to attach it separately?

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #791

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-25 04:04 UTC, Catacola requested changes
Thanks for getting a start on this.

When I tried to view the changes, the page threw a js error as noted in a comment.

Additionally, when I loaded the lantern view, the top nav bar was misformatted. Make sure to check those views after modifying these components since they're used in multiple places. Feel free to create new versions or subclasses of these components for these views where needed.

Example of top bar on lantern view:
<img width="930" alt="Screen Shot 2021-02-24 at 10 04 29 PM" src="https://user-images.githubusercontent.com/5516210/109101424-46602e80-76ec-11eb-8be0-b4d89d7b9a7f.png">

2021-02-25 04:04 UTC, Catacola commented on src/components/layouts/CoreLayout.js
> +              {Object.keys(activeOption.pages).map((option) => {
When I try to load this view, I get an error on this line:
> TypeError: Cannot read property 'pages' of undefined

2021-02-25 17:26 UTC, MeloncholyShiro commented on src/assets/styles/spec/components/topbar.scss
> +    width: 100%;
Done

2021-02-25 17:26 UTC, MeloncholyShiro commented on src/components/layouts/CoreLayout.js
> +              {Object.keys(activeOption.pages).map((option) => {
Fixed

2021-02-25 17:29 UTC, MeloncholyShiro commented
> 
> 
> Thanks for getting a start on this.
> 
> When I tried to view the changes, the page threw a js error as noted in a comment.
> 
> Additionally, when I loaded the lantern view, the top nav bar was misformatted. Make sure to check those views after modifying these components since they're used in multiple places. Feel free to create new versions or subclasses of these components for these views where needed.
> 
> Example of top bar on lantern view:
> <img alt="Screen Shot 2021-02-24 at 10 04 29 PM" width="930" src="https://user-images.githubusercontent.com/5516210/109101424-46602e80-76ec-11eb-8be0-b4d89d7b9a7f.png">

Do I need to write the tests? Is it necessary, or will the tests that I already have be enough?

2021-02-26 05:58 UTC, Catacola requested changes
Functionality is looking good so far.

When I load the view up, however, the header bar doesn't span the page:
<img width="941" alt="Screen Shot 2021-02-25 at 11 57 10 PM" src="https://user-images.githubusercontent.com/5516210/109261253-2fd9d600-77c5-11eb-9d96-0086a3368c0e.png">

2021-02-26 05:59 UTC, Catacola commented on src/assets/styles/spec/components/topbar.scss
> +        border-top: 0.25rem solid #25b894;
When repeating color hex strings like this, you should go ahead and make a variable, either local to this file or in a shared file.

2021-02-26 18:07 UTC, MeloncholyShiro commented
> 
> 
> Functionality is looking good so far.
> 
> When I load the view up, however, the header bar doesn't span the page:
> <img alt="Screen Shot 2021-02-25 at 11 57 10 PM" width="941" src="https://user-images.githubusercontent.com/5516210/109261253-2fd9d600-77c5-11eb-9d96-0086a3368c0e.png">

Ops, miss 1 line styles :(

2021-03-01 04:45 UTC, Catacola commented
This is looking good, thanks!

@jovergaag Could you give this a once over as you're much more experienced with the front end than I am?

2021-03-03 23:46 UTC, jovergaag requested changes
Hi @MeloncholyShiro This is looking pretty good!

I found one UI issue, and have a suggestion for how structure the new header. Let me know if you have any questions!

2021-03-03 23:46 UTC, jovergaag commented on src/assets/styles/spec/components/topbar.scss
> +      width: 100%;
Same here - We don't need to set each of these specifically if they are all 100%! What was that offscreen-size doing?

I have noticed that at certain widths, the dropdown gets cut off on the right hand side:

<img width="617" alt="Screen Shot 2021-03-03 at 3 01 06 PM" src="https://user-images.githubusercontent.com/5872651/109884325-9e89ba00-7c31-11eb-86e1-783c10c976d4.png">

2021-03-03 23:46 UTC, jovergaag commented on src/components/layouts/CoreLayout.js
> +        <div className="CoreHeader">
Please move this header into its own component, named `CoreNavigation`. Thank you!

2021-03-03 23:46 UTC, jovergaag commented on src/components/layouts/CoreLayout.js
> +              <Select
Inside of the `CoreNavigation`,  lets wrap this Select in a component as well. Do you have access to https://github.com/Recidiviz/public-dashboard ? We are trying to transition as much of this repo to be similar to that repo as possible to make it easier to developers to switch back and forth between repos and also because maybe eventually one day they will be merged.

What would it look like to add the `NavGroup` and `NavGroupItem` components here?

2021-03-03 23:46 UTC, jovergaag commented on src/components/layouts/__tests__/CoreLayout.test.js
> +import { useLocation } from "react-router-dom";
Please add a copyright header to this file!

2021-03-03 23:46 UTC, jovergaag commented on src/components/layouts/__tests__/CoreLayout.test.js
> +  }),
The `matchPath`  mock on line 16 is no longer used.

2021-03-07 07:14 UTC, Catacola commented
@MeloncholyShiro  @jovergaag I had some free time this weekend, so I rebased and took this one the rest of the way so we can land on Monday.

2021-03-07 07:15 UTC, merged