Add nested sub-office district filter of US_PA
Recidiviz/pulse-dashboard pull request #818
Opened 2021-02-25 00:02 UTC by daschi

## Description of the change

This PR adds the nested filter options for the PA district filter. It also updates the district chart to display the level 1 sub-offices instead of the level 2 district office on the x-axis. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #714 
> Closes #735

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-25 19:06 UTC, jovergaag reviewed
Just a few thoughts. LMK what you think. Overall I love that you're using only `level_1_supervision_location` in the filters and not level_2.

Now that I'm typing that out - do we need to remove level_2 from the `dataFilters`?

2021-02-25 19:06 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +    return this.rootStore.districtsStore.districtKeys;
I keep going back and forth about whether we want these getters on the different stores of if se should just access the the other store's value directly. So for example, should we remove this getter ad just access `this.rootStore.districtsStore.districtKeys` on line 126 and 129. What is the benefit of putting the getter here?

2021-02-25 19:06 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsByDistrict/RevocationsByDistrict.js
> -const CHART_TITLE = "Admissions by district";
I think we should set this based on the translation rather than from the store. That is more consistent with other charts.

2021-02-25 20:15 UTC, daschi commented on src/RootStore/TenantStore/tenants.js
> +  districtFilterValueKey: {
Yeah I am also worried about this, open to suggestions! I'll add comments now to see if it helps...may help us figure out the best way to refactor.

2021-02-25 20:38 UTC, daschi commented on src/RootStore/__tests__/FiltersStore.test.js
> +      US_PA: "levelTwoSupervisionLocation",
Hmm..I actually decided to mock it here so we could test that the logic is working. Do you think it's going to stay this way for the lifetime of the app and so we don't need to test for potentially different filter keys?

2021-02-25 20:38 UTC, daschi commented on src/RootStore/__tests__/FiltersStore.test.js
> +              label: "03 - HARRISBURG",
@sychang wanted to switch it to uppercase while QAing this so that it matches the values in other filters.

2021-02-25 20:42 UTC, daschi commented on src/RootStore/FiltersStore.js
> +    return this.rootStore.districtsStore.districtKeys;
I added it because I thought it was easier to read, but if you think it's adding more code that's not helpful I can remove it!

2021-02-25 20:49 UTC, daschi commented on src/RootStore/FiltersStore.js
> +    return this.rootStore.districtsStore.districtKeys;
Removing it is better -- I removed both the loading & keys and just accessed the districts store directly! thanks :)

2021-02-26 17:53 UTC, jovergaag commented on src/RootStore/__tests__/FiltersStore.test.js
> +              label: "03 - HARRISBURG",
We should have done that formatting in the metric file...oh well.

2021-02-26 19:11 UTC, jovergaag requested changes
I still need to test IE11 and tablet but here are some things to get started on.

2021-02-26 19:11 UTC, jovergaag commented on src/RootStore/TenantStore/tenants.js
> +  districtFilterValueKey: {
I think the comments help a lot.

2021-02-26 19:11 UTC, jovergaag commented on src/RootStore/__tests__/FiltersStore.test.js
> +      US_PA: "levelTwoSupervisionLocation",
I actually like your idea of mocking it here to test that functionality. It might not stay this way forever so smart idea.

2021-02-26 19:11 UTC, jovergaag commented on src/RootStore/__tests__/FiltersStore.test.js
> +      US_PA: "levelTwoSupervisionLocation",
It might be worth a comment though just to make sure that the next person looking at this doesn't think either the test or the implementation is a mistake and try to change it.

2021-02-26 19:11 UTC, jovergaag commented on src/RootStore/utils/districtOptions.js
> +  return `${id} - ${label.toUpperCase().replace(" DO", "")}`;
We should have done this formatting in the metric file too...sigh

2021-02-26 19:11 UTC, jovergaag commented on src/components/charts/new_revocations/RevocationsByDistrict/RevocationsByDistrict.js
> +    const CHART_TITLE = translate("revocationsByDistrictChartTitle");
The new 'Sub-office' label needs a little more room int he LH nav so that it doesn't wrap 

<img width="756" alt="Screen Shot 2021-02-26 at 10 00 44 AM" src="https://user-images.githubusercontent.com/5872651/109344137-2e3efb00-7823-11eb-943e-e93647a19be7.png">
-

2021-02-26 19:15 UTC, daschi commented on src/RootStore/__tests__/FiltersStore.test.js
> +              label: "03 - HARRISBURG",
Ah yes - that's why I added a comment to that formatting issue

2021-02-26 19:26 UTC, daschi commented on src/RootStore/DistrictsStore.js
> +      districtIdToLabel[d[primaryIdKey]] = d[primaryLabelKey];
Ah interesting. This is happening when the currentTenantId has changed - which changes the district keys to use, but the new supervision locations file hasn't been loaded yet, so it is generating the mapping with the MO data using the PA keys...will try to see if I can stop that

2021-02-26 19:34 UTC, jovergaag commented
One more thing.
* I see that the rate line is behind the tooltip. Is there anyway to adjust the z-index on that to put it on top? I know thats not a requirement of this issue but while you're here...

Tablet and I look fine. I found an IE11 bug when selecting a district from the filter but it is in prod so I made a separate bug card for it.

2021-02-26 20:00 UTC, jovergaag submitted a review, later dismissed
I'm getting one giant `undefined` district bar with no other districts. I think the map changes messed things up.
<img width="1121" alt="Screen Shot 2021-02-26 at 11 59 53 AM" src="https://user-images.githubusercontent.com/5872651/109349088-3e0e0d80-782a-11eb-890a-6a916c23470e.png">

2021-02-26 20:03 UTC, jovergaag approved these changes
Amazing! Good job on this very complex problem.

🔍

2021-02-26 20:04 UTC, merged