added dropdown menu
Recidiviz/pulse-dashboard pull request #819
Opened 2021-02-25 15:52 UTC by AlexK-ino

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-26 05:46 UTC, Catacola requested changes
Nice start! The button looks really slick.

One minor thing to note is that the selected label and the dropdown arrow shouldn't move when changing options. Note the distance between the arrow and the edge of the bubble in these two shots:
<img width="219" alt="Screen Shot 2021-02-25 at 11 29 59 PM" src="https://user-images.githubusercontent.com/5516210/109260125-30716d00-77c3-11eb-8973-5eb2e1635b93.png">
<img width="215" alt="Screen Shot 2021-02-25 at 11 29 51 PM" src="https://user-images.githubusercontent.com/5516210/109260127-310a0380-77c3-11eb-9da7-d73adcbce318.png">

Align the top item to instead be in line with the dropdown options. In the example below, "Facilities" should be aligned with the red line.
<img width="215" alt="Screen Shot 2021-02-25 at 11 41 49 PM" src="https://user-images.githubusercontent.com/5516210/109260386-a7a70100-77c3-11eb-992d-5b78facf85b0.png">

The arrow should have the same right margin and the text's left margin.

2021-02-26 12:55 UTC, AlexK-ino commented
Thanks for the comment, yes I corrected the placement!

2021-03-01 04:42 UTC, Catacola commented
The alignment looks better on the drop down.

I see two things to address:
1. When selecting an option from the dropdown, the view does not change.
2. The profile component is not aligned with the right side of the page.
<img width="1783" alt="Screen Shot 2021-02-28 at 10 40 29 PM" src="https://user-images.githubusercontent.com/5516210/109452724-019f0500-7a16-11eb-84e3-0e4dceec2e01.png">

2021-03-02 05:15 UTC, Catacola requested changes
Looking good! Just a few minor changes to note.

2021-03-02 05:15 UTC, Catacola commented on src/assets/styles/spec/components/topbar.scss
>    @include to($breakpoint-md) {
Line 31 (which I can't seem to comment on directly) breaks the right alignment when in a mid-sized view:
<img width="1438" alt="Screen Shot 2021-03-01 at 11 06 10 PM" src="https://user-images.githubusercontent.com/5516210/109600610-fa91f880-7ae2-11eb-9c3d-b2ae48f08a1e.png">

Since we want to set width to 100% no matter what, we can remove the @include clauses here.

2021-03-02 05:15 UTC, Catacola commented on src/components/layouts/CoreLayout.scss
> +        box-shadow: inset 0px -1px 1px rgba(19, 44, 82, 0.3);
Please use rem wherever possible. Our base element size is 16 px. Feel free to round to 1 or 2 decimal points. For example, I would translate 1px as 0.1rem or 0.06rem, depending on which looks better.

2021-03-03 07:05 UTC, Catacola commented
Looks good!

A great followup task would be to add the Methodology page: https://github.com/Recidiviz/pulse-dashboard/issues/824

2021-03-03 07:06 UTC, Catacola approved these changes

2021-03-06 03:31 UTC, merged