Officer chart finishing touches
Recidiviz/pulse-dashboard pull request #831
Opened 2021-02-26 21:24 UTC by jovergaag

## Description of the change

Puts the finishing touches on the officer chart.

* Changes the x-axis labels to pull from `officer_label` - and formats the name correctly
* Only displays agent whose caseload is 10 or greater in the rates chart
* hides the rate line for now on the rates chart
* small styling tweaks
* updated methodology

QA doc here: https://docs.google.com/document/d/1o1mJD0Cbb8B9M-Dt10uWkbPbhzbnSNN3XO9_gQ4bEmQ/edit

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #779 and #812

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-02-26 22:15 UTC, daschi requested changes

2021-02-26 22:15 UTC, daschi commented on src/utils/transforms/labels.js
> +const formatOfficerLabel = (label) => {
This is throwing an error on both pages, I think that with the new data the officer name now has a colon instead of a dash.

2021-03-02 00:20 UTC, jovergaag commented on src/utils/transforms/labels.js
> +const formatOfficerLabel = (label) => {
Hmm, I'm not seeing this, the chart looks fine. Did you refresh your local cache? LMK if you are still seeing this error.

2021-03-02 16:25 UTC, daschi commented on src/utils/transforms/labels.js
> +const formatOfficerLabel = (label) => {
I am still seeing this on US_MO:

![Screen Shot 2021-03-02 at 11 23 54 AM](https://user-images.githubusercontent.com/5402804/109679768-e208f900-7b49-11eb-8d8a-9d6a76eac7ee.png)


and in the data from staging it looks like the officer names have a colon instead of a dash

2021-03-02 16:26 UTC, daschi commented on src/utils/transforms/labels.js
> +const formatOfficerLabel = (label) => {
Although I guess that might not be the issue since it's working fine in US_PA and the names have the same format!

2021-03-02 16:29 UTC, daschi commented on src/utils/transforms/labels.js
> +const formatOfficerLabel = (label) => {
It looks like the culprit is an officer that is missing the officer_label.

2021-03-03 04:20 UTC, jovergaag commented on src/utils/transforms/labels.js
> +const formatOfficerLabel = (label) => {
I still am not seeing this. What filters state are you using that is generating the error in MO? I also don't see any rows in the view where officer_label is null so I'm not quite sure where this is coming from. 🔍

2021-03-03 04:21 UTC, jovergaag commented on src/utils/transforms/labels.js
> +const formatOfficerLabel = (label) => {
@daschi ^^

2021-03-03 16:53 UTC, daschi commented on src/utils/transforms/labels.js
> +const formatOfficerLabel = (label) => {
Hm weird, seems to be working now - but I think we should put a guard here in case it happens again so that the chart doesn't crash... maybe this could just return an empty string or something if label is empty? Or filter the dataset for null officer_labels?

2021-03-03 16:54 UTC, daschi commented on src/utils/transforms/labels.js
> +const formatOfficerLabel = (label) => {
I guess the better solution would be to have this validation on officer_label be on the backend view.

2021-03-03 16:56 UTC, daschi approved these changes
This looks like it's working now! Just a suggestion to maybe guard against possible undefined officer labels so it doesn't crash the chart, and I also noticed a warning from the `PercentRevokedChart` propTypes, `datasets[].backgroundColor` is typed as a func instead of a string, not sure if you'd want to fix that in this PR.

2021-03-04 05:25 UTC, merged