Fix district filter jump bug on IE11
Recidiviz/pulse-dashboard pull request #838
Opened 2021-03-01 18:31 UTC by MeloncholyShiro

## Description of the change

The bug consisted of several things:
1) IE11 does not know what <main> is
2) React + IE11 doesn't know how to dynamically update inline styles

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #827 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-02 05:18 UTC, Catacola commented
Thank you for fixing my broken code. IE11 strikes again!

2021-03-02 05:18 UTC, Catacola approved these changes

2021-03-04 00:10 UTC, jovergaag requested changes
Thank you @MeloncholyShiro ! Couple of classnames notes. Also I noticed that the padding above the profile dropdown disappeared on IE11.

<img width="941" alt="Screen Shot 2021-03-03 at 4 01 07 PM" src="https://user-images.githubusercontent.com/5872651/109889797-e6610f00-7c3a-11eb-84b2-70f8d1164991.png">

2021-03-04 00:10 UTC, jovergaag commented on src/components/Revocations.js
> +          "Revocations__top-65": !hideTopBar,
Hm, these classnames are difficult to understand. Let's just add `Revocations--top-bar-hidden": hideTopBar`.

2021-03-04 00:10 UTC, jovergaag commented on src/components/Revocations.scss
> +  &__top-0 {
So here `Revocations--top-bar-hidden` we set `top: 0`, otherwise we set `top: 65` up in the `.Revocations` block above. Does that work?

2021-03-04 23:18 UTC, jovergaag requested changes
I think you can revert that last commit - it is doing very strange things to the animation. Sorry for leading you astray!

I reverted the commit locally but am still seeing a gap between the filters bar and the top of the window during the scroll in IE11. I think this still needs a bit of work.

![2021-03-04 15 15 29](https://user-images.githubusercontent.com/5872651/110043632-99457180-7cfc-11eb-8c28-1bab63eb85fc.gif)

2021-03-05 00:12 UTC, MeloncholyShiro commented
> I think you can revert that last commit - it is doing very strange things to the animation. Sorry for leading you astray!
> 
> I reverted the commit locally but am still seeing a gap between the filters bar and the top of the window during the scroll in IE11. I think this still needs a bit of work.
> 
> ![2021-03-04 15 15 29](https://user-images.githubusercontent.com/5872651/110043632-99457180-7cfc-11eb-8c28-1bab63eb85fc.gif)

Okay, I'll work on that! I also wanted to ask. should I go through the whole project and remove inline styles and HTML Tags that IE doesn't support, like <main>?

2021-03-08 17:58 UTC, jovergaag commented
@MeloncholyShiro 

> should I go through the whole project and remove inline styles and HTML Tags that IE doesn't support, like < main >?

Not in this PR. I think let's just fix this header bug and I'll create another issue to fix the incompatible IE11 styles. Great idea!

2021-03-08 22:34 UTC, Catacola commented
> I reverted the commit locally but am still seeing a gap between the filters bar and the top of the window during the scroll in IE11. I think this still needs a bit of work.

I think that gap is due to the way I implemented hiding. The filter bar and nav bar are separate elements and they don't share a common parent. The top bar hides and the bottom bar changes it's snap position at a breakpoint or upon scrolling up. However, if we get to the top before the nav bar finished its animation, the filter bar will run into its snap position. The real fix to this will be to move the filter bar up into the nav bar and have that component slide on and off screen as a unit. This should be much easier thanks to Daniela's work splitting up this codebase.

2021-03-18 16:09 UTC, closed without merging