Admission type filter
Recidiviz/pulse-dashboard pull request #850
Opened 2021-03-02 23:21 UTC by jovergaag

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #844, #845, #715

## Checklists

Enables the admission type filter for PA.

To do this it also required the downloads to be re-worked such that the downloaded methodology and filters string in the images such that the filters string only included filters that were enabled per tenant.

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-03 17:21 UTC, daschi requested changes
Mostly naming questions/suggestions! There is this new issue that I see on this branch but not on master - https://github.com/Recidiviz/pulse-dashboard/issues/852

Let me know if you'd like to look into it here, or if you want me to investigate it separately?

2021-03-03 17:21 UTC, daschi commented on src/RootStore/utils/__tests__/getFilters.test.js
> +  fit("outputs all expected admission type", () => {
`fit` => `it`

2021-03-03 17:21 UTC, daschi commented on src/RootStore/FiltersStore.js
> +      filtersString: getFilters(enabledFilters),
These two might be clearer named as `getFiltersDescription` and `getViolationTypeDescription`

2021-03-03 17:21 UTC, daschi commented on src/RootStore/FiltersStore.js
> +  get stringsForDownload() {
How do you feel about calling this `filtersDescriptions` instead ? Open to both names just wanted to throw it out there.

2021-03-03 17:21 UTC, daschi commented on src/utils/downloads/createMethodologyFile.js
> +  const filtersText = filters;
It might be clearer to just name this argument filtersText, otherwise it seems like it could be the filters object

2021-03-03 22:29 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +  get stringsForDownload() {
Love it.

2021-03-04 15:51 UTC, daschi approved these changes
Looks good, just have one style suggestion and a typo.

Also - I noticed on the district chart that the yAxis is still showing floats instead of full integers..I thought that'd been fixed previously? If it's not being worked on somewhere else I could open a quick PR for that one liner...lemme know!

2021-03-04 15:51 UTC, daschi commented on src/RootStore/DataStore/helpers.js
> + * @param {Array} filters.levelOneSupervisionLocation - level_1_supervision_location IDs or "All"
I think this should be `levelTwoSupervisionLocation`

2021-03-04 15:51 UTC, daschi commented on src/RootStore/FiltersStore.js
> +    const enabledFilters = Object.entries(filters).reduce(
If you're calling `Object.fromEntries` and then `Object.entries`, could you just use `toJS(this.filters)` on line 149 to get the filters as a nested array and then use `filters` directly on line 150?

2021-03-04 18:55 UTC, jovergaag commented
> Also - I noticed on the district chart that the yAxis is still showing floats instead of full integers..I thought that'd been fixed previously? If it's not being worked on somewhere else I could open a quick PR for that one liner...lemme know!

It was fixed in the officer chart which just landed so I'll double check that it is fixed once I merge master here. thanks!

2021-03-04 19:09 UTC, jovergaag commented on src/RootStore/FiltersStore.js
> +    const enabledFilters = Object.entries(filters).reduce(
`toJS` returns a map, so I still have get an array of objects from the map. Your suggestion didn't quite work but I tweaked it a bit and think its better now!

2021-03-05 22:51 UTC, merged