Feature/projections reorg
Recidiviz/pulse-dashboard pull request #855
Opened 2021-03-03 22:36 UTC by daschi

## Description of the change

This PR is the first step towards separating the code between the Core and Lantern dashboards so that when we start adding in more views for the Core/Leadership dashboard, it won't affect Lantern. 

There's still a lot of clean up that we could do, but for now I tried to just organize everything in either a `lantern/` directory or a `core/` directory. I tried not to change too much code, but I did move around a lot of functions (and their tests) inside various `utils/` folders so that helper functions that are only used in core or lantern live in those directories. Functions that are used in both were kept within the top level `utils/` folder, and I tried to flatten it as much as possible. I ended up keeping the `utils/downloads` and the `utils/authentication` folders.

Take a look and let me know if you have any ideas or suggestions for how this might be better organized, or if I missed anything!
 
## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #853 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-04 06:13 UTC, Catacola reviewed
It's getting late, so I can't give this the focus it deserves right now, but what I've looked at seems good so far. Thank you!

2021-03-04 06:13 UTC, Catacola commented on src/App.js
> +import UsNdProgrammingExplore from "./core/programming/Explore";
This is going to make life so much easier!

We MAY need to rename these in the future to be more ND specific, but we can cross that bridge when we get there.

2021-03-04 22:36 UTC, jovergaag requested changes
Its easier to just make these notes here rather than trying to find the files so here goes...

- Can we please rename toggles -> filters. I find these directories and component names so incredibly confusing. We can also do that later...just seems like here would be a good place to do it.
- Question in line below about where to put controls that are specific to lantern or core - but that eventually could be shared. Like `MultiSelect` or `SelectDropdown`. I'm not sure what is best but the styles are diverging so much that we might want to just maintain completely separate components which would mean moving them into their appropriate directory. 

Other than that I love it. soooooo much better.

2021-03-05 16:10 UTC, daschi commented on src/controls/MultiSelect/MultiSelect.js
> -import { optionPropType } from "../../propTypes";
Hm good question. This MultiSelect is pretty specific to how the filters and data is set up in lantern, whereas the `Select` component is really just a wrapper around `react-select`. I think we should probably remove most of the styling from the controls directory and make the users of these controls define the styles.  For now I will move `MultiSelect` and `SelectDropdown` to lantern since their interface and use cases are so specific.

2021-03-05 17:50 UTC, Catacola commented on src/controls/MultiSelect/MultiSelect.js
> -import { optionPropType } from "../../propTypes";
https://github.com/Recidiviz/pulse-dashboard/pull/847 breaks out the Core Multiselect into its own component

2021-03-05 18:15 UTC, daschi commented on src/controls/MultiSelect/MultiSelect.js
> -import { optionPropType } from "../../propTypes";
OK - in that case maybe we should move the lantern `MultiSelect` into lantern after #847 rebases from this work?

2021-03-05 19:29 UTC, Catacola commented on src/controls/MultiSelect/MultiSelect.js
> -import { optionPropType } from "../../propTypes";
Works for me!

2021-03-05 19:40 UTC, Catacola approved these changes
Nice change from toggle to filter.
I appreciate the consolidation of utils.
This all looks good to me.

2021-03-05 20:43 UTC, jovergaag approved these changes

2021-03-05 20:43 UTC, merged