Projections route and Spinner
Recidiviz/pulse-dashboard pull request #865
Opened 2021-03-04 23:12 UTC by MeloncholyShiro

## Description of the change

I hope I understood the task correctly. I have implemented a loading circle with animation, and at the same time made a new path, and the item in the side menu Core Layout, not quite understand what I meant by the empty component, so just in case I did not add directly inside the component <PageTemplate>, I would be glad if you correct me :)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #825 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-05 07:23 UTC, Catacola requested changes
Looking very nice!

2021-03-05 07:23 UTC, Catacola commented on src/components/CoreLoadingIndicator.scss
> +    animation: loading-ring 1s cubic-bezier(0.5, 0, 0.5, 1) infinite;
I like the choice of `cubic-bezier`! It's not what I was expecting, but upon seeing it, I think it's a good fit. Thanks!

2021-03-05 07:23 UTC, Catacola commented on src/components/CoreLoadingIndicator.scss
> +    line-height: 24px;
Please convert the `px` to `rem` assuming a element size of 16px.

2021-03-05 07:23 UTC, Catacola commented on src/components/CoreLoadingIndicator.scss
> +$RING-SIZE: 48px;
3rem

2021-03-11 17:40 UTC, daschi commented
@MeloncholyShiro Thank you for your work on this, to keep it moving forward with some other work I'm doing, I'm going to take over this branch and merge it with my other work.

2021-03-11 18:52 UTC, Catacola approved these changes
🔥 Ze 🚀

2021-03-11 19:31 UTC, merged