Alexk methodology page
Recidiviz/pulse-dashboard pull request #888
Opened 2021-03-09 16:02 UTC by AlexK-ino

## Description of the change

> Added a new methodology page

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #824

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-09 16:11 UTC, AlexK-ino commented
@Catacola hello!
I have encountered this situation:
I need to make a smooth scroll on the anchor and the same way that the hash stays in the location, to be able to copy the path. As it turned out, these are mutually exclusive things, or I have not found an alternative yet:

1. I added smooth scrolling with JS, but then the hash does not change
2. If hash changes - page abruptly goes to the desired block and no smoothness

Thanks!
Alexander

2021-03-10 15:56 UTC, AlexK-ino commented
Hello @Catacola!
For some reason, Travis falls down 
Locally, all the specified commands in travis.yml
have no errors. 
I tried specifying the Node version for it, but this does not solve the problem

2021-03-11 06:23 UTC, Catacola commented
The travis failure is due to a git issue. It wasn't seeing a file that was there due to a casing issue. If you pull `feature/core-header-refresh` and rebase on it, the issues should be resolved.

2021-03-11 06:43 UTC, Catacola requested changes
This is looking very promising, thanks! Just a few minor notes besides the rebase.

2021-03-11 06:43 UTC, Catacola commented on src/core/methodology/Methodology.scss
> +      font-family: "Libre Franklin", serif;
Baskerville

2021-03-11 06:43 UTC, Catacola commented on src/assets/styles/spec/components/pageContainer.scss
> +    // padding-left: $collapsed-size;
Please remove

2021-03-12 05:49 UTC, Catacola commented
Looks good! I'll go ahead and add it to our overall feature branch

2021-03-12 05:49 UTC, merged