Alexk topline vitals
Recidiviz/pulse-dashboard pull request #895
Opened 2021-03-11 15:50 UTC by AlexK-ino

## Description of the change

> Description here

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #871 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-12 07:25 UTC, Catacola requested changes
This is off to a good start! Besides a few nits below, the only other thing I noticed is that the text and wreath move by a pixel or two when the card becomes selected. For an extreme example which makes the text wrap, see the Timely Contacts card:
Unclicked:
<img width="302" alt="Screen Shot 2021-03-12 at 1 23 28 AM" src="https://user-images.githubusercontent.com/5516210/110906487-a00e4e80-82d1-11eb-9831-bcf084694537.png">
Clicked:
<img width="309" alt="Screen Shot 2021-03-12 at 1 23 32 AM" src="https://user-images.githubusercontent.com/5516210/110906499-a3a1d580-82d1-11eb-8cfe-a749e9671739.png">

Besides that, if you can please rebase against `feature/vitals` and clean up the git history so we only see your changes, it will make reviewing much easier. Thanks!

2021-03-12 07:25 UTC, Catacola commented on src/core/community/CoreVitalSummaryCard.scss
> +  height: 96px;
Please translate to rem throughout this file except for the shadows.

2021-03-12 07:25 UTC, Catacola commented on src/core/community/CoreVitalSummaryCard.scss
> +      background-color: #a43939;
Whoops, I forgot to give you the alpha channel. Please change this one and its border to `rgba(164, 57, 57, 0.7)`

2021-03-12 07:25 UTC, Catacola commented on src/core/community/CoreVitalSummaryCard.scss
> +      background-image: url("./assets/img/wreath.svg");
The wreath and the greenish background show display when percentage is 95% or more. This logic has it set to show when `status = "GREAT"`

2021-03-12 07:25 UTC, Catacola commented on src/core/community/CoreCommunityVitals.js
> +  ];
We don't need to sort the cards based on percentage or group. They just happened to be ordered that way in the mocks.

2021-03-12 07:48 UTC, AlexK-ino commented on src/core/community/CoreVitalSummaryCard.scss
> +      background-color: #a43939;
Should this solution be in POOR status or NEEDS IMPROVEMENT?
![image](https://user-images.githubusercontent.com/75606430/110908860-7597b200-8320-11eb-8de2-89ea9bffe640.png)

2021-03-12 07:49 UTC, AlexK-ino commented on src/core/community/CoreVitalSummaryCard.scss
> +      background-image: url("./assets/img/wreath.svg");
This style will only be used in a class that includes "great"

2021-03-12 07:53 UTC, AlexK-ino commented on src/core/community/CoreCommunityVitals.js
> +  ];
Oh, I'm sorry. 
I don't fully understand how the data will come in, so I purposely mixed them up in the mock-data so they could be put in the right order at the front.
![image](https://user-images.githubusercontent.com/75606430/110909374-138b7c80-8321-11eb-90e5-b8feb8f499f9.png)
I'll just do them in this order then

2021-03-12 15:36 UTC, Catacola commented on src/core/community/CoreVitalSummaryCard.scss
> +      background-color: #a43939;
You're right. It should be in "NEEDS IMPROVEMENT". Thanks for catching that.

2021-03-12 15:42 UTC, Catacola commented on src/core/community/CoreVitalSummaryCard.scss
> +      background-image: url("./assets/img/wreath.svg");
The idea was the the wreath/green background should be independent of the dark green border used when status="GREAT". This way, we can have a card like the following that has the dark green border but no wreath:
<img width="418" alt="Screen Shot 2021-03-12 at 9 40 30 AM" src="https://user-images.githubusercontent.com/5516210/110962800-fce02800-8316-11eb-9ebc-e4ea0c6299c6.png">

Let's modify the task slightly to add a 5th state: "EXCELLENT". The difference between "GREAT" and "EXCELLENT" is that they both have the dark green border, but "EXCELLENT" also has the green background and the wreath.

2021-03-16 04:15 UTC, Catacola approved these changes
Looks good! I'll make this one small change and land it. Thanks!

2021-03-16 04:15 UTC, Catacola commented on src/core/community/CoreVitalSummaryCard.js
> +  status: PropTypes.oneOf(["POOR", "NEEDS_IMPROVEMENT", "GOOD", "GREAT"])
\+ "EXCELLENT"

2021-03-16 04:21 UTC, merged