Meloncholyshiro vitals caseload table
Recidiviz/pulse-dashboard pull request #905
Opened 2021-03-15 03:04 UTC by MeloncholyShiro

## Description of the change

I've implemented all the functionality I need (I hope), plus a working sort. I used BEM and REM, if you tell me what else needs to be done, I'll be glad. The component itself is ready and works out of the box with the data you gave in the task

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #874 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-18 18:07 UTC, jovergaag requested changes

2021-03-18 18:07 UTC, jovergaag commented on src/core/statewideViewTable.js
> +                        <div
We have a `SortableIcon` component in the lantern dashboard. Maybe that could be pulled out and shared to be used here. Or maybe even the whole `Sortable` component?

2021-03-19 02:07 UTC, Catacola commented
@AlexK-ino Can you make these changes today since Ivan is no longer working on this project? The other issue out should be a trivial change.

2021-03-22 22:05 UTC, daschi commented
@Catacola @jovergaag  This could still use some work updating the styles and typescript types, but I was thinking maybe that can be worked on separate from this PR. Let me know what you think!

2021-03-23 00:29 UTC, jovergaag approved these changes
This looks great!! I made a couple of comments but none of them are show stopping.

🏅

2021-03-23 00:29 UTC, jovergaag commented on src/core/VitalsSummaryTable/VitalsSummaryTable.tsx
> +  const columns = useMemo(
This looks so much better!

2021-03-23 00:29 UTC, jovergaag commented on src/core/VitalsSummaryTable/VitalsSummaryTable.tsx
> +  // TODO: Either convert back to JS or extend the react-table types that are out of date
Eh - I support reverting to JS if react-table is giving us trouble.

2021-03-23 00:29 UTC, jovergaag commented on src/core/community/CoreCommunityVitals.js
> +  const stateName = tenants[currentTenantId].name;
Should `stateName` go on the `tenantStore`?

2021-03-23 00:29 UTC, jovergaag commented on src/core/utils/index.ts
> +export function formatPercent(percentage: number): string {
This could also go in `src/utils/labels.js` where a bunch of other formatters lives. Maybe labels isn't the best name for that file...

2021-03-23 04:15 UTC, Catacola approved these changes
Also minor comments. Looks good otherwise!

2021-03-23 04:15 UTC, Catacola commented on src/core/VitalsSummaryTable/BubbleTableCell.tsx
> +      "VitalsSummaryTable__bubble--90": value > 80 && value < 90,
Missing edge cases. When `value` is 70, 80, or 90, the bubble will be unstyled.

2021-03-23 04:15 UTC, Catacola commented on src/core/VitalsSummaryTable/VitalsSummaryTable.tsx
> +  // TODO: Either convert back to JS or extend the react-table types that are out of date
You can also use the trick I use for semiotic charts to import a package into ts without types:
```js
const ResponsiveXYFrame = require("semiotic/lib/ResponsiveXYFrame") as any;
```

2021-03-23 04:15 UTC, Catacola commented on src/tenants.ts
> +      community: ["explore", "vitals"],
Since you're adding this path back, you can change `enableCoreTabNavigation` back to `true` in `flags.js` to get tabbed navigation back. We can address not showing it if there's only one option with Sonia before launching.

2021-03-23 15:50 UTC, merged