Add filters for time period and gender to the projections dashboard
Recidiviz/pulse-dashboard pull request #925
Opened 2021-03-17 16:50 UTC by daschi

## Description of the change

This is the first step towards adding the filters bar to the projections dashboard. I decided to create a separate `CoreFiltersStore` to manage the filters state instead of following the current core pattern of `useState` in the components. I think this will help us when we transition to using mobx for all of core. 

I only added the filters for `timePeriod` and `gender` for now because those are what are available in the demo data. The only data that will show up in the filters is for timePeriod = 6 months and gender = Male for now. 

I posted a question about the remaining filters that we need to add in the linked issue:

- Legal Status
- Facility
- Custody Level
- Supervision Type
- Supervision Level
- District

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Related to https://github.com/Recidiviz/recidiviz-data/issues/6094

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-17 23:51 UTC, jovergaag requested changes
Just a few things. Making progress!

2021-03-17 23:51 UTC, jovergaag commented on src/RootStore/CoreFiltersStore.ts
> +  timePeriod: timePeriodOptions[4].value,
It might be nice to put a `defaultValue` getter on the `timePeriodOptions` object like we do in Lantern to avoid this index value here. Same for the next line.

2021-03-17 23:51 UTC, jovergaag commented on src/RootStore/CoreFiltersStore.ts
> +  filters: Filters = defaultFilters;
Its not an `observable.map`. Yay we're learning :)

2021-03-17 23:51 UTC, jovergaag commented on src/core/CoreFilterBar.scss
> +        color: #5d747e;
Should we add this to `colors.js`?

2021-03-17 23:51 UTC, jovergaag commented on src/core/CoreFilterBar.tsx
> +          {setGender && gender && (
I wonder if we should be guarding for `gender` and `setGender` in the component instead of on this line? It makes more sense to me to handle an undefined value or an undefined callback inside of the component than in the display logic.

2021-03-17 23:51 UTC, jovergaag commented on src/core/CoreFilterBar.tsx
> +          {setGender && gender && (
same for all of these filters in this component

2021-03-17 23:51 UTC, jovergaag commented on src/core/CoreFilterBar.tsx
> +  metricPeriodFilterOptions?: FilterOption[];
`replaceLa` lol. Maybe we should make an issue to do this in the data platform.

2021-03-17 23:51 UTC, jovergaag commented on src/core/PageProjections/index.tsx
> +  const setFilters = (filterKey: string) => (value: string) => {
Why are you doing it this way instead of accessing the `filtersStore` in the `CoreFilterBar` directly?

2021-03-17 23:51 UTC, jovergaag commented on src/core/PopulationSummaryMetrics/HistoricalSummaryMetrics.tsx
> +  const timePeriodLabel = formatTimePeriodLabel(get(filters, "timePeriod"));
Should this go into a store somewhere? I see the exact same line in `ProjectedSummaryMetrics`

2021-03-17 23:51 UTC, jovergaag commented on src/core/PopulationSummaryMetrics/HistoricalSummaryMetrics.tsx
> +  const timePeriodLabel = formatTimePeriodLabel(get(filters, "timePeriod"));
Once we have the Metrics models - we can put the whole heading on the metric 🎉

2021-03-18 05:42 UTC, Catacola reviewed
This is coming along nicely! I suggest rebasing on master. There are a few styling changes around wrapping the filter bar on narrow screen I think you should pick up and may affect some of your styling.

2021-03-18 05:42 UTC, Catacola commented on src/RootStore/CoreFiltersStore.ts
> +export default class CoreFiltersStore {
From the naming here, is the idea that we will store all filters related to core features here? We already have filters for the existing core views and I can see more filters being adding with new features in the future. I think that's perfectly fine, but if this store is just for population-related things, can we name it as such?

2021-03-18 05:42 UTC, Catacola commented on src/core/CoreFilterBar.scss
> -  }
Thank you for cleaning up my CSS! It looks like you're a few commits behind master. I don't think my changes will conflict, but I did make some small tweaks to this code to make everything play nice on IE11.

2021-03-18 05:42 UTC, Catacola commented on src/core/CoreFilterBar.tsx
> +          {setGender && gender && (
I believe the idea here is that we have a generic FilterBar component which displays any filters we need across the core views in the app. The change to TS required the double guard since we have no way currently to assure that gender is passed if setGender is passed. Now we could do some better type guarding by requiring an object with both `value` and `setter` keys for each filter so TS can guard against only getting just one or the other.

That said, I think we may be trying to cram too many options into this filter bar now. Would it make sense to have a separate filer bar for each view or set of views. E.g. `PopulationFilterBar`, `GoalsFilterBar`, and `CommunityFilterBar`, that all render using a more generic component like this under the hood? If the set of filters are close enough, we could reuse a bar between views, but I think this one may have gotten out of hand.

This change is almost certainly out of score for this diff, but it feel like a nice clean project for April clean up.

2021-03-18 05:42 UTC, Catacola commented on src/core/PageTemplate.js
> +    <div id="mainContent">
This is such a better layout. Thank you!

That said, IE11 doesn't support \<main\> and other semantic tags because it hates fun: https://caniuse.com/?search=main

2021-03-18 18:35 UTC, daschi commented on src/RootStore/CoreFiltersStore.ts
> +export default class CoreFiltersStore {
Hm yeah my original thinking was that this could be expanded to manage the filters on all the views, but until we are ready for that I think it makes sense to name this to be specifically for PopulationProjections

2021-03-18 19:25 UTC, daschi commented on src/core/CoreFilterBar.tsx
> +          {setGender && gender && (
Agree it would be nice to separate it out so that we can get a clearer picture of what each view needs. I think for this PR I will create a more generic wrapper around the filter bar and separate it out, and also use the filters store directly in the component.

2021-03-18 19:26 UTC, daschi commented on src/core/PageProjections/index.tsx
> +  const setFilters = (filterKey: string) => (value: string) => {
The `CoreFilterBar` just has a lot going on in there, but I think the solution here is to create a new filter bar for the population page until we can clean up the other views.

2021-03-18 21:08 UTC, daschi commented on src/core/CoreFilterBar.scss
> +        color: #5d747e;
possibly? I'm not sure - I know soon we want to switch to using the component library for all typography and colors, so for now I am just adding them like this until we can get them from the library.

2021-03-18 21:11 UTC, daschi commented on src/core/CoreFilterBar.tsx
> +  metricPeriodFilterOptions?: FilterOption[];
Created a general filters refactor issue that we can expand on - https://github.com/Recidiviz/pulse-dashboard/issues/930

2021-03-18 21:11 UTC, daschi commented on src/core/CoreFilterBar.tsx
> +  metricPeriodFilterOptions?: FilterOption[];
Oops, realized after I posted this that's not the issue you meant - making another one :)

2021-03-18 21:18 UTC, daschi commented on src/core/PopulationSummaryMetrics/HistoricalSummaryMetrics.tsx
> +  const timePeriodLabel = formatTimePeriodLabel(get(filters, "timePeriod"));
Yeah that would be good...I think it makes sense to move this to the filters store for now..

2021-03-18 22:09 UTC, daschi commented on src/core/CoreConstants.scss
> +$slate-80: rgba(53, 83, 98, 0.8);
This came from a chat with @soniachokshi, I wanted to update the filter title to a color in the design system, so she decided on Slate 80. Let me know what you think about adding the color names here to match the design system, I think that's the direction @ohaibbq is taking in the component library so I was hoping it would make things easier when we switch over to that!

2021-03-18 22:16 UTC, jovergaag requested changes

2021-03-18 22:16 UTC, jovergaag commented on src/core/CoreFilterBar.tsx
> +  metricPeriodFilterOptions?: FilterOption[];
Oh. ok. The normalizing logic is a little hairy. Maybe the issue is just to map the district name to the normalized district name. Or even add a metric file that has this has this mapping that can be requested from the API.

2021-03-18 22:16 UTC, jovergaag commented on src/core/PopulationSummaryMetrics/ProjectedSummaryMetrics.tsx
> +    <MetricsCard heading={`Next ${timePeriodLabel}`} subheading="Projected">
I'm getting a bunch of `Computed value CorePopulationFiltersStore@12.timePeriodLabel is being read outside a reactive context. Doing a full recompute` warnings on the page. This component (and others that use `timePeriodLabel) should be observers.

2021-03-18 22:16 UTC, jovergaag commented on src/core/PopulationSummaryMetrics/index.tsx
> +    .filter(recordMatchesSimulationTag("POLICY_A"))
Should `POLICY_A` this be a constant?

2021-03-19 01:35 UTC, Catacola commented on src/core/PopulationSummaryMetrics/index.tsx
> +    .filter(recordMatchesSimulationTag("POLICY_A"))
So this is a bit of prep for the future. For now, we have one projection based on current policy. In not too long, we will start shipping a set of projections based upon different policy assumptions. At this point, this field will become relevant. Maybe for now, we can change it to "DEFAULT" or "NO_CHANGE" or anything else. I want to make it as easy to understand as possible.

2021-03-19 13:41 UTC, daschi commented on src/core/CoreFilterBar.tsx
> +  metricPeriodFilterOptions?: FilterOption[];
I tried to capture it here: https://github.com/Recidiviz/recidiviz-data/issues/6518

2021-03-19 14:20 UTC, daschi commented on src/core/PopulationSummaryMetrics/index.tsx
> +    .filter(recordMatchesSimulationTag("POLICY_A"))
Will the different policy projections be selected from a filter dropdown?

2021-03-19 16:02 UTC, daschi commented
After chatting with @Catacola on slack, I'm going to update this PR to include this feature: #933

2021-03-19 20:58 UTC, jovergaag approved these changes
🚴‍♀️

2021-03-23 00:08 UTC, jovergaag commented on src/core/routes.ts
> +      return CORE_VIEWS.community;
This feels very cumbersome to me.  Maintaining both constants with the permutations of paths to views might get to be difficult to maintain as the number of tenants and views available to them grows. I don't know what the answer is, it just doesn't sit very well.

My mind thought a `PageStore` that had `view` getter on it would be easier to understand and use, instead of routes. Routes also feels misleading since this just accessing some constants and not doing any routing. But thats just my two cents...i dont feel super strongly about these!

2021-03-23 02:44 UTC, Catacola commented on src/core/utils/filterOptions.ts
> +  { label: "3 months", value: "3" },
3 months shouldn't be an option for population projections, but 2 years should be.

2021-03-23 02:44 UTC, Catacola commented on src/core/PopulationSummaryMetrics/index.tsx
> +    .filter(recordMatchesSimulationTag("POLICY_A"))
> Will the different policy projections be selected from a filter dropdown?

The interface is TBD. This feature is is for V2. We will not allow users to select different policies when we launch. I could just change this tag to `"PROJECTED"` for now for all projected data.

2021-03-23 02:44 UTC, Catacola commented on src/core/utils/filterOptions.ts
> +    width: "7rem",
This one is completely my fault. I made a hack for the width because it was only on some options. Now that it's propagating, should we look into reworking the filter bar so this can be defined via CSS instead of in js? I don't want to slow you down, so just add this issue as a TODO and I'll cover it: https://github.com/Recidiviz/pulse-dashboard/issues/940

2021-03-23 02:44 UTC, Catacola commented on src/core/utils/timePeriod.ts
> +  if (numMonths === 1) return `${months} month`;
Nit, no need for string creation on the fly:
```js
if (numMonths === 1) return "1 month";
```

2021-03-23 02:44 UTC, Catacola commented on src/core/utils/timePeriod.ts
> +  if (numMonths === 12) return `${numMonths / 12} year`;
Ditto
```js
if (numMonths === 12) return "1 year";
```

2021-03-23 02:44 UTC, Catacola commented on src/core/routes.ts
> +      return CORE_VIEWS.community;
I agree that this can spiral out of control soon and feels a bit cumbersome. However, the mapping so far seems like it can be summarized as `"/$view/something" -> $view`. Would it be worth just reducing to that and then special-casing anything the the future.

I'm also not extremely set on one solution now. I'm often happy building something out with the knowledge that it won't scale, but that it works for now. The process of growing the app in other places will sometimes expose the "right" answer in a way we can't see now.

2021-03-23 14:32 UTC, daschi commented on src/core/PopulationSummaryMetrics/index.tsx
> +      // TODO: Remove the check for "all" once fixture data is updated
Yes good idea, captured it here: #941

2021-03-23 14:34 UTC, daschi commented on src/core/routes.ts
> +      return CORE_VIEWS.community;
Yeah I see how it can become cumbersome. I can try to simplify this for now and rename the file to `views`, does that seem better?

2021-03-23 14:49 UTC, daschi commented on src/core/utils/filterOptions.ts
> +  { label: "3 months", value: "3" },
This is for the Explore view filters, it just shows as being newly added because I changed this file to be TypeScript. The filter options used on the projections page is in the `PopulationFilterOptions` object.

2021-03-23 18:27 UTC, jovergaag approved these changes
💹

2021-03-23 19:37 UTC, Catacola approved these changes

2021-03-23 19:44 UTC, merged