Create restrictedDistrict subsets
Recidiviz/pulse-dashboard pull request #934
Opened 2021-03-19 20:12 UTC by jovergaag

## Description of the change

Creates subsets based on restricted district. 
* Adds restricted district t the query params
* Creates a subset, caches the subset and responds to the network request with the data filtered based on the level_1_supervision_location.

TODO:
- [ ] Add restricted district to refreshCache job? - Currently the response time when you first hit the cache with a restricted district param is quite slow. Should we pre-populate the cache for every subset for every district?

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #749

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-22 15:08 UTC, daschi reviewed
Just a few initial thoughts, happy to chat more about this on slack! 

Re: caching all the subsets for the restricted districts, I think we could wait for the restricted access file to be fetched & cached, and then use that to get the unique location IDs that we would need to create subsets for. The restricted access file would only need to be fetched and cached once and then can just be accessed for every file that gets subsetted/cached.

2021-03-22 15:08 UTC, daschi commented on server/utils/cacheKeys.js
> +  if (cacheKeySubset && FILES_WITH_SUBSETS.includes(metricName)) {
I'm not sure it makes sense to check for `cacheKeySubset` after we already de-structure the object on line 129.

2021-03-22 15:08 UTC, daschi commented on server/utils/cacheKeys.js
> +  return appendRestrictedDistrictKey(cacheKey, restrictedDistrict);
Just thinking aloud here...but maybe we can avoid making this code super specific to US_MO needs by storing state-specific subset manifests in the data bucket that can be cached. Then based on the stateCode and the filters that come in the request we can select the subset manifest to use, and there can be one specifically for US_MO that lists all of the supervision locations as their own subsets.

2021-03-22 20:05 UTC, jovergaag commented on server/filters/createSubset.js
> +  const filters = getFiltersByMetricName(metricName, subsetFilters);
Great suggestions!

2021-03-22 20:12 UTC, jovergaag commented on server/filters/createSubset.js
> +      .concat(["level_1_supervision_location"])
Yes!

2021-03-22 20:23 UTC, jovergaag commented on server/filters/subsetFileHelpers.js
> +        subsetFilters[dimensionKey],
Good catch. I had removed it at a point prior to ensuring `level_1_supervision_location` is an array...fixed.

2021-03-22 20:40 UTC, jovergaag commented on server/utils/cacheKeys.js
> +  const { restrictedDistrict } = cacheKeySubset;
No. US_PA should never have a `restrictedDistrict` param, in that case this this object is undefined and the cacheKey is not appended.

2021-03-22 20:43 UTC, jovergaag commented on server/utils/cacheKeys.js
> +  if (cacheKeySubset && FILES_WITH_SUBSETS.includes(metricName)) {
I ended up changing this section a little - hopefully it makes more sense now.

2021-03-22 20:48 UTC, jovergaag commented on server/utils/cacheKeys.js
> +  return appendRestrictedDistrictKey(cacheKey, restrictedDistrict);
I think thats a good idea. That above approach might be a bit complex because some users have a restricted district and others don't - so we would need to add logic around layering the subset dimensions in a way that some subsets have the restrictedDistrict treatment and others don't.

In the spirit of getting this out quickly to move on to the Torch launch, maybe we leave it as is for now and when the second state that requires its own unique `subset_manifest` we can add in the flexibility at that point.

2021-03-22 22:00 UTC, jovergaag commented
@daschi This is ready for another review

> Re: caching all the subsets for the restricted districts, I think we could wait for the restricted access file to be fetched & cached, and then use that to get the unique location IDs that we would need to create subsets for. The restricted access file would only need to be fetched and cached once and then can just be accessed for every file that gets subsetted/cached.

I have been doing some QA with @sychang and we decided that the time investment in warming the cache with the restricted-district subsets is not a priority. The added latency of the BE generating the subset on demand is not significant enough to merit the additional time to make the necessary changes to `refreshRedisCache`.

2021-03-22 22:06 UTC, daschi commented on server/utils/cacheKeys.js
> +  const { restrictedDistrict } = cacheKeySubset;
Ah okay - I think this would cause an error then if we try to destructure a property that doesn't exist on the `cacheKeySubset`

2021-03-23 19:12 UTC, daschi requested changes
There's an issue that I'm seeing on the frontend - if you start with a restricted district on US_MO and then switch with that same user to US_PA, it still makes requests to the API with the restrictedDistrict in the query param and the API response returns 0 data points for all files.

2021-03-23 22:20 UTC, jovergaag commented
> There's an issue that I'm seeing on the frontend - if you start with a restricted district on US_MO and then switch with that same user to US_PA, it still makes requests to the API with the restrictedDistrict in the query param and the API response returns 0 data points for all files.

Good find. Fixed.

2021-03-23 23:54 UTC, daschi approved these changes
A few more questions but not merge-blocking..

2021-03-23 23:54 UTC, daschi commented on .travis.yml
> +  - yarn install --force
We might wanna keep an eye on this as it might make our builds a bit slower

2021-03-23 23:54 UTC, daschi commented on src/RootStore/DataStore/helpers.js
> +      console.error(
Was this causing an error with json demo data?

2021-03-23 23:54 UTC, daschi commented on src/RootStore/DataStore/BaseDataStore.js
> +      this.filters, [this.rootStore.restrictedDistrict],
Why enforce this style?

2021-03-24 22:43 UTC, jovergaag commented on src/RootStore/DataStore/helpers.js
> +      console.error(
It throws an error when using JSON data rather than optimized data - because we don't have the whole `dimension_manifest` for those files, only what can be built from the `subset_manifest`.

2021-03-24 22:48 UTC, jovergaag commented on src/RootStore/DataStore/BaseDataStore.js
> +      this.filters, [this.rootStore.restrictedDistrict],
Changed!

2021-03-24 22:49 UTC, jovergaag commented on .travis.yml
> +  - yarn install --force
I removed the `--force` and re-ran the build on travis, which was successful. But I'm worried that without it anytime there is a change in shared-filters we will have this problem again. Or even on master, will master fail to build?

2021-03-24 23:43 UTC, merged