Add the weekly percent change above vitals chart
Recidiviz/pulse-dashboard pull request #958
Opened 2021-03-26 13:34 UTC by daschi

## Description of the change

This PR adds the 7-day and 28-day percent change above the Vitals chart. These numbers are calculated from the time series data. 

![Screen Shot 2021-03-26 at 9 33 36 AM](https://user-images.githubusercontent.com/5402804/112639172-587ddb80-8e16-11eb-90f6-65e094d78dfd.png)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #945 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-26 20:02 UTC, Catacola approved these changes

2021-03-26 20:02 UTC, Catacola commented on src/core/controls/PercentDelta.tsx
> +type DeltaDirections = keyof typeof deltaDirections;
Genius

2021-03-26 20:10 UTC, jovergaag requested changes

2021-03-26 20:10 UTC, jovergaag commented on src/core/PageVitals/index.tsx
> +const twentyEightDaysAgo = mockTimeSeriesData[0];
Are we certain that the earliest date will always be first? Should we sort it first to be sure?

2021-03-26 20:10 UTC, jovergaag commented on src/core/controls/PercentDelta.tsx
> +const PercentDelta: React.FC<PropTypes> = ({
It would be nice to have a test for this considering the logic in `getDeltaDirection`

2021-03-26 20:50 UTC, daschi commented on src/core/PageVitals/index.tsx
> +const twentyEightDaysAgo = mockTimeSeriesData[0];
I'm not sure how the view is being sorted, but yes we should definitely sort the records by date when they're first transformed from the raw api data.

2021-03-29 19:15 UTC, jovergaag approved these changes
🔽 ⏫

2021-03-29 19:15 UTC, jovergaag commented on src/core/VitalsWeeklyChange/index.tsx
> +  // todo - send a classname to percentdelta to update styles
Did you want to wrap up these TODOs in this PR or is there one that follows?

2021-03-29 19:16 UTC, jovergaag commented on src/core/VitalsWeeklyChange/index.tsx
> +  // todo - send a classname to percentdelta to update styles
NVM - was going commit by commit and found them resolved later!

2021-03-29 19:27 UTC, merged