Fetch vitals data from GCS through API and into FE components
Recidiviz/pulse-dashboard pull request #960
Opened 2021-03-26 18:28 UTC by jovergaag

## Description of the change

Fetches the `vitals_summaries` and `vitals_time_series` data from GCS and serves it on the `/api/:state_code/vitals` endpoint. Fetches vitals data from `PageVitals` and passes it to the vitals components.

Adds fixtures for both metric files. The summaries series includes state level, office level, and officer level data for once those views are enabled.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #6553 and #6555

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-29 13:16 UTC, daschi reviewed
I have a few questions, I think this might be easier to review if it were rebased onto the branch `daschi-945-day-summary` or just rebased onto the updated `feature/vitals` because the chart sizing is a little off. Also, I was wondering about the vitals timeseries data because all of the metric types have the same datapoints, is the view not being exported yet in staging?

2021-03-29 13:16 UTC, daschi commented on src/core/models/VitalsTimeSeriesMetric.ts
> +      parentWeeklyAvg: 100,
Is this value not available yet on the data? Should we just remove it until it's being used?

2021-03-29 18:58 UTC, jovergaag commented on src/core/PageVitals/index.tsx
> +    id: "RISK_ASSESSMENTS",
Yes. I changed CONTACTS to CONTACT as well to keep them all singular.

2021-03-29 18:59 UTC, jovergaag commented on src/core/PageVitals/index.tsx
> +    (d) => d.entityId === currentEntity && d.parentEntityId === d.entityId
Yes, for this PR we are only showing the STATE_DOC view of the vitals page. In my officer view branch I'm setting local state to update the `currentEntity` depending on the view.

2021-03-29 19:05 UTC, jovergaag commented on src/core/PageVitals/index.tsx
> +    parentEntitySummary && getSummaryCards(parentEntitySummary);
It shouldn't ever be undefined, but because of the `summaryCards.find` on line 93, `summaryCards` potentially can be undefined so TypeScript complains about this without the guard.  Definitely open to other ways of approaching this to keep TS happy...

2021-03-29 19:05 UTC, jovergaag commented on src/core/PageVitals/index.tsx
> +    summaryCards && getSummaryDetail(summaryCards, selectedCardId);
Same as above.

2021-03-29 19:07 UTC, jovergaag commented on src/core/models/VitalsTimeSeriesMetric.ts
> +      parentWeeklyAvg: 100,
I was leaving it on there to help with the parent trend line work. But now that I'm looking at the epic it looks like there isn't an issue for that in this sprint so I'll go ahead and remove it!

2021-03-29 19:26 UTC, daschi commented on src/core/PageVitals/index.tsx
> +    parentEntitySummary && getSummaryCards(parentEntitySummary);
Hmm..one way would be to use the `as VitalsSummaryRecord` type assertion in the find, let me know what you think about this:


```ts
function getEntitySummaries(
  vitalsSummaries: VitalsSummaryRecord[],
  currentEntity: string
): {
  parentEntitySummary: VitalsSummaryRecord;
  childEntitySummaries: VitalsSummaryRecord[];
} {
  const parentEntitySummary = vitalsSummaries.find(
    (d) => d.entityId === currentEntity && d.parentEntityId === d.entityId
  ) as VitalsSummaryRecord;
  const childEntitySummaries = vitalsSummaries.filter(
    (d) => d.parentEntityId === currentEntity && d.parentEntityId !== d.entityId
  );

  return { parentEntitySummary, childEntitySummaries };
}
```

2021-03-29 19:32 UTC, jovergaag commented on src/core/PageVitals/index.tsx
> +    parentEntitySummary && getSummaryCards(parentEntitySummary);
Thank you.

2021-03-29 20:09 UTC, daschi commented on src/core/PageVitals/index.tsx
> +          {summaryDetail && (
With the type assertion you can also remove these conditionals on line 176 and 166

2021-03-29 22:03 UTC, daschi commented on server/core/demo_data/vitals_time_series.json
> +{"date": "2021-13-21", "entity_id": "STATE_DOC", "metric": "OVERALL", "value": "77", "avg_7d": "80"}
These "13" dates seem like typos and I think are causing the chart to error on hover, I think there's 12 of them in this file

2021-03-29 23:29 UTC, Catacola approved these changes
Solid work. Thanks!

2021-03-29 23:29 UTC, Catacola commented on src/components/Loading.js
> +  <div className="Loading sweet-loading" style={{ margin: "0 auto" }}>
200 points for Hufflepuff

2021-03-30 13:23 UTC, daschi requested changes
Just wanted to request to update the data file to remove the invalid dates before merging!

2021-03-30 20:20 UTC, daschi approved these changes

2021-03-30 21:05 UTC, merged