Add rolling average trend line to vitals chart
Recidiviz/pulse-dashboard pull request #965
Opened 2021-03-29 18:33 UTC by daschi

## Description of the change

This PR adds a rolling average trendline to the vitals chart based on the values from the `weeklyAvg` property. 

On chart hover, the bar should highlight and the line should display a point! Thanks to @Catacola and @macfarlandian to helping me make that possible 🙏 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #950 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-29 19:28 UTC, jovergaag requested changes
Cool! Nice job. Just a couple of UI polish things.

2021-03-29 19:28 UTC, jovergaag commented on src/core/VitalsSummaryChart/index.tsx
> +            return <circle cx={cx} cy={cy} r={4} fill={styles.indigo} />;
I noticed that the circle is on the right hand side of the bar instead of the middle (as I would have expected from line 82). 
<img width="188" alt="Screen Shot 2021-03-29 at 12 24 50 PM" src="https://user-images.githubusercontent.com/5872651/112889005-ee6d6c80-9089-11eb-8d76-260fdba4d06d.png">

2021-03-29 19:28 UTC, jovergaag commented on src/core/VitalsSummaryChart/index.tsx
> +            return <circle cx={cx} cy={cy} r={4} fill={styles.indigo} />;
Also, sometimes the tooltip hides the datapoint.

<img width="267" alt="Screen Shot 2021-03-29 at 12 26 29 PM" src="https://user-images.githubusercontent.com/5872651/112889235-3b514300-908a-11eb-9a40-242fd96c57d7.png">

2021-03-29 20:35 UTC, daschi commented on src/core/VitalsSummaryChart/index.tsx
> +            return <circle cx={cx} cy={cy} r={4} fill={styles.indigo} />;
I moved the line and the points slightly with -5px, but I'm not sure how to control the tooltip positioning...I tried using the `annotationSettings` for layout but it didn't seem to apply.

2021-03-29 20:56 UTC, macfarlandian commented on src/core/VitalsSummaryChart/index.tsx
> +            interactive: true,
i wonder if you'd be better off leaving this false, it makes for slightly weird hover behavior? the tooltip just kind of moves a little if your mouse moves too close to the point

2021-03-29 20:56 UTC, macfarlandian commented on src/core/VitalsSummaryChart/index.tsx
> +        pieceHoverAnnotation
similarly I wonder if the UX would be a little smoother if instead of this prop you just passed a `column-hover` annotation instead. if theres a big gap between the line and the bar you wind up with kind of a "dead zone" where the chart doesn't respond to hover

2021-03-29 20:56 UTC, macfarlandian commented on src/core/VitalsSummaryChart/index.tsx
> +            return <circle cx={cx} cy={cy} r={4} fill={styles.indigo} />;
I haven't yet figured out a good way to generalize this but there is [some logic in Spotlight](https://github.com/Recidiviz/public-dashboard/blob/master/spotlight-client/src/charts/XHoverController.tsx#L150) to place the tooltip off to the left or right depending on which side has more room ... i'm not sure if it will work as-is in an `OrdinalFrame`, haven't tested it, but might be something to go on here

2021-03-29 22:29 UTC, Catacola reviewed
Looks very nice!

I saw that the dots on hover are a little bit off-center compared to the bars. It looks like the left edge of the circle is centered instead of the center. Maybe adding `transform: translateX(-50%)` to the dots might fix this.
<img width="144" alt="Screen Shot 2021-03-29 at 5 17 13 PM" src="https://user-images.githubusercontent.com/5516210/112907107-e70e8900-90b2-11eb-8eb9-d0912a5d0c40.png">

2021-03-30 13:56 UTC, daschi commented on src/core/VitalsSummaryChart/index.tsx
> +        pieceHoverAnnotation
great suggestion, I think the hover behavior is much better now with column hover

2021-03-30 15:44 UTC, daschi commented
> I saw that the dots on hover are a little bit off-center compared to the bars. It looks like the left edge of the circle is centered instead of the center. Maybe adding transform: translateX(-50%) to the dots might fix this.

@Catacola I tried to align the points better, but am finding it really challenging since the annotation `ordinal-line` doesn't provide coordinates that align with the OR frame coordinates. What I came up with is an estimation of the position, based on the column width and the "middle" position, which I think the value is actually the middle of the column width * 2 for what I think is the voronoi hover area. This works OK with the line transformed left by `-0.9%`, but since the value of `cx` on the point is dependent on a dynamic column width, it starts to stray at much bigger or smaller chart widths.

I considered adding a `pixelColumnWidth`, but that makes the chart unresponsive to chart width changes. 

What I think we need to do is set the `transform` value on the `ordinal-line` `path` svg element equal to the calculation in the `svgAnnotationRules` for `cx`, then I think it would align perfectly and be responsive to changing the chart width. However I didn't find a way yet to make that work..

Let me know what you think of it as it is now and if you want to chat / have any ideas!!

2021-03-30 16:11 UTC, Catacola approved these changes
This look so much better! Thank you! I think this is good enough to at least land, if not launch. I say we let Sonia look at it during review and if changes need to be made, we'll do it then.

2021-03-30 16:11 UTC, Catacola commented on src/core/VitalsSummaryChart/index.tsx
> +            // // Shift the point slightly to the left to center it
Nit: double comment

2021-03-30 17:40 UTC, macfarlandian commented
@daschi I have been poking at this some more, I think it's the fixed `BAR_WIDTH` setting that is wreaking havoc with your positioning here. Semiotic naturally wants to size every bar as a percentage of its column width and place it at the center ... overriding that for the bars forces the points and line out of alignment. If you were to do away with that then `column.middle` would actually mean what it says and stuff should start fitting into place without having to fudge the positioning

2021-03-30 18:40 UTC, daschi commented on src/core/VitalsSummaryChart/VitalsSummaryChart.scss
> +  transform: translate(0, 1rem);
Oh this is leftover, I probably don't need it anymore!

2021-03-30 19:48 UTC, merged