"Office" view of the Vitals Page
Recidiviz/pulse-dashboard pull request #966
Opened 2021-03-30 20:43 UTC by jovergaag

## Description of the change

- Enables the "Office" view of the Vitals Summary Page. The Office view is accessible by clicking the office name in the summary table. 
- adds an optional `:entityId` param to the path such that the URL can be shared 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #961 

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-30 20:47 UTC, jovergaag commented on src/utils/navigation.ts
> +export function convertIdToSlug(id: string): string {
I have confirmed with @caroletouma that the `entity_id` will be in the format `123_OFFICER_JONES` or `OFFICE_A`. Dashes, commas, and periods are being removed from the officer names to generate the id.

2021-03-30 21:13 UTC, Catacola approved these changes
This looks really nice. Thank you!

I assume this PR doesn't update the chart for the office view because we just don't have fake time series data for the offices yet. Can you add a TODO to add that filter to the chart once we get that data, please?

2021-03-30 21:14 UTC, Catacola commented
The base of this diff just changed to `feature/vitals`. Was this intended?

2021-03-30 21:17 UTC, jovergaag commented
> The base of this diff just changed to `feature/vitals`. Was this intended?

Yes - I merged the API branch that it was based off of. I just merged the feature branch so the file diff is up to date now - but the commit history is a bit of a mess. Sorry for that.

2021-03-30 21:18 UTC, jovergaag commented on src/core/PageVitals/helpers.ts
> +      };
Oh you're right, I had worked through a few different options here and didn't clean up once I landed on this. Thanks!

2021-03-30 21:20 UTC, jovergaag commented
> I assume this PR doesn't update the chart for the office view because we just don't have fake time series data for the offices yet. Can you add a TODO to add that filter to the chart once we get that data, please?

I'll just do it here. Will take 2 secs...

2021-03-31 14:11 UTC, daschi requested changes

2021-03-31 14:11 UTC, daschi commented on src/core/PageVitals/helpers.ts
> +    (d) => d.entityId === currentEntityId && d.parentEntityId === d.entityId
I think you want to remove the check here for `d.parentEntityId === d.entityId`, this seems like it'll return `undefined` for the office entity.

2021-03-31 14:11 UTC, daschi commented on src/core/PageVitals/helpers.ts
> +    (d) => d.metric === selectedCardId && d.entityId === currentEntityId
This is currently breaking the page because we don't have this data in the bucket yet. Should we wait to merge this until that's being exported (or use mock data in the meantime)?

2021-03-31 14:11 UTC, daschi commented on src/core/VitalsSummaryTable/VitalsSummaryTable.tsx
> +            Header: toTitleCase(entityType),
I think the link is missing the hover style here:
 
<img width="186" alt="Screen Shot 2021-03-31 at 10 07 09 AM" src="https://user-images.githubusercontent.com/5402804/113157401-dc660800-9208-11eb-90b6-e401ba667ef4.png">

2021-03-31 14:11 UTC, daschi commented on src/core/PageVitals/index.tsx
>          </div>
The state name is still at the top instead of the office name, was that because you're planning to do that as part of the breadcrumbs work?

<img width="164" alt="Screen Shot 2021-03-31 at 10 09 11 AM" src="https://user-images.githubusercontent.com/5402804/113157707-251dc100-9209-11eb-9f32-27147154b111.png">

2021-03-31 14:11 UTC, daschi commented on src/utils/__tests__/navigation.test.ts
> +describe("getPathsFromNavigation", () => {
Thanks for adding these tests! 🪂

2021-03-31 14:13 UTC, daschi commented on src/core/PageVitals/helpers.ts
> +    (d) => d.entityId === currentEntityId && d.parentEntityId === d.entityId
Oh hm I see in the demo data there's two records per office, one which matching parent/entity ids. What's the reasoning behind having duplicate data ? Seems weird to have a record that has a parent refer to itself as a parent?

2021-03-31 16:14 UTC, Catacola commented on src/core/PageVitals/helpers.ts
> +    (d) => d.metric === selectedCardId && d.entityId === currentEntityId
It runs in demo mode, but you make a good point.

2021-03-31 18:56 UTC, jovergaag commented on src/core/PageVitals/helpers.ts
> +    (d) => d.entityId === currentEntityId && d.parentEntityId === d.entityId
The convention is that if `d.parentEntityId === d.entityId` then that row is the summary row used for the cards, otherwise it is used in the table. I'll add a comment to that effect.

2021-03-31 19:31 UTC, jovergaag commented on src/core/PageVitals/helpers.ts
> +    (d) => d.metric === selectedCardId && d.entityId === currentEntityId
Try it now. I put the demo data jsons into the bucket.

2021-03-31 19:42 UTC, jovergaag commented on src/core/VitalsSummaryTable/VitalsSummaryTable.tsx
> +            Header: toTitleCase(entityType),
Great catch.

2021-03-31 19:42 UTC, jovergaag commented on src/core/PageVitals/index.tsx
>          </div>
Yes exactly.

2021-04-01 13:40 UTC, daschi commented on src/core/PageVitals/helpers.ts
> +    (d) => d.entityId === currentEntityId && d.parentEntityId === d.entityId
Does the the non-summary row have different data?

2021-04-01 13:43 UTC, daschi approved these changes
awesome!

2021-04-01 17:35 UTC, merged