Copy updates for US_PA Admissions -> Recommitments
Recidiviz/pulse-dashboard pull request #970
Opened 2021-03-30 23:05 UTC by jovergaag

## Description of the change

We are showing board decisions on the PA Lantern dashboard, which represents "recommitments," so saying "Admissions" is causing confusing.

Changed all instances of "Admissions", "Admission", and "Admitted" on the frontend to "Recommitments", "Recommitment", and "Recommitted."

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #957

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-03-31 13:37 UTC, daschi requested changes
I think the filters description for the exported image should also be updated, right now it still formats the filter as "All admission types".

2021-03-31 13:37 UTC, daschi commented on src/RootStore/TenantStore/us_pa_methodology.js
>        header: `What the "Admission count" chart shows`,
Should the headers on lines 56 and 61 be updated to recommitment ?

2021-03-31 13:37 UTC, daschi commented on src/RootStore/TenantStore/us_pa_methodology.js
> +      body: `This chart plots people who were recommitted on a board action to an SCI, CCC, or Contract Facility from parole during the time period selected by the user, according to their most serio
I still see a lot of references to `admission` in this file, do these not need to be updated?

2021-03-31 13:37 UTC, daschi commented on src/lantern/FiltersBar/AdmissionTypeFilter.js
> +    <FilterField label="Recommitment Type">
If this component is only used for PA maybe it should be renamed?

2021-03-31 18:51 UTC, jovergaag commented on src/RootStore/TenantStore/us_pa_methodology.js
>        header: `What the "Admission count" chart shows`,
I missed a bunch. Fixed all of the "Admission" instances that I missed.

2021-03-31 22:05 UTC, jovergaag commented on src/lantern/FiltersBar/AdmissionTypeFilter.js
> +    <FilterField label="Recommitment Type">
I sounds like we want to keep this as "Admission Type" and US_PA "Recommitment Type" is the exception to the rule - even though it is the only one currently (as per the convo in #team-lantern)

2021-03-31 22:40 UTC, jovergaag commented
> I think the filters description for the exported image should also be updated, right now it still formats the filter as "All admission types".

I totally missed this comment. Thanks for bringing it to my attention! Fixed.

2021-04-01 13:36 UTC, daschi approved these changes

2021-04-01 18:17 UTC, merged