Vitals summary breadcrumbs
Recidiviz/pulse-dashboard pull request #974
Opened 2021-03-31 23:55 UTC by jovergaag

## Description of the change

Allows the user a path to find their way back to the state level vitals summary page, from the officer view. To do this, we needed to add `entity_type` onto the `VitalsSummaryRecord` model.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #870

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-04-01 14:17 UTC, daschi requested changes
This is great! It's hard to see if the time series chart is working though because it looks like all of the entities in the demo data have the same values. I wonder if we should randomize those a bit so we can see the chart updating when we change entities. Not a big deal though and we can wait to QA with actual data too!

2021-04-01 14:17 UTC, daschi commented on src/core/VitalsSummaryBreadcrumbs/index.tsx
> +    entityType === ENTITY_TYPES.DISTRICT_LEVEL
I wonder if we will eventually want to have something closer to lantern, like numbered levels (level_1_entity, etc), particularly if other states will have more than these 3 entity types. I think this works well for now, just wanted to bring that question up.

2021-04-01 17:31 UTC, jovergaag commented on src/core/VitalsSummaryBreadcrumbs/index.tsx
> +    entityType === ENTITY_TYPES.DISTRICT_LEVEL
Hmm, good question. Let me think on that a little. We definitely will have the third level (officer), so you're right that maybe we should lay the groundwork for that here.

2021-04-01 18:29 UTC, jovergaag commented on src/core/VitalsSummaryBreadcrumbs/index.tsx
> +    entityType === ENTITY_TYPES.DISTRICT_LEVEL
I think that sticking with the `primary` and `secondary` naming might be more clear because the different entities will appear in the different breadcrumb divs depending on what entity is currently selected. So sometimes state name is in `primary` and other times office is in `primary`. If we try to do something with `level_1` and `level_2` in the breadcrumbs, it might get confusing since that is how the office/sub-office are categorized. So, for example, we might be trying to insert a `level_1` office id into a `level_2` breadcrumb div which is confusing. Does that make sense?

Once we enable more levels, we can just enable the `tertiary` breadcrumb, etc.

Thoughts?

2021-04-01 18:33 UTC, jovergaag commented on src/core/VitalsSummaryBreadcrumbs/index.tsx
> +    entityType === ENTITY_TYPES.DISTRICT_LEVEL
Or did you mean changing to levels for ENTITY_TYPES?

2021-04-01 20:06 UTC, daschi commented on src/core/VitalsSummaryBreadcrumbs/index.tsx
> +    entityType === ENTITY_TYPES.DISTRICT_LEVEL
Oh yeah I meant changing the data that comes through in entity_types, so we're not needing to come up with entity type names that are specific to each state. So instead of "STATE_DOC" it would be like level_1 and "DISTRICT_LEVEL" would be level_2, etc.

2021-04-01 23:21 UTC, jovergaag commented on src/core/VitalsSummaryBreadcrumbs/index.tsx
> +    entityType === ENTITY_TYPES.DISTRICT_LEVEL
OK, so Carole and I talked about it, and we left STATE, and PO because those are so specific and will have very specific roles in the page, but changed district to LEVEL_1_SUPERVISON_LOCATION to be consistent with Lantern. LEVEL_1_SUPERVISION_LOCATION will always be the most fine grain district level, so if there is a sub-office the sub-office will be level_1 and the district will be level_2.

2021-04-01 23:21 UTC, jovergaag commented on src/core/VitalsSummaryBreadcrumbs/index.tsx
> +    entityType === ENTITY_TYPES.DISTRICT_LEVEL
@daschi :)

2021-04-02 14:15 UTC, daschi approved these changes
I like the new entity type naming system, I think it'll be helpful when we have more levels! I just had one question about the entity type case for the table, but this looks good 🥞

2021-04-02 14:15 UTC, daschi commented on src/core/VitalsSummaryTable/VitalsSummaryTable.tsx
> +      return "STATE_DOC";
It should never get STATE here right, since it will never be a child entity?

2021-04-02 17:29 UTC, jovergaag commented on src/core/VitalsSummaryTable/VitalsSummaryTable.tsx
> +      return "STATE_DOC";
yes you're right. I'll remove it

2021-04-02 17:43 UTC, merged