Implement vitals dashboard responsive design
Recidiviz/pulse-dashboard pull request #980
Opened 2021-04-01 21:52 UTC by daschi

## Description of the change

Adds styles for breakpoints at 1366, 1024, 768 for tablet views. 

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #975

## Checklists

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

2021-04-01 22:56 UTC, jovergaag requested changes
Beautiful! IE11 is of course...the problem child. 😈

2021-04-01 22:56 UTC, jovergaag commented on src/core/VitalsSummaryTable/VitalsSummaryTable.scss
> +        &#entity {
This isn't working in IE11

2021-04-01 22:56 UTC, jovergaag commented on src/core/PageVitals/PageVitals.scss
> +    @media screen and (max-width: $core-breakpoint-sm) {
I tested IE11 at 1000px screen width (not a likely scenario but doesn't hurt to fix it). The Summary cards are not wrapping.

<img width="978" alt="Screen Shot 2021-04-01 at 3 51 14 PM" src="https://user-images.githubusercontent.com/5872651/113362084-6645cc00-9302-11eb-8753-a6098b49626d.png">

2021-04-02 14:27 UTC, daschi commented on src/core/PageVitals/PageVitals.scss
> +    @media screen and (max-width: $core-breakpoint-sm) {
Hm yeah I chatted with Sonia about this and she said it wasn't P0 to fix for IE11, but I'll spend a bit of time this morning to see if it's an easy fix

2021-04-02 14:44 UTC, daschi commented on src/core/VitalsSummaryTable/VitalsSummaryTable.scss
> +        &#entity {
Yeah, `position: sticky` isn't supported in IE11, I think we should either not have the fixed column be a feature in IE11, or make a separate issue to investigate the best way to implement this in a table for IE11.

2021-04-06 18:37 UTC, jovergaag approved these changes
🎨

2021-04-06 18:37 UTC, jovergaag commented on src/core/VitalsSummaryTable/VitalsSummaryTable.scss
> +        &#entity {
I made an [issue](https://app.zenhub.com/workspaces/torch--5ec36552cdfe7bc58f04bdbe/issues/recidiviz/pulse-dashboard/992) for this for next sprint.

2021-04-06 19:09 UTC, merged